import type { Flashcard } from "./types";

// ────────────────────────────────────────────────────────────────────────────
// SET 13 — SOCIAL MEDIA
// ────────────────────────────────────────────────────────────────────────────
const socialMediaCards: Flashcard[] = [
  {
    id: "sm-connected",
    front: "to stay connected on social media",
    back: "giữ liên lạc trên mạng xã hội",
    pronunciation: "/tu steɪ kəˈnɛktɪd ɒn ˈsəʊʃl ˈmiːdiə/",
    example: "We stay connected on social media.",
  },
  {
    id: "sm-fuel-anxiety",
    front: "to fuel feelings of anxiety, depression and isolation",
    back: "thúc đẩy cảm giác lo lắng, trầm cảm và cô lập",
    pronunciation: "/tu ˈfjuːəl ˈfiːlɪŋz əv æŋˈzaɪəti/",
    example: "Social media fuels feelings of anxiety.",
  },
  {
    id: "sm-platforms",
    front: "social media platforms",
    back: "các nền tảng mạng xã hội",
    pronunciation: "/ˈsəʊʃl ˈmiːdiə ˈplætfɔːmz/",
    example: "There are many social media platforms.",
  },
  {
    id: "sm-communication-tool",
    front: "a powerful communication tool",
    back: "một công cụ giao tiếp mạnh mẽ",
    pronunciation: "/ə ˈpaʊərfʊl kəˌmjuːnɪˈkeɪʃn tuːl/",
    example: "Social media is a powerful communication tool.",
  },
  {
    id: "sm-exchange",
    front: "to exchange and share information, thoughts, and ideas across virtual networks",
    back: "trao đổi và chia sẻ thông tin, suy nghĩ và ý tưởng trên các mạng ảo",
    pronunciation: "/tu ɪksˈtʃeɪndʒ ənd ʃeər/",
    example: "Social media lets us exchange ideas across virtual networks.",
  },
  {
    id: "sm-mental-health",
    front: "to negatively affect mental health",
    back: "ảnh hưởng tiêu cực đến sức khỏe tâm thần",
    pronunciation: "/tu ˈnɛɡətɪvli əˈfɛkt ˈmɛntl hɛlθ/",
    example: "Too much social media negatively affects mental health.",
  },
  {
    id: "sm-browsing",
    front: "to spend too much time browsing social networks",
    back: "dành quá nhiều thời gian lướt các mạng xã hội",
    pronunciation: "/tu spɛnd tuː mʌtʃ taɪm ˈbraʊzɪŋ/",
    example: "She spends too much time browsing.",
  },
  {
    id: "sm-compulsively",
    front: "to compulsively check your phone",
    back: "check điện thoại liên tục",
    pronunciation: "/tu kəmˈpʌlsɪvli tʃɛk jɔːr fəʊn/",
    example: "Many compulsively check their phone.",
  },
  {
    id: "sm-turn-off",
    front: "to turn off notifications",
    back: "tắt thông báo (của các ứng dụng)",
    pronunciation: "/tu tɜːn ɒf ˌnəʊtɪfɪˈkeɪʃnz/",
    example: "Turn off notifications during work.",
  },
  {
    id: "sm-limit-30",
    front: "to limit the use of social media to 30 minutes a day",
    back: "hạn chế thời gian sử dụng mạng xã hội xuống còn 30 phút mỗi ngày",
    pronunciation: "/tu ˈlɪmɪt ðə juːs/",
    example: "I limit my social media use to 30 minutes a day.",
  },
  {
    id: "sm-take-break",
    front: "to take a break from social media",
    back: "tạm dừng sử dụng mạng xã hội một thời gian",
    pronunciation: "/tu teɪk ə breɪk frəm ˈsəʊʃl ˈmiːdiə/",
    example: "I need to take a break from social media.",
  },
  {
    id: "sm-detox",
    front: "to take a social media detox",
    back: "detox mạng xã hội",
    pronunciation: "/tu teɪk ə ˈsəʊʃl ˈmiːdiə ˈdiːtɒks/",
    example: "She went on a social media detox.",
  },
  {
    id: "sm-keep-touch",
    front: "to keep in touch and share photos",
    back: "giữ liên lạc và chia sẻ ảnh",
    pronunciation: "/tu kiːp ɪn tʌtʃ/",
    example: "We keep in touch through social media.",
  },
  {
    id: "sm-distant-together",
    front: "to bring distant people together",
    back: "mang những người ở xa lại với nhau",
    pronunciation: "/tu brɪŋ ˈdɪstənt ˈpiːpl təˈɡeðər/",
    example: "Social media brings distant people together.",
  },
  {
    id: "sm-reunite",
    front: "to reunite long lost relatives",
    back: "đoàn tụ những người thân bị mất liên lạc bấy lâu nay",
    pronunciation: "/tu ˌriːjuːˈnaɪt lɒŋ lɒst ˈrɛlətɪvz/",
    example: "Social media reunites long lost relatives.",
  },
  {
    id: "sm-data-breaches",
    front: "the risk of data breaches",
    back: "nguy cơ rò rỉ dữ liệu",
    pronunciation: "/ðə rɪsk əv ˈdeɪtə briːtʃɪz/",
    example: "There is the risk of data breaches.",
  },
  {
    id: "sm-loopholes",
    front: "security loopholes",
    back: "những lỗ hổng bảo mật",
    pronunciation: "/sɪˈkjʊərəti ˈluːphəʊlz/",
    example: "Hackers exploit security loopholes.",
  },
  {
    id: "sm-malicious",
    front: "to spread malicious content like scams and malware",
    back: "phát tán nội dung độc hại như lừa đảo và phần mềm độc hại",
    pronunciation: "/tu sprɛd məˈlɪʃəs ˈkɒntɛnt/",
    example: "Hackers spread malicious content.",
  },
  {
    id: "sm-location",
    front: "to automatically track and collect location data",
    back: "tự động theo dõi và thu thập dữ liệu vị trí (của người dùng)",
    pronunciation: "/tu ˌɔːtəˈmætɪkli træk/",
    example: "Many apps automatically collect location data.",
  },
  {
    id: "sm-friend-request",
    front: "to accept a new friend request",
    back: "chấp nhận yêu cầu kết bạn mới",
    pronunciation: "/tu əkˈsɛpt ə njuː frɛnd rɪˈkwɛst/",
    example: "I accepted a new friend request.",
  },
  {
    id: "sm-delete-account",
    front: "to delete your social media account",
    back: "xóa tài khoản mạng xã hội của bạn",
    pronunciation: "/tu dɪˈliːt jɔːr ˈsəʊʃl ˈmiːdiə əˈkaʊnt/",
    example: "He deleted his social media account.",
  },
  {
    id: "sm-compromised",
    front: "to prevent your data from getting compromised",
    back: "ngăn không cho dữ liệu của bạn bị xâm phạm",
    pronunciation: "/tu prɪˈvɛnt jɔːr ˈdeɪtə frəm ˈɡɛtɪŋ ˈkɒmprəmaɪzd/",
    example: "Use strong passwords to prevent your data from getting compromised.",
  },
  // Idioms & articles
  {
    id: "sm-associations",
    front: "to have associations with …",
    back: "có liên quan tới",
    pronunciation: "/tu həv əˌsəʊʃiˈeɪʃnz wɪð/",
    example: "Social media has associations with anxiety.",
  },
  {
    id: "sm-trigger",
    front: "to trigger (v)",
    back: "gây ra",
    pronunciation: "/tu ˈtrɪɡər/",
    example: "Social media may trigger feelings of inadequacy.",
  },
  {
    id: "sm-as-though",
    front: "as though",
    back: "cứ như là",
    pronunciation: "/əz ðəʊ/",
    example: "She acts as though everyone is watching her.",
  },
  {
    id: "sm-envy",
    front: "feelings of envy and dissatisfaction",
    back: "cảm giác ghen tị và không hài lòng",
    pronunciation: "/ˈfiːlɪŋz əv ˈɛndʒi/",
    example: "Social media may cause feelings of envy.",
  },
  {
    id: "sm-facilitate",
    front: "to facilitate (v)",
    back: "tạo điều kiện cho",
    pronunciation: "/tu fəˈsɪlɪteɪt/",
    example: "Social media can facilitate cyberbullying.",
  },
  {
    id: "sm-means-of",
    front: "a means of …",
    back: "một cách thức để làm gì",
    pronunciation: "/ə miːnz əv/",
    example: "Social media is a means of communication.",
  },
  {
    id: "sm-social-skills",
    front: "social skills",
    back: "các kỹ năng xã hội",
    pronunciation: "/ˈsəʊʃl skɪlz/",
    example: "Children develop social skills through play.",
  },
  {
    id: "sm-marginalized",
    front: "marginalized groups",
    back: "các nhóm yếu thế",
    pronunciation: "/ˈmɑːdʒɪnəlaɪzd ɡruːps/",
    example: "Social media helps marginalized groups connect.",
  },
  {
    id: "sm-interact",
    front: "to interact with somebody",
    back: "tương tác với ai đó",
    pronunciation: "/tu ˌɪntərˈækt wɪð ˈsʌmwʌn/",
    example: "Children need to interact with peers.",
  },
  {
    id: "sm-like-minded",
    front: "like-minded individuals",
    back: "những cá nhân có cùng chí hướng",
    pronunciation: "/laɪk ˈmaɪndɪd ˌɪndɪˈvɪdʒuəlz/",
    example: "Find like-minded individuals online.",
  },
];

// ────────────────────────────────────────────────────────────────────────────
// SET 14 — WORK & CAREER
// ────────────────────────────────────────────────────────────────────────────
const workCards: Flashcard[] = [
  {
    id: "wk-productivity",
    front: "work productivity",
    back: "năng suất làm việc",
    pronunciation: "/wɜːk ˌprɒdʌkˈtɪvəti/",
    example: "Sleep affects work productivity.",
  },
  {
    id: "wk-nine-five",
    front: "a nine-to-five job",
    back: "công việc giờ hành chính",
    pronunciation: "/ə naɪn tu faɪv dʒɒb/",
    example: "He works a nine-to-five job.",
  },
  {
    id: "wk-performance",
    front: "poor work performance",
    back: "hiệu suất làm việc kém",
    pronunciation: "/pʊər wɜːk pəˈfɔːməns/",
    example: "Stress leads to poor work performance.",
  },
  {
    id: "wk-sick-leave",
    front: "sick leave",
    back: "nghỉ phép vì bệnh",
    pronunciation: "/sɪk liːv/",
    example: "He took sick leave for a week.",
  },
  {
    id: "wk-environment",
    front: "professional work environment",
    back: "môi trường làm việc chuyên nghiệp",
    pronunciation: "/prəˈfɛʃənl wɜːk ɪnˈvaɪərənmənt/",
    example: "We aim for a professional work environment.",
  },
  {
    id: "wk-well-paid",
    front: "to get a well-paid job",
    back: "có được một công việc được trả lương tốt",
    pronunciation: "/tu ɡet ə wɛl peɪd dʒɒb/",
    example: "She wants a well-paid job.",
  },
  {
    id: "wk-salary",
    front: "to earn a high salary",
    back: "có được mức lương cao",
    pronunciation: "/tu ɜːn ə haɪ ˈsæləri/",
    example: "He earns a high salary.",
  },
  {
    id: "wk-satisfaction",
    front: "job satisfaction",
    back: "sự hài lòng khi làm việc",
    pronunciation: "/dʒɒb ˌsætɪsˈfækʃn/",
    example: "Job satisfaction matters more than salary.",
  },
  {
    id: "wk-long-hours",
    front: "to work long hours",
    back: "làm việc nhiều giờ",
    pronunciation: "/tu wɜːk lɒŋ ˈaʊəz/",
    example: "Many employees work long hours.",
  },
  {
    id: "wk-limit-hours",
    front: "to limit work hours",
    back: "giới hạn giờ làm việc",
    pronunciation: "/tu ˈlɪmɪt wɜːk ˈaʊəz/",
    example: "Many companies now limit work hours.",
  },
  {
    id: "wk-health-issues",
    front: "to suffer from various health issues",
    back: "mắc các vấn đề về sức khỏe",
    pronunciation: "/tu ˈsʌfər frəm ˈveəriəs hɛlθ ˈɪʃuːz/",
    example: "Overworked people suffer from various health issues.",
  },
  {
    id: "wk-low-productivity",
    front: "low productivity",
    back: "năng suất thấp",
    pronunciation: "/ləʊ ˌprɒdʌkˈtɪvəti/",
    example: "Long hours lead to low productivity.",
  },
  {
    id: "wk-case-in-point",
    front: "a case in point",
    back: "một ví dụ điển hình",
    pronunciation: "/ə keɪs ɪn pɔɪnt/",
    example: "My cousin is a case in point.",
  },
  {
    id: "wk-exhausted",
    front: "to frequently feel exhausted",
    back: "thường xuyên cảm thấy kiệt sức",
    pronunciation: "/tu ˈfriːkwəntli fiːl ɪɡˈzɔːstɪd/",
    example: "He frequently feels exhausted.",
  },
  {
    id: "wk-errors",
    front: "to make more errors at work",
    back: "sai sót nhiều hơn tại sở làm",
    pronunciation: "/tu meɪk mɔːr ˈɛrəz ət wɜːk/",
    example: "Tired workers make more errors at work.",
  },
  {
    id: "wk-consequences",
    front: "to have serious consequences for...",
    back: "gây ra hậu quả nặng nề cho",
    pronunciation: "/tu həv ˈsɪəriəs ˈkɒnsɪkwənsɪz/",
    example: "It has serious consequences for families.",
  },
  {
    id: "wk-busy",
    front: "busy work schedules",
    back: "lịch trình công việc bận rộn",
    pronunciation: "/ˈbɪzi wɜːk ˈʃɛdjuːlz/",
    example: "Busy work schedules prevent family time.",
  },
  {
    id: "wk-self-employed",
    front: "to be self-employed",
    back: "tự làm chủ",
    pronunciation: "/tu biː sɛlf ɪmˈplɔɪd/",
    example: "She is self-employed.",
  },
  {
    id: "wk-pursue",
    front: "to pursue a career",
    back: "theo đuổi sự nghiệp",
    pronunciation: "/tu pəˈsjuː ə kəˈrɪər/",
    example: "He chose to pursue a career in music.",
  },
  {
    id: "wk-skills-experience",
    front: "to learn various skills and experience",
    back: "học được những kỹ năng và kinh nghiệm",
    pronunciation: "/tu lɜːn ˈveəriəs skɪlz/",
    example: "Internships help you learn various skills and experience.",
  },
  // Work from home
  {
    id: "wk-wfh-flexibility",
    front: "to provide us with flexibility and convenience",
    back: "cung cấp cho chúng ta sự linh hoạt và tiện lợi",
    pronunciation: "/tu prəˈvaɪd ʌs wɪð ˌflɛksəˈbɪləti/",
    example: "Remote jobs provide flexibility and convenience.",
  },
  {
    id: "wk-wfh-no-office",
    front: "do not need to go to the office on a daily basis",
    back: "không cần tới công sở hàng ngày",
    pronunciation: "/duː nɒt niːd tu ɡəʊ tu ði ˈɒfɪs/",
    example: "Remote workers don't go to the office daily.",
  },
  {
    id: "wk-wfh-commute",
    front: "to save a large amount of time commuting back and forth to work",
    back: "tiết kiệm một lượng lớn thời gian đi lại giữa nhà và nơi làm việc",
    pronunciation: "/tu seɪv ə lɑːdʒ əˈmaʊnt əv taɪm kəˈmjuːtɪŋ/",
    example: "Working from home saves commuting time.",
  },
  {
    id: "wk-wfh-freedom",
    front: "to have the freedom to choose where and when they want to work",
    back: "có sự tự do lựa chọn nơi đâu và khi nào họ muốn làm việc",
    pronunciation: "/tu həv ðə ˈfriːdəm/",
    example: "Freelancers have the freedom to choose when to work.",
  },
  {
    id: "wk-wfh-discipline",
    front: "to require high levels of discipline and commitment",
    back: "đòi hỏi mức độ kỷ luật và cam kết cao",
    pronunciation: "/tu rɪˈkwaɪər haɪ ˈlɛvlz/",
    example: "Self-employment requires high levels of discipline.",
  },
  {
    id: "wk-wfh-no-supervision",
    front: "to have no supervision and restrictions",
    back: "không có sự giám sát hay hạn chế nào",
    pronunciation: "/tu həv nəʊ ˌsuːpəˈvɪʒn/",
    example: "Remote workers have no supervision.",
  },
  {
    id: "wk-wfh-loneliness",
    front: "might experience feelings of loneliness and isolation sometimes",
    back: "thỉnh thoảng có thể cảm thấy cô đơn và bị cô lập",
    pronunciation: "/maɪt ɪkˈspɪəriəns ˈfiːlɪŋz/",
    example: "Remote workers may feel lonely sometimes.",
  },
  {
    id: "wk-wfh-distracted",
    front: "to easily get distracted by things like movies / online games / …",
    back: "dễ bị sao nhãng bởi những thứ như phim ảnh, trò chơi trực tuyến",
    pronunciation: "/tu ˈiːzili ɡet dɪˈstræktɪd/",
    example: "It's easy to get distracted by online games.",
  },
  {
    id: "wk-wfh-concentrate",
    front: "cannot concentrate entirely on their work",
    back: "không thể hoàn toàn tập trung vào công việc",
    pronunciation: "/ˈkænɒt ˈkɒnsntreɪt ɪnˈtaɪəli/",
    example: "He can't concentrate entirely on his work.",
  },
  {
    id: "wk-wfh-negative-affect",
    front: "to negatively affect their work performance and productivity",
    back: "ảnh hưởng tiêu cực tới hiệu suất làm việc",
    pronunciation: "/tu ˈnɛɡətɪvli əˈfɛkt/",
    example: "Distractions negatively affect performance.",
  },
  {
    id: "wk-wfh-social-skills",
    front: "to find it difficult to develop social skills (communication, teamwork skills, …)",
    back: "khó phát triển các kỹ năng xã hội",
    pronunciation: "/tu faɪnd ɪt ˈdɪfɪkəlt/",
    example: "Remote work makes it harder to develop social skills.",
  },
  {
    id: "wk-wfh-less-chance",
    front:
      "to have less chance to interact and communicate directly with their colleagues and clients",
    back: "có ít cơ hội tương tác và giao tiếp trực tiếp với đồng nghiệp và khách hàng",
    pronunciation: "/tu həv lɛs tʃɑːns/",
    example: "Remote workers have less chance to communicate directly with colleagues.",
  },
  // Paraphrases
  {
    id: "wk-para-employees",
    front: "employees ≈ staff",
    back: "nhân viên",
    pronunciation: "/ɪmˈplɔɪiːz/",
    example: "All staff are invited to the meeting.",
  },
  {
    id: "wk-para-employers",
    front: "employers ≈ bosses",
    back: "chủ, người sử dụng lao động",
    pronunciation: "/ɪmˈplɔɪəz/",
    example: "Employers should respect workers.",
  },
  {
    id: "wk-para-longer-hours",
    front: "to work longer hours ≈ to spend more time at work",
    back: "làm việc nhiều giờ hơn",
    pronunciation: "/tu wɜːk lɒŋɡər ˈaʊəz/",
    example: "She spends more time at work these days.",
  },
  {
    id: "wk-para-opportunities",
    front: "more job opportunities ≈ greater employment possibilities",
    back: "nhiều cơ hội nghề nghiệp hơn",
    pronunciation: "/mɔːr dʒɒb ˌɒpəˈtjuːnətiz/",
    example: "Tech offers greater employment possibilities.",
  },
  {
    id: "wk-para-time-working",
    front:
      "to spend a large amount of time working ≈ to devote a huge amount of time to their work",
    back: "dành một lượng thời gian lớn làm việc",
    pronunciation: "/tu spend ə lɑːdʒ əˈmaʊnt əv taɪm/",
    example: "He devotes a huge amount of time to his work.",
  },
  {
    id: "wk-para-impact",
    front:
      "to have a severe impact on... ≈ to have an adverse impact on... ≈ to have a harmful impact on... ≈ to have a negative impact on...",
    back: "có ảnh hưởng tiêu cực / có hại lên",
    pronunciation: "/tu həv ə sɪˈvɪər ˈɪmpækt/",
    example: "Long hours have a harmful impact on health.",
  },
  {
    id: "wk-para-low-productivity",
    front: "low work productivity ≈ poor work performance",
    back: "hiệu suất làm việc thấp",
    pronunciation: "/ləʊ wɜːk ˌprɒdʌkˈtɪvəti/",
    example: "Stress leads to poor work performance.",
  },
  {
    id: "wk-para-errors",
    front: "to make more errors at work ≈ to be more likely to have accidents",
    back: "sai sót nhiều hơn / có khả năng cao gặp tai nạn",
    pronunciation: "/tu meɪk mɔːr ˈɛrəz/",
    example: "Tired workers are more likely to have accidents.",
  },
  {
    id: "wk-para-good-job",
    front: "to get a good job ≈ to get a well-paid job",
    back: "có được một công việc tốt",
    pronunciation: "/tu ɡet ə ɡʊd dʒɒb/",
    example: "Graduates want to get a well-paid job.",
  },
  {
    id: "wk-para-bored",
    front: "to feel bored and stressed ≈ to experience feelings of boredom and stress",
    back: "cảm thấy buồn chán và căng thẳng",
    pronunciation: "/tu fiːl bɔːd ənd strɛst/",
    example: "Many experience feelings of boredom and stress.",
  },
  {
    id: "wk-para-leadership",
    front: "to take on leadership roles ≈ to be in leadership positions",
    back: "đảm nhận các vai trò lãnh đạo / ở vị trí lãnh đạo",
    pronunciation: "/tu teɪk ɒn ˈliːdərʃɪp rəʊlz/",
    example: "She is in leadership positions.",
  },
  {
    id: "wk-para-damage",
    front:
      "to cause a company great damage ≈ to sign risky contracts and face a risk of monetary loss",
    back: "gây cho công ty tổn thất nặng nề / ký kết các hợp đồng rủi ro và đối mặt với nguy cơ mất tiền",
    pronunciation: "/tu kɔːz ə ˈkʌmpəni ɡreɪt ˈdæmɪdʒ/",
    example: "Bad decisions cause a company great damage.",
  },
  {
    id: "wk-para-unemployment",
    front:
      "higher unemployment rates ≈ increase in the proportion of people who are out of work/jobless",
    back: "tỷ lệ thất nghiệp cao hơn / sự gia tăng trong tỷ lệ người không có việc làm",
    pronunciation: "/ˈhaɪər ˌʌnˈɛmplɔɪmənt reɪts/",
    example: "There is an increase in the proportion of people who are jobless.",
  },
  {
    id: "wk-para-passion",
    front:
      "the career that they are genuinely passionate about ≈ the career path that they have a passion for",
    back: "sự nghiệp mà họ thực sự đam mê",
    pronunciation: "/ðə kəˈrɪər ðæt ðeɪ ɑːr ˈdʒɛnjuɪnli ˈpæʃənət əˈbaʊt/",
    example: "Follow the career path that you have a passion for.",
  },
  {
    id: "wk-para-skills",
    front:
      "to have the chance to learn various skills and experience ≈ to have the opportunity to learn a wide range of useful skills and experience ≈ to have the opportunity to develop their creative thinking and sharpen their skills and abilities",
    back: "có cơ hội học hỏi những kỹ năng và kinh nghiệm hữu ích / có cơ hội phát triển tư duy sáng tạo và rèn luyện các kỹ năng, năng lực",
    pronunciation: "/tu həv ðə tʃɑːns tu lɜːn/",
    example: "Internships give the opportunity to develop their creative thinking.",
  },
  {
    id: "wk-para-pursue",
    front: "to pursue their careers ≈ to chase after their dream careers",
    back: "theo đuổi sự nghiệp của họ",
    pronunciation: "/tu pəˈsjuː ðeə kəˈrɪərz/",
    example: "She chases after her dream career.",
  },
  {
    id: "wk-para-same-position",
    front:
      "to stay in the same position for too long ≈ to do the same jobs for years ≈ to stay in the same job for a long period of time",
    back: "ở tại một vị trí trong thời gian dài",
    pronunciation: "/tu steɪ ɪn ðə seɪm pəˈzɪʃn/",
    example: "Many stay in the same job for years.",
  },
  {
    id: "wk-para-unemploy-rates",
    front:
      "unemployment rates ≈ unemployment levels ≈ levels of joblessness ≈ levels of unemployment",
    back: "tỷ lệ thất nghiệp",
    pronunciation: "/ˌʌnˈɛmplɔɪmənt reɪts/",
    example: "Unemployment levels have dropped.",
  },
  {
    id: "wk-para-unemployed",
    front:
      "the proportion of people who are unemployed ≈ the proportion of people who are jobless ≈ the proportion of people without work",
    back: "tỷ lệ người thất nghiệp",
    pronunciation: "/ðə prəˈpɔːʃn əv ˈpiːpl huː ɑːr ˌʌnˈɛmplɔɪd/",
    example: "The proportion of people who are jobless is rising.",
  },
];

export { socialMediaCards, workCards };
