import type { Flashcard } from "./types";

// ────────────────────────────────────────────────────────────────────────────
// SET 9 — LANGUAGES
// ────────────────────────────────────────────────────────────────────────────
const languagesCards: Flashcard[] = [
  {
    id: "lang-minority",
    front: "minority languages",
    back: "những ngôn ngữ thiểu số, được ít người nói",
    pronunciation: "/maɪˈnɒrəti ˈlæŋɡwɪdʒɪz/",
    example: "Minority languages are at risk of disappearing.",
  },
  {
    id: "lang-commonly",
    front: "commonly spoken languages",
    back: "những ngôn ngữ được nói phổ biến",
    pronunciation: "/ˈkɒmənli ˈspəʊkən ˈlæŋɡwɪdʒɪz/",
    example: "English is among the most commonly spoken languages.",
  },
  {
    id: "lang-most-widely",
    front: "the most widely spoken language",
    back: "ngôn ngữ được nói rộng rãi nhất",
    pronunciation: "/ðə məʊst ˈwaɪdli ˈspəʊkən ˈlæŋɡwɪdʒ/",
    example: "English is the most widely spoken language.",
  },
  {
    id: "lang-same",
    front: "to speak the same language",
    back: "nói cùng một thứ tiếng",
    pronunciation: "/tu spiːk ðə seɪm ˈlæŋɡwɪdʒ/",
    example: "We don't speak the same language.",
  },
  {
    id: "lang-foreign",
    front: "foreign/second languages",
    back: "ngôn ngữ nước ngoài / thứ hai",
    pronunciation: "/ˈfɒrɪn ˈlæŋɡwɪdʒɪz/",
    example: "She speaks three foreign languages.",
  },
  {
    id: "lang-mother",
    front: "mother tongue",
    back: "tiếng mẹ đẻ",
    pronunciation: "/ˈmʌðər tʌŋ/",
    example: "English is not her mother tongue.",
  },
  {
    id: "lang-dialects",
    front: "local dialects",
    back: "tiếng địa phương",
    pronunciation: "/ˈləʊkl ˈdaɪəlɛkts/",
    example: "Many local dialects are disappearing.",
  },
  {
    id: "lang-heritage",
    front: "the world's linguistic heritage",
    back: "di sản ngôn ngữ thế giới",
    pronunciation: "/ðə wɜːldz lɪŋˈɡwɪstɪk ˈhɛrɪtɪdʒ/",
    example: "We should protect the world's linguistic heritage.",
  },
  {
    id: "lang-means-communication",
    front: "a common means of communication",
    back: "một cách thức giao tiếp phổ biến",
    pronunciation: "/ə ˈkɒmən miːnz əv kəˌmjuːnɪˈkeɪʃn/",
    example: "English is a common means of communication.",
  },
  {
    id: "lang-proficiency",
    front: "to have a high level of proficiency in...",
    back: "thành thạo ngôn ngữ nào đó",
    pronunciation: "/tu həv ə haɪ ˈlɛvl əv prəˈfɪʃənsi/",
    example: "She has a high level of proficiency in English.",
  },
  {
    id: "lang-conversation",
    front: "to be able to hold a conversation in...",
    back: "có khả năng giao tiếp bằng ngôn ngữ nào đó",
    pronunciation: "/tu biː ˈeɪbl tu həʊld ə ˌkɒnvəˈseɪʃn/",
    example: "He can hold a conversation in French.",
  },
  {
    id: "lang-dominant",
    front: "to adopt the dominant language",
    back: "nói ngôn ngữ chiếm ưu thế",
    pronunciation: "/tu əˈdɒpt ðə ˈdɒmɪnənt ˈlæŋɡwɪdʒ/",
    example: "Many adopt the dominant language to fit in.",
  },
  {
    id: "lang-vital-part",
    front: "to be a vital part of...",
    back: "là một phần thiết yếu của",
    pronunciation: "/tu biː ə ˈvaɪtl pɑːt/",
    example: "Language is a vital part of culture.",
  },
  {
    id: "lang-extinction",
    front: "to be in danger of extinction",
    back: "đứng trước sự tuyệt chủng",
    pronunciation: "/tu biː ɪn ˈdeɪndʒər əv ɪkˈstɪŋkʃn/",
    example: "Many languages are in danger of extinction.",
  },
  {
    id: "lang-allow-disappear",
    front: "to allow a language to disappear",
    back: "cho phép một ngôn ngữ biến mất",
    pronunciation: "/tu əˈlaʊ ə ˈlæŋɡwɪdʒ tu ˌdɪsəˈpɪər/",
    example: "We shouldn't allow languages to disappear.",
  },
  {
    id: "lang-barriers",
    front: "to encounter language barriers",
    back: "gặp phải những rào cản ngôn ngữ",
    pronunciation: "/tu ɪnˈkaʊntər ˈlæŋɡwɪdʒ ˈbæriəz/",
    example: "They encountered language barriers while abroad.",
  },
  {
    id: "lang-miscommunication",
    front: "misunderstanding and miscommunication",
    back: "sự hiểu lầm và nhầm lẫn",
    pronunciation: "/ˌmɪsʌndəˈstændɪŋ ənd ˌmɪskəˌmjuːnɪˈkeɪʃn/",
    example: "Misunderstanding can lead to conflict.",
  },
  {
    id: "lang-tension",
    front: "to lead to tension and conflicts",
    back: "dẫn đến căng thẳng và mâu thuẫn",
    pronunciation: "/tu liːd tu ˈtɛnʃn ənd ˈkɒnflɪkts/",
    example: "It may lead to tension and conflicts.",
  },
  {
    id: "lang-expensive",
    front: "expensive language programmes",
    back: "những chương trình ngôn ngữ đắt tiền",
    pronunciation: "/ɪkˈspɛnsɪv ˈlæŋɡwɪdʒ ˈprəʊɡræmz/",
    example: "Many language programmes are expensive.",
  },
  {
    id: "lang-preservation",
    front: "language preservation",
    back: "sự bảo tồn ngôn ngữ",
    pronunciation: "/ˈlæŋɡwɪdʒ ˌprɛzəˈveɪʃn/",
    example: "Language preservation is essential.",
  },
  {
    id: "lang-every-effort",
    front: "to make every possible effort to protect/ save ...",
    back: "nỗ lực hết sức để bảo vệ / cứu",
    pronunciation: "/tu meɪk ˈɛvri ˈpɒsəbl ˈɛfət/",
    example: "We should make every possible effort to protect them.",
  },
  {
    id: "lang-traditional-values",
    front: "the traditional and cultural values attached to...",
    back: "những giá trị văn hóa truyền thống gắn với",
    pronunciation: "/ðə trəˈdɪʃənl ənd ˈkʌltʃərəl ˈvæljuːz/",
    example: "Languages contain traditional and cultural values.",
  },
  {
    id: "lang-cultural-diversity",
    front: "to contribute to cultural diversity",
    back: "góp phần vào sự đa dạng văn hóa",
    pronunciation: "/tu kənˈtrɪbjuːt tu ˈkʌltʃərəl daɪˈvɜːsəti/",
    example: "Languages contribute to cultural diversity.",
  },
  {
    id: "lang-linguistic-diversity",
    front: "linguistic diversity",
    back: "sự đa dạng ngôn ngữ",
    pronunciation: "/lɪŋˈɡwɪstɪk daɪˈvɜːsəti/",
    example: "Linguistic diversity is decreasing.",
  },
  {
    id: "lang-identity",
    front: "to maintain the identity and heritage of a community",
    back: "duy trì bản sắc và di sản của một cộng đồng",
    pronunciation: "/tu meɪnˈteɪn ði aɪˈdɛntəti/",
    example: "Languages help maintain the identity of a community.",
  },
  {
    id: "lang-deeper-insights",
    front:
      "to get deeper insights into different ways of thinking and living of different cultures and peoples across the globe",
    back: "có cái nhìn sâu sắc hơn về cách nghĩ, cách sống của các dân tộc và nền văn hóa khác nhau trên toàn cầu",
    pronunciation: "/tu ɡet ˈdiːpər ˈɪnsaɪts/",
    example: "Learning languages gives deeper insights into different cultures.",
  },
  {
    id: "lang-policy",
    front: "language education policy",
    back: "chính sách giáo dục ngôn ngữ",
    pronunciation: "/ˈlæŋɡwɪdʒ ˌɛdjuˈkeɪʃn ˈpɒləsi/",
    example: "Each country has its language education policy.",
  },
  {
    id: "lang-support",
    front: "to support language learning",
    back: "hỗ trợ việc học ngôn ngữ",
    pronunciation: "/tu səˈpɔːt ˈlæŋɡwɪdʒ ˈlɜːnɪŋ/",
    example: "Governments should support language learning.",
  },
  {
    id: "lang-machine-translation",
    front: "machine translation",
    back: "việc dịch ngôn ngữ bằng máy",
    pronunciation: "/məˈʃiːn trænzˈleɪʃn/",
    example: "Machine translation is increasingly accurate.",
  },
  {
    id: "lang-waste-time",
    front: "to be a waste of time",
    back: "tốn thời gian",
    pronunciation: "/tu biː ə weɪst əv taɪm/",
    example: "Some think learning a language is a waste of time.",
  },
  {
    id: "lang-translation-apps",
    front: "translation apps",
    back: "các ứng dụng dịch ngôn ngữ",
    pronunciation: "/trænzˈleɪʃn æps/",
    example: "Translation apps make communication easier.",
  },
  {
    id: "lang-decline",
    front: "to witness a decline in linguistic diversity",
    back: "chứng kiến sự suy giảm trong đa dạng ngôn ngữ",
    pronunciation: "/tu ˈwɪtnəs ə dɪˈklaɪn/",
    example: "We are witnessing a decline in linguistic diversity.",
  },
  {
    id: "lang-heritage-lang",
    front: "heritage language",
    back: "ngôn ngữ được kế thừa từ đời này sang đời khác",
    pronunciation: "/ˈhɛrɪtɪdʒ ˈlæŋɡwɪdʒ/",
    example: "Vietnamese is a heritage language of many overseas communities.",
  },
];

// ────────────────────────────────────────────────────────────────────────────
// SET 10 — MAKEUP & APPEARANCE
// ────────────────────────────────────────────────────────────────────────────
const makeupCards: Flashcard[] = [
  {
    id: "mu-wear-makeup",
    front: "to wear makeup every day",
    back: "trang điểm mỗi ngày",
    pronunciation: "/tu weər ˈmeɪkʌp/",
    example: "She wears makeup every day.",
  },
  {
    id: "mu-makeup-free",
    front: "to go makeup-free",
    back: "không trang điểm, để mặt mộc",
    pronunciation: "/tu ɡəʊ ˈmeɪkʌp friː/",
    example: "I prefer to go makeup-free.",
  },
  {
    id: "mu-natural-beauty",
    front: "to enhance your natural beauty",
    back: "nâng tầm / làm tôn lên vẻ đẹp tự nhiên của bạn",
    pronunciation: "/tu ɪnˈhɑːns jɔːr ˈnætʃərəl ˈbjuːti/",
    example: "Makeup can enhance your natural beauty.",
  },
  {
    id: "mu-dark-circles",
    front: "to have dark circles under your eyes",
    back: "có quầng thâm dưới mắt",
    pronunciation: "/tu həv dɑːk ˈsɜːklz ˈʌndər jɔːr aɪz/",
    example: "She has dark circles under her eyes.",
  },
  {
    id: "mu-brighten-skin",
    front: "to brighten your skin",
    back: "làm sáng làn da của bạn",
    pronunciation: "/tu ˈbraɪtn jɔːr skɪn/",
    example: "This product helps brighten your skin.",
  },
  {
    id: "mu-fine-lines",
    front: "to hide fine lines and wrinkles",
    back: "che giấu nếp nhăn",
    pronunciation: "/tu haɪd faɪn laɪnz ənd ˈrɪŋklz/",
    example: "Anti-aging creams hide fine lines and wrinkles.",
  },
  {
    id: "mu-anti-aging",
    front: "to look for anti-aging formulas",
    back: "tìm kiếm các công thức chống lão hóa",
    pronunciation: "/tu lʊk fɔːr ænti ˈeɪdʒɪŋ ˈfɔːmjələz/",
    example: "Many women look for anti-aging formulas.",
  },
  {
    id: "mu-confidence",
    front: "to boost your confidence",
    back: "tăng sự tự tin của bạn",
    pronunciation: "/tu buːst jɔːr ˈkɒnfɪdəns/",
    example: "Makeup can boost your confidence.",
  },
  {
    id: "mu-acne-scars",
    front: "to have acne scars or other blemishes",
    back: "có sẹo mụn hoặc các nhược điểm khác",
    pronunciation: "/tu həv ˈækni skɑːz/",
    example: "Some people have acne scars.",
  },
  {
    id: "mu-heavy-makeup",
    front: "to wear heavy makeup",
    back: "trang điểm đậm",
    pronunciation: "/tu weər ˈhɛvi ˈmeɪkʌp/",
    example: "She wears heavy makeup at night.",
  },
  {
    id: "mu-natural-look",
    front: "to prefer a natural look",
    back: "thích cách trang điểm nhẹ nhàng, tự nhiên",
    pronunciation: "/tu prɪˈfɜːr ə ˈnætʃərəl lʊk/",
    example: "I prefer a natural look.",
  },
  {
    id: "mu-remove-makeup",
    front: "to remove makeup before cleansing",
    back: "tẩy trang trước khi rửa mặt",
    pronunciation: "/tu rɪˈmuːv ˈmeɪkʌp bɪˈfɔːr ˈklɛnzɪŋ/",
    example: "Always remove makeup before cleansing.",
  },
  {
    id: "mu-prime",
    front: "to prime your face",
    back: "dùng kem lót",
    pronunciation: "/tu praɪm jɔːr feɪs/",
    example: "I prime my face before foundation.",
  },
  {
    id: "mu-ready-world",
    front: "to feel ready for the world",
    back: "cảm thấy sẵn sàng ra ngoài gặp gỡ mọi người",
    pronunciation: "/tu fiːl ˈrɛdi fɔːr ðə wɜːld/",
    example: "A little makeup and I feel ready for the world.",
  },
  {
    id: "mu-skin-break",
    front: "to give skin a little break from the blush and bronzer",
    back: "cho da nghỉ ngơi",
    pronunciation: "/tu ɡɪv skɪn ə ˈlɪtl breɪk/",
    example: "I give my skin a break from blush.",
  },
  {
    id: "mu-foundation-brush",
    front: "to use a foundation brush",
    back: "sử dụng cọ nền",
    pronunciation: "/tu juːz ə faʊnˈdeɪʃn brʌʃ/",
    example: "She uses a foundation brush.",
  },
  {
    id: "mu-concealer",
    front: "to apply some concealer",
    back: "thoa một ít kem che khuyết điểm",
    pronunciation: "/tu əˈplaɪ sʌm kənˈsiːlər/",
    example: "Apply some concealer for dark circles.",
  },
  {
    id: "mu-imperfections",
    front: "to hide your imperfections",
    back: "che giấu những điểm không hoàn hảo của bạn",
    pronunciation: "/tu haɪd jɔːr ɪmˈpɜːfekʃnz/",
    example: "Makeup hides imperfections.",
  },
  {
    id: "mu-brighten-face",
    front: "to brighten up the darkest areas of your face",
    back: "làm sáng những vùng tối nhất trên khuôn mặt",
    pronunciation: "/tu ˈbraɪtn ʌp ðə ˈdɑːkɪst ˈeəriəz/",
    example: "Concealer brightens up the darkest areas.",
  },
  {
    id: "mu-youthful",
    front: "to give your face a more youthful appearance",
    back: "làm cho khuôn mặt trông trẻ trung hơn",
    pronunciation: "/tu ɡɪv jɔːr feɪs ə mɔːr ˈjuːθfʊl əˈpɪərəns/",
    example: "Makeup gives a more youthful appearance.",
  },
  // Products
  {
    id: "mu-lipstick",
    front: "lipstick",
    back: "son môi",
    pronunciation: "/ˈlɪpstɪk/",
    example: "She wore red lipstick.",
  },
  {
    id: "mu-lip-gloss",
    front: "lip gloss",
    back: "son bóng",
    pronunciation: "/lɪp ɡlɒs/",
    example: "Lip gloss makes your lips shiny.",
  },
  {
    id: "mu-lip-liner",
    front: "lip liner",
    back: "chì kẻ viền môi",
    pronunciation: "/lɪp ˈlaɪnər/",
    example: "Apply lip liner before lipstick.",
  },
  {
    id: "mu-foundation",
    front: "foundation",
    back: "phấn nền",
    pronunciation: "/faʊnˈdeɪʃn/",
    example: "Choose a foundation that matches your skin.",
  },
  {
    id: "mu-face-powder",
    front: "face powder",
    back: "phấn phủ",
    pronunciation: "/feɪs ˈpaʊdər/",
    example: "Face powder sets makeup.",
  },
  {
    id: "mu-blush",
    front: "blush",
    back: "phấn má",
    pronunciation: "/blʌʃ/",
    example: "She applied pink blush.",
  },
  {
    id: "mu-highlighter",
    front: "highlighter",
    back: "phấn highlight",
    pronunciation: "/ˈhaɪlaɪtər/",
    example: "Apply highlighter on your cheekbones.",
  },
  {
    id: "mu-primer",
    front: "primer",
    back: "kem lót",
    pronunciation: "/ˈpraɪmər/",
    example: "Use primer for longer-lasting makeup.",
  },
  {
    id: "mu-eye-shadow",
    front: "eye shadow",
    back: "phấn mắt",
    pronunciation: "/aɪ ˈʃædəʊ/",
    example: "She picked a purple eye shadow.",
  },
  {
    id: "mu-eyeliner",
    front: "eyeliner",
    back: "bút kẻ viền mắt",
    pronunciation: "/ˈaɪlaɪnər/",
    example: "Eyeliner makes eyes pop.",
  },
  {
    id: "mu-mascara",
    front: "mascara",
    back: "mascara",
    pronunciation: "/mæˈskɑːrə/",
    example: "She forgot to wear mascara.",
  },
  // Idioms
  {
    id: "mu-beauty-only-skin-deep",
    front: "Beauty is only skin deep",
    back: "tính cách, tâm hồn, trí tuệ quan trọng hơn diện mạo",
    pronunciation: "/ˈbjuːti ɪz ˈəʊnli skɪn diːp/",
    example: "Beauty is only skin deep.",
  },
  {
    id: "mu-beauty-eye-beholder",
    front: "Beauty is in the eye of the beholder",
    back: "vẻ đẹp nằm trong đôi mắt của người xem/kẻ si tình",
    pronunciation: "/ˈbjuːti ɪz ɪn ði aɪ əv ðə bɪˈhəʊldər/",
    example: "Beauty is in the eye of the beholder.",
  },
  {
    id: "mu-dressed-to-kill",
    front: "dressed to kill",
    back: "ăn diện để thu hút sự chú ý",
    pronunciation: "/drɛst tu kɪl/",
    example: "She arrived dressed to kill.",
  },
  {
    id: "mu-no-hair-out",
    front: "not a hair out of place",
    back: "vẻ ngoài gọn gàng, đầu tóc chỉn chu",
    pronunciation: "/nɒt ə heər aʊt əv pleɪs/",
    example: "She looked not a hair out of place.",
  },
  {
    id: "mu-skin-and-bone",
    front: "(all) skin and bone(s)",
    back: "da bọc xương (rất gầy)",
    pronunciation: "/ɔːl skɪn ənd bəʊnz/",
    example: "After the illness she was all skin and bone.",
  },
];

export { languagesCards, makeupCards };
