import type { Flashcard } from "./types";

// ────────────────────────────────────────────────────────────────────────────
// SET 18 — LIFE & CULTURE (City / Culture / Tourism / Transport / Housing / Working from Home / Christmas / Tet / Sport)
// ────────────────────────────────────────────────────────────────────────────
const lifeCultureCards: Flashcard[] = [
  // ── City Life ─────────────────────────────────────────────────────────
  {
    id: "cl-metropolis",
    front: "a large metropolis = a big city",
    back: "một đô thị lớn = một thành phố lớn",
    pronunciation: "/məˈtrɒpəlɪs/",
    example: "Tokyo is a large metropolis.",
  },
  {
    id: "cl-city-dwellers",
    front: "city dwellers",
    back: "cư dân thành phố",
    pronunciation: "/ˈdwɛləz/",
    example: "City dwellers enjoy many amenities.",
  },
  {
    id: "cl-urbanisation",
    front: "urbanisation = urban sprawl",
    back: "đô thị hóa",
    pronunciation: "/ˌɜːbənaɪˈzeɪʃn/",
    example: "Urbanisation transforms landscapes.",
  },
  {
    id: "cl-intensive-urban",
    front: "intensive urban growth",
    back: "tăng trưởng đô thị mạnh mẽ",
    pronunciation: "/ɪnˈtɛnsɪv ˈɜːbən ɡrəʊθ/",
    example: "Intensive urban growth strains infrastructure.",
  },
  {
    id: "cl-residential-area",
    front: "a residential area",
    back: "khu dân cư",
    pronunciation: "/ˌrɛzɪˈdɛnʃl ˈɛəriə/",
    example: "We live in a quiet residential area.",
  },
  {
    id: "cl-industrial-zone",
    front: "an industrial zone",
    back: "khu công nghiệp",
    pronunciation: "/ɪnˈdʌstriəl zəʊn/",
    example: "Industrial zones are on the city's edge.",
  },
  {
    id: "cl-find-it-difficult",
    front: "to find it difficult to...",
    back: "cảm thấy khó khăn làm gì",
    pronunciation: "/faɪnd ɪt ˈdɪfɪkəlt tu/",
    example: "Many find it difficult to afford rent.",
  },
  {
    id: "cl-basic-needs",
    front: "to meet their basic needs",
    back: "đáp ứng nhu cầu cơ bản của họ",
    pronunciation: "/biːsɪk niːdz/",
    example: "Cities help meet their basic needs.",
  },
  {
    id: "cl-migrate-countryside",
    front: "to migrate from the countryside to cities",
    back: "di cư từ nông thôn ra thành phố",
    pronunciation: "/ˈkʌntrisaɪd/",
    example: "Many migrate from countryside to cities.",
  },
  {
    id: "cl-search-of-work",
    front: "in search of work",
    back: "để tìm việc",
    pronunciation: "/ɪn sɜːtʃ əv wɜːk/",
    example: "They come in search of work.",
  },
  {
    id: "cl-better-life",
    front: "in the hope of having a better life",
    back: "với hy vọng có một cuộc sống tốt đẹp hơn",
    pronunciation: "/həʊp əv hævɪŋ ə ˈbɛtər laɪf/",
    example: "They move hoping for a better life.",
  },
  {
    id: "cl-high-living-costs",
    front: "high living costs",
    back: "chi phí sinh hoạt cao",
    pronunciation: "/lɪvɪŋ kɒsts/",
    example: "High living costs burden city residents.",
  },
  {
    id: "cl-pollution-noise",
    front: "high levels of pollution and noise",
    back: "mức độ ô nhiễm và tiếng ồn cao",
    pronunciation: "/ˈnɔɪz/",
    example: "Cities have high levels of noise.",
  },
  {
    id: "cl-poor-air-quality",
    front: "poor air quality",
    back: "chất lượng không khí kém",
    pronunciation: "/pɔːr ɛə ˈkwɒlɪti/",
    example: "Poor air quality affects health.",
  },
  {
    id: "cl-pay-higher-prices",
    front: "to pay higher prices for food, accommodation and transportation",
    back: "trả giá cao hơn cho thức ăn, chỗ ở và phương tiện đi lại",
    pronunciation: "/əˌkɒməˈdeɪʃn/",
    example: "Cities mean paying higher prices.",
  },
  {
    id: "cl-traffic-congestion-problems",
    front:
      "traffic congestion, high crime and poverty rates, environmental degradation, lack of sufficient housing/open space",
    back: "tắc nghẽn giao thông, tỷ lệ tội phạm và đói nghèo cao, suy thoái môi trường, thiếu nhà ở / không gian mở",
    pronunciation: "/kənˈdʒɛstʃn/",
    example: "Cities face traffic, crime and pollution.",
  },
  {
    id: "cl-health-problems",
    front: "to suffer from various health problems such as asthma, obesity or stroke",
    back: "bị các vấn đề sức khỏe khác nhau như hen suyễn, béo phì hoặc đột quỵ",
    pronunciation: "/ˈæsmə/",
    example: "City life causes asthma and obesity.",
  },
  {
    id: "cl-higher-risk",
    front: "to be at a higher risk of stress, depression, anxiety disorders",
    back: "có nguy cơ cao bị căng thẳng, trầm cảm, rối loạn lo âu",
    pronunciation: "/haɪər rɪsk/",
    example: "City life raises stress risks.",
  },
  {
    id: "cl-sedentary",
    front: "to lead a sedentary lifestyle",
    back: "có một lối sống ít vận động",
    pronunciation: "/ˈsɛdntri/",
    example: "City dwellers lead sedentary lifestyles.",
  },
  {
    id: "cl-poor-quality",
    front: "to have a poor quality of life",
    back: "có chất lượng cuộc sống kém",
    pronunciation: "/kwɒlɪti əv laɪf/",
    example: "Some have a poor quality of life.",
  },
  {
    id: "cl-slums",
    front: "to live in slums or informal settlements",
    back: "sống trong khu ổ chuột hoặc khu định cư không chính thức",
    pronunciation: "/slʌmz/",
    example: "Many still live in slums.",
  },
  {
    id: "cl-sewage",
    front: "inadequate sewage facilities",
    back: "cơ sở thoát nước không đầy đủ",
    pronunciation: "/ɪnˈædɪkwət ˈsjuːɪdʒ/",
    example: "Slums lack adequate sewage facilities.",
  },
  {
    id: "cl-water-sanitation",
    front: "water and sanitation problems",
    back: "những vấn đề về nước và vệ sinh",
    pronunciation: "/ˌsænɪˈteɪʃn/",
    example: "Sanitation problems plague poor areas.",
  },
  {
    id: "cl-gap-rich-poor",
    front: "to have a wider gap between rich and poor",
    back: "có khoảng cách rộng hơn giữa người giàu và người nghèo",
    pronunciation: "/ɡæp bɪˈtwiːn rɪtʃ ənd pɔːr/",
    example: "Cities widen the rich-poor gap.",
  },
  {
    id: "cl-financial-difficulties",
    front: "to face financial difficulties = to struggle financially",
    back: "đối mặt với khó khăn tài chính",
    pronunciation: "/faɪˈnænʃl ˈdɪfɪkəltiz/",
    example: "Many face financial difficulties.",
  },
  {
    id: "cl-faster-pace",
    front: "a faster pace of life",
    back: "tốc độ sống nhanh hơn",
    pronunciation: "/ˈfɑːstə peɪs/",
    example: "City life is faster-paced.",
  },
  {
    id: "cl-inner-city",
    front: "to live in inner-city areas = to live in central parts of cities",
    back: "sống ở khu vực nội thành = sống ở trung tâm thành phố",
    pronunciation: "/ˈɪnər sɪti/",
    example: "We live in inner-city areas.",
  },
  {
    id: "cl-transport-links",
    front: "to have better transport links",
    back: "có hệ thống giao thông tốt hơn",
    pronunciation: "/ˈtrænspɔːt lɪŋks/",
    example: "Cities have better transport links.",
  },
  {
    id: "cl-job-opportunities",
    front: "to offer more job opportunities",
    back: "cung cấp nhiều cơ hội việc làm hơn",
    pronunciation: "/dʒɒb ˌɒpəˈtjuːnɪtiz/",
    example: "Cities offer more job opportunities.",
  },
  {
    id: "cl-amenities",
    front: "to be close to amenities such as shopping centres, cinemas, libraries",
    back: "gần các tiện nghi như trung tâm mua sắm, rạp chiếu phim, thư viện",
    pronunciation: "/əˈmɛnɪtiz/",
    example: "Cities are close to all amenities.",
  },
  {
    id: "cl-better-facilities",
    front: "to have access to better educational facilities, medical services",
    back: "được tiếp cận với các cơ sở giáo dục, dịch vụ y tế tốt hơn",
    pronunciation: "/ɛdjuˈkeɪʃənl fəˈsɪlɪtiz/",
    example: "Cities have better schools and hospitals.",
  },
  // ── Culture ────────────────────────────────────────────────────────────
  {
    id: "cu-instil",
    front: "to instil cultural and traditional values into somebody",
    back: "thấm nhuần các giá trị truyền thống và văn hóa vào ai đó",
    pronunciation: "/ɪnˈstɪl/",
    example: "Schools instil cultural values in students.",
  },
  {
    id: "cu-cultural-diversity",
    front: "cultural diversity",
    back: "sự đa dạng văn hóa",
    pronunciation: "/ˈkʌltʃərəl daɪˈvɜːsəti/",
    example: "Cultural diversity enriches society.",
  },
  {
    id: "cu-cultural-identity",
    front: "cultural identity",
    back: "bản sắc văn hóa",
    pronunciation: "/aɪˈdɛntəti/",
    example: "Language shapes cultural identity.",
  },
  {
    id: "cu-cultural-heritage",
    front: "cultural heritage",
    back: "di sản văn hóa",
    pronunciation: "/ˈhɛrɪtɪdʒ/",
    example: "We must preserve cultural heritage.",
  },
  {
    id: "cu-cultural-assimilation",
    front: "cultural assimilation",
    back: "sự hòa tan văn hóa",
    pronunciation: "/əˌsɪmɪˈleɪʃn/",
    example: "Cultural assimilation can be harmful.",
  },
  {
    id: "cu-traditional-beliefs",
    front: "traditional beliefs and customs",
    back: "các phong tục và niềm tin truyền thống",
    pronunciation: "/ˈkʌstəmz/",
    example: "Traditions include beliefs and customs.",
  },
  {
    id: "cu-loss-cultures",
    front: "the loss of traditional cultures = the disappearance of traditional ways of life",
    back: "sự mất đi của các văn hóa truyền thống",
    pronunciation: "/ˌdɪsəˈpɪərəns/",
    example: "We face the loss of traditional cultures.",
  },
  {
    id: "cu-adopt-new",
    front: "to adopt a new culture",
    back: "theo một nền văn hóa mới",
    pronunciation: "/əˈdɒpt ə njuː ˈkʌltʃər/",
    example: "Some adopt a new culture.",
  },
  {
    id: "cu-danger-extinction",
    front: "to be in danger of extinction",
    back: "đứng trước nguy cơ tuyệt chủng",
    pronunciation: "/ɪkˈstɪŋkʃn/",
    example: "Many languages are in danger of extinction.",
  },
  {
    id: "cu-culture-shock",
    front: "culture shock and other culture-related problems",
    back: "sốc văn hóa và những vấn đề khác liên quan đến văn hóa",
    pronunciation: "/ˈkʌltʃər ʃɒk/",
    example: "Travelers experience culture shock.",
  },
  {
    id: "cu-great-shock",
    front: "to experience great culture shock",
    back: "trải qua cú sốc văn hóa lớn",
    pronunciation: "/ɡreɪt ˈkʌltʃər ʃɒk/",
    example: "Immigrants may experience great culture shock.",
  },
  {
    id: "cu-broad-benefits",
    front: "to bring a wide range of benefits to...",
    back: "mang lại nhiều lợi ích cho ...",
    pronunciation: "/braɪd ˈrændʒ əv ˈbɛnɪfɪts/",
    example: "Multiculturalism brings many benefits.",
  },
  {
    id: "cu-negative-impact",
    front: "to have a negative/detrimental impact on...",
    back: "có tác động tiêu cực lên ...",
    pronunciation: "/ˌdɛtrɪˈmɛntl/",
    example: "Tourism has a detrimental impact on culture.",
  },
  {
    id: "cu-deeper-insight",
    front: "to get deeper insight into...",
    back: "có được cái nhìn sâu sắc hơn về ...",
    pronunciation: "/ˈɪnsaɪt/",
    example: "Travel gives deeper insight into cultures.",
  },
  {
    id: "cu-experience-diversity",
    front: "to travel to other countries for experiencing culture diversity",
    back: "đi du lịch nước ngoài để trải nghiệm sự đa dạng văn hóa",
    pronunciation: "/ˌɪkspɪəriənsɪŋ/",
    example: "I travel to experience cultural diversity.",
  },
  {
    id: "cu-broaden-horizons",
    front: "to broaden their horizons",
    back: "mở mang tầm nhìn của họ",
    pronunciation: "/ˈbrɔːdn ˈhɒrɪznz/",
    example: "Travel broadens your horizons.",
  },
  {
    id: "cu-respect",
    front: "to show great respect for...",
    back: "thể hiện sự tôn trọng ai đó / điều gì đó",
    pronunciation: "/rɪˈspɛkt/",
    example: "Show great respect for other cultures.",
  },
  {
    id: "cu-sense-identity",
    front: "a strong sense of identity",
    back: "một cái tôi / bản sắc mạnh mẽ",
    pronunciation: "/strɒŋ sɛns əv aɪˈdɛntəti/",
    example: "Cultures provide a strong sense of identity.",
  },
  {
    id: "cu-western-influence",
    front: "the growing influence of western culture",
    back: "sự ảnh hưởng ngày càng tăng của văn hóa phương Tây",
    pronunciation: "/ˈwɛstən ˈkʌltʃər/",
    example: "Western culture influences local traditions.",
  },
  {
    id: "cu-minority-languages",
    front: "the disappearance of some minority languages",
    back: "sự biến mất của 1 số ngôn ngữ thiểu số",
    pronunciation: "/maɪˈnɒrɪti/",
    example: "Some minority languages are dying out.",
  },
  {
    id: "cu-multicultural",
    front: "a multicultural society",
    back: "một xã hội đa văn hóa",
    pronunciation: "/ˌmʌltiˈkʌltʃərəl/",
    example: "Many cities are multicultural societies.",
  },
  {
    id: "cu-cultural-backgrounds",
    front: "people of different cultural backgrounds",
    back: "người thuộc các nền văn hóa khác nhau",
    pronunciation: "/ˈbækɡraʊndz/",
    example: "People from different cultural backgrounds thrive.",
  },
  {
    id: "cu-tension-conflict",
    front: "to lead to tension and conflict",
    back: "dẫn tới căng thẳng và xung đột",
    pronunciation: "/ˈtɛnʃn/",
    example: "Cultural differences can lead to conflict.",
  },
  {
    id: "cu-abandon",
    front: "to abandon one's own culture",
    back: "từ bỏ văn hóa của ai đó",
    pronunciation: "/əˈbændən/",
    example: "People shouldn't abandon their culture.",
  },
  // ── Tourism ───────────────────────────────────────────────────────────
  {
    id: "tu-travel-abroad",
    front: "to travel abroad = to travel to a foreign country",
    back: "đi du lịch nước ngoài",
    pronunciation: "/əˈbrɔːd/",
    example: "I love to travel abroad.",
  },
  {
    id: "tu-sight-seeing",
    front: "to go sight-seeing",
    back: "đi tham quan",
    pronunciation: "/ˈsaɪtˌsiːɪŋ/",
    example: "We go sight-seeing on weekends.",
  },
  {
    id: "tu-relax-stress",
    front: "a great way to relax and reduce stress",
    back: "một cách tuyệt vời để xả hơi và giảm căng thẳng",
    pronunciation: "/rɪˈlæks/",
    example: "Travel is a great way to relax.",
  },
  {
    id: "tu-have-opportunity",
    front: "to have the opportunity to...",
    back: "có cơ hội làm gì",
    pronunciation: "/ˌɒpəˈtjuːnəti/",
    example: "Tourism lets us have the opportunity to learn.",
  },
  {
    id: "tu-different-cultures",
    front: "to experience different cultures and traditions",
    back: "trải nghiệm những nền văn hóa và truyền thống khác nhau",
    pronunciation: "/ˈkʌltʃəz/",
    example: "We experience different cultures.",
  },
  {
    id: "tu-new-language",
    front: "to learn a new language",
    back: "học một ngôn ngữ mới",
    pronunciation: "/njuː ˈlæŋɡwɪdʒ/",
    example: "Many learn a new language when travelling.",
  },
  {
    id: "tu-broaden-horizons",
    front: "to broaden our horizons",
    back: "mở rộng tầm mắt của chúng ta",
    pronunciation: "/ˈbrɔːdn ˈhɒrɪznz/",
    example: "Travel broadens our horizons.",
  },
  {
    id: "tu-useful-skills",
    front: "to learn useful skills",
    back: "học được những kỹ năng hữu ích",
    pronunciation: "/ˈjuːsfʊl skɪlz/",
    example: "Travel teaches useful skills.",
  },
  {
    id: "tu-important-role",
    front: "to play an important role in...",
    back: "đóng một vai trò quan trọng trong ...",
    pronunciation: "/ɪmˈpɔːtənt rəʊl/",
    example: "Tourism plays an important role in the economy.",
  },
  {
    id: "tu-local-people",
    front: "to create more job opportunities for local people",
    back: "tạo ra nhiều cơ hội việc làm hơn cho người dân địa phương",
    pronunciation: "/ˈləʊkl ˈpiːpl/",
    example: "Tourism creates jobs for locals.",
  },
  {
    id: "tu-living-standards",
    front: "to improve living standards",
    back: "cải thiện mức sống",
    pronunciation: "/ˈlɪvɪŋ ˈstændədz/",
    example: "Tourism improves living standards.",
  },
  {
    id: "tu-high-living-costs",
    front: "high living costs",
    back: "chi phí cuộc sống cao",
    pronunciation: "/haɪ ˈlɪvɪŋ kɒsts/",
    example: "Tourism raises high living costs.",
  },
  {
    id: "tu-pose-threat",
    front: "to pose a serious threat to...",
    back: "gây ra sự đe dọa nghiêm trọng cho ...",
    pronunciation: "/pəʊz ə ˈsɪəriəs θrɛt/",
    example: "Tourism poses threats to nature.",
  },
  {
    id: "tu-destroy-habitats",
    front: "to destroy natural habitats",
    back: "phá hủy môi trường sống tự nhiên",
    pronunciation: "/dɪˈstrɔɪ ˈnætʃərəl ˈhæbɪtæts/",
    example: "Mass tourism destroys habitats.",
  },
  {
    id: "tu-loss-cultures",
    front: "the loss of traditional cultures",
    back: "việc mất đi các văn hóa truyền thống",
    pronunciation: "/lɒs əv trəˈdɪʃənl ˈkʌltʃəz/",
    example: "Tourism may erode traditional cultures.",
  },
  {
    id: "tu-cultural-diversity",
    front: "cultural diversity",
    back: "sự đa dạng văn hóa",
    pronunciation: "/daɪˈvɜːsəti/",
    example: "Cultural diversity attracts tourists.",
  },
  {
    id: "tu-destinations",
    front: "popular tourist destinations = famous tourist attractions",
    back: "những điểm đến du lịch phổ biến",
    pronunciation: "/ˌdɛstɪˈneɪʃn/",
    example: "Bali is a popular tourist destination.",
  },
  {
    id: "tu-millions-tourists",
    front: "to attract millions of tourists",
    back: "thu hút hàng triệu khách du lịch",
    pronunciation: "/əˈtrækt/",
    example: "Bangkok attracts millions of tourists.",
  },
  {
    id: "tu-boost-economy",
    front: "to boost economy",
    back: "thúc đẩy kinh tế",
    pronunciation: "/buːst ɪˈkɒnəmi/",
    example: "Tourism boosts the economy.",
  },
  {
    id: "tu-spectacular",
    front: "to see spectacular landscapes, wildlife and plants",
    back: "chiêm ngưỡng những khung cảnh tuyệt vời, động thực vật hoang dã",
    pronunciation: "/spɛkˈtækjʊlər/",
    example: "We see spectacular landscapes.",
  },
  {
    id: "tu-range-benefits",
    front: "to bring a wide range of benefits",
    back: "mang tới rất nhiều lợi ích",
    pronunciation: "/braɪd reɪndʒ əv ˈbɛnɪfɪts/",
    example: "Tourism brings many benefits.",
  },
  {
    id: "tu-cause-damage",
    front: "to cause damage to...",
    back: "gây tổn thất cho ...",
    pronunciation: "/kɔːz ˈdæmɪdʒ/",
    example: "Tourism can cause damage to ecosystems.",
  },
  {
    id: "tu-tourist",
    front: "tourist = traveler = visitor",
    back: "du khách",
    pronunciation: "/ˈtʊərɪst/",
    example: "Visitors enjoy the local cuisine.",
  },
  {
    id: "tu-traditional-jobs",
    front: "traditional jobs and skills",
    back: "những kỹ năng và công việc truyền thống",
    pronunciation: "/trəˈdɪʃənl dʒɒbs/",
    example: "Modern tourism threatens traditional jobs.",
  },
  {
    id: "tu-disappear",
    front: "to disappear = to die out",
    back: "biến mất",
    pronunciation: "/dɪsəˈpɪər/",
    example: "Traditional crafts can disappear.",
  },
  {
    id: "tu-adopt-culture",
    front: "to adopt a new culture",
    back: "theo một nền văn hóa mới",
    pronunciation: "/əˈdɒpt ə njuː ˈkʌltʃər/",
    example: "Tourists may adopt new cultures.",
  },
  {
    id: "tu-culture-shock",
    front: "culture shock",
    back: "sốc văn hóa",
    pronunciation: "/ˈkʌltʃər ʃɒk/",
    example: "Many travellers face culture shock.",
  },
  {
    id: "tu-pressure-environment",
    front: "to put heavy pressure on the environment",
    back: "đặt áp lực nặng nề lên môi trường",
    pronunciation: "/ˈprɛʃər ɒn ði ɪnˈvaɪərənmənt/",
    example: "Tourism pressures the environment.",
  },
  // ── Transport ─────────────────────────────────────────────────────────
  {
    id: "tr-car-users",
    front: "people who travel by car = people travelling by car = car users",
    back: "những người đi lại bằng xe hơi",
    pronunciation: "/kɑː ˈjuːzəz/",
    example: "Car users contribute to congestion.",
  },
  {
    id: "tr-train-passengers",
    front: "people who travel by train = people travelling by train = train passengers",
    back: "những người đi lại bằng xe lửa",
    pronunciation: "/treɪn ˈpæsɪndʒəz/",
    example: "Train passengers prefer fast travel.",
  },
  {
    id: "tr-drive-to-work",
    front: "to drive to work = to travel/go/commute to work by car",
    back: "đi làm bằng xe hơi",
    pronunciation: "/draɪv tuː wɜːk/",
    example: "Many drive to work daily.",
  },
  {
    id: "tr-public-transport",
    front: "to use public transport instead of private vehicles",
    back: "sử dụng phương tiện giao thông công cộng thay vì xe riêng",
    pronunciation: "/ˈpʌblɪk ˈtrænspɔːt/",
    example: "Use public transport to ease traffic.",
  },
  {
    id: "tr-popular-commute",
    front: "the most popular way to commute = the most popular mode of transport",
    back: "cách phổ biến nhất để đi lại / phương tiện giao thông phổ biến nhất",
    pronunciation: "/kəˈmjuːt/",
    example: "Cars are the most popular mode of transport.",
  },
  {
    id: "tr-commuting-costs",
    front: "commuting costs",
    back: "chi phí đi lại",
    pronunciation: "/kəˈmjuːtɪŋ kɒsts/",
    example: "Commuting costs add up over time.",
  },
  {
    id: "tr-long-distances",
    front: "to commute/travel long distances to...",
    back: "đi quãng đường dài tới ...",
    pronunciation: "/lɒŋ ˈdɪstənsɪz/",
    example: "Many commute long distances daily.",
  },
  {
    id: "tr-daily-commute",
    front: "daily travel = daily commute",
    back: "việc đi lại hàng ngày",
    pronunciation: "/ˈdeɪli kəˈmjuːt/",
    example: "Daily commute takes time.",
  },
  {
    id: "tr-driving-influence",
    front: "driving under the influence of...",
    back: "lái xe dưới sự ảnh hưởng của ...",
    pronunciation: "/ˈɪnfluəns/",
    example: "Never drive under the influence of alcohol.",
  },
  {
    id: "tr-run-red-light",
    front: "to run a red light",
    back: "vượt đèn đỏ",
    pronunciation: "/rʌn ə rɛd laɪt/",
    example: "Running a red light is dangerous.",
  },
  {
    id: "tr-pedestrian",
    front: "pedestrian (n)",
    back: "người đi bộ",
    pronunciation: "/pɪˈdɛstriən/",
    example: "Pedestrians cross at the zebra.",
  },
  {
    id: "tr-cycle-lanes",
    front: "cycle lanes = bike lanes",
    back: "những tuyến đường dành cho người đi xe đạp",
    pronunciation: "/ˈsaɪkəl leɪnz/",
    example: "Cycle lanes keep cyclists safe.",
  },
  {
    id: "tr-traffic-safety",
    front: "to improve road traffic safety",
    back: "cải thiện an toàn giao thông đường bộ",
    pronunciation: "/rəʊd ˈtræfɪk ˈseɪfti/",
    example: "Better signs improve traffic safety.",
  },
  {
    id: "tr-reduce-accidents",
    front: "to reduce traffic accidents",
    back: "giảm thiểu tai nạn giao thông",
    pronunciation: "/rɪˈdjuːs ˈtræfɪk ˈæksɪdənts/",
    example: "Speed cameras reduce traffic accidents.",
  },
  {
    id: "tr-driving-offence",
    front: "driving offence",
    back: "sự vi phạm luật giao thông",
    pronunciation: "/ˈdraɪvɪŋ ˈɒfəns/",
    example: "Speeding is a driving offence.",
  },
  {
    id: "tr-licence-suspension",
    front: "licence suspension",
    back: "việc tịch thu bằng lái",
    pronunciation: "/ˈlaɪsəns səˌspɛnʃn/",
    example: "Drink-driving leads to licence suspension.",
  },
  {
    id: "tr-speed-cameras",
    front: "to install speed cameras",
    back: "lắp đặt các camera theo dõi tốc độ",
    pronunciation: "/spiːd ˈkæmərəz/",
    example: "Speed cameras deter speeding.",
  },
  {
    id: "tr-speeding",
    front: "speeding (n)",
    back: "việc lái xe quá tốc độ",
    pronunciation: "/ˈspiːdɪŋ/",
    example: "Speeding causes accidents.",
  },
  {
    id: "tr-stricter-punishments",
    front: "to impose stricter punishments on somebody",
    back: "áp đặt các hình phạt nghiêm khắc hơn lên ai đó",
    pronunciation: "/ɪmˈpəʊz ˈstrɪktər ˈpʌnɪʃmənts/",
    example: "Impose stricter punishments on speeders.",
  },
  {
    id: "tr-traffic-jams",
    front: "traffic jams = traffic congestion",
    back: "sự ùn tắc giao thông",
    pronunciation: "/ˈtræfɪk dʒæmz/",
    example: "Traffic jams waste time and fuel.",
  },
  {
    id: "tr-driving-habits",
    front: "bad driving habits",
    back: "những thói quen xấu khi lái xe",
    pronunciation: "/bæd ˈdraɪvɪŋ ˈhæbɪts/",
    example: "Bad driving habits cause accidents.",
  },
  {
    id: "tr-congestion-pricing",
    front: "congestion pricing = congestion charges",
    back: "việc thu phí ùn tắc giao thông",
    pronunciation: "/kənˈdʒɛstʃn ˈpraɪsɪŋ/",
    example: "Congestion pricing reduces city traffic.",
  },
  {
    id: "tr-ban-cars",
    front: "to ban cars from city centres",
    back: "cấm xe hơi khỏi các trung tâm thành phố",
    pronunciation: "/bæn kɑːz/",
    example: "Some cities ban cars from centres.",
  },
  {
    id: "tr-parking-space",
    front: "parking space",
    back: "khu vực đậu xe",
    pronunciation: "/ˈpɑːkɪŋ speɪs/",
    example: "Parking space is limited downtown.",
  },
  {
    id: "tr-pose-threat",
    front: "to pose a serious threat to...",
    back: "gây ra sự đe dọa nghiêm trọng cho ...",
    pronunciation: "/pəʊz ə ˈsɪəriəs θrɛt/",
    example: "Cars pose threats to the environment.",
  },
  {
    id: "tr-dangerous-drivers",
    front: "dangerous drivers",
    back: "những người lái xe nguy hiểm",
    pronunciation: "/ˈdeɪndʒərəs ˈdraɪvəz/",
    example: "Dangerous drivers should be penalised.",
  },
  {
    id: "tr-encouraged",
    front: "to be encouraged to...",
    back: "được khuyến khích làm gì",
    pronunciation: "/ɪnˈkʌrɪdʒd tu/",
    example: "People are encouraged to cycle.",
  },
  {
    id: "tr-raise-awareness",
    front: "to raise people's awareness",
    back: "nâng cao ý thức con người",
    pronunciation: "/reɪz ˈpiːplz əˈwɛənəs/",
    example: "Campaigns raise awareness of safety.",
  },
  // ── Housing & Architecture ────────────────────────────────────────────
  {
    id: "ha-ventilation-materials",
    front: "the use of good ventilation and durable materials",
    back: "việc sử dụng chất liệu bền vững và hệ thống thông gió tốt",
    pronunciation: "/ˌvɛntɪˈleɪʃn/",
    example: "Houses need good ventilation.",
  },
  {
    id: "ha-minor-modifications",
    front: "minor modifications",
    back: "những điều chỉnh nhỏ",
    pronunciation: "/ˈmaɪnər ˌmɒdɪfɪˈkeɪʃnz/",
    example: "Minor modifications can refresh a home.",
  },
  {
    id: "ha-modern-building",
    front: "to meet modern building requirements = to meet the requirements of modern use",
    back: "đáp ứng yêu cầu của kiến trúc hiện đại",
    pronunciation: "/ˈbɪldɪŋ rɪˈkwaɪərmənts/",
    example: "Houses meet modern building requirements.",
  },
  {
    id: "ha-protect-cultural",
    front: "to protect cultural resources",
    back: "bảo vệ nguồn lực văn hóa",
    pronunciation: "/ˈkʌltʃərəl rɪˈsɔːsɪz/",
    example: "We protect cultural resources in old buildings.",
  },
  {
    id: "ha-preservation-efforts",
    front: "preservation efforts",
    back: "những nỗ lực bảo tồn",
    pronunciation: "/ˌprɛzəˈveɪʃn ˈɛfəts/",
    example: "Preservation efforts save historic sites.",
  },
  {
    id: "ha-under-threat",
    front: "to be under threat from...",
    back: "bị đe dọa bởi ...",
    pronunciation: "/ʌndər θrɛt/",
    example: "Buildings under threat from climate change.",
  },
  {
    id: "ha-destroyed-replaced",
    front: "to be destroyed and replaced by ... = to be demolished to make way for ...",
    back: "bị dỡ bỏ / phá hủy và bị thay thế bởi ...",
    pronunciation: "/dɪˈmɒlɪʃt tuː meɪk weɪ fɔːr/",
    example: "Old buildings are demolished to make way for new ones.",
  },
  {
    id: "ha-build-construct",
    front: "to build = to construct",
    back: "xây dựng",
    pronunciation: "/kənˈstrʌkt/",
    example: "They construct new homes yearly.",
  },
  {
    id: "ha-historic-buildings",
    front: "historic buildings = historical architectural styles = buildings with historic values",
    back: "những tòa nhà với những giá trị lịch sử",
    pronunciation: "/hɪˈstɒrɪk ˈbɪldɪŋz/",
    example: "Historic buildings are worth protecting.",
  },
  {
    id: "ha-materials",
    front: "materials such as plastic, wood, stone, reinforced concrete",
    back: "các chất liệu như nhựa, gỗ, đá, bê tông",
    pronunciation: "/ˌriːɪnˈfɔːst ˈkɒŋkriːt/",
    example: "Modern buildings use reinforced concrete.",
  },
  {
    id: "ha-quality-materials",
    front: "high-quality / low-quality materials",
    back: "chất liệu chất lượng cao / thấp",
    pronunciation: "/ˈkwɒlɪti məˈtɪəriəlz/",
    example: "Choose high-quality materials for durability.",
  },
  {
    id: "ha-vertical-vs-horizontal",
    front: "vertical buildings vs horizontal buildings",
    back: "tòa nhà thẳng đứng vs tòa nhà ngang",
    pronunciation: "/ˈvɜːtɪkl ˈbɪldɪŋz/",
    example: "Skyscrapers are vertical buildings.",
  },
  {
    id: "ha-integral-part",
    front: "to be an integral part of...",
    back: "là 1 phần không thể thiếu của ...",
    pronunciation: "/ˈɪntɪɡrəl/",
    example: "Architecture is an integral part of culture.",
  },
  {
    id: "ha-iconic-buildings",
    front: "iconic buildings",
    back: "những tòa nhà mang tính biểu tượng",
    pronunciation: "/aɪˈkɒnɪk/",
    example: "Eiffel Tower is an iconic building.",
  },
  {
    id: "ha-traditional-styles",
    front: "to construct new houses in traditional architectural styles",
    back: "xây nhà mới theo kiến trúc truyền thống",
    pronunciation: "/trəˈdɪʃənl ˌɑːkɪˈtɛktʃərəl/",
    example: "New houses use traditional styles.",
  },
  {
    id: "ha-mirror-standards",
    front: "to mirror past architectural standards",
    back: "phản chiếu những tiêu chuẩn kiến trúc của quá khứ",
    pronunciation: "/ˈmɪrər pɑːst/",
    example: "Some new buildings mirror past standards.",
  },
  {
    id: "ha-energy-efficient",
    front: "energy-efficient homes",
    back: "những ngôi nhà sử dụng năng lượng hiệu quả",
    pronunciation: "/ˈɛnədʒi ɪˈfɪʃənt/",
    example: "Energy-efficient homes save money.",
  },
  {
    id: "ha-reflect-culture",
    front: "to reflect the culture of a society",
    back: "phản chiếu văn hóa của một xã hội",
    pronunciation: "/rɪˈflɛkt/",
    example: "Homes reflect a society's culture.",
  },
  {
    id: "ha-tourist-destination",
    front: "to become a famous tourist destination",
    back: "trở thành địa điểm du lịch nổi tiếng",
    pronunciation: "/ˈdɛstɪˌneɪʃn/",
    example: "Old towns become tourist destinations.",
  },
  {
    id: "ha-demolition",
    front: "the destruction of historic buildings = the demolition of historic buildings",
    back: "việc phá hủy những tòa nhà lịch sử",
    pronunciation: "/ˌdɛməˈlɪʃn/",
    example: "Demolition of historic buildings is controversial.",
  },
  {
    id: "ha-prevent-disrepair",
    front: "to prevent historic buildings from falling into disrepair",
    back: "ngăn chặn những tòa nhà lịch sử rơi vào tình trạng hư hỏng",
    pronunciation: "/dɪsrɪˈpɛər/",
    example: "Maintain buildings to prevent disrepair.",
  },
  {
    id: "ha-prevent-damage",
    front: "to prevent damage to...",
    back: "ngăn ngừa tổn thất đối với",
    pronunciation: "/prɪˈvɛnt ˈdæmɪdʒ/",
    example: "Prevent damage to historic sites.",
  },
  {
    id: "ha-save-from-neglect",
    front: "to save ... from the threat of neglect",
    back: "cứu ... khỏi mối đe dọa của sự thờ ơ",
    pronunciation: "/nɪˈɡlɛkt/",
    example: "Save buildings from neglect.",
  },
  {
    id: "ha-risk-neglect",
    front: "to be at risk from neglect and decay",
    back: "rơi vào nguy cơ bị thờ ơ và suy tàn",
    pronunciation: "/rɪsk frəm nɪˈɡlɛkt/",
    example: "Many buildings are at risk from neglect.",
  },
  {
    id: "ha-repair-maintenance",
    front: "to require regular repair and maintenance",
    back: "đòi hỏi sự bảo trì và sửa chữa thường xuyên",
    pronunciation: "/rɪˈpɛər ənd ˈmeɪntənəns/",
    example: "Old homes require regular maintenance.",
  },
  // ── Working from Home ─────────────────────────────────────────────────
  {
    id: "wf-9-to-5",
    front: "9-to-5 office jobs",
    back: "công việc văn phòng từ 9 giờ sáng tới 5 giờ chiều",
    pronunciation: "/naɪn tuː faɪv/",
    example: "9-to-5 jobs are common.",
  },
  {
    id: "wf-flexibility",
    front: "to provide us with flexibility and convenience",
    back: "cung cấp cho chúng ta sự linh hoạt và tiện lợi",
    pronunciation: "/ˌflɛksəˈbɪləti/",
    example: "WFH provides flexibility.",
  },
  {
    id: "wf-work-whenever",
    front: "to work whenever and wherever they prefer",
    back: "làm việc bất cứ khi nào và bất cứ nơi đâu họ thích",
    pronunciation: "/wɜːk wɛnˈɛvər/",
    example: "Remote workers choose when they work.",
  },
  {
    id: "wf-work-alone",
    front: "to have to learn how to work alone effectively",
    back: "phải học cách làm việc 1 mình như thế nào cho hiệu quả",
    pronunciation: "/wɜːk əˈləʊn/",
    example: "Remote workers must learn to work alone.",
  },
  {
    id: "wf-not-need-office",
    front: "to not need to go to the office on a daily basis",
    back: "không cần tới công sở hàng ngày",
    pronunciation: "/ɡəʊ tuː ði ˈɒfɪs/",
    example: "WFH means no daily office commute.",
  },
  {
    id: "wf-save-commuting",
    front: "to save a large amount of time commuting back and forth to work",
    back: "tiết kiệm 1 lượng lớn thời gian đi lại",
    pronunciation: "/kəˈmjuːtɪŋ/",
    example: "WFH saves commuting time.",
  },
  {
    id: "wf-wasted-time",
    front: "to not need to waste time sitting in traffic",
    back: "không cần lãng phí thời gian kẹt xe",
    pronunciation: "/ˈweɪst taɪm/",
    example: "No more wasting time in traffic.",
  },
  {
    id: "wf-extra-time",
    front: "to have extra time for other important tasks",
    back: "có thêm thời gian cho các việc quan trọng hơn",
    pronunciation: "/ˈɛkstrə taɪm/",
    example: "WFH gives extra time for family.",
  },
  {
    id: "wf-spend-children",
    front: "to spend extra time with their children or spouse → to strengthen family relationships",
    back: "dành thêm thời gian với con cái hay bạn đời của họ → củng cố tình cảm gia đình",
    pronunciation: "/ˈɛkstrə taɪm/",
    example: "WFH strengthens family relationships.",
  },
  {
    id: "wf-total-control",
    front:
      "to be in total control of their working environment → to be free to create their own working environment so that they can feel comfortable while working",
    back: "hoàn toàn kiểm soát môi trường làm việc của họ → tự do tạo ra môi trường làm việc riêng để họ có thể cảm thấy thoải mái khi làm việc",
    pronunciation: "/ˈkɒmfətəbl/",
    example: "WFH gives total control of the environment.",
  },
  {
    id: "wf-freedom-choose",
    front: "to have the freedom to choose where and when they want to work",
    back: "có sự tự do lựa chọn nơi đâu và khi nào họ muốn làm việc",
    pronunciation: "/ˈfriːdəm tuː tʃuːz/",
    example: "Remote workers have the freedom to choose.",
  },
  {
    id: "wf-discipline",
    front: "to require high levels of discipline and commitment",
    back: "đòi hỏi mức độ kỷ luật và cam kết cao",
    pronunciation: "/dɪsɪplɪn/",
    example: "WFH requires discipline.",
  },
  {
    id: "wf-no-supervision",
    front: "to have no supervision and restrictions",
    back: "không có sự giám sát hay hạn chế nào",
    pronunciation: "/ˌsjuːpəˈvɪʒn/",
    example: "WFH has no supervision.",
  },
  {
    id: "wf-loneliness",
    front: "to might experience feelings of loneliness and isolation sometimes",
    back: "thỉnh thoảng có thể trải qua cảm giác cô đơn và đơn độc",
    pronunciation: "/ˈləʊnlinəs/",
    example: "Remote workers may feel lonely.",
  },
  {
    id: "wf-easily-distracted",
    front: "to easily get distracted by things like movies / online games /...",
    back: "dễ dàng bị sao nhãng bởi các thứ như phim, games online",
    pronunciation: "/dɪˈstræktɪd/",
    example: "WFH workers get easily distracted.",
  },
  {
    id: "wf-concentrate",
    front: "to cannot concentrate entirely on their work",
    back: "không thể hoàn toàn tập trung vào công việc",
    pronunciation: "/ˈkɒnsntreɪt/",
    example: "Distractions prevent concentration.",
  },
  {
    id: "wf-work-performance",
    front: "to negatively affect their work performance and productivity",
    back: "ảnh hưởng tiêu cực tới hiệu suất làm việc",
    pronunciation: "/pəˈfɔːməns/",
    example: "WFH can affect productivity.",
  },
  {
    id: "wf-develop-skills",
    front: "to find it difficult to develop social skills (communication, teamwork skills, ...)",
    back: "khó phát triển các kỹ năng xã hội (kỹ năng giao tiếp, làm việc đội nhóm, ...)",
    pronunciation: "/dɪˈvɛləp ˈsəʊʃl skɪlz/",
    example: "Remote work makes social skills harder to develop.",
  },
  {
    id: "wf-interact-colleagues",
    front:
      "to have less chance to interact and communicate directly with their colleagues and clients",
    back: "có ít cơ hội tương tác và giao tiếp trực tiếp với đồng nghiệp và khách hàng",
    pronunciation: "/ˌɪntərˈækt/",
    example: "WFH limits interactions with colleagues.",
  },
  // ── Christmas ─────────────────────────────────────────────────────────
  {
    id: "ch-invite-friends",
    front: "to invite some friends over for dinner",
    back: "mời vài người bạn tới nhà ăn tối",
    pronunciation: "/ɪnˈvaɪt/",
    example: "We invite friends over for dinner.",
  },
  {
    id: "ch-birth-anniversary",
    front: "to mark the birth anniversary of Jesus Christ",
    back: "đánh dấu kỷ niệm ngày sinh của Chúa Giêsu",
    pronunciation: "/bɜːθ əˈnɪvərsəri/",
    example: "Christmas marks Jesus Christ's birth.",
  },
  {
    id: "ch-exchange-gifts",
    front: "to exchange gifts with friends / family members",
    back: "trao đổi quà tặng với bạn bè / thành viên gia đình",
    pronunciation: "/ɪksˈtʃeɪndʒ ɡɪfts/",
    example: "We exchange gifts at Christmas.",
  },
  {
    id: "ch-quality-time",
    front: "to spend quality time with family members",
    back: "dành thời gian chất lượng với các thành viên trong gia đình",
    pronunciation: "/ˈkwɒlɪti taɪm/",
    example: "Christmas is for quality family time.",
  },
  {
    id: "ch-christmas-tree",
    front: "to buy a big Christmas tree",
    back: "mua một cây thông giáng sinh lớn",
    pronunciation: "/ˈkrɪsməs triː/",
    example: "We buy a big Christmas tree.",
  },
  {
    id: "ch-special-meal",
    front: "to prepare a special meal for their family",
    back: "chuẩn bị một bữa ăn đặc biệt cho gia đình họ",
    pronunciation: "/ˈspɛʃl miːl/",
    example: "Families prepare a special meal.",
  },
  {
    id: "ch-decorate-houses",
    front: "to decorate houses with coloured string lights, bauble ornaments and tiny flowers",
    back: "trang trí nhà cửa với đèn dây đầy màu sắc, đồ trang trí trang trí và các bông hoa li ti",
    pronunciation: "/ˈdɛkəreɪt ˈhaʊzɪz/",
    example: "Houses are decorated with lights.",
  },
  {
    id: "ch-religious",
    front: "a religious celebration",
    back: "một lễ kỷ niệm tôn giáo",
    pronunciation: "/rɪˈlɪdʒəs/",
    example: "Christmas is a religious celebration.",
  },
  {
    id: "ch-week-off",
    front: "to have a week off to celebrate Christmas",
    back: "có một tuần nghỉ để ăn mừng lễ Giáng sinh",
    pronunciation: "/wiːk ɒf/",
    example: "We have a week off at Christmas.",
  },
  {
    id: "ch-biggest-festival",
    front: "one of the biggest / most important festivals in western countries",
    back: "một trong những lễ hội lớn nhất / quan trọng nhất ở các nước phương tây",
    pronunciation: "/ˈbɪɡɪst ˈfɛstɪvəlz/",
    example: "Christmas is a major festival.",
  },
  {
    id: "ch-eat-drink-dance",
    front: "to eat, drink, dance, play music together",
    back: "ăn, uống, nhảy múa, chơi nhạc cùng nhau",
    pronunciation: "/pleɪ ˈmjuːzɪk/",
    example: "We eat, drink, dance together.",
  },
  {
    id: "ch-stay-home",
    front: "to stay at home and watch some Christmas movies",
    back: "ở nhà và xem một số bộ phim Giáng sinh",
    pronunciation: "/steɪ ət həʊm/",
    example: "Some stay home and watch Christmas movies.",
  },
  {
    id: "ch-white-christmas",
    front: "to travel to a place where I can celebrate a white Christmas",
    back: "du lịch đến một nơi mà tôi có thể ăn mừng Giáng sinh trắng",
    pronunciation: "/kɛlɪbreɪt ə waɪt ˈkrɪsməs/",
    example: "I travel for a white Christmas.",
  },
  {
    id: "ch-great-time",
    front: "to have a great time together",
    back: "có một thời gian tuyệt vời bên nhau",
    pronunciation: "/ɡreɪt taɪm/",
    example: "We have a great time together.",
  },
  {
    id: "ch-snowfall",
    front: "to experience some Christmas snowfall",
    back: "trải nghiệm tuyết rơi Giáng sinh",
    pronunciation: "/ˈsnəʊfɔːl/",
    example: "Christmas snowfall is magical.",
  },
  {
    id: "ch-snow-angels",
    front: "to make snow angels",
    back: "làm thiên thần tuyết",
    pronunciation: "/snəʊ ˈeɪndʒəlz/",
    example: "Children love making snow angels.",
  },
  {
    id: "ch-try-skiing",
    front: "to try skiing",
    back: "thử trượt tuyết",
    pronunciation: "/ˈskiːɪŋ/",
    example: "We try skiing in winter.",
  },
  {
    id: "ch-25-december",
    front: "to take place on 25th December",
    back: "diễn ra vào ngày 25 tháng 12",
    pronunciation: "/tʌwɛnti faɪfθ dɪˈsɛmbər/",
    example: "Christmas Day takes place on 25th December.",
  },
  {
    id: "ch-christmas-eve",
    front: "to be celebrated the night before which is called Christmas Eve",
    back: "được tổ chức vào đêm trước đó được gọi là đêm trước Giáng sinh",
    pronunciation: "/ˈkrɪsməs iːv/",
    example: "Christmas Eve is the night before.",
  },
  {
    id: "ch-hang-around",
    front: "to hang out around some streets",
    back: "đi chơi quanh một vài con đường",
    pronunciation: "/hæŋ aʊt/",
    example: "We hang out around the streets.",
  },
  {
    id: "ch-take-pictures",
    front: "to take lots of pictures",
    back: "chụp thật nhiều ảnh",
    pronunciation: "/teɪk lɒts əv ˈpɪktʃəz/",
    example: "We take lots of pictures.",
  },
  // ── Tet Holiday ────────────────────────────────────────────────────────
  {
    id: "th-week-off-tết",
    front: "to have one week off during Tet holiday",
    back: "được nghỉ một tuần trong dịp tết",
    pronunciation: "/tɛt ˈhɒlɪdeɪ/",
    example: "We have a week off during Tet.",
  },
  {
    id: "th-five-ten-days",
    front: "to often get five or even ten days off to celebrate Tet",
    back: "thường được nghỉ năm hoặc thậm chí mười ngày để ăn mừng Tết",
    pronunciation: "/fɪv d eɪz ɒf/",
    example: "We get 5-10 days off for Tet.",
  },
  {
    id: "th-lights-flowers",
    front: "to decorate their houses with coloured-string lights and colourful flowers",
    back: "trang trí nhà của họ với đèn dây màu và hoa lá đầy màu sắc",
    pronunciation: "/ˈkʌlərd straɪŋ laɪts/",
    example: "Houses are decorated for Tet.",
  },
  {
    id: "th-hang-streets-photos",
    front: "to hang out around some streets and take lots of photos",
    back: "đi chơi quanh một số đường phố và chụp rất nhiều ảnh",
    pronunciation: "/hæŋ aʊt/",
    example: "Many hang around streets and take photos.",
  },
  {
    id: "th-enjoy-meals",
    front: "to enjoy time / share meals with friends or family members",
    back: "tận hưởng thời gian / ăn những bữa ăn với bạn bè hoặc các thành viên trong gia đình",
    pronunciation: "/ɪnˈdʒɔɪ/",
    example: "We enjoy meals together at Tet.",
  },
  {
    id: "th-sing-dance-music",
    front: "to sing, dance, play music and play some games together",
    back: "hát, nhảy, chơi nhạc và chơi một số trò chơi cùng nhau",
    pronunciation: "/pleɪ sʌm ɡeɪmz/",
    example: "Families sing, dance and play games.",
  },
  {
    id: "th-loved-ones",
    front: "to spend quality time with their loved ones",
    back: "dành thời gian chất lượng với những người thân yêu của họ",
    pronunciation: "/kwɒlɪti taɪm/",
    example: "Tet is for spending time with loved ones.",
  },
  {
    id: "th-special-meal-for",
    front: "to prepare a special meal for...",
    back: "chuẩn bị một bữa ăn đặc biệt cho ...",
    pronunciation: "/prɪˈpɛər ə ˈspɛʃəl miːl/",
    example: "Prepare a special meal for the family.",
  },
  {
    id: "th-pray-church-pagoda",
    front: "to go to church / pagoda to pray for their families",
    back: "đến nhà thờ / chùa để cầu nguyện cho gia đình họ",
    pronunciation: "/pəˈɡəʊdə/",
    example: "Many go to pagoda at Tet.",
  },
  {
    id: "th-come-dinner",
    front: "to come over for dinner",
    back: "đến ăn tối",
    pronunciation: "/kʌm ˈəʊvər/",
    example: "Come over for dinner this weekend.",
  },
  {
    id: "th-lucky-money",
    front: "to give / receive lucky money",
    back: "tặng / nhận tiền lì xì",
    pronunciation: "/ˈlʌki mʌni/",
    example: "Children receive lucky money at Tet.",
  },
  {
    id: "th-visit-grandparents",
    front: "to visit their grandparents / friends / teachers,…",
    back: "thăm ông bà / bạn bè / giáo viên của họ",
    pronunciation: "/ˈvɪzɪt ˈɡrænˌpɛrənts/",
    example: "We visit grandparents at Tet.",
  },
  {
    id: "th-ancestors-stories",
    front: "to tell us stories about how our ancestors celebrated Tet in the past",
    back: "kể cho chúng tôi những câu chuyện về cách tổ tiên của chúng tôi ăn mừng Tết trong quá khứ",
    pronunciation: "/ˈænsɛstəz/",
    example: "Grandparents tell stories of past Tet.",
  },
  {
    id: "th-buy-new-things",
    front: "to buy new clothes / new shoes / new household items,…",
    back: "mua quần áo mới / giày mới / đồ gia dụng mới",
    pronunciation: "/njuː kloʊðz/",
    example: "We buy new clothes for Tet.",
  },
  {
    id: "th-play-cards",
    front: "to play cards",
    back: "chơi bài",
    pronunciation: "/pleɪ kɑːdz/",
    example: "Playing cards is a Tet tradition.",
  },
  {
    id: "th-prosperity-luck",
    front: "to represent prosperity, wealth and luck",
    back: "đại diện cho sự thịnh vượng, giàu có và may mắn",
    pronunciation: "/prɒsˈpɛrəti/",
    example: "Plants represent prosperity at Tet.",
  },
  {
    id: "th-best-wishes",
    front: "to give somebody my best wishes",
    back: "gửi tới ai đó những lời chúc tốt đẹp nhất của tôi",
    pronunciation: "/bɛst ˈwɪʃɪz/",
    example: "Send best wishes to family.",
  },
  {
    id: "th-first-footing",
    front: "to be the first person to enter somebody's house in the New Year",
    back: "là người đầu tiên xông nhà ai đó trong năm mới",
    pronunciation: "/fɜːst ˈfʊtɪŋ/",
    example: "First-footing is a Tet tradition.",
  },
  {
    id: "th-first-footing-n",
    front: "first-footing",
    back: "sự xông đất",
    pronunciation: "/fɜːst ˈfʊtɪŋ/",
    example: "First-footing is an important custom.",
  },
  {
    id: "th-full-blessings",
    front: "to be full of blessings",
    back: "tràn đầy phước lành",
    pronunciation: "/ˈblɛsɪŋz/",
    example: "May your year be full of blessings.",
  },
  // ── Sport and Exercise ────────────────────────────────────────────────
  {
    id: "sx-extreme-sports",
    front: "extreme sports = dangerous sports",
    back: "thể thao mạo hiểm",
    pronunciation: "/ɪkˈstriːm spɔːts/",
    example: "Extreme sports are risky.",
  },
  {
    id: "sx-life-threatening",
    front: "to be highly dangerous and life-threatening",
    back: "nguy hiểm và đe dọa đến tính mạng",
    pronunciation: "/laɪf ˈθrɛtnɪŋ/",
    example: "Some sports are life-threatening.",
  },
  {
    id: "sx-high-risk",
    front: "to involve a high level of risk",
    back: "liên quan đến mức độ rủi ro cao",
    pronunciation: "/haɪ lɛvl əv rɪsk/",
    example: "Extreme sports involve high risk.",
  },
  {
    id: "sx-bungee",
    front: "bungee jumping / freediving / ice climbing / skydiving / mountain biking /...",
    back: "nhảy bungee / nhảy tự do / leo núi băng / nhảy dù / đi xe đạp leo núi / ...",
    pronunciation: "/ˈbʌndʒi ˈdʒʌmpɪŋ/",
    example: "Bungee jumping is popular.",
  },
  {
    id: "sx-team-individual",
    front: "team sports vs individual sports",
    back: "thể thao đồng đội vs thể thao cá nhân",
    pronunciation: "/tiːm spɔːts/",
    example: "Football is a team sport.",
  },
  {
    id: "sx-sedentary-lifestyle",
    front: "to lead a sedentary lifestyle",
    back: "có một lối sống ít vận động",
    pronunciation: "/ˈsɛdntri ˈlaɪfˌstaɪl/",
    example: "Many lead sedentary lifestyles.",
  },
  {
    id: "sx-regular-exercise",
    front: "to take regular exercise",
    back: "tập thể dục thường xuyên",
    pronunciation: "/ˈrɛɡjʊlər ˈɛksərsaɪz/",
    example: "Take regular exercise for health.",
  },
  {
    id: "sx-physical-activities",
    front: "to spend more time engaging in physical activities",
    back: "dành nhiều thời gian hơn để tham gia vào các hoạt động thể chất",
    pronunciation: "/ˈfɪzɪkl ækˈtɪvɪtiz/",
    example: "Engage in physical activities.",
  },
  {
    id: "sx-keep-fit",
    front: "to keep fit and stay healthy",
    back: "giữ dáng và có sức khỏe tốt",
    pronunciation: "/kiːp fɪt/",
    example: "Exercise keeps you fit.",
  },
  {
    id: "sx-reduce-stress",
    front: "to reduce stress and depression",
    back: "giảm căng thẳng và trầm cảm",
    pronunciation: "/rɪˈdjuːs strɛs/",
    example: "Sport reduces stress.",
  },
  {
    id: "sx-burn-calories",
    front: "to burn calories and build muscle → to maintain a healthy weight",
    back: "đốt calo và xây dựng cơ bắp → duy trì một cân nặng tốt",
    pronunciation: "/bɜːn ˈkæləriz/",
    example: "Exercise burns calories and builds muscle.",
  },
  {
    id: "sx-independence",
    front: "to have the opportunity to develop independence",
    back: "có cơ hội phát triển sự độc lập",
    pronunciation: "/ˌɪndɪˈpɛndəns/",
    example: "Sport develops independence.",
  },
  {
    id: "sx-effort-goals",
    front: "to make every possible effort to achieve their goals",
    back: "cố gắng hết sức để đạt được mục tiêu của họ",
    pronunciation: "/ˈɛfət tuː əˈtʃiːv/",
    example: "Athletes make effort to achieve goals.",
  },
  {
    id: "sx-sacrifice-team",
    front: "to sacrifice themselves for the sake of their team",
    back: "hy sinh bản thân vì lợi ích của cả đội",
    pronunciation: "/ˈsækrɪfaɪs/",
    example: "Players sacrifice for their team.",
  },
  {
    id: "sx-life-lessons",
    front: "to learn valuable life lessons",
    back: "học những bài học cuộc sống quý báu",
    pronunciation: "/ˈvæljuəbl laɪf ˈlɛsnz/",
    example: "Sport teaches life lessons.",
  },
  {
    id: "sx-team-environment",
    front: "to learn how to work effectively in a team environment",
    back: "tìm hiểu cách làm việc hiệu quả trong môi trường đội nhóm",
    pronunciation: "/tiːm ɪnˈvaɪərənmənt/",
    example: "Sport teaches teamwork.",
  },
  {
    id: "sx-challenge-themselves",
    front: "to have the chance to challenge themselves",
    back: "có cơ hội để thử thách bản thân",
    pronunciation: "/ˈtʃælɪndʒ/",
    example: "Sport challenges self.",
  },
  {
    id: "sx-limits",
    front: "to push themselves to their limits",
    back: "đẩy bản thân đến giới hạn",
    pronunciation: "/pʊʃ ðəmˈsɛlvz tuː ðeə ˈlɪmɪts/",
    example: "Push yourself to your limits.",
  },
  {
    id: "sx-comfort-zone",
    front: "to step out of their comfort zone",
    back: "bước ra khỏi vùng thoải mái của họ",
    pronunciation: "/ˈkʌmfət zəʊn/",
    example: "Step out of your comfort zone.",
  },
  {
    id: "sx-pose-threat",
    front: "to pose a serious threat to...",
    back: "đặt ra một mối đe dọa nghiêm trọng cho ...",
    pronunciation: "/pəʊz ə ˈsɪəriəs θrɛt/",
    example: "Injuries pose serious threats.",
  },
  {
    id: "sx-serious-injuries",
    front: "to suffer from serious injuries or even death",
    back: "bị thương nặng hoặc thậm chí tử vong",
    pronunciation: "/ˈsɪəriəs ˈɪndʒəriz/",
    example: "Athletes risk serious injuries.",
  },
  {
    id: "sx-special-training",
    front: "to require special training and specialised gear/equipment",
    back: "yêu cầu đào tạo đặc biệt và dụng cụ / thiết bị chuyên dụng",
    pronunciation: "/ˈspɛʃəl ˈtreɪnɪŋ/",
    example: "Extreme sports need special training.",
  },
  {
    id: "sx-undergo-training",
    front: "to undergo appropriate training",
    back: "trải qua quá trình đào tạo phù hợp",
    pronunciation: "/ˌʌndəˈɡəʊ əˈprəʊpriət ˈtreɪnɪŋ/",
    example: "Undergo appropriate training first.",
  },
];

export { lifeCultureCards };
