import type { Flashcard } from "./types";

// ────────────────────────────────────────────────────────────────────────────
// SET 17 — TECHNOLOGY & SOCIETY (AI / Energy / Technology / Foreign Aid / Government Spending / Stress / Overpopulation)
// ────────────────────────────────────────────────────────────────────────────
const techSocietyCards: Flashcard[] = [
  // ── Artificial Intelligence — BENEFITS ────────────────────────────────
  {
    id: "ai-eradicate",
    front: "to help eradicate war, disease & poverty",
    back: "giúp xóa bỏ chiến tranh, bệnh tật và nghèo đói",
    pronunciation: "/ɪˈrædɪkeɪt/",
    example: "AI could help eradicate disease and poverty.",
  },
  {
    id: "ai-better-diagnoses",
    front: "to help us make better diagnoses",
    back: "giúp chúng ta chẩn đoán tốt hơn",
    pronunciation: "/ˌdaɪəɡˈnəʊsɪz/",
    example: "AI helps doctors make better diagnoses.",
  },
  {
    id: "ai-cure-cancer",
    front: "to find new ways to cure cancer",
    back: "tìm cách mới để chữa ung thư",
    pronunciation: "/kjuːr ˈkæŋsər/",
    example: "Researchers use AI to cure cancer.",
  },
  {
    id: "ai-huge-benefit",
    front: "to be a huge benefit to society",
    back: "là một lợi ích to lớn cho xã hội",
    pronunciation: "/hjuːdʒ ˈbɛnɪfɪt/",
    example: "AI is a huge benefit to society.",
  },
  {
    id: "ai-enhance-efficiency",
    front: "to enhance our efficiency",
    back: "nâng cao hiệu quả làm việc của chúng ta",
    pronunciation: "/ɪnˈhɑːns ɪˈfɪʃənsi/",
    example: "AI tools enhance our efficiency.",
  },
  {
    id: "ai-tedious-tasks",
    front:
      "to do tedious tasks → allow us to do the more interpersonal and creative aspect of work",
    back: "thực hiện các nhiệm vụ tẻ nhạt → cho phép chúng ta thực hiện công việc thuộc các khía cạnh cá nhân và sáng tạo hơn",
    pronunciation: "/ˈtiːdiəs tɑːsks/",
    example: "AI handles tedious tasks so we can be creative.",
  },
  {
    id: "ai-mundane-tasks",
    front: "mundane tasks (answering emails) → will be done by intelligent assistants",
    back: "những nhiệm vụ nhàm chán, mang tính lặp đi lặp lại (trả lời email) → sẽ được thực hiện bởi các trợ lý thông minh",
    pronunciation: "/ˈmʌndeɪn/",
    example: "AI assistants do mundane tasks.",
  },
  {
    id: "ai-smart-homes",
    front: "smart homes → reduce energy usage + provide better security",
    back: "nhà thông minh → giảm sử dụng năng lượng + cung cấp bảo mật tốt hơn",
    pronunciation: "/smɑːt həʊmz/",
    example: "Smart homes save energy and improve security.",
  },
  {
    id: "ai-better-health-care",
    front: "to get better health care",
    back: "có được chăm sóc sức khỏe tốt hơn",
    pronunciation: "/bɛtər hɛlθ keər/",
    example: "AI helps people get better health care.",
  },
  {
    id: "ai-intensive-labour",
    front: "to be capable of performing tasks → would once have required intensive human labour",
    back: "có khả năng thực hiện các nhiệm vụ → đã từng đòi hỏi nhiều sức người",
    pronunciation: "/ɪnˈtɛnsɪv ˈhjuːmən ˈleɪbər/",
    example: "AI handles tasks that used to require intensive labour.",
  },
  {
    id: "ai-complex-functions",
    front: "to perform complex functions (facial recognition)",
    back: "thực hiện các chức năng phức tạp (nhận dạng khuôn mặt)",
    pronunciation: "/ˈkɒmplɛks ˈfʌŋkʃnz/",
    example: "AI performs complex functions such as facial recognition.",
  },
  {
    id: "ai-backbreaking",
    front: "to perform intensive human labour & backbreaking tasks",
    back: "thực hiện công việc chuyên sâu của con người và các công việc nặng nhọc",
    pronunciation: "/ˈbækbreɪkɪŋ/",
    example: "AI helps with backbreaking tasks.",
  },
  {
    id: "ai-reduce-workload",
    front: "to reduce the workload of humans",
    back: "giảm khối lượng công việc của con người",
    pronunciation: "/ˈwɜːkləʊd/",
    example: "AI reduces the workload of humans.",
  },
  {
    id: "ai-precise-predictions",
    front: "to make more precise predictions about extreme events",
    back: "đưa ra dự đoán chính xác hơn về các sự kiện khắc nghiệt",
    pronunciation: "/prɪˈsaɪz prɪˈdɪkʃnz/",
    example: "AI makes more precise predictions about extreme events.",
  },
  {
    id: "ai-climate-data",
    front: "to observe & analyse increasingly complex climate data",
    back: "quan sát và phân tích dữ liệu khí hậu ngày càng phức tạp",
    pronunciation: "/ˈkleɪmət ˈdeɪtə/",
    example: "AI observes and analyses complex climate data.",
  },
  {
    id: "ai-climate-understanding",
    front: "to have an increased understanding of the effects and reasons for climate change",
    back: "hiểu biết nhiều hơn về tác động và lý do của biến đổi khí hậu",
    pronunciation: "/ɪnˈkrɪːst/",
    example: "AI helps understand climate change better.",
  },
  // ── Artificial Intelligence — DANGERS ────────────────────────────────
  {
    id: "ai-cause-great-harm",
    front: "to cause great harm",
    back: "gây tác hại lớn",
    pronunciation: "/kɔːz ɡreɪt hɑːm/",
    example: "Misused AI can cause great harm.",
  },
  {
    id: "ai-human-survival",
    front: "to become a threat to human survival",
    back: "trở thành mối đe dọa cho sự sống còn của con người",
    pronunciation: "/ˈhjuːmən səˈvaɪvl/",
    example: "Out-of-control AI might threaten human survival.",
  },
  {
    id: "ai-no-human-emotions",
    front: "to be unlikely to exhibit human emotions (love or hate)",
    back: "không thể biểu lộ cảm xúc của con người (yêu hay ghét)",
    pronunciation: "/ɪɡˈzɪbɪt ɪˈməʊʃnz/",
    example: "AI is unlikely to exhibit human emotions.",
  },
  {
    id: "ai-might-risk",
    front: "AI might become a risk",
    back: "AI có thể trở thành một sự rủi ro",
    pronunciation: "/raɪsk/",
    example: "AI might become a serious risk.",
  },
  {
    id: "ai-devastating",
    front: "to be programmed to do something devastating",
    back: "được lập trình để làm những công việc mang tính tàn phá",
    pronunciation: "/ˈdɛvəsteɪtɪŋ/",
    example: "AI can be programmed to do devastating things.",
  },
  {
    id: "ai-autonomous-weapons",
    front: "autonomous weapons → are programmed to kill",
    back: "vũ khí tự trị → được lập trình để tiêu diệt",
    pronunciation: "/ɔːˈtɒnəməs ˈwɛpənz/",
    example: "Autonomous weapons are programmed to kill.",
  },
  {
    id: "ai-mass-casualties",
    front: "in the hands of ... → to cause mass casualties",
    back: "vào tay của ... → gây thương vong hàng loạt",
    pronunciation: "/mæs ˈkæʒuəltiz/",
    example: "AI in the wrong hands can cause mass casualties.",
  },
  {
    id: "ai-arms-race",
    front: "an AI arms race / an AI war",
    back: "một cuộc chạy đua vũ trang AI / một cuộc chiến AI",
    pronunciation: "/ɑːmz reɪs/",
    example: "There could be an AI arms race.",
  },
  {
    id: "ai-more-intelligent",
    front: "to have the potential to become more intelligent than any human",
    back: "có tiềm năng trở nên thông minh hơn bất kỳ con người nào",
    pronunciation: "/pəˈtɛnʃl/",
    example: "AI may become more intelligent than any human.",
  },
  {
    id: "ai-unpredictable",
    front: "to have no surefire way of predicting how it will behave",
    back: "không có cách nào chắc chắn để dự đoán nó sẽ hành xử như thế nào",
    pronunciation: "/ˈʃʊərˌfaɪər/",
    example: "We cannot predict exactly how AI will behave.",
  },
  {
    id: "ai-our-existence",
    front: "to be a threat to our existence",
    back: "là mối đe dọa cho sự tồn tại của chúng ta",
    pronunciation: "/ɪɡˈzɪstəns/",
    example: "AI could become a threat to our existence.",
  },
  {
    id: "ai-massive-harm",
    front: "to result in massive harm",
    back: "dẫn đến tác hại lớn",
    pronunciation: "/ˈmæsɪv hɑːm/",
    example: "Misuse of AI may result in massive harm.",
  },
  {
    id: "ai-hacked",
    front: "to get hacked",
    back: "bị hack",
    pronunciation: "/hækt/",
    example: "AI systems can get hacked.",
  },
  {
    id: "ai-track-every-move",
    front: "to track and analyse an individual's every move online",
    back: "theo dõi và phân tích mọi hành động của một cá nhân trên mạng",
    pronunciation: "/ˈɪndɪˌvɪdʒuəlz ˈɛvri muːv/",
    example: "AI tracks and analyses every move online.",
  },
  {
    id: "ai-malicious",
    front: "to be used for dangerous & malicious purposes",
    back: "bị sử dụng cho mục đích nguy hiểm và độc hại",
    pronunciation: "/məˈlɪʃəs/",
    example: "AI can be used for malicious purposes.",
  },
  {
    id: "ai-unforeseen",
    front: "to create unintended & unforeseen consequences",
    back: "tạo ra những hậu quả không lường trước được",
    pronunciation: "/ˌʌnfɔːˈsiːn/",
    example: "AI may create unforeseen consequences.",
  },
  {
    id: "ai-end-humanity",
    front: "to be the end of humanity",
    back: "là sự kết thúc của nhân loại",
    pronunciation: "/hjuːˈmænəti/",
    example: "Some fear AI could be the end of humanity.",
  },
  {
    id: "ai-take-over",
    front: "to take over the planet completely & permanently",
    back: "chiếm đoạt hành tinh hoàn toàn & vĩnh viễn",
    pronunciation: "/teɪk ˈəʊvər/",
    example: "AI might take over the planet permanently.",
  },
  {
    id: "ai-abusd-terrorist",
    front: "to be abused by terrorist groups",
    back: "bị lạm dụng bởi các nhóm khủng bố",
    pronunciation: "/əˈbjuːzd/",
    example: "AI could be abused by terrorist groups.",
  },
  {
    id: "ai-misuse",
    front: "the misuse of AI",
    back: "sự lạm dụng AI",
    pronunciation: "/ˌmɪsˈjuːs/",
    example: "The misuse of AI is a growing concern.",
  },
  // ── AI — Other Useful Vocabulary ──────────────────────────────────────
  {
    id: "ai-self-driving",
    front: "self-driving cars",
    back: "xe tự lái",
    pronunciation: "/sɛlf ˈdraɪvɪŋ/",
    example: "Self-driving cars are powered by AI.",
  },
  {
    id: "ai-human-like",
    front: "robots with human-like characteristics",
    back: "robot có đặc điểm giống con người",
    pronunciation: "/ˈhjuːmən laɪk/",
    example: "Researchers build robots with human-like characteristics.",
  },
  {
    id: "ai-prevent-negative",
    front: "to prevent potential negative consequences",
    back: "ngăn ngừa hậu quả tiêu cực tiềm ẩn",
    pronunciation: "/prɪˈvɛnt/",
    example: "We must prevent negative consequences of AI.",
  },
  {
    id: "ai-voice-activated",
    front: "voice-activated computers",
    back: "máy tính được kích hoạt bằng giọng nói",
    pronunciation: "/vɔɪs ˈæktɪveɪtɪd/",
    example: "Voice-activated computers respond to speech.",
  },
  {
    id: "ai-facial-recognition",
    front: "facial recognition algorithms",
    back: "thuật toán nhận dạng khuôn mặt",
    pronunciation: "/ˈfeɪʃl ˌrɛkəɡˈnɪʃn/",
    example: "Facial recognition algorithms identify people.",
  },
  {
    id: "ai-destructive-potential",
    front: "to minimise its destructive potential",
    back: "giảm thiểu khả năng phá hủy của nó",
    pronunciation: "/dɪˈstrʌktɪv pəˈtɛnʃl/",
    example: "We must minimise AI's destructive potential.",
  },
  {
    id: "ai-grab-headlines",
    front: "fears about … grab headlines",
    back: "nỗi sợ về ... tràn đầy headlines",
    pronunciation: "/ɡræb ˈhɛdˌlaɪnz/",
    example: "Fears about AI grab headlines.",
  },
  {
    id: "ai-application",
    front: "thanks to the application of AI",
    back: "nhờ ứng dụng AI",
    pronunciation: "/ˌæplɪˈkeɪʃn/",
    example: "Thanks to AI, healthcare has improved.",
  },
  {
    id: "ai-blindly-control",
    front: "to let … blindly control us",
    back: "để ... kiểm soát chúng ta một cách mù quáng",
    pronunciation: "/ˈblaɪndli/",
    example: "We must not let AI blindly control us.",
  },
  {
    id: "ai-nuclear-arms",
    front: "a nuclear arms race",
    back: "một cuộc chạy đua vũ trang hạt nhân",
    pronunciation: "/ˈnjuːkliər/",
    example: "A nuclear arms race is a global threat.",
  },
  {
    id: "ai-accelerating",
    front: "the accelerating development of AI",
    back: "sự phát triển nhanh chóng của AI",
    pronunciation: "/əkˈsɛləreɪtɪŋ/",
    example: "The accelerating development of AI raises concerns.",
  },
  // ── Energy ────────────────────────────────────────────────────────────
  {
    id: "en-environmentally-friendly",
    front: "environmentally-friendly (adj)",
    back: "thân thiện với môi trường",
    pronunciation: "/ɪnˌvaɪərənˈmɛntəli ˈfrɛndli/",
    example: "Solar panels are environmentally friendly.",
  },
  {
    id: "en-renewable-vs-non",
    front: "renewable/infinite energy sources vs non-renewable energy sources",
    back: "các nguồn năng lượng tái tạo được vs các nguồn năng lượng không tái tạo được",
    pronunciation: "/rɪˈnjuːəbl/",
    example: "Solar is renewable; coal is non-renewable.",
  },
  {
    id: "en-nuclear-power",
    front: "nuclear power = nuclear energy",
    back: "năng lượng hạt nhân",
    pronunciation: "/ˈnjuːkliər ˈpaʊər/",
    example: "Nuclear power generates electricity.",
  },
  {
    id: "en-nuclear-weapon",
    front: "nuclear weapon",
    back: "vũ khí hạt nhân",
    pronunciation: "/ˈnjuːkliər ˈwɛpən/",
    example: "Nuclear weapons are a global threat.",
  },
  {
    id: "en-nuclear-accident",
    front: "nuclear accident = nuclear disaster",
    back: "tai nạn / thảm họa hạt nhân",
    pronunciation: "/njuːˈklɪər əˈsɪdənt/",
    example: "The Chernobyl nuclear disaster changed history.",
  },
  {
    id: "en-leakage-materials",
    front: "a leakage of nuclear materials into the environment",
    back: "sự rò rỉ các nhiên liệu hạt nhân vào môi trường",
    pronunciation: "/ˈliːkɪdʒ/",
    example: "Leakage of nuclear materials is dangerous.",
  },
  {
    id: "en-radiation",
    front: "high levels of radiation",
    back: "mức độ phóng xạ cao",
    pronunciation: "/ˌreɪdiˈeɪʃn/",
    example: "High levels of radiation harm health.",
  },
  {
    id: "en-nuclear-improvements",
    front: "improvements in nuclear technology",
    back: "những sự cải thiện trong công nghệ hạt nhân",
    pronunciation: "/ɪmˈpruːvmənts/",
    example: "Improvements in nuclear technology reduce risks.",
  },
  {
    id: "en-solar-wind-water",
    front: "solar, wind or water power",
    back: "năng lượng mặt trời, gió và nước",
    pronunciation: "/ˈsəʊlər wɪnd ˈɔːtə/",
    example: "Solar, wind or water power is clean.",
  },
  {
    id: "en-power-stations",
    front: "power stations = power plants",
    back: "các nhà máy năng lượng",
    pronunciation: "/ˈpaʊər plɑːnts/",
    example: "Power stations generate electricity.",
  },
  {
    id: "en-fossil-fuels",
    front: "fossil fuels such as coal, oil or natural gas",
    back: "nhiên liệu hóa thạch như than đá, dầu và khí tự nhiên",
    pronunciation: "/ˈfɒsl fjuːəlz/",
    example: "Burning fossil fuels releases CO2.",
  },
  {
    id: "en-generate-electricity",
    front: "to generate/produce electricity",
    back: "sản xuất điện",
    pronunciation: "/ˈdʒɛnəreɪt/",
    example: "Wind turbines generate electricity.",
  },
  {
    id: "en-greenhouse-emissions",
    front: "to release greenhouse gas emissions to the atmosphere",
    back: "thải khí thải nhà kính ra bầu khí quyển",
    pronunciation: "/ˈɡriːnhaʊs ɡæz ɪˈmɪʃnz/",
    example: "Fossil fuels release greenhouse gas emissions.",
  },
  {
    id: "en-sustainable-energy",
    front: "sustainable energy sources",
    back: "các nguồn năng lượng bền vững",
    pronunciation: "/səˈsteɪnəbl/",
    example: "Sustainable energy sources protect the environment.",
  },
  {
    id: "en-threat-environment",
    front: "to pose a serious threat to people and the environment",
    back: "gây ra 1 mối đe dọa nghiêm trọng cho con người và môi trường",
    pronunciation: "/pəʊz ə ˈsɪəriəs θrɛt/",
    example: "Nuclear waste poses serious threats.",
  },
  {
    id: "en-exploitation",
    front: "the exploitation of natural resources",
    back: "sự khai thác các nguồn tài nguyên thiên nhiên",
    pronunciation: "/ˌɛksplɔɪˈteɪʃn/",
    example: "The exploitation of natural resources harms the planet.",
  },
  {
    id: "en-depletion",
    front: "the depletion of natural resources",
    back: "sự cạn kiệt các nguồn tài nguyên thiên nhiên",
    pronunciation: "/dɪˈpliːʃn/",
    example: "The depletion of natural resources is a global concern.",
  },
  {
    id: "en-global-warming",
    front: "to lead to environmental degradation / global warming",
    back: "dẫn tới sự suy thoái môi trường / nóng lên toàn cầu",
    pronunciation: "/dɪˈɡrədeɪʃn/",
    example: "Fossil fuels lead to global warming.",
  },
  {
    id: "en-consumption",
    front: "energy consumption",
    back: "sự tiêu thụ năng lượng",
    pronunciation: "/ɪnˈvɛrəmɛntl ˈdɪɡrəˈdeɪʃn/",
    example: "Reducing energy consumption saves money.",
  },
  {
    id: "en-global-needs",
    front: "to meet global energy needs",
    back: "đáp ứng nhu cầu năng lượng toàn cầu",
    pronunciation: "/miːt ˈɡləʊbl ˈɛnədʒi niːdz/",
    example: "Renewable sources help meet global energy needs.",
  },
  {
    id: "en-run-out",
    front: "to run out",
    back: "cạn kiệt",
    pronunciation: "/rʌn aʊt/",
    example: "Fossil fuels will run out one day.",
  },
  {
    id: "en-solar-panels",
    front: "to install solar panels",
    back: "lắp đặt các tấm pin năng lượng mặt trời",
    pronunciation: "/ɪnˈstɔːl ˈsəʊlər ˈpænlz/",
    example: "Install solar panels on rooftops.",
  },
  {
    id: "en-wind-farm",
    front: "to build / set up a wind farm",
    back: "xây dựng 1 tua bin được dùng để sản xuất điện từ gió",
    pronunciation: "/wɪnd fɑːm/",
    example: "Set up a wind farm to generate power.",
  },
  {
    id: "en-devastating-impact",
    front: "to have a devastating impact on people / the environment / marine ecosystems",
    back: "có tác động tàn phá đối với con người / môi trường / hệ sinh thái biển",
    pronunciation: "/ˈdɛvəsteɪtɪŋ/",
    example: "Oil spills have devastating impacts.",
  },
  {
    id: "en-energy-efficient",
    front: "energy-efficient / energy-saving appliances",
    back: "các thiết bị tiết kiệm năng lượng",
    pronunciation: "/ˈɛnədʒi ɪˈfɪʃənt/",
    example: "Use energy-efficient appliances.",
  },
  // ── Technology ─────────────────────────────────────────────────────────
  {
    id: "tc-tech-advances",
    front: "technological advances = technological developments",
    back: "những tiến bộ trong công nghệ",
    pronunciation: "/ˌtɛknəˈlɒdʒɪkl ədˈvaːnsɪz/",
    example: "Technological advances shape our lives.",
  },
  {
    id: "tc-personal-professional",
    front: "people's personal and professional relationships",
    back: "mối quan hệ cá nhân và sự nghiệp",
    pronunciation: "/ˌprəˈfɛʃənl rɪˈleɪʃnʃɪps/",
    example: "Tech affects personal and professional relationships.",
  },
  {
    id: "tc-keep-in-contact",
    front: "to keep in contact with = to keep in touch with",
    back: "giữ liên lạc với",
    pronunciation: "/kiːp ɪn ˈkɒntækt/",
    example: "Apps help us keep in contact with family.",
  },
  {
    id: "tc-loved-ones",
    front: "loved ones",
    back: "những người yêu thương",
    pronunciation: "/lʌvd wʌnz/",
    example: "We miss our loved ones abroad.",
  },
  {
    id: "tc-way-of-communication",
    front: "as a way of communication",
    back: "như là một cách thức giao tiếp",
    pronunciation: "/weɪ əv kəˌmjuːnɪˈkeɪʃn/",
    example: "Email is a popular way of communication.",
  },
  {
    id: "tc-tech-devices",
    front: "technological devices and applications",
    back: "những ứng dụng và thiết bị công nghệ",
    pronunciation: "/dɪˈvaɪsɪz ənd ˌæplɪˈkeɪʃnz/",
    example: "Tech devices and applications are everywhere.",
  },
  {
    id: "tc-business-network",
    front: "to expand business network",
    back: "mở rộng mạng lưới kinh doanh",
    pronunciation: "/ɪkˈspænd ˈbɪznəs ˈnɛtwɜːk/",
    example: "LinkedIn helps expand business networks.",
  },
  {
    id: "tc-telecommunication",
    front: "telecommunication services",
    back: "các dịch vụ viễn thông",
    pronunciation: "/ˌtɛlɪkəˌmjuːnɪˈkeɪʃn/",
    example: "Telecommunication services connect people.",
  },
  {
    id: "tc-more-opportunities",
    front: "to have more opportunities to...",
    back: "có nhiều cơ hội hơn để ...",
    pronunciation: "/ˌɒpəˈtjuːnɪtiz/",
    example: "Tech provides more opportunities to learn.",
  },
  {
    id: "tc-internet-smartphone",
    front: "an internet-connected smart phone",
    back: "chiếc điện thoại được kết nối internet",
    pronunciation: "/ˈɪntənɛt kəˈnɛktɪd/",
    example: "Internet-connected smartphones are essential today.",
  },
  {
    id: "tc-multiple-tasks",
    front: "to do multiple tasks all at the same time",
    back: "thực hiện nhiều công việc cùng một lúc",
    pronunciation: "/ˈmʌltɪpl tɑːsks/",
    example: "Tech lets us do multiple tasks at once.",
  },
  {
    id: "tc-social-isolation",
    front: "to suffer from social isolation",
    back: "bị sự cô lập xã hội",
    pronunciation: "/ˌsəʊʃl ˌaɪsəˈleɪʃn/",
    example: "People suffer from social isolation.",
  },
  {
    id: "tc-browse-internet",
    front: "to surf / browse the internet",
    back: "lướt web",
    pronunciation: "/sɜːf ðə ˈɪntənɛt/",
    example: "Children browse the internet daily.",
  },
  {
    id: "tc-interactive-activities",
    front: "to take part in interactive activities",
    back: "tham gia vào các hoạt động có tính tương tác",
    pronunciation: "/ˌɪntərˈæktɪv/",
    example: "Students join interactive activities online.",
  },
  {
    id: "tc-video-lessons",
    front: "to take video lessons with someone",
    back: "tham dự buổi học video với ai đó",
    pronunciation: "/ˈvɪdiəʊ ˈlɛsnz/",
    example: "We can take video lessons with native speakers.",
  },
  {
    id: "tc-virtual-interact",
    front: "to interact through computers rather than face to face",
    back: "tương tác thông qua máy tính thay vì trực tiếp",
    pronunciation: "/ˌɪntərˈækt θruː kəmˈpjuːtəz/",
    example: "We now interact through computers.",
  },
  {
    id: "tc-face-to-face",
    front: "face-to-face meetings",
    back: "các cuộc họp gặp mặt trực tiếp",
    pronunciation: "/feɪs tuː feɪs/",
    example: "Face-to-face meetings build stronger bonds.",
  },
  {
    id: "tc-online-meetings",
    front: "online meetings = virtual meetings",
    back: "các cuộc họp online",
    pronunciation: "/ˈɒnˌlaɪn ˈmiːtɪŋz/",
    example: "Online meetings save travel time.",
  },
  {
    id: "tc-discourage-interaction",
    front: "to discourage real interaction",
    back: "ngăn cản sự tương tác thực",
    pronunciation: "/dɪsˈkʌrɪdʒ/",
    example: "Screens discourage real interaction.",
  },
  {
    id: "tc-loss-traditional",
    front: "the loss of traditional cultures",
    back: "sự mất đi của các văn hóa truyền thống",
    pronunciation: "/lɒs əv trəˈdɪʃənl ˈkʌltʃəz/",
    example: "Modern tech can cause the loss of traditional cultures.",
  },
  {
    id: "tc-quality-of-life",
    front: "to improve the quality of life",
    back: "cải thiện chất lượng cuộc sống",
    pronunciation: "/ˈkwɒlɪti əv laɪf/",
    example: "Tech improves the quality of life.",
  },
  {
    id: "tc-access-information",
    front: "to give someone access to information",
    back: "cho ai đó sự truy cập vào thông tin",
    pronunciation: "/ˈæksɛs tuː ˌɪnfəˈmeɪʃn/",
    example: "The internet gives access to information.",
  },
  {
    id: "tc-social-networking",
    front: "social networking sites such as Facebook or Twitter",
    back: "mạng xã hội như Facebook hay Twitter",
    pronunciation: "/ˈsəʊʃl ˈnɛtwɜːkɪŋ/",
    example: "Social networking sites connect people.",
  },
  // ── Foreign Aid — ADVANTAGES ──────────────────────────────────────────
  {
    id: "fa-emergency-aid",
    front: "emergency aid in times of disaster → to save lives",
    back: "hỗ trợ khẩn cấp trong thời gian xảy ra thảm họa → cứu sống nhiều người",
    pronunciation: "/ɪˈmɜːdʒənsi eɪd/",
    example: "Emergency aid during disasters saves lives.",
  },
  {
    id: "fa-rebuild-livelihoods",
    front: "to rebuild livelihoods and housing after a disaster",
    back: "xây dựng lại sinh kế và nhà ở sau thảm họa",
    pronunciation: "/riːˈbɪld ˈlaɪvlihʊdz/",
    example: "Aid helps rebuild livelihoods after disasters.",
  },
  {
    id: "fa-medical-training",
    front:
      "the provision of medical training, medicines and equipment can improve health and standards of living",
    back: "cung cấp đào tạo y tế, thuốc men và thiết bị có thể cải thiện sức khỏe và mức sống",
    pronunciation: "/prəˈvɪʒn/",
    example: "Medical training improves health standards.",
  },
  {
    id: "fa-aid-agriculture",
    front: "aid for agriculture → to increase food production",
    back: "viện trợ cho nông nghiệp → tăng sản xuất lương thực",
    pronunciation: "/eɪd fɔːr ˈæɡrɪkʌltʃər/",
    example: "Aid for agriculture increases food production.",
  },
  {
    id: "fa-clean-water",
    front:
      "projects that develop clean water and sanitation → improved health and living standards",
    back: "các dự án phát triển nước sạch và vệ sinh → cải thiện mức sống và sức khỏe",
    pronunciation: "/klɪːn ˈwɔːtər/",
    example: "Clean water projects improve living standards.",
  },
  {
    id: "fa-diplomatic-relations",
    front: "diplomatic relations will be nurtured",
    back: "quan hệ ngoại giao sẽ được nuôi dưỡng",
    pronunciation: "/ˌdɪpləˈmætɪk rɪˈleɪʃnz/",
    example: "Foreign aid nurtures diplomatic relations.",
  },
  {
    id: "fa-economic-opportunities",
    front: "to provide economic opportunities for the giver and the recipient",
    back: "cung cấp cơ hội kinh tế cho người cung cấp viện trợ và người nhận viện trợ",
    pronunciation: "/ˌiːkəˈnɒmɪk ˌɒpəˈtjuːnɪtiz/",
    example: "Aid creates economic opportunities for both sides.",
  },
  {
    id: "fa-improved-relationships",
    front:
      "improved international relationships → form the foundation of trade talks, security agreements",
    back: "mối quan hệ quốc tế được cải thiện → hình thành nền tảng của đàm phán thương mại, thỏa thuận an ninh",
    pronunciation: "/ˌɪntəˈnæʃənəl/",
    example: "Aid improves international relationships.",
  },
  // ── Foreign Aid — DISADVANTAGES ───────────────────────────────────────
  {
    id: "fa-dependence",
    front:
      "to increase the dependence of less economically developed countries on donor countries → a loan → struggle to repay",
    back: "tăng sự phụ thuộc của các nước kém phát triển kinh tế lên các nước tài trợ → cho vay → khó khăn trả nợ",
    pronunciation: "/dɪˈpɛndəns/",
    example: "Aid can increase dependence on donor countries.",
  },
  {
    id: "fa-corruption",
    front:
      "corruption / increased bureaucracy → local politicians using aid for their own means or for political gain",
    back: "tham nhũng / quan liêu gia tăng → các chính trị gia địa phương sử dụng viện trợ cho mục đích riêng của họ hay lợi ích chính trị",
    pronunciation: "/kəˈrʌpʃn/",
    example: "Corruption can divert aid from intended recipients.",
  },
  {
    id: "fa-political-pressure",
    front: "to put political or economic pressure on receiving countries",
    back: "gây áp lực chính trị hoặc kinh tế đối với các nước nhận viện trợ",
    pronunciation: "/pəˈlɪtɪkl ˈprɛʃər/",
    example: "Aid may be used to pressure receiving countries.",
  },
  {
    id: "fa-political-tool",
    front:
      "to be offered as a political tool → as a tool to control the recipient country in terms of favours → setting up military bases",
    back: "được cung cấp như một công cụ chính trị → như một công cụ để kiểm soát quốc gia nhận viện trợ về các ưu đãi → thiết lập các căn cứ quân sự",
    pronunciation: "/pəˈlɪtɪkl tuːl/",
    example: "Aid can be used as a political tool.",
  },
  {
    id: "fa-no-small-farmers",
    front: "aid for agriculture → sometimes do not benefit small farmers",
    back: "viện trợ cho nông nghiệp → đôi khi không mang lại lợi ích cho những người nông dân nhỏ",
    pronunciation: "/smɔːl ˈfɑːməz/",
    example: "Agricultural aid sometimes doesn't reach small farmers.",
  },
  {
    id: "fa-intended-recipient",
    front: "to fail to reach the right people / the intended recipient",
    back: "không tới được đúng người / người mà được chọn để nhận viện trợ",
    pronunciation: "/ɪnˈtɛndɪd rɪˈsɪpiənt/",
    example: "Aid often fails to reach intended recipients.",
  },
  {
    id: "fa-local-inflation",
    front: "to increase local prices (inflation)",
    back: "tăng giá cả ở địa phương (lạm phát)",
    pronunciation: "/ˌɪnfleɪʃn/",
    example: "Aid may increase local prices and inflation.",
  },
  {
    id: "fa-deeper-debt",
    front:
      "to leave poorer countries deeper in debt and poverty → instead of using their funds → invest in profitable projects, they use → pay their debts",
    back: "khiến các nước nghèo càng chìm sâu vào nợ nần và nghèo đói → thay vì sử dụng tiền của họ → đầu tư vào các dự án có lợi nhuận, họ sử dụng → trả nợ",
    pronunciation: "/dɪpər ɪn dɛt/",
    example: "Aid can leave countries deeper in debt.",
  },
  // ── Foreign Aid — Other Useful Vocabulary ─────────────────────────────
  {
    id: "fa-spent-poorly",
    front: "to be spent poorly on projects that fail to...",
    back: "bị chi cho các dự án mà không hoàn thành được mục tiêu gì đó",
    pronunciation: "/spɛnt ˈpɔːrli/",
    example: "Aid is often spent poorly on failing projects.",
  },
  {
    id: "fa-no-transparency",
    front: "to be spent with barely any transparency about where and how it was delivered",
    back: "được chi tiêu với hầu như không có sự minh bạch về nơi được chỉ và cách thức được chi viện trợ",
    pronunciation: "/trænsˈpærənsi/",
    example: "Lack of transparency in aid delivery is a concern.",
  },
  {
    id: "fa-targeted-poverty",
    front: "to be targeted at poverty reduction",
    back: "nhắm vào mục tiêu giảm nghèo",
    pronunciation: "/ˈtɑːɡɪtɪd/",
    example: "Effective aid should be targeted at poverty reduction.",
  },
  {
    id: "fa-global-challenges",
    front:
      "to address global challenges including antimicrobial resistance, food security and building resilience to natural disasters",
    back: "giải quyết các thách thức toàn cầu bao gồm kháng kháng sinh, an ninh lương thực và xây dựng khả năng chống chịu với thiên tai",
    pronunciation: "/ˌæntɪmaɪˈkrəʊbiəl rɪˈzɪstəns/",
    example: "Aid addresses global challenges like antimicrobial resistance.",
  },
  {
    id: "fa-safer-world",
    front: "to help to build a safer, healthier, more prosperous world for...",
    back: "giúp xây dựng một thế giới an toàn hơn, lành mạnh hơn, thịnh vượng hơn cho ...",
    pronunciation: "/prəˈspɛrəs/",
    example: "Aid helps build a healthier world.",
  },
  {
    id: "fa-vaccinate",
    front: "to vaccinate children from preventable diseases",
    back: "tiêm phòng cho trẻ em khỏi các bệnh có thể phòng ngừa được",
    pronunciation: "/ˈvæksɪneɪt/",
    example: "Aid funds help vaccinate children.",
  },
  {
    id: "fa-way-out-poverty",
    front: "to help people work their way out of poverty",
    back: "giúp mọi người thoát nghèo",
    pronunciation: "/weɪ aʊt əv ˈpɒvəti/",
    example: "Aid helps people work their way out of poverty.",
  },
  {
    id: "fa-economic-uncertainty",
    front: "in a time of deep economic uncertainty",
    back: "trong thời điểm bất ổn kinh tế trầm trọng",
    pronunciation: "/ˌiːkəˈnɒmɪk ʌnˈsɜːtnti/",
    example: "Aid is critical in times of deep economic uncertainty.",
  },
  // ── Government Spending ───────────────────────────────────────────────
  {
    id: "gs-government-money",
    front:
      "government money = public money = national budgets = state budgets = government funding",
    back: "ngân sách nhà nước",
    pronunciation: "/ˈpʌblɪk ˈmʌni/",
    example: "Government money funds public services.",
  },
  {
    id: "gs-spend-money",
    front:
      "to spend money on something = to invest money in something = to allocate money to something",
    back: "chi tiền vào việc gì",
    pronunciation: "/əˈləʊkeɪt ˈmʌni/",
    example: "Governments allocate money to essential sectors.",
  },
  {
    id: "gs-investment",
    front: "investment (n)",
    back: "sự đầu tư",
    pronunciation: "/ɪnˈvɛstmənt/",
    example: "Investment in education pays off.",
  },
  {
    id: "gs-important-sectors",
    front: "important sectors = essential sectors",
    back: "những lĩnh vực quan trọng",
    pronunciation: "/ˈɛsənʃl ˈsɛktəz/",
    example: "Health is an essential sector.",
  },
  {
    id: "gs-medical-services",
    front: "medical services = health care = medical care",
    back: "lĩnh vực y tế / chăm sóc sức khỏe",
    pronunciation: "/ˈhɛlθ keər/",
    example: "Medical services require funding.",
  },
  {
    id: "gs-schooling",
    front: "schooling = education",
    back: "giáo dục",
    pronunciation: "/ˈskuːlɪŋ/",
    example: "Schooling is fundamental.",
  },
  {
    id: "gs-huge-amount",
    front: "a huge amount of money = millions of dollars",
    back: "khoản tiền khổng lồ / hàng triệu đô la",
    pronunciation: "/hjuːdʒ əˈmaʊnt/",
    example: "Bridges cost millions of dollars.",
  },
  {
    id: "gs-waste-budget",
    front: "a waste of the budget = a waste of public money = money-wasting",
    back: "phí tiền",
    pronunciation: "/weɪst əv ðə ˈbʌdʒɪt/",
    example: "Some spending is a waste of public money.",
  },
  {
    id: "gs-financial-support",
    front: "to provide financial support for = to offer financial assistance to = to give money to",
    back: "hỗ trợ tài chính cho ...",
    pronunciation: "/faɪˈnænʃl səˈpɔːt/",
    example: "The government provides financial support for low-income families.",
  },
  {
    id: "gs-financial-resources",
    front: "financial resources",
    back: "các nguồn lực tài chính",
    pronunciation: "/faɪˈnænʃl rɪˈsɔːsɪz/",
    example: "We need financial resources to succeed.",
  },
  {
    id: "gs-government-incentives",
    front: "government incentives",
    back: "trợ cấp của chính phủ",
    pronunciation: "/ɪnˈsɛntɪvz/",
    example: "Government incentives encourage investment.",
  },
  {
    id: "gs-raise-awareness",
    front: "to raise people's awareness",
    back: "nâng cao ý thức con người",
    pronunciation: "/reɪz əˈwɛənəs/",
    example: "Campaigns raise people's awareness.",
  },
  {
    id: "gs-public-services",
    front: "to provide public services",
    back: "cung cấp các dịch vụ công",
    pronunciation: "/ˈpʌblɪk ˈsɜːvɪsɪz/",
    example: "Governments provide public services.",
  },
  {
    id: "gs-new-jobs",
    front: "to create new jobs",
    back: "tạo ra việc làm mới",
    pronunciation: "/kriˈeɪt njuː dʒɒbz/",
    example: "New infrastructure creates new jobs.",
  },
  {
    id: "gs-support-poverty",
    front: "to support people who are living in poverty",
    back: "hỗ trợ người nghèo",
    pronunciation: "/səˈpɔːt ˈpiːpl huː ɑːr ˈlɪvɪŋ ɪn ˈpɒvəti/",
    example: "We should support people in poverty.",
  },
  {
    id: "gs-help-state",
    front: "help from the state = government help",
    back: "sự giúp đỡ từ chính phủ",
    pronunciation: "/hɛlp frəm ðə steɪt/",
    example: "Help from the state is essential for recovery.",
  },
  {
    id: "gs-government-support",
    front: "government support for... = government funding for...",
    back: "sự hỗ trợ của chính phủ cho ...",
    pronunciation: "/ˈɡʌvənmənt səˈpɔːt/",
    example: "Government support for healthcare saves lives.",
  },
  {
    id: "gs-alternative-support",
    front: "to rely on alternative sources of financial support",
    back: "dựa vào các nguồn hỗ trợ tài chính khác",
    pronunciation: "/ɔːlˈtɜːnətɪv/",
    example: "We rely on alternative sources of financial support.",
  },
  {
    id: "gs-cut-costs",
    front: "to cut all kinds of costs related to...",
    back: "cắt giảm toàn bộ chi phí liên quan đến",
    pronunciation: "/kʌt kɔːsts/",
    example: "We need to cut costs related to administration.",
  },
  {
    id: "gs-responsible",
    front: "to be responsible for...",
    back: "chịu trách nhiệm về vấn đề gì",
    pronunciation: "/rɪˈspɒnsəbl/",
    example: "Governments are responsible for public welfare.",
  },
  {
    id: "gs-social-security",
    front: "social security",
    back: "an ninh xã hội",
    pronunciation: "/ˈsəʊʃl sɪˈkjʊərəti/",
    example: "Social security supports retirees.",
  },
  {
    id: "gs-spending-categories",
    front: "government spending categories",
    back: "các khoản mục chi tiêu của chính phủ",
    pronunciation: "/ˈkætəɡəriz/",
    example: "Health is a major spending category.",
  },
  {
    id: "gs-infrastructure",
    front: "infrastructure investment",
    back: "sự đầu tư vào cơ sở hạ tầng",
    pronunciation: "/ˈɪnfrəˌstrʌktʃər/",
    example: "Infrastructure investment improves transportation.",
  },
  {
    id: "gs-research-spending",
    front: "research spending",
    back: "chi tiêu cho lĩnh vực nghiên cứu",
    pronunciation: "/rɪˈsɜːtʃ ˈspɛndɪŋ/",
    example: "Research spending fuels innovation.",
  },
  // ── Stress ────────────────────────────────────────────────────────────
  {
    id: "ss-shield-from",
    front: "to shield somebody from something",
    back: "bảo vệ ai đó khỏi gì",
    pronunciation: "/ʃiːld ˈsʌmwʌn frəm/",
    example: "Friends shield us from stress.",
  },
  {
    id: "ss-essential-life",
    front: "an essential part of life",
    back: "một phần thiết yếu của cuộc sống",
    pronunciation: "/ɪˈsɛnʃl pɑːt əv laɪf/",
    example: "Stress is an essential part of life.",
  },
  {
    id: "ss-important-tasks",
    front: "to complete important tasks",
    back: "hoàn thành các nhiệm vụ quan trọng",
    pronunciation: "/kəmˈpliːt/",
    example: "Focus helps complete important tasks.",
  },
  {
    id: "ss-fail-to",
    front: "to fail to do something",
    back: "thất bại / không làm được việc gì",
    pronunciation: "/feɪl tuː duː/",
    example: "We sometimes fail to manage stress.",
  },
  {
    id: "ss-dampen-spirits",
    front: "to dampen your spirits",
    back: "làm giảm tinh thần của bạn",
    pronunciation: "/ˈdæmpən jɔːr ˈspɪrɪts/",
    example: "Bad news can dampen your spirits.",
  },
  {
    id: "ss-overcome-challenges",
    front: "to overcome life's challenges",
    back: "vượt qua các thử thách của cuộc sống",
    pronunciation: "/ˌəʊvəˈkʌm/",
    example: "Resilience helps overcome challenges.",
  },
  {
    id: "ss-sense-of-control",
    front: "to feel a greater sense of control",
    back: "cảm thấy mình kiểm soát sự việc tốt hơn",
    pronunciation: "/sɛns əv kənˈtrəʊl/",
    example: "Planning brings a sense of control.",
  },
  {
    id: "ss-realistic-plan",
    front: "to develop a realistic, practical plan",
    back: "xây dựng một kế hoạch thực tế",
    pronunciation: "/ˌrɪəˈlɪstɪk plæn/",
    example: "Develop a realistic plan to reduce stress.",
  },
  {
    id: "ss-fit-needs",
    front: "to fit your own needs",
    back: "phù hợp với nhu cầu của riêng bạn",
    pronunciation: "/fɪt jɔːr əʊn niːdz/",
    example: "The plan should fit your own needs.",
  },
  {
    id: "ss-peaceful-life",
    front: "to lead a more peaceful life",
    back: "dẫn tới một cuộc sống bình yên hơn",
    pronunciation: "/ˈpiːsfʊl laɪf/",
    example: "Meditation can lead to a peaceful life.",
  },
  {
    id: "ss-life-altering",
    front: "life-altering events",
    back: "những sự kiện thay đổi cuộc đời",
    pronunciation: "/laɪf ˈɔːltərɪŋ/",
    example: "Divorce is a life-altering event.",
  },
  {
    id: "ss-care-loved-one",
    front: "to care for a loved one during illness",
    back: "chăm sóc người thân trong thời gian bị bệnh",
    pronunciation: "/keər fɔːr ə lʌvd wʌn/",
    example: "Caring for a loved one can be stressful.",
  },
  {
    id: "ss-painful-loss",
    front: "to deal with a painful loss",
    back: "đối phó với một mất mát đau đớn",
    pronunciation: "/ˈpeɪnfʊl lɒs/",
    example: "We deal with painful loss in different ways.",
  },
  {
    id: "ss-difficult-divorce",
    front: "to live through a difficult divorce",
    back: "sống qua một cuộc ly hôn đầy khó khăn",
    pronunciation: "/ˈdɪfɪkəlt dɪˈvɔːs/",
    example: "Many live through difficult divorces.",
  },
  {
    id: "ss-completely-overwhelmed",
    front: "to feel completely overwhelmed",
    back: "cảm thấy hoàn toàn choáng ngợp",
    pronunciation: "/kəmˈpliːtli ˌəʊvəˈwɛlmd/",
    example: "Parents often feel completely overwhelmed.",
  },
  {
    id: "ss-happiness",
    front: "to be key foundations of happiness",
    back: "là nền tảng chính của hạnh phúc",
    pronunciation: "/ˈfʌndɪˈmeɪʃnz əv ˈhæpinəs/",
    example: "Health is key foundations of happiness.",
  },
  {
    id: "ss-stress-free",
    front: "to live a stress-free life",
    back: "sống một cuộc sống không còn căng thẳng",
    pronunciation: "/strɛs friː/",
    example: "We all want to live a stress-free life.",
  },
  {
    id: "ss-struggle-debt",
    front: "to struggle with debt",
    back: "đấu tranh với nợ nần",
    pronunciation: "/ˈstrʌɡl wɪð dɛt/",
    example: "Many struggle with debt.",
  },
  {
    id: "ss-economic-instability",
    front: "a period of economic instability",
    back: "thời kỳ bất ổn kinh tế",
    pronunciation: "/ˌɪnstəˈbɪləti/",
    example: "Periods of economic instability cause stress.",
  },
  {
    id: "ss-stable-job-market",
    front: "to enter a stable job market",
    back: "tham gia vào một thị trường việc làm ổn định",
    pronunciation: "/ˈsteɪbl dʒɒb ˈmɑːkɪt/",
    example: "Graduates enter the job market.",
  },
  {
    id: "ss-stress-resilience",
    front: "stress resilience",
    back: "khả năng phục hồi sau một giai đoạn căng thẳng",
    pronunciation: "/rɪˈzɪliəns/",
    example: "Stress resilience helps cope with pressure.",
  },
  {
    id: "ss-provoke-worry",
    front: "to provoke worry",
    back: "kích động trạng thái lo lắng",
    pronunciation: "/prəˈvəʊk ˈwʌri/",
    example: "Uncertainty provokes worry.",
  },
  {
    id: "ss-heighten-anxiety",
    front: "to heighten anxiety",
    back: "làm tăng sự lo âu",
    pronunciation: "/ˈhaɪtn ˌæŋˈzaɪəti/",
    example: "Caffeine heightens anxiety.",
  },
  {
    id: "ss-positive-changes",
    front: "to make positive changes",
    back: "tạo ra những thay đổi tích cực",
    pronunciation: "/ˈpɒzətɪv ˈtʃeɪndʒɪz/",
    example: "Make positive changes in your life.",
  },
  {
    id: "ss-cardiovascular",
    front: "to increase the risk of cardiovascular disease, cancer and high blood pressure",
    back: "tăng nguy cơ mắc bệnh tim mạch, ung thư và huyết áp cao",
    pronunciation: "/ˌkɑːdiəʊˈvæskjʊlər dɪˈziːz/",
    example: "Stress increases the risk of cardiovascular disease.",
  },
  {
    id: "ss-vulnerable",
    front: "to be vulnerable to something",
    back: "dễ bị tổn thương với cái gì",
    pronunciation: "/ˈvʌlnərəbl/",
    example: "Children are vulnerable to stress.",
  },
  {
    id: "ss-good-use",
    front: "to make good use of something",
    back: "sử dụng tốt thứ gì",
    pronunciation: "/ɡʊd juːs/",
    example: "Make good use of your free time.",
  },
  {
    id: "ss-positive-outcome",
    front: "to create a positive outcome",
    back: "tạo ra một kết quả tích cực",
    pronunciation: "/ˈpɒzətɪv ˈaʊtkʌm/",
    example: "Together we can create a positive outcome.",
  },
  {
    id: "ss-cultivate-emotions",
    front: "to cultivate positive emotions",
    back: "nuôi dưỡng cảm xúc tích cực",
    pronunciation: "/ˈkʌltɪveɪt ɪˈməʊʃnz/",
    example: "Cultivate positive emotions daily.",
  },
  {
    id: "ss-stay-positive",
    front: "to stay positive",
    back: "lạc quan",
    pronunciation: "/steɪ ˈpɒzətɪv/",
    example: "Stay positive during tough times.",
  },
  {
    id: "ss-constructive-steps",
    front: "to take constructive steps to tackle something",
    back: "thực hiện các bước mang tính xây dựng để giải quyết vấn đề gì",
    pronunciation: "/kənˈstrʌktɪv stɛps/",
    example: "Take constructive steps to tackle stress.",
  },
  {
    id: "ss-make-time",
    front: "to make time for something",
    back: "dành thời gian cho",
    pronunciation: "/meɪk taɪm/",
    example: "Make time for your hobbies.",
  },
  {
    id: "ss-recover-pressure",
    front: "to recover from a period of pressure",
    back: "phục hồi sau một thời gian áp lực",
    pronunciation: "/rɪˈkʌvər/",
    example: "Allow yourself time to recover.",
  },
  {
    id: "ss-rapport",
    front: "to establish a good rapport with somebody",
    back: "thiết lập mối quan hệ tốt với ai",
    pronunciation: "/ˈræpɔːr/",
    example: "Establish rapport with your team.",
  },
  {
    id: "ss-great-deal-harm",
    front: "to do a great deal of harm",
    back: "gây ra nhiều thiệt hại",
    pronunciation: "/ɡreɪt diːl əv hɑːm/",
    example: "Stress can do a great deal of harm.",
  },
  {
    id: "ss-instill-confidence",
    front: "to instill a sense of confidence",
    back: "làm thấm nhuần niềm tin",
    pronunciation: "/ɪnˈstɪl/",
    example: "Mentors instill confidence in students.",
  },
  {
    id: "ss-anxiety-disorder",
    front: "to suffer from an anxiety disorder",
    back: "bị rối loạn lo âu",
    pronunciation: "/æŋˈzaɪəti dɪsˈɔːdər/",
    example: "Many suffer from anxiety disorders.",
  },
  // ── Overpopulation — CAUSES ────────────────────────────────────────────
  {
    id: "op-medical-care",
    front: "improved medical care / advances in the medical field / medical advances",
    back: "cải thiện chăm sóc y tế / tiến bộ trong lĩnh vực y tế / tiến bộ y tế",
    pronunciation: "/ˈmɛdɪkl keər/",
    example: "Medical advances extend life expectancy.",
  },
  {
    id: "op-critical-health",
    front: "to treat critical health ailments",
    back: "điều trị các bệnh nguy hiểm",
    pronunciation: "/ˈkrɪtɪkl hɛlθ/",
    example: "We can treat critical health ailments now.",
  },
  {
    id: "op-control-epidemics",
    front: "to control epidemics",
    back: "kiểm soát dịch bệnh",
    pronunciation: "/kənˈtrəʊl ˌɛpɪˈdɛmɪks/",
    example: "Vaccines help control epidemics.",
  },
  {
    id: "op-vaccines-antibiotics",
    front:
      "vaccines, antibiotics (penicillin), organ transplants, antiviral drugs, stem cell therapy,…",
    back: "vắc-xin, kháng sinh (penicillin), cấy ghép nội tạng, thuốc kháng vi-rút, liệu pháp tế bào gốc,...",
    pronunciation: "/ˌæntɪˌvaɪrəl drʌɡz/",
    example: "Vaccines and antibiotics have saved billions.",
  },
  {
    id: "op-food-security",
    front: "progress in food production and food security",
    back: "tiến bộ trong sản xuất thực phẩm và an ninh lương thực",
    pronunciation: "/fuːd sɪˈkjʊərəti/",
    example: "Modern farming improves food security.",
  },
  {
    id: "op-agricultural-productivity",
    front: "increases in agricultural productivity",
    back: "tăng năng suất nông nghiệp",
    pronunciation: "/ˌæɡrɪˈkʌltʃərəl ˌprɒdʌkˈtɪvəti/",
    example: "Agricultural productivity has soared.",
  },
  {
    id: "op-GM-resistant",
    front: "genetically modified foods → more resistant to diseases, pests,…",
    back: "thực phẩm biến đổi gen → có khả năng kháng bệnh, sâu bệnh tốt hơn",
    pronunciation: "/dʒɪˈnɛtɪkli ˈmɒdɪfaɪd/",
    example: "GM foods are more resistant to pests.",
  },
  {
    id: "op-improve-yields",
    front: "to improve crop yields",
    back: "nâng cao năng suất cây trồng",
    pronunciation: "/kɒp jiːldz/",
    example: "New techniques improve crop yields.",
  },
  {
    id: "op-migration",
    front: "migration",
    back: "di cư",
    pronunciation: "/maɪˈɡreɪʃn/",
    example: "Migration increases urban populations.",
  },
  {
    id: "op-developed-countries",
    front: "to move to developed countries (in search of better jobs)",
    back: "chuyển đến các nước phát triển (tìm kiếm việc làm tốt hơn)",
    pronunciation: "/dɪˈvɛləpt ˈkʌntriz/",
    example: "Many move to developed countries for jobs.",
  },
  {
    id: "op-family-planning",
    front: "lack of family planning",
    back: "thiếu kế hoạch hóa gia đình",
    pronunciation: "/ˈfæmɪli ˈplænɪŋ/",
    example: "Lack of family planning fuels overpopulation.",
  },
  {
    id: "op-illiterate",
    front:
      "people → illiterate / live below the poverty line / have little or no knowledge about family planning",
    back: "người → mù chữ / sống dưới mức nghèo khổ / có ít hoặc không có kiến thức về kế hoạch hóa gia đình",
    pronunciation: "/ɪˈlɪtərət/",
    example: "Many illiterate people lack family planning.",
  },
  {
    id: "op-married-early",
    front: "to get married at an early age",
    back: "kết hôn khi còn nhỏ tuổi",
    pronunciation: "/ˈmærɪd ət ən ˈɜːli eɪdʒ/",
    example: "Some get married at an early age.",
  },
  {
    id: "op-access-education",
    front: "lack of access to education",
    back: "không được tiếp cận với giáo dục",
    pronunciation: "/ˈæksɛs tuː ˌɛdjuˈkeɪʃn/",
    example: "Many lack access to education.",
  },
  {
    id: "op-contraception",
    front: "difficulty in accessing contraception",
    back: "khó tiếp cận với biện pháp tránh thai",
    pronunciation: "/ˌkɒntrəˈsɛpʃn/",
    example: "Many have difficulty accessing contraception.",
  },
  // ── Overpopulation — EFFECTS ────────────────────────────────────────────
  {
    id: "op-resource-depletion",
    front: "depletion of natural resources / environmental damage",
    back: "cạn kiệt tài nguyên thiên nhiên / thiệt hại tới môi trường",
    pronunciation: "/dɪˈpliːʃn/",
    example: "Population growth depletes natural resources.",
  },
  {
    id: "op-fertilizer-impact",
    front:
      "agriculture → the application of chemical fertilizers + the widespread use of pesticides → have a severe impact on the environment",
    back: "nông nghiệp → áp dụng phân bón hóa học + sử dụng rộng rãi thuốc trừ sâu → có tác động nghiêm trọng đến môi trường",
    pronunciation: "/ˈpɛstɪsaɪdz/",
    example: "Pesticides have a severe impact on the environment.",
  },
  {
    id: "op-pollution",
    front: "pollution",
    back: "ô nhiễm",
    pronunciation: "/pəˈluːʃn/",
    example: "Pollution worsens with overpopulation.",
  },
  {
    id: "op-industrial-burn",
    front:
      "more industrial sites → the burning of fossil fuels → an increase in heat-trapping gases / acid rain / air pollution / global warming,...",
    back: "nhiều địa điểm công nghiệp hơn → việc đốt nhiên liệu hóa thạch → sự gia tăng khí khí thải / mưa axit / ô nhiễm không khí / nóng lên toàn cầu, ...",
    pronunciation: "/fɒsl fjuːəlz/",
    example: "Industrial growth releases heat-trapping gases.",
  },
  {
    id: "op-untreated-sewage",
    front: "untreated sewage → released into rivers → provide food for bacteria",
    back: "nước thải chưa được xử lý → thải ra sông → cung cấp thức ăn cho vi khuẩn",
    pronunciation: "/ʌnˈtriːtɪd ˈsjuːɪdʒ/",
    example: "Untreated sewage pollutes rivers.",
  },
  {
    id: "op-deforestation-remove",
    front: "the removal of vast areas of natural forest → for the benefits of humans",
    back: "loại bỏ các khu vực rộng lớn rừng tự nhiên → vì lợi ích của con người",
    pronunciation: "/vɑːst ˈɛəriəz/",
    example: "Vast areas of forest are removed.",
  },
  {
    id: "op-biodiversity-decline",
    front:
      "habitat destruction + a reduction in soil fertility + poor soil structure → a decrease in biodiversity",
    back: "hủy hoại môi trường sống + giảm độ phì nhiêu của đất + cấu trúc đất kém → giảm đa dạng sinh học",
    pronunciation: "/ˌbaɪəʊdaɪˈvɜːsɪti/",
    example: "Habitat destruction decreases biodiversity.",
  },
  {
    id: "op-conflicts-wars",
    front: "conflicts and wars",
    back: "xung đột và chiến tranh",
    pronunciation: "/ˈkɒnflɪkts/",
    example: "Conflicts and wars erupt over resources.",
  },
  {
    id: "op-water-wars",
    front: "conflict over water / water scarcity / face an acute shortage of water → lead to wars",
    back: "xung đột về nước / khan hiếm nước / đối mặt với tình trạng thiếu nước cấp tính → dẫn đến chiến tranh",
    pronunciation: "/ˈwɔːtər ˈskɛəsəti/",
    example: "Water scarcity can lead to wars.",
  },
  {
    id: "op-epidemics-pandemics",
    front: "increased emergence of new epidemics and pandemics",
    back: "gia tăng sự xuất hiện của dịch bệnh và đại dịch mới",
    pronunciation: "/pænˈdɛmɪks/",
    example: "Overcrowding increases new epidemics.",
  },
  {
    id: "op-infectious-diseases",
    front:
      "overcrowded living conditions + pollution + malnutrition + inadequate healthcare → infectious diseases",
    back: "điều kiện sống quá đông đúc + ô nhiễm + suy dinh dưỡng + chăm sóc sức khỏe không đầy đủ → các bệnh truyền nhiễm",
    pronunciation: "/ɪnˈfɛkʃəs dɪˈziːzɪz/",
    example: "Overcrowding triggers infectious diseases.",
  },
  {
    id: "op-higher-crime",
    front: "higher crime rates",
    back: "tỷ lệ tội phạm cao hơn",
    pronunciation: "/ˈkraɪm reɪts/",
    example: "Overpopulation drives higher crime rates.",
  },
  {
    id: "op-animal-extinction",
    front: "animal extinction",
    back: "sự tuyệt chủng các loài động vật",
    pronunciation: "/ˌænɪml ɪkˈstɪŋkʃn/",
    example: "Habitat destruction causes animal extinction.",
  },
  {
    id: "op-extinct-species",
    front:
      "habitat destruction (chop down forests → tourist facilities / farmland,…) → the extinction of many species",
    back: "hủy hoại môi trường sống (chặt phá rừng → các cơ sở du lịch / đất nông nghiệp, ...) → sự tuyệt chủng của nhiều loài",
    pronunciation: "/ˈspeɪʃiːz/",
    example: "Forest destruction leads to species extinction.",
  },
  // ── Overpopulation — OTHER ─────────────────────────────────────────────
  {
    id: "op-rapidly-growing",
    front: "rapidly growing human populations",
    back: "dân số tăng trưởng nhanh chóng",
    pronunciation: "/ˈræpɪdli ˈɡrəʊɪŋ/",
    example: "Rapidly growing populations strain resources.",
  },
  {
    id: "op-population-bomb",
    front: "a population bomb = a population explosion",
    back: "sự bùng nổ dân số",
    pronunciation: "/ˈpɒpjʊˌleɪʃn bɒm/",
    example: "Some call it a population bomb.",
  },
  {
    id: "op-alarming-rates",
    front: "to increase at alarming rates",
    back: "tăng ở mức độ đáng báo động",
    pronunciation: "/əˈlɑːmɪŋ reɪts/",
    example: "Populations increase at alarming rates.",
  },
  {
    id: "op-birth-rates",
    front: "an increase in global birth rates",
    back: "1 sự tăng trong tỷ lệ sinh toàn cầu",
    pronunciation: "/bɜːθ reɪts/",
    example: "Global birth rates have increased.",
  },
  {
    id: "op-life-expectancy",
    front:
      "advances in science, technology, medicine, food production / better medical services / technological breakthroughs → an increase in life expectancy / a decline in mortality rates",
    back: "các tiến bộ trong khoa học, công nghệ, y tế, sản xuất thực phẩm / dịch vụ y tế tốt hơn / các đột phá trong lĩnh vực công nghệ → sự tăng trong tuổi thọ / giảm tỷ lệ tử vong",
    pronunciation: "/maɪˈmɔːtəlɪti reɪts/",
    example: "Medical advances increase life expectancy.",
  },
  {
    id: "op-increased-demands",
    front: "increased demands for water / food / fossil fuels / natural resources /...",
    back: "nhu cầu tăng đối với nước / thực phẩm / nhiên liệu hóa thạch / các nguồn tài nguyên thiên nhiên / ...",
    pronunciation: "/dɪˈmɑːndz/",
    example: "Demand for water rises with population.",
  },
  {
    id: "op-depletion-natural",
    front: "to lead to the depletion of natural resources",
    back: "dẫn tới sự cạn kiệt các nguồn tài nguyên thiên nhiên",
    pronunciation: "/dɪˈpliːʃn/",
    example: "Overuse leads to the depletion of natural resources.",
  },
  {
    id: "op-carrying-capacity",
    front: "to exceed the carrying capacity of the Earth",
    back: "vượt quá sức chứa của trái đất",
    pronunciation: "/ˈkærɪɪŋ kəˈpæsəti/",
    example: "We have exceeded the Earth's carrying capacity.",
  },
  {
    id: "op-end-survival",
    front: "to put an end to human survival",
    back: "đặt dấu chấm hết cho sự tồn tại của con người",
    pronunciation: "/ˈɜːθ ˈkærɪɪŋ kəˈpæsəti/",
    example: "Overuse could put an end to human survival.",
  },
  {
    id: "op-pressure-water-food",
    front: "to put heavy pressure on water / food supplies",
    back: "đặt áp lực nặng nề lên nguồn cung cấp nước / thực phẩm",
    pronunciation: "/ˈprɛʃər ɒn ˈsʌplaɪz/",
    example: "Growing populations pressure water supplies.",
  },
  {
    id: "op-threat-well-being",
    front: "to pose a serious threat to the well-being of planet Earth",
    back: "gây ra mối đe dọa nghiêm trọng cho sức khỏe của trái đất",
    pronunciation: "/wɛl ˈbiːɪŋ/",
    example: "Overpopulation threatens the Earth's well-being.",
  },
  {
    id: "op-environmental-degradation",
    front:
      "to lead to environmental degradation / air, water pollution / soil contamination / global warming / deforestation / desertification / widespread famine / conflicts and wars / higher unemployment rates / higher levels of crime / other serious social problems",
    back: "dẫn tới sự suy thoái môi trường / ô nhiễm không khí, nước / ô nhiễm đất / nóng lên toàn cầu / tàn phá rừng / hoang mạc hóa / đói nghèo trên diện rộng / mâu thuẫn và chiến tranh / tỷ lệ thất nghiệp cao hơn / mức độ tội phạm cao hơn / các vấn đề xã hội khác",
    pronunciation: "/dɪˌzɜːtɪfɪˈkeɪʃn/",
    example: "Overuse leads to environmental degradation.",
  },
  {
    id: "op-population-control",
    front: "population control methods",
    back: "các phương pháp kiểm soát dân số",
    pronunciation: "/kənˈtrəʊl ˈmɛθədz/",
    example: "Population control methods exist.",
  },
  {
    id: "op-family-planning-limit",
    front: "family planning / limit family sizes",
    back: "kế hoạch hóa gia đình / giới hạn kích cỡ gia đình",
    pronunciation: "/lɪmɪt ˈfæmɪli saɪzɪz/",
    example: "Limit family sizes to control population.",
  },
  {
    id: "op-public-awareness",
    front: "to raise public awareness",
    back: "nâng cao ý thức cộng đồng",
    pronunciation: "/reɪz ˈpʌblɪk əˈwɛənəs/",
    example: "Campaigns raise public awareness.",
  },
  {
    id: "op-sex-education",
    front: "to provide sex education in schools",
    back: "cung cấp giáo dục giới tính trong các trường học",
    pronunciation: "/sɛks ˌɛdjuˈkeɪʃn/",
    example: "Sex education in schools is essential.",
  },
];

export { techSocietyCards };
