import type { Flashcard } from "./types";

// ────────────────────────────────────────────────────────────────────────────
// SET 15 — WRITING TASK 1 (Process / Map / Synonyms)
// ────────────────────────────────────────────────────────────────────────────
const writingTask1Cards: Flashcard[] = [
  // Process man-made
  {
    id: "wt1-dug-out",
    front: "to be dug out of the ground",
    back: "được đào lên khỏi mặt đất",
    pronunciation: "/tu biː dʌɡ aʊt əv ðə ɡraʊnd/",
    example: "Clay is dug out of the ground.",
  },
  {
    id: "wt1-metal-grid",
    front: "to be placed onto a metal grid",
    back: "được đặt lên một vỉ kim loại",
    pronunciation: "/tu biː pleɪst ˈɒntuː ə ˈmɛtl ɡrɪd/",
    example: "Bricks are placed onto a metal grid.",
  },
  {
    id: "wt1-roller",
    front: "to be put through a roller",
    back: "được đưa qua băng chuyền",
    pronunciation: "/tu biː pʊt θruː ə ˈrəʊlər/",
    example: "The dough is put through a roller.",
  },
  {
    id: "wt1-small-chunks",
    front: "to break it into small chunks",
    back: "đập nó thành những mảnh nhỏ",
    pronunciation: "/tu breɪk ɪt ˈɪntuː smɔːl tʃʌŋks/",
    example: "We break it into small chunks.",
  },
  {
    id: "wt1-mixed",
    front: "to be mixed with ...",
    back: "được trộn với",
    pronunciation: "/tu biː mɪkst wɪð/",
    example: "The clay is mixed with sand.",
  },
  {
    id: "wt1-mould",
    front: "to be either put in a mould or cut by a wire cutter",
    back: "hoặc được đưa vào một cái khuôn hoặc được cắt bởi một cái máy cắt gạch",
    pronunciation: "/tu biː ˈaɪðər pʊt ɪn ə məʊld ɔːr kʌt baɪ ə ˈwaɪər ˈkʌtər/",
    example: "The mixture is put in a mould or cut by a wire cutter.",
  },
  {
    id: "wt1-well-shaped",
    front: "well-shaped (adj)",
    back: "có hình dạng đẹp",
    pronunciation: "/wel ʃeɪpt/",
    example: "Bricks are well-shaped.",
  },
  {
    id: "wt1-drying-oven",
    front: "to be laid in a drying oven",
    back: "được đặt vào một cái lò nung",
    pronunciation: "/tu biː leɪd ɪn ə ˈdraɪɪŋ ˈʌvn/",
    example: "The bricks are laid in a drying oven.",
  },
  {
    id: "wt1-kiln",
    front: "to be then heated in a kiln",
    back: "được đun nóng trong một cái buồng",
    pronunciation: "/tu biː ðɛn ˈhiːtɪd ɪn ə kɪln/",
    example: "The bricks are heated in a kiln.",
  },
  {
    id: "wt1-mod-temp",
    front: "moderate temperature",
    back: "nhiệt độ vừa phải",
    pronunciation: "/ˈmɒdərət ˈtɛmprətʃər/",
    example: "The bricks are heated at a moderate temperature.",
  },
  {
    id: "wt1-cooled",
    front: "to be cooled",
    back: "được làm nguội",
    pronunciation: "/tu biː kuːld/",
    example: "The bricks are cooled.",
  },
  {
    id: "wt1-packaged",
    front: "to be packaged",
    back: "được đóng gói",
    pronunciation: "/tu biː ˈpækɪdʒd/",
    example: "The product is packaged.",
  },
  {
    id: "wt1-transported",
    front: "to be transported to... / to be delivered to...",
    back: "được vận chuyển tới",
    pronunciation: "/tu biː trænˈspɔːtɪd tuː/",
    example: "The goods are transported to shops.",
  },
  {
    id: "wt1-picked",
    front: "to be picked by hand",
    back: "được hái bằng tay",
    pronunciation: "/tu biː pɪkt baɪ hænd/",
    example: "Coffee beans are picked by hand.",
  },
  {
    id: "wt1-dried-sun",
    front: "to be dried in the sun",
    back: "được phơi khô dưới ánh nắng mặt trời",
    pronunciation: "/tu biː draɪd ɪn ðə sʌn/",
    example: "Coffee beans are dried in the sun.",
  },
  {
    id: "wt1-sold",
    front: "to be sold to ...",
    back: "được bán cho",
    pronunciation: "/tu biː səʊld tuː/",
    example: "Coffee jars are sold to consumers.",
  },
  {
    id: "wt1-harvested",
    front: "to be harvested",
    back: "được thu hoạch",
    pronunciation: "/tu biː ˈhɑːvɪstɪd/",
    example: "Corn is harvested.",
  },
  // Process natural
  {
    id: "wt1-changes",
    front: "to experience/undergo significant changes",
    back: "trải qua những thay đổi đáng kể",
    pronunciation: "/tu ɪkˈspɪəriəns sɪɡˈnɪfɪkənt ˈtʃeɪndʒɪz/",
    example: "The salmon experiences significant changes.",
  },
  {
    id: "wt1-physical-stages",
    front: "to pass through three distinct physical stages",
    back: "trải qua ba giai đoạn vật lý khác nhau",
    pronunciation: "/tu pɑːs θruː θriː dɪˈstɪŋkt ˈfɪzɪkl steɪdʒɪz/",
    example: "It passes through three distinct physical stages.",
  },
  {
    id: "wt1-lay-eggs",
    front: "to lay a couple of/ a massive number of eggs",
    back: "đẻ một vài / một số lượng lớn trứng",
    pronunciation: "/tu leɪ ə kʌpl əv eɡz/",
    example: "Female salmon lay a massive number of eggs.",
  },
  {
    id: "wt1-begin-life",
    front: "to begin life as eggs",
    back: "bắt đầu cuộc sống là những trái trứng",
    pronunciation: "/tu bɪˈɡɪn laɪf əz eɡz/",
    example: "They begin life as eggs.",
  },
  {
    id: "wt1-hatch",
    front: "to hatch within 3 to 5 days",
    back: "nở trong vòng 3 đến 5 ngày",
    pronunciation: "/tu hætʃ wɪˈðɪn θriː tu faɪv deɪz/",
    example: "The eggs hatch within 3 to 5 days.",
  },
  {
    id: "wt1-hatch-into",
    front: "to hatch into …",
    back: "nở thành con gì",
    pronunciation: "/tu hætʃ ˈɪntuː/",
    example: "The eggs hatch into tiny fish.",
  },
  {
    id: "wt1-hatching-process",
    front: "the hatching process",
    back: "quá trình nở",
    pronunciation: "/ðə ˈhætʃɪŋ ˈprəʊses/",
    example: "The hatching process takes 3 to 5 days.",
  },
  {
    id: "wt1-cm-length",
    front: "to be … cm in length / to be … cm long",
    back: "dài … cm",
    pronunciation: "/tu biː sɛntɪmiːtəz ɪn lɛŋθ/",
    example: "It is 5 cm long.",
  },
  {
    id: "wt1-vary",
    front: "to vary in size/colours/shapes",
    back: "đa dạng về kích thước / màu sắc / hình dạng",
    pronunciation: "/tu ˈveəri ɪn saɪz/",
    example: "They vary in size and colour.",
  },
  {
    id: "wt1-termed",
    front: "to be termed … / to be commonly called …",
    back: "được gọi chung là",
    pronunciation: "/tu biː tɜːmd/",
    example: "They are commonly called salmon.",
  },
  {
    id: "wt1-adult-size",
    front:
      "to grow to adult size / grow to maturity / turn into an adult / become fully-grown adults",
    back: "tăng trưởng thành kích thước trưởng thành / tới giai đoạn trưởng thành",
    pronunciation: "/tu ɡrəʊ tu əˈdʌlt saɪz/",
    example: "They grow to adult size.",
  },
  {
    id: "wt1-adult-stage",
    front: "to make it to the adult stage",
    back: "đạt tới giai đoạn trưởng thành",
    pronunciation: "/tu meɪk ɪt tu ði əˈdʌlt steɪdʒ/",
    example: "Few make it to the adult stage.",
  },
  {
    id: "wt1-emerge",
    front: "to emerge / appear",
    back: "xuất hiện",
    pronunciation: "/tu iˈmɜːdʒ/",
    example: "Adult salmon emerge from the river.",
  },
  {
    id: "wt1-feeding",
    front: "feeding grounds",
    back: "khu vực kiếm ăn",
    pronunciation: "/ˈfiːdɪŋ ɡraʊndz/",
    example: "Salmon travel to feeding grounds.",
  },
  {
    id: "wt1-feed-on",
    front: "to feed on ...",
    back: "ăn cái gì",
    pronunciation: "/tu fiːd ɒn/",
    example: "Tadpoles feed on plants.",
  },
  {
    id: "wt1-gills",
    front: "external gills / internal gills",
    back: "cái mang bên ngoài / cái mang bên trong",
    pronunciation: "/ɪkˈstɜːnl ɡɪlz/",
    example: "Tadpoles have external gills.",
  },
  {
    id: "wt1-hind-legs",
    front: "to grow the hind legs / the front legs",
    back: "mọc chân sau / chân trước",
    pronunciation: "/tu ɡrəʊ ðə haɪnd lɛɡz/",
    example: "Frogs grow their hind legs first.",
  },
  {
    id: "wt1-double-size",
    front: "to grow quickly in size / double in size",
    back: "phát triển nhanh chóng về kích thước / kích thước gấp đôi",
    pronunciation: "/tu ɡrəʊ ˈkwɪkli ɪn saɪz/",
    example: "They grow quickly in size.",
  },
  {
    id: "wt1-shed-skin",
    front: "to shed their old skin / shed their outer layer",
    back: "thay da cũ / thay lớp ngoài của chúng",
    pronunciation: "/tu ʃɛd ðeər əʊld skɪn/",
    example: "Snakes shed their old skin.",
  },
  {
    id: "wt1-moult",
    front: "to moult several times",
    back: "thay lông vài lần",
    pronunciation: "/tu məʊlt ˈsɛvrəl taɪmz/",
    example: "Birds moult several times a year.",
  },
  {
    id: "wt1-breathe-underwater",
    front: "to breathe underwater",
    back: "hít thở dưới nước",
    pronunciation: "/tu briːð ˈʌndərwɔːtər/",
    example: "Fish breathe underwater.",
  },
  {
    id: "wt1-mass-migration",
    front: "to make mass migration across long distances",
    back: "thực hiện di cư hàng loạt với khoảng cách dài",
    pronunciation: "/tu meɪk mæs maɪˈɡreɪʃn əˈkrɒs lɒŋ ˈdɪstənsɪz/",
    example: "Salmon make mass migration across long distances.",
  },
  {
    id: "wt1-cycle-repeats",
    front: "the cycle repeats itself / starts again",
    back: "chu kỳ lặp lại / bắt đầu lại",
    pronunciation: "/ðə ˈsaɪkl rɪˈpiːts ɪtˈsɛlf/",
    example: "The cycle repeats itself.",
  },
  {
    id: "wt1-life-cycle",
    front: "the life cycle takes/lasts … days/weeks/...",
    back: "vòng đời kéo dài … ngày / tuần /...",
    pronunciation: "/ðə laɪf ˈsaɪkl/",
    example: "The life cycle lasts 10 weeks.",
  },
  {
    id: "wt1-after-development",
    front: "after … days/weeks of development",
    back: "sau … ngày / tuần phát triển",
    pronunciation: "/ˈɑːftər/",
    example: "After 3 days of development.",
  },
  {
    id: "wt1-normally-live",
    front: "to normally live for … to … weeks/months/years",
    back: "thường sống từ … đến … tuần / tháng / năm",
    pronunciation: "/tu ˈnɔːməli lɪv fɔːr/",
    example: "They normally live for 2 to 3 years.",
  },
  {
    id: "wt1-over-course",
    front: "over the course of … days/weeks",
    back: "trong bao nhiêu ngày / tuần",
    pronunciation: "/ˈəʊvər ðə kɔːs/",
    example: "Over the course of 7 days.",
  },
  {
    id: "wt1-covered-with",
    front: "to be covered with …",
    back: "được che phủ, bao phủ bởi",
    pronunciation: "/tu biː ˈkʌvərd wɪð/",
    example: "It is covered with feathers.",
  },
  {
    id: "wt1-build-nests",
    front: "to build their nests in trees/on the ground",
    back: "xây dựng tổ của chúng trên cây / trên mặt đất",
    pronunciation: "/tu bɪld ðeər nɛsts ɪn triːz/",
    example: "Birds build their nests in trees.",
  },
  {
    id: "wt1-optimal-conditions",
    front: "under optimal conditions",
    back: "trong điều kiện tối ưu",
    pronunciation: "/ˈʌndər ˈɒptɪməl kənˈdɪʃnz/",
    example: "Under optimal conditions, salmon thrive.",
  },
  {
    id: "wt1-adverse-circumstances",
    front: "in adverse circumstances",
    back: "trong các trường hợp bất lợi",
    pronunciation: "/ɪn ˈædvɜːrs ˈsɜːkəmstənsɪz/",
    example: "In adverse circumstances, few survive.",
  },
  // Synonyms
  {
    id: "wt1-syn-0to14",
    front: "the 0 to 14 age group ≈ children aged 14 or under ≈ the youngest group",
    back: "nhóm tuổi từ 0 tới 14",
    pronunciation: "/ðə zɪərəʊ tu fɔːtiːn eɪdʒ ɡruːp/",
    example: "The 0 to 14 age group is the largest.",
  },
  {
    id: "wt1-syn-30to50",
    front: "the 30 to 50 age group ≈ people aged 30 to 50 ≈ people between the ages of 30 and 50",
    back: "nhóm tuổi từ 30 tới 50",
    pronunciation: "/ðə θɜːti tu fɪfti eɪdʒ ɡruːp/",
    example: "The 30 to 50 age group dominates the workforce.",
  },
  {
    id: "wt1-syn-populations",
    front: "the populations of … ≈ the demographics of …",
    back: "dân số của",
    pronunciation: "/ðə ˌpɒpjʊˈleɪʃnz əv/",
    example: "The populations of urban areas are growing.",
  },
  {
    id: "wt1-syn-chart",
    front: "the chart ≈ the line graph/ the pie chart/ the bar chart/ the table/ the process/ …",
    back: "biểu đồ",
    pronunciation: "/ðə tʃɑːt/",
    example: "The chart shows population growth.",
  },
  {
    id: "wt1-syn-show",
    front: "to show ≈ to compare/ illustrate/ give information on/ show key data on …",
    back: "thể hiện / so sánh",
    pronunciation: "/tu ʃəʊ/",
    example: "The chart shows key data on age groups.",
  },
  {
    id: "wt1-syn-rise-rapidly",
    front: "to rise rapidly ≈ to experience a rapid increase",
    back: "tăng nhanh",
    pronunciation: "/tu raɪz ˈræpɪdli/",
    example: "Sales rose rapidly last year.",
  },
  {
    id: "wt1-syn-decrease",
    front: "to decrease slowly ≈ to see a slow decline",
    back: "giảm chậm",
    pronunciation: "/tu dɪˈkriːs ˈsləʊli/",
    example: "Prices decreased slowly over the year.",
  },
  {
    id: "wt1-syn-by-contrast",
    front: "By contrast, … ≈ … illustrate a different pattern",
    back: "Ngược lại, ...",
    pronunciation: "/baɪ ˈkɒntrɑːst/",
    example: "By contrast, sales fell in Asia.",
  },
  {
    id: "wt1-syn-similarly",
    front: "Similarly, … ≈ show a similar pattern",
    back: "Tương tự vậy",
    pronunciation: "/ˈsɪmələli/",
    example: "Similarly, revenue grew in Europe.",
  },
  {
    id: "wt1-syn-while",
    front: "while … ≈ whilst … ≈ whereas …",
    back: "trong khi",
    pronunciation: "/waɪl/",
    example: "While sales rose, profits fell.",
  },
  {
    id: "wt1-syn-in-terms",
    front: "in terms of … ≈ regarding … ≈ Looking at …, it can be seen that …",
    back: "Khi nói về",
    pronunciation: "/ɪn tɜːmz əv/",
    example: "In terms of size, this city is the largest.",
  },
  {
    id: "wt1-syn-given-period",
    front: "over the given period ≈ during this time frame",
    back: "trong suốt giai đoạn nào đó",
    pronunciation: "/ˈəʊvər ðə ˈɡɪvn ˈpɪəriəd/",
    example: "Over the given period, prices rose.",
  },
  {
    id: "wt1-syn-10year",
    front: "over a 10-year period ≈ over a period of 10 years",
    back: "trong giai đoạn 10 năm",
    pronunciation: "/ˈəʊvər ə pɪəriəd əv tɛn jɪəz/",
    example: "Over a 10-year period, the city grew.",
  },
  {
    id: "wt1-syn-1990-2000",
    front: "from 1990 to 2000 ≈ between 1990 and 2000",
    back: "từ năm 1990 tới 2000",
    pronunciation: "/frəm/",
    example: "From 1990 to 2000, sales doubled.",
  },
  {
    id: "wt1-syn-2-years",
    front: "in 1990 and 2000 ≈ in two different years, 1990 and 2000",
    back: "trong 2 năm, 1990 và 2000",
    pronunciation: "/ɪn tuː ˈdɪfrənt jɪəz/",
    example: "Sales rose in 1990 and 2000.",
  },
  {
    id: "wt1-syn-collecting",
    front: "beginning with collecting … ≈ starting with the collection of …",
    back: "bắt đầu bằng việc thu thập",
    pronunciation: "/bɪˈɡɪnɪŋ wɪð kəˈlɛktɪŋ/",
    example: "Starting with the collection of data.",
  },
  {
    id: "wt1-syn-packaging",
    front: "ending with … being packaged … ≈ ending at the packing stage",
    back: "kết thúc ở giai đoạn đóng gói",
    pronunciation: "/ˈɛndɪŋ wɪð/",
    example: "The process ends at the packing stage.",
  },
  {
    id: "wt1-syn-transported",
    front: "to be transported to … ≈ to be delivered to …",
    back: "được vận chuyển tới",
    pronunciation: "/tu biː trænˈspɔːtɪd tuː/",
    example: "Goods are delivered to stores.",
  },
  {
    id: "wt1-syn-life-cycle",
    front: "the life cycle of … ≈ the development of …",
    back: "vòng đời / sự phát triển của con gì",
    pronunciation: "/ðə laɪf ˈsaɪkl əv/",
    example: "The life cycle of a butterfly.",
  },
  {
    id: "wt1-syn-percentage",
    front: "the percentage of … ≈ the proportion of …",
    back: "tỷ lệ",
    pronunciation: "/ðə pəˈsɛntɪdʒ əv/",
    example: "The percentage of users grew.",
  },
  // Map - Population
  {
    id: "wt1-population",
    front: "Nơi nào đó + has a population of + số dân + people",
    back: "có dân số là...",
    pronunciation: "/həz ə ˌpɒpjʊˈleɪʃn əv/",
    example: "This city has a population of 1000 people.",
  },
  {
    id: "wt1-inhabitants",
    front: "Nơi nào đó + has + số dân + inhabitants",
    back: "có ... cư dân",
    pronunciation: "/ɪnˈhæbɪtənts/",
    example: "This city has 1000 inhabitants.",
  },
  {
    id: "wt1-population-of",
    front: "The population of + nơi nào đó + is + số dân",
    back: "Dân số của ... là",
    pronunciation: "/ðə ˌpɒpjʊˈleɪʃn əv/",
    example: "The population of this city is 1000.",
  },
  // Map - Roads
  {
    id: "wt1-roads",
    front: "The main road runs through the entire city from North to South",
    back: "Tuyến đường chính chạy xuyên qua toàn thành phố từ Bắc vào Nam",
    pronunciation: "/ðə meɪn rəʊd rʌnz θruː ði ɪnˈtaɪə sɪti/",
    example: "The main road runs through the entire city from North to South.",
  },
  {
    id: "wt1-run-through",
    front: "run through = pass through = go through = cross",
    back: "chạy xuyên qua",
    pronunciation: "/rʌn θruː/",
    example: "The road crosses the river.",
  },
  // Map - Position
  {
    id: "wt1-direction",
    front: "east/ west/ south/ north",
    back: "đông/ tây/ nam/ bắc",
    pronunciation: "/iːst wɛst saʊθ nɔːθ/",
    example: "The school is in the north of the river.",
  },
  {
    id: "wt1-position",
    front: "left/ right/ top/ bottom/ middle/ centre",
    back: "trái/ phải/ trên/ dưới/ giữa/ trung tâm",
    pronunciation: "/lɛft raɪt/",
    example: "The shop is in the centre of the city.",
  },
  {
    id: "wt1-situated",
    front: "to be situated/ located/ positioned",
    back: "nằm ở",
    pronunciation: "/tu biː ˈsɪtʃueɪtɪd/",
    example: "The school is located to the north of the river.",
  },
  // Length
  {
    id: "wt1-length-of",
    front: "Nơi nào đó + has a length of + chiều dài",
    back: "có chiều dài là",
    pronunciation: "/həz ə lɛŋθ əv/",
    example: "The island has a length of 250 km.",
  },
  {
    id: "wt1-total-length",
    front: "Nơi nào đó's total length is + chiều dài",
    back: "tổng chiều dài là",
    pronunciation: "/ˈtəʊtl lɛŋθ/",
    example: "The island's total length is about 250 km.",
  },
  {
    id: "wt1-km-long",
    front: "Nơi nào đó + is + chiều dài + long",
    back: "dài bao nhiêu",
    pronunciation: "/kɪˈlɒmiːtə lɒŋ/",
    example: "The island is 250 km long.",
  },
  // Change - unchanged / extended / narrowed / moved / disappeared / replaced
  {
    id: "wt1-unchanged",
    front: "Nơi nào đó + remain unchanged / still exist",
    back: "giữ nguyên",
    pronunciation: "/rɪˈmeɪn ʌnˈtʃeɪndʒd/",
    example: "From 1980 to 2000, the school remained unchanged.",
  },
  {
    id: "wt1-expanded",
    front: "Nơi nào đó + to be + expanded/ extended/ widened / become + bigger",
    back: "được mở rộng",
    pronunciation: "/ɪkˈspændɪd/",
    example: "Between 2000 and 2005, the car park was slightly extended.",
  },
  {
    id: "wt1-lengthened",
    front: "Nơi nào đó + to be + lengthened",
    back: "được kéo dài",
    pronunciation: "/ˈlɛŋθnd/",
    example: "The industrial complex was significantly lengthened.",
  },
  {
    id: "wt1-narrowed",
    front: "Nơi nào đó + to be + narrowed / become + smaller",
    back: "được thu hẹp",
    pronunciation: "/ˈnærəʊd/",
    example: "The shopping mall was dramatically narrowed.",
  },
  {
    id: "wt1-shortened",
    front: "Nơi nào đó + to be + shortened",
    back: "được rút ngắn",
    pronunciation: "/ˈʃɔːtnd/",
    example: "The railway line was slightly shortened.",
  },
  {
    id: "wt1-moved",
    front: "Nơi nào đó + to be + moved/ relocated to + nơi mới",
    back: "được di chuyển tới",
    pronunciation: "/tu biː muːvd/",
    example: "The school was relocated to the north of the village.",
  },
  {
    id: "wt1-demolished",
    front: "Nơi nào đó + to be + demolished / destroyed / knocked down",
    back: "bị phá hủy",
    pronunciation: "/tu biː dɪˈmɒlɪʃt/",
    example: "The hospital was demolished.",
  },
  {
    id: "wt1-forest-cleared",
    front: "Rừng cây + to be + cleared / chopped down / cut down",
    back: "bị chặt phá",
    pronunciation: "/tu biː klɪəd/",
    example: "The woodland was cut down.",
  },
  {
    id: "wt1-built",
    front: "Nơi nào đó + to be + built / constructed / erected",
    back: "được xây dựng",
    pronunciation: "/tu biː bɪlt/",
    example: "A new school was built next to the car park.",
  },
  {
    id: "wt1-make-way",
    front: "Nơi nào đó + to be + demolished + to make way for + nơi mới",
    back: "bị phá để nhường chỗ cho",
    pronunciation: "/tu meɪk weɪ fɔːr/",
    example: "The school was demolished to make way for a science block.",
  },
  {
    id: "wt1-replaced-by",
    front: "Nơi nào đó + to be + demolished + and replaced by + nơi mới",
    back: "bị phá và thay thế bởi",
    pronunciation: "/rɪˈpleɪst baɪ/",
    example: "The school was demolished and replaced by a science block.",
  },
  {
    id: "wt1-replace",
    front: "Nơi mới + to be + built + to replace + nơi cũ",
    back: "được xây để thay thế",
    pronunciation: "/tu rɪˈpleɪs/",
    example: "A science block was built to replace the school.",
  },
  {
    id: "wt1-on-site",
    front: "Nơi mới + to be + built + on the original site of + nơi cũ",
    back: "được xây trên vị trí cũ của",
    pronunciation: "/ɒn ði əˈrɪdʒənl saɪt əv/",
    example: "A new block was built on the original site of the school.",
  },
  {
    id: "wt1-appear",
    front: "Nơi nào đó + appear / disappear",
    back: "xuất hiện / biến mất",
    pronunciation: "/əˈpɪər/",
    example: "A new park appeared next to the school.",
  },
];

export { writingTask1Cards };
