import { FlashcardSet } from "./types";

/** Built-in flashcard sets: Chinese vocabulary — food & drinks.
 *  Auto-generated from `tu_vung_tieng_trung_an_uong_ro_rang.xlsx`.
 *  Columns: Chủ đề | Nhóm | STT | Tiếng Trung | Phiên âm | Tiếng Việt */
export const builtinZhFoodSets: FlashcardSet[] = [
  {
    id: "builtin:zh-food-cac-mon-khai-vi",
    name: "Các món khai vị",
    description: "Món ăn · Các món khai vị (5 từ vựng tiếng Trung về ẩm thực)",
    icon: "utensils",
    color: "#ef4444",
    builtin: true,
    cards: [
      { id: "zh-food-cac-mon-khai-vi-1", front: "凉拌蔬菜", back: "Nộm rau củ", pronunciation: "liángbàn shūcài" },
      { id: "zh-food-cac-mon-khai-vi-2", front: "凉拌卷心菜", back: "Nộm bắp cải", pronunciation: "liángbàn juǎnxīncài" },
      { id: "zh-food-cac-mon-khai-vi-3", front: "凉拌黄瓜", back: "Dưa chuột trộn", pronunciation: "liángbàn huángguā" },
      { id: "zh-food-cac-mon-khai-vi-4", front: "凉拌菜", back: "Nộm", pronunciation: "liángbàn cài" },
      { id: "zh-food-cac-mon-khai-vi-5", front: "清淡口味", back: "Món thanh đạm", pronunciation: "qīng dàn kǒuwèi" }
    ],
  },
  {
    id: "builtin:zh-food-cac-mon-chinh",
    name: "Các món chính",
    description: "Món ăn · Các món chính (32 từ vựng tiếng Trung về ẩm thực)",
    icon: "utensils",
    color: "#ef4444",
    builtin: true,
    cards: [
      { id: "zh-food-cac-mon-chinh-1", front: "面包", back: "Bánh mì", pronunciation: "miànbāo" },
      { id: "zh-food-cac-mon-chinh-2", front: "包子", back: "Bánh bao", pronunciation: "bāozi" },
      { id: "zh-food-cac-mon-chinh-3", front: "肠粉/卷筒粉", back: "Bánh cuốn", pronunciation: "chángfěn/juǎn tǒng fěn" },
      { id: "zh-food-cac-mon-chinh-4", front: "炸糕", back: "Bánh rán", pronunciation: "zhàgāo" },
      { id: "zh-food-cac-mon-chinh-5", front: "面包和鸡蛋", back: "Bánh mì kẹp trứng", pronunciation: "miànbāo hé jīdàn" },
      { id: "zh-food-cac-mon-chinh-6", front: "香蕉饼", back: "Bánh chuối", pronunciation: "xiāngjiāo bǐng" },
      { id: "zh-food-cac-mon-chinh-7", front: "饼干", back: "Bích quy", pronunciation: "bǐnggān" },
      { id: "zh-food-cac-mon-chinh-8", front: "肉包，菜包", back: "Bánh bao nhân thịt, nhân rau củ", pronunciation: "ròubāo, cài bāo" },
      { id: "zh-food-cac-mon-chinh-9", front: "汤圆", back: "Bánh trôi, chè trôi nước", pronunciation: "tāngyuán" },
      { id: "zh-food-cac-mon-chinh-10", front: "薄粉/粉纸", back: "Bánh tráng", pronunciation: "báo fěn/fěn zhǐ" },
      { id: "zh-food-cac-mon-chinh-11", front: "馒头", back: "Bánh màn thầu", pronunciation: "mántou" },
      { id: "zh-food-cac-mon-chinh-12", front: "粽子", back: "Bánh tét, bánh chưng", pronunciation: "zòngzi" },
      { id: "zh-food-cac-mon-chinh-13", front: "锅贴", back: "Món há cảo chiên", pronunciation: "guō tiē" },
      { id: "zh-food-cac-mon-chinh-14", front: "生煎包", back: "Bánh bao chiên", pronunciation: "shēng jiān bāo" },
      { id: "zh-food-cac-mon-chinh-15", front: "葱油饼", back: "Bánh kẹp hành chiên", pronunciation: "cōng yóu bǐng" },
      { id: "zh-food-cac-mon-chinh-16", front: "鸡蛋饼", back: "Bánh trứng", pronunciation: "jīdàn bǐng" },
      { id: "zh-food-cac-mon-chinh-17", front: "肉夹馍", back: "Bánh mì kẹp Tây An (Bánh mì sandwich theo phong cách Trung Quốc kẹp thịt bên trong)", pronunciation: "ròu jiā mó" },
      { id: "zh-food-cac-mon-chinh-18", front: "面包和牛餐肉", back: "Bánh mì pate", pronunciation: "miànbāo héniú cān ròu" },
      { id: "zh-food-cac-mon-chinh-19", front: "片米饼", back: "Bánh cốm", pronunciation: "piàn mǐ bǐng" },
      { id: "zh-food-cac-mon-chinh-20", front: "糯米软糕", back: "Bánh dẻo", pronunciation: "nuòmǐ ruǎn gāo" },
      { id: "zh-food-cac-mon-chinh-21", front: "月饼", back: "Bánh trung thu", pronunciation: "yuèbǐng" },
      { id: "zh-food-cac-mon-chinh-22", front: "蛋糕", back: "Bánh gatô", pronunciation: "dàngāo" },
      { id: "zh-food-cac-mon-chinh-23", front: "鱼米线", back: "Bún cá", pronunciation: "yúmǐxiàn" },
      { id: "zh-food-cac-mon-chinh-24", front: "螺蛳粉", back: "Bún ốc", pronunciation: "luósī fěn" },
      { id: "zh-food-cac-mon-chinh-25", front: "蟹汤米线", back: "Bún riêu cua", pronunciation: "xiè tāng mǐxiàn" },
      { id: "zh-food-cac-mon-chinh-26", front: "烤肉米线", back: "Bún chả", pronunciation: "kǎoròu mǐxiàn" },
      { id: "zh-food-cac-mon-chinh-27", front: "鱼露米线", back: "Bún mắm", pronunciation: "yúlù mǐxiàn" },
      { id: "zh-food-cac-mon-chinh-28", front: "汤粉", back: "Bún", pronunciation: "tāngfěn" },
      { id: "zh-food-cac-mon-chinh-29", front: "方便面", back: "Mì ăn liền", pronunciation: "fāngbiànmiàn" },
      { id: "zh-food-cac-mon-chinh-30", front: "广南米粉", back: "Mì quảng", pronunciation: "Guǎngnán mǐfěn" },
      { id: "zh-food-cac-mon-chinh-31", front: "馄饨面", back: "Mì vằn thắn (hoành thánh)", pronunciation: "húntún miàn" },
      { id: "zh-food-cac-mon-chinh-32", front: "面食", back: "miànshí" }
    ],
  },
  {
    id: "builtin:zh-food-cac-loai-mi",
    name: "Các loại mì",
    description: "Món ăn · Các loại mì (19 từ vựng tiếng Trung về ẩm thực)",
    icon: "utensils",
    color: "#ef4444",
    builtin: true,
    cards: [
      { id: "zh-food-cac-loai-mi-1", front: "牛肉拉面", back: "Mì thịt bò", pronunciation: "niúròu lāmiàn" },
      { id: "zh-food-cac-loai-mi-2", front: "打卤面", back: "Mì có nước sốt đậm đặc", pronunciation: "dǎlǔ miàn" },
      { id: "zh-food-cac-loai-mi-3", front: "葱油拌面", back: "Mì sốt dầu hành", pronunciation: "cōng yóu bàn miàn" },
      { id: "zh-food-cac-loai-mi-4", front: "雪菜肉丝面", back: "Mì nấu với cải chua cùng thịt bằm", pronunciation: "xuě cài ròusī miàn" },
      { id: "zh-food-cac-loai-mi-5", front: "蚝油炒面", back: "Mì xào dầu hào", pronunciation: "háoyóu chǎomiàn" },
      { id: "zh-food-cac-loai-mi-6", front: "干炒牛河粉", back: "Phở xào thịt bò", pronunciation: "gān chǎo niú héfěn" },
      { id: "zh-food-cac-loai-mi-7", front: "牛肉粉/牛肉粉丝汤", back: "Phở bò", pronunciation: "niúròu fěn/niúròu mǐfěntāng" },
      { id: "zh-food-cac-loai-mi-8", front: "河粉", back: "Phở", pronunciation: "héfěn" },
      { id: "zh-food-cac-loai-mi-9", front: "鸡肉粉/鸡肉粉丝汤", back: "Phở gà", pronunciation: "jīròu fěn/jīròu fěnsī tāng" },
      { id: "zh-food-cac-loai-mi-10", front: "炒饭", back: "Cơm rang", pronunciation: "chǎofàn" },
      { id: "zh-food-cac-loai-mi-11", front: "剩饭", back: "Cơm nguội", pronunciation: "shèngfàn" },
      { id: "zh-food-cac-loai-mi-12", front: "炒牛肉饭", back: "Cơm thịt bò xào", pronunciation: "chǎo niúròu fàn" },
      { id: "zh-food-cac-loai-mi-13", front: "茄汁油豆腐塞肉饭", back: "Cơm thịt đậu sốt cà chua", pronunciation: "qié zhī yóu dòufu sāi ròu fàn" },
      { id: "zh-food-cac-loai-mi-14", front: "白饭/米饭", back: "Cơm trắng", pronunciation: "báifàn/mǐfàn" },
      { id: "zh-food-cac-loai-mi-15", front: "汤饭 / 泡饭", back: "Món cơm chan súp", pronunciation: "tāngfàn / pàofàn" },
      { id: "zh-food-cac-loai-mi-16", front: "蛋炒饭", back: "Cơm chiên trứng", pronunciation: "dàn chǎofàn" },
      { id: "zh-food-cac-loai-mi-17", front: "排骨汤", back: "Canh sườn", pronunciation: "páigǔ tāng" },
      { id: "zh-food-cac-loai-mi-18", front: "冬瓜汤", back: "Canh bí", pronunciation: "dōngguā tāng" },
      { id: "zh-food-cac-loai-mi-19", front: "一汤类", back: "yī tāng lèi" }
    ],
  },
  {
    id: "builtin:zh-food-cac-loai-canh",
    name: "Các loại Canh",
    description: "Món ăn · Các loại Canh (40 từ vựng tiếng Trung về ẩm thực)",
    icon: "utensils",
    color: "#ef4444",
    builtin: true,
    cards: [
      { id: "zh-food-cac-loai-canh-1", front: "麻辣烫", back: "Món canh cay (nấu cùng hỗn hợp nhiều đồ ăn kèm)", pronunciation: "málà tàng" },
      { id: "zh-food-cac-loai-canh-2", front: "番茄蛋汤", back: "Canh cà chua nấu trứng", pronunciation: "fānqié dàn tāng" },
      { id: "zh-food-cac-loai-canh-3", front: "榨菜肉丝汤", back: "Canh su hào nấu thịt bằm", pronunciation: "zhàcài ròusī tāng" },
      { id: "zh-food-cac-loai-canh-4", front: "酸辣汤", back: "Canh chua cay", pronunciation: "suānlà tāng" },
      { id: "zh-food-cac-loai-canh-5", front: "酸菜粉丝汤", back: "Súp bún tàu nấu với cải chua", pronunciation: "suāncài fěnsī tāng" },
      { id: "zh-food-cac-loai-canh-6", front: "黄豆排骨汤", back: "Canh đậu nành nấu sườn non", pronunciation: "huáng dòu pái gǔ tāng" },
      { id: "zh-food-cac-loai-canh-7", front: "糯米饭", back: "Xôi", pronunciation: "nuòmǐ fàn" },
      { id: "zh-food-cac-loai-canh-8", front: "木整糯米饭", back: "Xôi gấc", pronunciation: "mù zhěng nuòmǐ fàn" },
      { id: "zh-food-cac-loai-canh-9", front: "绿豆面糯米团", back: "Xôi xéo", pronunciation: "lǜdòu miàn nuòmǐ tuán" },
      { id: "zh-food-cac-loai-canh-10", front: "稀饭", back: "Cháo trắng", pronunciation: "xīfàn" },
      { id: "zh-food-cac-loai-canh-11", front: "皮蛋瘦肉粥", back: "Cháo trắng nấu với hột vịt bích thảo cùng thịt nạc", pronunciation: "Pídàn shòuròu zhōu" },
      { id: "zh-food-cac-loai-canh-12", front: "及第粥", back: "Cháo lòng", pronunciation: "jídì zhōu" },
      { id: "zh-food-cac-loai-canh-13", front: "艇仔粥", back: "Cháo hải sản", pronunciation: "tǐng zǎi zhōu" },
      { id: "zh-food-cac-loai-canh-14", front: "毛蛋", back: "Trứng vịt lộn", pronunciation: "máodàn" },
      { id: "zh-food-cac-loai-canh-15", front: "汉堡", back: "Hamburger", pronunciation: "Hàn bǎo" },
      { id: "zh-food-cac-loai-canh-16", front: "三明治", back: "Sandwich", pronunciation: "sānmíngzhì" },
      { id: "zh-food-cac-loai-canh-17", front: "米粉", back: "Bún, phở", pronunciation: "mǐfěn" },
      { id: "zh-food-cac-loai-canh-18", front: "烧卖", back: "Xíu mại", pronunciation: "shāomai" },
      { id: "zh-food-cac-loai-canh-19", front: "香肠", back: "Lạp xưởng", pronunciation: "xiāngcháng" },
      { id: "zh-food-cac-loai-canh-20", front: "茄汁烩鱼/西红柿烩鱼丝", back: "Cá sốt cà chua", pronunciation: "qiézhī huìyú/Xīhóngshì huì yú sī" },
      { id: "zh-food-cac-loai-canh-21", front: "煎鸡蛋", back: "Trứng ốp la", pronunciation: "jiān jīdàn" },
      { id: "zh-food-cac-loai-canh-22", front: "手撕包菜", back: "Bắp cải xào", pronunciation: "shǒu sī bāo cài" },
      { id: "zh-food-cac-loai-canh-23", front: "干锅牛蛙", back: "Ếch xào sả ớt", pronunciation: "gān guō niúwā" },
      { id: "zh-food-cac-loai-canh-24", front: "肉松", back: "Ruốc", pronunciation: "ròusōng" },
      { id: "zh-food-cac-loai-canh-25", front: "糖醋排骨", back: "Sườn xào chua ngọt", pronunciation: "táng cù páigǔ" },
      { id: "zh-food-cac-loai-canh-26", front: "白灼菜心", back: "Món cải rổ xào", pronunciation: "bái zhuó càixīn" },
      { id: "zh-food-cac-loai-canh-27", front: "蚝油生菜", back: "Xà lách xào dầu hào", pronunciation: "háoyóu shēngcài" },
      { id: "zh-food-cac-loai-canh-28", front: "芹菜炒豆干", back: "Rau cần xào đậu phụ", pronunciation: "qíncài chǎo dòugān" },
      { id: "zh-food-cac-loai-canh-29", front: "龙井虾仁", back: "Tôm lột vỏ xào", pronunciation: "lóng jǐng xiārén" },
      { id: "zh-food-cac-loai-canh-30", front: "芙蓉蛋", back: "Món trứng phù dung", pronunciation: "fúróng dàn" },
      { id: "zh-food-cac-loai-canh-31", front: "青椒玉米", back: "Món bắp xào", pronunciation: "qīng jiāoyùmǐ" },
      { id: "zh-food-cac-loai-canh-32", front: "鱼丸汤", back: "Súp cá viên", pronunciation: "yú wán tāng" },
      { id: "zh-food-cac-loai-canh-33", front: "烧烤", back: "Đồ nướng", pronunciation: "hāokǎo" },
      { id: "zh-food-cac-loai-canh-34", front: "春卷", back: "Nem cuốn, chả nem", pronunciation: "chūnjuǎn" },
      { id: "zh-food-cac-loai-canh-35", front: "豆腐脑", back: "Món đậu phụ sốt tương", pronunciation: "dòufu nǎo" },
      { id: "zh-food-cac-loai-canh-36", front: "豆腐乳/腐乳", back: "Chao", pronunciation: "dòufu rǔ/fǔrǔ" },
      { id: "zh-food-cac-loai-canh-37", front: "鸳鸯火锅", back: "Lẩu uyên ương", pronunciation: "yuān yāng huǒ guō" },
      { id: "zh-food-cac-loai-canh-38", front: "鲜肉馄饨", back: "Hoành thánh thịt bằm", pronunciation: "xiānròu húntun" },
      { id: "zh-food-cac-loai-canh-39", front: "肉团", back: "Giò", pronunciation: "ròutuán" },
      { id: "zh-food-cac-loai-canh-40", front: "炙肉", back: "Chả", pronunciation: "zhì ròu" }
    ],
  },
  {
    id: "builtin:zh-food-cac-mon-trang-mieng",
    name: "Các món tráng miệng",
    description: "Món ăn · Các món tráng miệng (7 từ vựng tiếng Trung về ẩm thực)",
    icon: "utensils",
    color: "#ef4444",
    builtin: true,
    cards: [
      { id: "zh-food-cac-mon-trang-mieng-1", front: "豆腐花", back: "Tào phớ", pronunciation: "dòufu huā" },
      { id: "zh-food-cac-mon-trang-mieng-2", front: "豆浆", back: "Sữa đậu nành", pronunciation: "dòujiāng" },
      { id: "zh-food-cac-mon-trang-mieng-3", front: "油条", back: "Quẩy", pronunciation: "yóutiáo" },
      { id: "zh-food-cac-mon-trang-mieng-4", front: "香蕉糖羹", back: "Chè chuối", pronunciation: "xiāngjiāo tánggēng" },
      { id: "zh-food-cac-mon-trang-mieng-5", front: "红茶", back: "Hồng Trà", pronunciation: "hóngchá" },
      { id: "zh-food-cac-mon-trang-mieng-6", front: "鲜奶", back: "Sữa tươi", pronunciation: "xiānnǎi" },
      { id: "zh-food-cac-mon-trang-mieng-7", front: "糖羹", back: "Chè", pronunciation: "tánggēng" }
    ],
  },
  {
    id: "builtin:zh-food-o-uong-co-con",
    name: "Đồ uống có cồn",
    description: "Đồ uống · Đồ uống có cồn (6 từ vựng tiếng Trung về ẩm thực)",
    icon: "utensils",
    color: "#f59e0b",
    builtin: true,
    cards: [
      { id: "zh-food-o-uong-co-con-1", front: "饮料", back: "Đồ uống", pronunciation: "yǐnliào" },
      { id: "zh-food-o-uong-co-con-2", front: "青岛啤酒", back: "Bia Thanh Đảo", pronunciation: "qīngdǎo píjiǔ" },
      { id: "zh-food-o-uong-co-con-3", front: "白兰地", back: "Rượu Brandy", pronunciation: "báilándì" },
      { id: "zh-food-o-uong-co-con-4", front: "香槟酒", back: "Rượu sâm banh", pronunciation: "xiāngbīnjiǔ" },
      { id: "zh-food-o-uong-co-con-5", front: "威士忌", back: "Rượu Whisky", pronunciation: "wēishìjì" },
      { id: "zh-food-o-uong-co-con-6", front: "女儿红", back: "Rượu nữ nhi hồng", pronunciation: "nǚ’ér hóng" }
    ],
  },
  {
    id: "builtin:zh-food-cac-loai-nuoc-giai-khat-khac",
    name: "Các loại nước giải khát khác",
    description: "Đồ uống · Các loại nước giải khát khác (4 từ vựng tiếng Trung về ẩm thực)",
    icon: "utensils",
    color: "#f59e0b",
    builtin: true,
    cards: [
      { id: "zh-food-cac-loai-nuoc-giai-khat-khac-1", front: "矿泉水", back: "Nước khoáng", pronunciation: "kuàngquán shuǐ" },
      { id: "zh-food-cac-loai-nuoc-giai-khat-khac-2", front: "汽水", back: "Nước có ga", pronunciation: "qìshuǐ" },
      { id: "zh-food-cac-loai-nuoc-giai-khat-khac-3", front: "柠檬水", back: "Nước chanh", pronunciation: "níngméng" },
      { id: "zh-food-cac-loai-nuoc-giai-khat-khac-4", front: "果汁", back: "Nước ép", pronunciation: "guǒzhī" }
    ],
  },
  {
    id: "builtin:zh-food-cac-loai-tra",
    name: "Các loại trà",
    description: "Đồ uống · Các loại trà (9 từ vựng tiếng Trung về ẩm thực)",
    icon: "utensils",
    color: "#f59e0b",
    builtin: true,
    cards: [
      { id: "zh-food-cac-loai-tra-1", front: "红茶", back: "Hồng trà", pronunciation: "hóngchá" },
      { id: "zh-food-cac-loai-tra-2", front: "冰沙", back: "Smoothie", pronunciation: "bīng shā" },
      { id: "zh-food-cac-loai-tra-3", front: "柠檬茶", back: "Trà chanh", pronunciation: "níngméng chá" },
      { id: "zh-food-cac-loai-tra-4", front: "黑茶", back: "Trà đen", pronunciation: "hēi chá" },
      { id: "zh-food-cac-loai-tra-5", front: "花茶", back: "Trà hoa", pronunciation: "huāchá" },
      { id: "zh-food-cac-loai-tra-6", front: "菊花茶", back: "Trà hoa cúc", pronunciation: "júhuā chá" },
      { id: "zh-food-cac-loai-tra-7", front: "玫瑰茶", back: "Trà hoa hồng", pronunciation: "méiguī chá" },
      { id: "zh-food-cac-loai-tra-8", front: "果茶", back: "Trà hoa quả", pronunciation: "guǒ chá" },
      { id: "zh-food-cac-loai-tra-9", front: "乌龙奶茶", back: "Trà ô long", pronunciation: "wū lóng nǎichá" }
    ],
  },
  {
    id: "builtin:zh-food-cac-loai-tra-sua",
    name: "Các loại trà sữa",
    description: "Đồ uống · Các loại trà sữa (20 từ vựng tiếng Trung về ẩm thực)",
    icon: "utensils",
    color: "#f59e0b",
    builtin: true,
    cards: [
      { id: "zh-food-cac-loai-tra-sua-1", front: "奶茶", back: "Trà sữa", pronunciation: "nǎichá" },
      { id: "zh-food-cac-loai-tra-sua-2", front: "咖啡奶茶", back: "Trà sữa cà phê", pronunciation: "kāfēi nǎichá" },
      { id: "zh-food-cac-loai-tra-sua-3", front: "焦糖奶茶", back: "Trà sữa caramel", pronunciation: "jiāo táng nǎichá" },
      { id: "zh-food-cac-loai-tra-sua-4", front: "草莓奶茶", back: "Trà sữa dâu tây", pronunciation: "cǎoméi nǎichá" },
      { id: "zh-food-cac-loai-tra-sua-5", front: "红豆奶茶", back: "Trà sữa đậu đỏ", pronunciation: "hóngdòu nǎichá" },
      { id: "zh-food-cac-loai-tra-sua-6", front: "芋头奶茶", back: "Trà sữa khoai môn", pronunciation: "yùtou nǎichá" },
      { id: "zh-food-cac-loai-tra-sua-7", front: "抹茶奶茶", back: "Trà sữa matcha", pronunciation: "mǒchá nǎichá" },
      { id: "zh-food-cac-loai-tra-sua-8", front: "布丁奶茶", back: "Trà sữa pudding", pronunciation: "bùdīng nǎichá" },
      { id: "zh-food-cac-loai-tra-sua-9", front: "芝士奶油奶茶", back: "Trà sữa phô mai", pronunciation: "zhīshì nǎiyóu nǎichá" },
      { id: "zh-food-cac-loai-tra-sua-10", front: "巧克力奶茶", back: "Trà sữa socola", pronunciation: "qiǎokèlì nǎichá" },
      { id: "zh-food-cac-loai-tra-sua-11", front: "泰式奶茶", back: "Trà sữa Thái", pronunciation: "tài shì nǎichá" },
      { id: "zh-food-cac-loai-tra-sua-12", front: "绿茶奶茶", back: "Trà sữa trà xanh", pronunciation: "lǜchá nǎichá" },
      { id: "zh-food-cac-loai-tra-sua-13", front: "珍珠奶茶", back: "Trà sữa trân châu", pronunciation: "zhēnzhū nǎichá" },
      { id: "zh-food-cac-loai-tra-sua-14", front: "黄金珍珠奶茶", back: "Trà sữa trân châu hoàng kim", pronunciation: "huángjīn zhēnzhū nǎichá" },
      { id: "zh-food-cac-loai-tra-sua-15", front: "白珍珠奶茶", back: "Trà sữa trân châu trắng", pronunciation: "bái zhēnzhū nǎichá" },
      { id: "zh-food-cac-loai-tra-sua-16", front: "蓝莓奶茶", back: "Trà sữa việt quất", pronunciation: "lánméi nǎichá" },
      { id: "zh-food-cac-loai-tra-sua-17", front: "芒果奶茶", back: "Trà sữa xoài", pronunciation: "mángguǒ nǎichá" },
      { id: "zh-food-cac-loai-tra-sua-18", front: "百香果绿茶", back: "Trà xanh chanh dây", pronunciation: "bǎixiāng lǜchá" },
      { id: "zh-food-cac-loai-tra-sua-19", front: "红豆抹茶", back: "Matcha đậu đỏ", pronunciation: "hóngdòu mǒchá" },
      { id: "zh-food-cac-loai-tra-sua-20", front: "黑糖珍珠鲜奶", back: "Sữa tươi trân châu đường đen", pronunciation: "hēitáng zhēnzhū xiān nǎi" }
    ],
  },
  {
    id: "builtin:zh-food-nhom-rau-mau-xanh",
    name: "Nhóm rau màu xanh",
    description: "Rau củ, trái cây · Nhóm rau màu xanh (13 từ vựng tiếng Trung về ẩm thực)",
    icon: "book-open",
    color: "#10b981",
    builtin: true,
    cards: [
      { id: "zh-food-nhom-rau-mau-xanh-1", front: "守宫木/天绿香", back: "Rau ngót", pronunciation: "shǒugōngmù/tiān lǜ xiāng" },
      { id: "zh-food-nhom-rau-mau-xanh-2", front: "盖菜", back: "Cải bẹ xanh", pronunciation: "gài cài" },
      { id: "zh-food-nhom-rau-mau-xanh-3", front: "蒿菜", back: "Cải cúc", pronunciation: "hāocài" },
      { id: "zh-food-nhom-rau-mau-xanh-4", front: "菜心", back: "Rau cải chíp", pronunciation: "càixīn" },
      { id: "zh-food-nhom-rau-mau-xanh-5", front: "娃娃菜", back: "Cải thảo nhỏ (Bằng cổ tay)", pronunciation: "wáwá cài" },
      { id: "zh-food-nhom-rau-mau-xanh-6", front: "青菜", back: "Cải xanh", pronunciation: "qīngcài" },
      { id: "zh-food-nhom-rau-mau-xanh-7", front: "莴苣", back: "Xà lách", pronunciation: "wōjù" },
      { id: "zh-food-nhom-rau-mau-xanh-8", front: "鱼腥草", back: "Lá diếp cá", pronunciation: "yú xīng cǎo" },
      { id: "zh-food-nhom-rau-mau-xanh-9", front: "萝卜", back: "Củ cải", pronunciation: "luóbo" },
      { id: "zh-food-nhom-rau-mau-xanh-10", front: "西兰花", back: "Súp lơ xanh, bông cải xanh, hoa lơ xanh", pronunciation: "xī lánhuā" },
      { id: "zh-food-nhom-rau-mau-xanh-11", front: "生菜", back: "Xà lách, rau sống", pronunciation: "shēngcài" },
      { id: "zh-food-nhom-rau-mau-xanh-12", front: "团生菜", back: "Xà lách bắp cuộn", pronunciation: "tuán shēngcài" },
      { id: "zh-food-nhom-rau-mau-xanh-13", front: "西洋菜", back: "Xà lách xoong", pronunciation: "xīyáng cài" }
    ],
  },
  {
    id: "builtin:zh-food-nhom-rau-nhieu-tinh-bot",
    name: "Nhóm rau nhiều tinh bột",
    description: "Rau củ, trái cây · Nhóm rau nhiều tinh bột (7 từ vựng tiếng Trung về ẩm thực)",
    icon: "book-open",
    color: "#10b981",
    builtin: true,
    cards: [
      { id: "zh-food-nhom-rau-nhieu-tinh-bot-1", front: "芋艿, 芋头", back: "Khoai môn", pronunciation: "yùnǎi,  yùtou" },
      { id: "zh-food-nhom-rau-nhieu-tinh-bot-2", front: "野芋, 小芋头", back: "Khoai sọ", pronunciation: "yě yù,  xiǎoyùtou" },
      { id: "zh-food-nhom-rau-nhieu-tinh-bot-3", front: "土豆", back: "Khoai tây", pronunciation: "tǔdòu" },
      { id: "zh-food-nhom-rau-nhieu-tinh-bot-4", front: "山药", back: "Khoai từ", pronunciation: "shānyào" },
      { id: "zh-food-nhom-rau-nhieu-tinh-bot-5", front: "木薯", back: "Sắn, khoai mì", pronunciation: "mùshǔ" },
      { id: "zh-food-nhom-rau-nhieu-tinh-bot-6", front: "玉米", back: "Ngô, bắp", pronunciation: "yùmǐ" },
      { id: "zh-food-nhom-rau-nhieu-tinh-bot-7", front: "栗子", back: "Hạt dẻ", pronunciation: "lìzi" }
    ],
  },
  {
    id: "builtin:zh-food-nhom-rau-mau-o-va-cam",
    name: "Nhóm rau màu đỏ và cam",
    description: "Rau củ, trái cây · Nhóm rau màu đỏ và cam (12 từ vựng tiếng Trung về ẩm thực)",
    icon: "book-open",
    color: "#10b981",
    builtin: true,
    cards: [
      { id: "zh-food-nhom-rau-mau-o-va-cam-1", front: "红椒", back: "Ớt chuông đỏ", pronunciation: "hóng jiāo" },
      { id: "zh-food-nhom-rau-mau-o-va-cam-2", front: "黄椒", back: "Ớt chuông vàng", pronunciation: "huáng jiāo" },
      { id: "zh-food-nhom-rau-mau-o-va-cam-3", front: "南瓜", back: "Bí đỏ, bí ngô", pronunciation: "nánguā" },
      { id: "zh-food-nhom-rau-mau-o-va-cam-4", front: "番薯, 甘薯, 红薯", back: "Khoai lang", pronunciation: "fānshǔ,  gānshǔ,  hóngshǔ" },
      { id: "zh-food-nhom-rau-mau-o-va-cam-5", front: "番茄, 西红柿", back: "Cà chua", pronunciation: "fānqié,  xīhóngshì" },
      { id: "zh-food-nhom-rau-mau-o-va-cam-6", front: "樱桃西红柿", back: "Cà chua bi", pronunciation: "yīngtáo xīhóngshì" },
      { id: "zh-food-nhom-rau-mau-o-va-cam-7", front: "胡萝卜", back: "Cà rốt", pronunciation: "húluóbo" },
      { id: "zh-food-nhom-rau-mau-o-va-cam-8", front: "红米苋", back: "Rau dền đỏ", pronunciation: "hóng mǐ xiàn" },
      { id: "zh-food-nhom-rau-mau-o-va-cam-9", front: "甜椒", back: "Ớt ngọt", pronunciation: "tiánjiāo" },
      { id: "zh-food-nhom-rau-mau-o-va-cam-10", front: "长黄辣椒", back: "Ớt vàng dài", pronunciation: "zhǎng huáng làjiāo" },
      { id: "zh-food-nhom-rau-mau-o-va-cam-11", front: "长红辣椒", back: "Ớt đỏ dài", pronunciation: "zhǎng hóng làjiāo" },
      { id: "zh-food-nhom-rau-mau-o-va-cam-12", front: "小红辣椒", back: "Ớt hiểm đỏ", pronunciation: "xiǎo hóng làjiāo" }
    ],
  },
  {
    id: "builtin:zh-food-nhom-cac-loai-au",
    name: "Nhóm các loại đậu",
    description: "Rau củ, trái cây · Nhóm các loại đậu (12 từ vựng tiếng Trung về ẩm thực)",
    icon: "book-open",
    color: "#10b981",
    builtin: true,
    cards: [
      { id: "zh-food-nhom-cac-loai-au-1", front: "豆荚", back: "Các loại đậu", pronunciation: "dòujiá" },
      { id: "zh-food-nhom-cac-loai-au-2", front: "芸豆", back: "Đậu cô ve", pronunciation: "yúndòu" },
      { id: "zh-food-nhom-cac-loai-au-3", front: "黑豆", back: "Đậu đen", pronunciation: "hēidòu" },
      { id: "zh-food-nhom-cac-loai-au-4", front: "红豆", back: "Đậu đỏ", pronunciation: "hóngdòu" },
      { id: "zh-food-nhom-cac-loai-au-5", front: "豇豆", back: "Đậu đũa", pronunciation: "jiāngdòu" },
      { id: "zh-food-nhom-cac-loai-au-6", front: "豌豆/荷兰豆", back: "Đậu Hà Lan", pronunciation: "wāndòu/hélándòu" },
      { id: "zh-food-nhom-cac-loai-au-7", front: "毛豆", back: "Đậu nành", pronunciation: "máodòu" },
      { id: "zh-food-nhom-cac-loai-au-8", front: "花生", back: "Lạc", pronunciation: "huāshēng" },
      { id: "zh-food-nhom-cac-loai-au-9", front: "四季豆", back: "Đậu que", pronunciation: "sìjì dòu" },
      { id: "zh-food-nhom-cac-loai-au-10", front: "蚕豆", back: "Đậu tằm", pronunciation: "cándòu" },
      { id: "zh-food-nhom-cac-loai-au-11", front: "秋葵", back: "Đậu bắp", pronunciation: "qiū kuí" },
      { id: "zh-food-nhom-cac-loai-au-12", front: "绿豆", back: "Đậu xanh", pronunciation: "lǜdòu" }
    ],
  },
  {
    id: "builtin:zh-food-cac-nhom-rau-khac",
    name: "Các nhóm rau khác",
    description: "Rau củ, trái cây · Các nhóm rau khác (46 từ vựng tiếng Trung về ẩm thực)",
    icon: "book-open",
    color: "#10b981",
    builtin: true,
    cards: [
      { id: "zh-food-cac-nhom-rau-khac-1", front: "薄荷", back: "Bạc hà", pronunciation: "bòhe" },
      { id: "zh-food-cac-nhom-rau-khac-2", front: "大白菜", back: "Bắp cải, rau cải thảo, bắp cải napa", pronunciation: "dàbáicài" },
      { id: "zh-food-cac-nhom-rau-khac-3", front: "紫甘菜/紫甘蓝", back: "Bắp cải tím", pronunciation: "zǐ gān cài/zǐ gān lán" },
      { id: "zh-food-cac-nhom-rau-khac-4", front: "芥菜", back: "Cải dưa, cải muối dưa, cải làn", pronunciation: "jiècài" },
      { id: "zh-food-cac-nhom-rau-khac-5", front: "小松菜", back: "Cải ngọt", pronunciation: "xiǎosōngcài" },
      { id: "zh-food-cac-nhom-rau-khac-6", front: "油菜", back: "Cải thìa trắng", pronunciation: "yóucài" },
      { id: "zh-food-cac-nhom-rau-khac-7", front: "水芹", back: "Rau cần nước, cần ta", pronunciation: "shuǐ qín" },
      { id: "zh-food-cac-nhom-rau-khac-8", front: "芹菜, 西芹", back: "Rau cần tây", pronunciation: "qíncài,  xīqín" },
      { id: "zh-food-cac-nhom-rau-khac-9", front: "洋芹", back: "Cần tây", pronunciation: "yáng qín" },
      { id: "zh-food-cac-nhom-rau-khac-10", front: "菠菜", back: "Chân vịt, cải bó xôi", pronunciation: "bōcài" },
      { id: "zh-food-cac-nhom-rau-khac-11", front: "莴笋", back: "Măng tây", pronunciation: "wōsǔn" },
      { id: "zh-food-cac-nhom-rau-khac-12", front: "叻沙叶", back: "Rau răm", pronunciation: "lè shā yè" },
      { id: "zh-food-cac-nhom-rau-khac-13", front: "咸菜", back: "Dưa muối", pronunciation: "xiáncài" },
      { id: "zh-food-cac-nhom-rau-khac-14", front: "芽菜/ 豆芽儿", back: "Giá đỗ", pronunciation: "yácài/dòuyá er" },
      { id: "zh-food-cac-nhom-rau-khac-15", front: "香葱", back: "Hành hoa", pronunciation: "xiāngcōng" },
      { id: "zh-food-cac-nhom-rau-khac-16", front: "大葱", back: "Hành poaro, hành tươi", pronunciation: "dàcōng" },
      { id: "zh-food-cac-nhom-rau-khac-17", front: "韭菜", back: "Hẹ", pronunciation: "jiǔcài" },
      { id: "zh-food-cac-nhom-rau-khac-18", front: "南瓜花", back: "Hoa bí", pronunciation: "nánguāhuā" },
      { id: "zh-food-cac-nhom-rau-khac-19", front: "芫茜", back: "Lá mùi tàu, ngò gai", pronunciation: "yuánqiàn" },
      { id: "zh-food-cac-nhom-rau-khac-20", front: "芦荟", back: "Lô hội, nha đam", pronunciation: "lúhuì" },
      { id: "zh-food-cac-nhom-rau-khac-21", front: "笋干", back: "Măng khô", pronunciation: "sǔn gān" },
      { id: "zh-food-cac-nhom-rau-khac-22", front: "冬笋", back: "Măng mạnh tông", pronunciation: "dōngsǔn" },
      { id: "zh-food-cac-nhom-rau-khac-23", front: "毛笋/竹笋", back: "Măng tre", pronunciation: "máo sǔn/zhúsǔn" },
      { id: "zh-food-cac-nhom-rau-khac-24", front: "苋菜", back: "Rau dền", pronunciation: "xiàncài" },
      { id: "zh-food-cac-nhom-rau-khac-25", front: "落葵", back: "Mồng tơi", pronunciation: "luòkuí" },
      { id: "zh-food-cac-nhom-rau-khac-26", front: "法菜", back: "Mùi tây", pronunciation: "fǎcài" },
      { id: "zh-food-cac-nhom-rau-khac-27", front: "莲根/藕", back: "Ngó sen", pronunciation: "liángēn/ǒu" },
      { id: "zh-food-cac-nhom-rau-khac-28", front: "蕃薯叶", back: "Rau lang", pronunciation: "fānshǔyè" },
      { id: "zh-food-cac-nhom-rau-khac-29", front: "积雪草", back: "Rau má", pronunciation: "jī xuě cǎo" },
      { id: "zh-food-cac-nhom-rau-khac-30", front: "香菜", back: "Rau mùi, ngò rí", pronunciation: "xiāngcài" },
      { id: "zh-food-cac-nhom-rau-khac-31", front: "空心菜", back: "Rau muống", pronunciation: "kōngxīncài" },
      { id: "zh-food-cac-nhom-rau-khac-32", front: "树仔菜", back: "Rau ngót", pronunciation: "shùzǎicài" },
      { id: "zh-food-cac-nhom-rau-khac-33", front: "海带", back: "Rong biển", pronunciation: "hǎidài" },
      { id: "zh-food-cac-nhom-rau-khac-34", front: "花菜", back: "Súp lơ (Hoa lơ), bông cải", pronunciation: "huācài" },
      { id: "zh-food-cac-nhom-rau-khac-35", front: "白花菜", back: "Súp lơ trắng, bông cải trắng", pronunciation: "bái huācài" },
      { id: "zh-food-cac-nhom-rau-khac-36", front: "紫苏", back: "Tía tô", pronunciation: "zǐsū" },
      { id: "zh-food-cac-nhom-rau-khac-37", front: "冬瓜", back: "Bí đao", pronunciation: "dōngguā" },
      { id: "zh-food-cac-nhom-rau-khac-38", front: "茄子", back: "Cà tím, cà pháo", pronunciation: "qiézi" },
      { id: "zh-food-cac-nhom-rau-khac-39", front: "莲子", back: "Hạt sen", pronunciation: "liánzǐ" },
      { id: "zh-food-cac-nhom-rau-khac-40", front: "胡椒", back: "Hạt tiêu", pronunciation: "hújiāo" },
      { id: "zh-food-cac-nhom-rau-khac-41", front: "苦瓜", back: "Mướp đắng, khổ qua", pronunciation: "kǔguā" },
      { id: "zh-food-cac-nhom-rau-khac-42", front: "青圆椒", back: "Ớt chuông xanh", pronunciation: "qīng yuán jiāo" },
      { id: "zh-food-cac-nhom-rau-khac-43", front: "青尖椒", back: "Ớt hiểm xanh", pronunciation: "qīng jiān jiāo" },
      { id: "zh-food-cac-nhom-rau-khac-44", front: "干辣椒", back: "Ớt khô", pronunciation: "gàn làjiāo" },
      { id: "zh-food-cac-nhom-rau-khac-45", front: "青椒", back: "Ớt xanh", pronunciation: "qīngjiāo" },
      { id: "zh-food-cac-nhom-rau-khac-46", front: "辣椒", back: "Quả ớt", pronunciation: "làjiāo" }
    ],
  },
  {
    id: "builtin:zh-food-cac-loai-nam",
    name: "Các loại nấm",
    description: "Rau củ, trái cây · Các loại nấm (9 từ vựng tiếng Trung về ẩm thực)",
    icon: "book-open",
    color: "#10b981",
    builtin: true,
    cards: [
      { id: "zh-food-cac-loai-nam-1", front: "木耳", back: "Mộc nhĩ, nấm mèo", pronunciation: "mùěr" },
      { id: "zh-food-cac-loai-nam-2", front: "百灵菇", back: "Nấm bạch linh", pronunciation: "bǎilínggū" },
      { id: "zh-food-cac-loai-nam-3", front: "鸡腿菇", back: "Nấm đùi gà", pronunciation: "jītuǐgū" },
      { id: "zh-food-cac-loai-nam-4", front: "牛肝菌", back: "Nấm gan bò", pronunciation: "niúgānjūn" },
      { id: "zh-food-cac-loai-nam-5", front: "海鲜菇", back: "Nấm hải sản", pronunciation: "hǎixiāngū" },
      { id: "zh-food-cac-loai-nam-6", front: "香菇", back: "Nấm hương", pronunciation: "xiānggū" },
      { id: "zh-food-cac-loai-nam-7", front: "金針菇", back: "Nấm kim châm", pronunciation: "jīnzhēngū" },
      { id: "zh-food-cac-loai-nam-8", front: "竹荪", back: "Nấm măng", pronunciation: "zhúsūn" },
      { id: "zh-food-cac-loai-nam-9", front: "口蘑", back: "Nấm mỡ", pronunciation: "kǒumó" }
    ],
  },
  {
    id: "builtin:zh-food-cac-loai-cu",
    name: "Các loại củ",
    description: "Rau củ, trái cây · Các loại củ (10 từ vựng tiếng Trung về ẩm thực)",
    icon: "book-open",
    color: "#10b981",
    builtin: true,
    cards: [
      { id: "zh-food-cac-loai-cu-1", front: "甜菜", back: "Củ dền", pronunciation: "tiáncài" },
      { id: "zh-food-cac-loai-cu-2", front: "高良姜", back: "Củ riềng", pronunciation: "gāoliángjiāng" },
      { id: "zh-food-cac-loai-cu-3", front: "马蹄", back: "Củ năng", pronunciation: "mǎtí" },
      { id: "zh-food-cac-loai-cu-4", front: "茭白", back: "Củ niễng", pronunciation: "jiāobái" },
      { id: "zh-food-cac-loai-cu-5", front: "黄姜", back: "Củ nghệ", pronunciation: "huángjiāng" },
      { id: "zh-food-cac-loai-cu-6", front: "香茅", back: "Củ sả", pronunciation: "xiāngmáo" },
      { id: "zh-food-cac-loai-cu-7", front: "莲藕", back: "Củ sen", pronunciation: "liánǒu" },
      { id: "zh-food-cac-loai-cu-8", front: "芜菁", back: "Củ su hào", pronunciation: "wújīng" },
      { id: "zh-food-cac-loai-cu-9", front: "姜", back: "Củ gừng", pronunciation: "jiāng" },
      { id: "zh-food-cac-loai-cu-10", front: "洋葱", back: "Hành tây", pronunciation: "yángcōng" }
    ],
  },
  {
    id: "builtin:zh-food-cac-loai-qua",
    name: "Các loại quả",
    description: "Rau củ, trái cây · Các loại quả (24 từ vựng tiếng Trung về ẩm thực)",
    icon: "book-open",
    color: "#10b981",
    builtin: true,
    cards: [
      { id: "zh-food-cac-loai-qua-1", front: "节瓜", back: "Quả bầu", pronunciation: "jiéguā" },
      { id: "zh-food-cac-loai-qua-2", front: "木鳖果", back: "Quả gấc", pronunciation: "mùbiēguǒ" },
      { id: "zh-food-cac-loai-qua-3", front: "山竹果", back: "Quả mãng cầu", pronunciation: "shānzhúguǒ" },
      { id: "zh-food-cac-loai-qua-4", front: "罗望子", back: "Quả me", pronunciation: "luówàngzi" },
      { id: "zh-food-cac-loai-qua-5", front: "角瓜", back: "Quả mướp", pronunciation: "jiǎoguā" },
      { id: "zh-food-cac-loai-qua-6", front: "橄榄", back: "Quả oliu", pronunciation: "gǎnlǎn" },
      { id: "zh-food-cac-loai-qua-7", front: "佛手瓜", back: "Quả susu", pronunciation: "fóshǒuguā" },
      { id: "zh-food-cac-loai-qua-8", front: "牛油果/油梨", back: "Quả bơ", pronunciation: "niúyóuguǒ/yóu lí" },
      { id: "zh-food-cac-loai-qua-9", front: "香蕉", back: "Quả chuối", pronunciation: "xiāngjiāo" },
      { id: "zh-food-cac-loai-qua-10", front: "西瓜", back: "Quả dưa hấu", pronunciation: "xīguā" },
      { id: "zh-food-cac-loai-qua-11", front: "柠檬", back: "Quả chanh", pronunciation: "níngméng" },
      { id: "zh-food-cac-loai-qua-12", front: "橙子", back: "Quả cam", pronunciation: "chéngzi" },
      { id: "zh-food-cac-loai-qua-13", front: "梨", back: "Quả lê", pronunciation: "lí" },
      { id: "zh-food-cac-loai-qua-14", front: "菠萝", back: "Quả dứa", pronunciation: "bōluó" },
      { id: "zh-food-cac-loai-qua-15", front: "草莓", back: "Dâu tây", pronunciation: "cǎoméi" },
      { id: "zh-food-cac-loai-qua-16", front: "葡萄", back: "Quả nho", pronunciation: "pútáo" },
      { id: "zh-food-cac-loai-qua-17", front: "椰子", back: "Quả dừa", pronunciation: "yēzi" },
      { id: "zh-food-cac-loai-qua-18", front: "猕猴桃", back: "Quả kiwi", pronunciation: "míhóutáo" },
      { id: "zh-food-cac-loai-qua-19", front: "樱桃", back: "Quả cherry", pronunciation: "yīngtáo" },
      { id: "zh-food-cac-loai-qua-20", front: "桃子", back: "Quả đào", pronunciation: "táozi" },
      { id: "zh-food-cac-loai-qua-21", front: "芒果", back: "Quả xoài", pronunciation: "mángguǒ" },
      { id: "zh-food-cac-loai-qua-22", front: "苹果", back: "Quả táo", pronunciation: "píngguǒ" },
      { id: "zh-food-cac-loai-qua-23", front: "杏子", back: "Quả mơ", pronunciation: "xìngzi" },
      { id: "zh-food-cac-loai-qua-24", front: "黄瓜", back: "Dưa chuột, dưa leo", pronunciation: "huángguā" }
    ],
  },
  {
    id: "builtin:zh-food-gia-vi-cay",
    name: "Gia vị cay",
    description: "Gia vị · Gia vị cay (19 từ vựng tiếng Trung về ẩm thực)",
    icon: "book-open",
    color: "#3b82f6",
    builtin: true,
    cards: [
      { id: "zh-food-gia-vi-cay-1", front: "香辛料", back: "Gia vị", pronunciation: "xiāngxīnliào" },
      { id: "zh-food-gia-vi-cay-2", front: "咖喱 粉", back: "Bột cà ri", pronunciation: "gālí fěn" },
      { id: "zh-food-gia-vi-cay-3", front: "姜粉", back: "Bột gừng", pronunciation: "jiāng fěn" },
      { id: "zh-food-gia-vi-cay-4", front: "姜", back: "Gừng", pronunciation: "jiāng" },
      { id: "zh-food-gia-vi-cay-5", front: "花椒粉", back: "Bột hạt tiêu Tứ Xuyên", pronunciation: "huājiāo fěn" },
      { id: "zh-food-gia-vi-cay-6", front: "辣椒粉", back: "Bột ớt", pronunciation: "làjiāo fěn" },
      { id: "zh-food-gia-vi-cay-7", front: "胡椒粉", back: "Bột tiêu", pronunciation: "hújiāo fěn" },
      { id: "zh-food-gia-vi-cay-8", front: "桂皮", back: "Quế Trung Quốc", pronunciation: "guì pí" },
      { id: "zh-food-gia-vi-cay-9", front: "黑胡椒", back: "Hạt tiêu đen", pronunciation: "hēihújiāo" },
      { id: "zh-food-gia-vi-cay-10", front: "花椒", back: "Hạt tiêu Tứ Xuyên", pronunciation: "huājiāo" },
      { id: "zh-food-gia-vi-cay-11", front: "白胡椒", back: "Hạt tiêu trắng", pronunciation: "báihújiāo" },
      { id: "zh-food-gia-vi-cay-12", front: "青花椒", back: "Tiêu Tứ Xuyên xanh", pronunciation: "qīng huājiāo" },
      { id: "zh-food-gia-vi-cay-13", front: "红花椒", back: "Ớt đỏ Tứ Tuyên", pronunciation: "hóng huājiāo" },
      { id: "zh-food-gia-vi-cay-14", front: "大蒜", back: "Tỏi", pronunciation: "dàsuàn" },
      { id: "zh-food-gia-vi-cay-15", front: "辣椒酱", back: "Tương ớt", pronunciation: "làjiāo jiàng" },
      { id: "zh-food-gia-vi-cay-16", front: "八角", back: "Cây hồi", pronunciation: "bājiǎo" },
      { id: "zh-food-gia-vi-cay-17", front: "小荳蔻", back: "Thảo quả", pronunciation: "xiǎodòukòu" },
      { id: "zh-food-gia-vi-cay-18", front: "黑豆蔻", back: "Thảo quả đen", pronunciation: "hēi dòukòu" },
      { id: "zh-food-gia-vi-cay-19", front: "沙爹", back: "sa tế", pronunciation: "shā diē" }
    ],
  },
  {
    id: "builtin:zh-food-gia-vi-ngot",
    name: "Gia vị ngọt",
    description: "Gia vị · Gia vị ngọt (14 từ vựng tiếng Trung về ẩm thực)",
    icon: "book-open",
    color: "#3b82f6",
    builtin: true,
    cards: [
      { id: "zh-food-gia-vi-ngot-1", front: "食糖", back: "Đường ăn", pronunciation: "shítáng" },
      { id: "zh-food-gia-vi-ngot-2", front: "糖粉", back: "Đường bột, đường xay", pronunciation: "táng fěn" },
      { id: "zh-food-gia-vi-ngot-3", front: "砂糖", back: "Đường cát", pronunciation: "shātáng" },
      { id: "zh-food-gia-vi-ngot-4", front: "代糖", back: "Đường hóa học", pronunciation: "dài táng" },
      { id: "zh-food-gia-vi-ngot-5", front: "冰糖", back: "Đường phèn", pronunciation: "bīngtáng" },
      { id: "zh-food-gia-vi-ngot-6", front: "精制糖", back: "Đường tinh chế, đường tinh luyện", pronunciation: "jīngzhì táng" },
      { id: "zh-food-gia-vi-ngot-7", front: "绵白糖", back: "Đường trắng", pronunciation: "mián bái táng" },
      { id: "zh-food-gia-vi-ngot-8", front: "方糖", back: "Đường viên", pronunciation: "fāng táng" },
      { id: "zh-food-gia-vi-ngot-9", front: "圆锥形糖块", back: "Đường viên hình nón", pronunciation: "yuánzhuī xíng táng kuài" },
      { id: "zh-food-gia-vi-ngot-10", front: "味精", back: "Mì chính, bột ngọt", pronunciation: "wèijīng" },
      { id: "zh-food-gia-vi-ngot-11", front: "调味种子", back: "Hạt nêm", pronunciation: "tiáowèi zhǒngzǐ" },
      { id: "zh-food-gia-vi-ngot-12", front: "甘草", back: "Rễ cam thảo Trung Quốc", pronunciation: "gāncǎo" },
      { id: "zh-food-gia-vi-ngot-13", front: "香草", back: "Thảo mộc", pronunciation: "xiāngcǎo" },
      { id: "zh-food-gia-vi-ngot-14", front: "豆瓣酱", back: "Đậu tương", pronunciation: "dòubànjiàng" }
    ],
  },
  {
    id: "builtin:zh-food-gia-vi-man",
    name: "Gia vị mặn",
    description: "Gia vị · Gia vị mặn (3 từ vựng tiếng Trung về ẩm thực)",
    icon: "book-open",
    color: "#3b82f6",
    builtin: true,
    cards: [
      { id: "zh-food-gia-vi-man-1", front: "盐", back: "Muối", pronunciation: "yán" },
      { id: "zh-food-gia-vi-man-2", front: "酱油", back: "Xì dầu", pronunciation: "jiàngyóu" },
      { id: "zh-food-gia-vi-man-3", front: "鱼露", back: "Nước mắm", pronunciation: "yúlù" }
    ],
  },
  {
    id: "builtin:zh-food-gia-vi-thom",
    name: "Gia vị thơm",
    description: "Gia vị · Gia vị thơm (16 từ vựng tiếng Trung về ẩm thực)",
    icon: "book-open",
    color: "#3b82f6",
    builtin: true,
    cards: [
      { id: "zh-food-gia-vi-thom-1", front: "茴香籽", back: "Hạt cây thì là", pronunciation: "huí xiāng zǐ" },
      { id: "zh-food-gia-vi-thom-2", front: "芝麻", back: "Hạt mè", pronunciation: "zhī ma" },
      { id: "zh-food-gia-vi-thom-3", front: "丁香", back: "Đinh hương", pronunciation: "dīngxiāng" },
      { id: "zh-food-gia-vi-thom-4", front: "五香粉", back: "Ngũ vị hương", pronunciation: "wǔxiāngfěn" },
      { id: "zh-food-gia-vi-thom-5", front: "肉荳蔻", back: "Nhục đậu khấu", pronunciation: "ròu dòukòu" },
      { id: "zh-food-gia-vi-thom-6", front: "孜然", back: "Cây thì là", pronunciation: "zī rán" },
      { id: "zh-food-gia-vi-thom-7", front: "小茴香", back: "Thì là", pronunciation: "xiǎohuíxiāng" },
      { id: "zh-food-gia-vi-thom-8", front: "葱", back: "Hành lá", pronunciation: "cōng" },
      { id: "zh-food-gia-vi-thom-9", front: "罗勒", back: "Húng quế", pronunciation: "luólè" },
      { id: "zh-food-gia-vi-thom-10", front: "墨角兰", back: "Lá kinh giới", pronunciation: "mòjiǎolán" },
      { id: "zh-food-gia-vi-thom-11", front: "欧芹", back: "Mùi tây", pronunciation: "ōuqín" },
      { id: "zh-food-gia-vi-thom-12", front: "香菜", back: "Ngò", pronunciation: "xiāngcài" },
      { id: "zh-food-gia-vi-thom-13", front: "牛至", back: "Rau kinh giới", pronunciation: "niúzhì" },
      { id: "zh-food-gia-vi-thom-14", front: "莳萝", back: "Rau thì là, rau thơm", pronunciation: "shíluó" },
      { id: "zh-food-gia-vi-thom-15", front: "百里香", back: "Xạ hương", pronunciation: "bǎilǐxiāng" },
      { id: "zh-food-gia-vi-thom-16", front: "芝麻油", back: "Dầu mè", pronunciation: "zhīmayóu" }
    ],
  },
  {
    id: "builtin:zh-food-gia-vi-chua",
    name: "Gia vị chua",
    description: "Gia vị · Gia vị chua (1 từ vựng tiếng Trung về ẩm thực)",
    icon: "book-open",
    color: "#3b82f6",
    builtin: true,
    cards: [
      { id: "zh-food-gia-vi-chua-1", front: "米醋", back: "Giấm gạo", pronunciation: "mǐcù" }
    ],
  },
  {
    id: "builtin:zh-food-gia-vi-hon-hop",
    name: "Gia vị hỗn hợp",
    description: "Gia vị · Gia vị hỗn hợp (3 từ vựng tiếng Trung về ẩm thực)",
    icon: "book-open",
    color: "#3b82f6",
    builtin: true,
    cards: [
      { id: "zh-food-gia-vi-hon-hop-1", front: "海鲜酱", back: "Nước sốt hải sản", pronunciation: "hǎixiānjiàng" },
      { id: "zh-food-gia-vi-hon-hop-2", front: "蚝油", back: "Sốt hàu", pronunciation: "háoyóu" },
      { id: "zh-food-gia-vi-hon-hop-3", front: "调料和油", back: "Nước sốt & dầu", pronunciation: "tiáoliào hé yóu" }
    ],
  },
  {
    id: "builtin:zh-food-set",
    name: "",
    description: "Khẩu vị ·  (7 từ vựng tiếng Trung về ẩm thực)",
    icon: "book-open",
    color: "#8b5cf6",
    builtin: true,
    cards: [
      { id: "zh-food-set-1", front: "酸", back: "Chua", pronunciation: "suān" },
      { id: "zh-food-set-2", front: "辣", back: "Cay", pronunciation: "là" },
      { id: "zh-food-set-3", front: "咸", back: "Mặn", pronunciation: "xián" },
      { id: "zh-food-set-4", front: "甜", back: "Ngọt", pronunciation: "tián" },
      { id: "zh-food-set-5", front: "苦", back: "Đắng", pronunciation: "kǔ" },
      { id: "zh-food-set-6", front: "鲜味", back: "Umami (một trong những vị cơ bản của nấu ăn)", pronunciation: "xiān wèi" },
      { id: "zh-food-set-7", front: "可口的", back: "Ngon miệng", pronunciation: "kěkǒu de" }
    ],
  },
  {
    id: "builtin:zh-food-set-2",
    name: "",
    description: "Cách chế biến ·  (18 từ vựng tiếng Trung về ẩm thực)",
    icon: "book-open",
    color: "#ec4899",
    builtin: true,
    cards: [
      { id: "zh-food-set-2-1", front: "烧", back: "Xào, chiên, quay, nướng", pronunciation: "shāo" },
      { id: "zh-food-set-2-2", front: "炒", back: "Xào", pronunciation: "chǎo" },
      { id: "zh-food-set-2-3", front: "剪", back: "Chiên", pronunciation: "jiǎn" },
      { id: "zh-food-set-2-4", front: "灼", back: "Chiên xù", pronunciation: "zhuó" },
      { id: "zh-food-set-2-5", front: "炸", back: "Rán", pronunciation: "zhà" },
      { id: "zh-food-set-2-6", front: "烤", back: "Nướng", pronunciation: "kǎo" },
      { id: "zh-food-set-2-7", front: "烩", back: "Xào, hấp (Cơm cùng thức ăn)", pronunciation: "huì" },
      { id: "zh-food-set-2-8", front: "清蒸", back: "Hấp, chưng", pronunciation: "qīngzhēng" },
      { id: "zh-food-set-2-9", front: "汆", back: "Trần, luộc nhanh", pronunciation: "cuān" },
      { id: "zh-food-set-2-10", front: "焗", back: "Hấp", pronunciation: "jù" },
      { id: "zh-food-set-2-11", front: "红烧", back: "Om đỏ", pronunciation: "hóng shāo" },
      { id: "zh-food-set-2-12", front: "炖", back: "Hầm", pronunciation: "dùn" },
      { id: "zh-food-set-2-13", front: "煨", back: "Nấu đun nhỏ lửa", pronunciation: "wēi" },
      { id: "zh-food-set-2-14", front: "熏", back: "Hun khói", pronunciation: "xūn" },
      { id: "zh-food-set-2-15", front: "冻", back: "Kho đông", pronunciation: "dòng" },
      { id: "zh-food-set-2-16", front: "包", back: "Bọc, gói", pronunciation: "bāo" },
      { id: "zh-food-set-2-17", front: "拌", back: "Gỏi", pronunciation: "bàn" },
      { id: "zh-food-set-2-18", front: "腌", back: "Muối chua", pronunciation: "yān" }
    ],
  },
  {
    id: "builtin:zh-food-set-3",
    name: "",
    description: "Mẫu câu giao tiếp ·  (22 từ vựng tiếng Trung về ẩm thực)",
    icon: "book-open",
    color: "#14b8a6",
    builtin: true,
    cards: [
      { id: "zh-food-set-3-1", front: "你喜欢吃什么？", back: "Bạn thích ăn gì?", pronunciation: "Nǐ xǐhuān chī shénme?" },
      { id: "zh-food-set-3-2", front: "我喜欢吃又酸又甜的。", back: "Tôi thích ăn món vừa có chua vừa ngọt.", pronunciation: "Wǒ xǐhuān chī yòu suān yòu tián de." },
      { id: "zh-food-set-3-3", front: "我喜欢吃中餐。", back: "Tôi thích ăn món Trung Quốc.", pronunciation: "Wǒ xǐhuān chī zhōngcān." },
      { id: "zh-food-set-3-4", front: "我不喜欢吃西餐。", back: "Tôi không thích ăn món Tây.", pronunciation: "Wǒ bù xǐhuān chī xīcān" },
      { id: "zh-food-set-3-5", front: "我不能吃辣的。", back: "Tôi không ăn được cay.", pronunciation: "Wǒ bù néng chī là de." },
      { id: "zh-food-set-3-6", front: "越南的生菜很好吃。", back: "Rau sống của Việt Nam rất ngon.", pronunciation: "Yuènán de shēngcài hěn hǎochī." },
      { id: "zh-food-set-3-7", front: "越南的水果很丰富多样。", back: "Trái cây ở Việt Nam rất phong phú và đa dạng.", pronunciation: "Yuènán de shuǐguǒ hěn fēngfù duōyàng." },
      { id: "zh-food-set-3-8", front: "芒果又酸又甜。", back: "Quả xoài vừa chua vừa ngọt.", pronunciation: "Mángguǒ yòu suān yòu tián" },
      { id: "zh-food-set-3-9", front: "榴莲有特别的味道。", back: "Sầu riêng có mùi vị rất đặc biệt.", pronunciation: "Liúlián yǒu tèbié de wèidào." },
      { id: "zh-food-set-3-10", front: "你要多吃一点儿水果和生菜。", back: "Bạn cần ăn nhiều hoa quả và rau sống một chút.", pronunciation: "Nǐ yào duō chī yì diǎnr shuǐguǒ hé shēngcài" },
      { id: "zh-food-set-3-11", front: "你不要吃太多肉类。", back: "Bạn đừng ăn nhiều thịt quá.", pronunciation: "Nǐ bú yào chī tài duō ròu lèi." },
      { id: "zh-food-set-3-12", front: "你吃早饭了吗？", back: "Bạn đã ăn sáng chưa?", pronunciation: "Nǐ chī zǎofàn le ma?" },
      { id: "zh-food-set-3-13", front: "今天我请你吃饭。", back: "Hôm nay tôi mời bạn ăn cơm.", pronunciation: "Jīntiān wǒ qǐng nǐ chīfàn." },
      { id: "zh-food-set-3-14", front: "你跟我一起去吃饭吧。", back: "Bạn đi ăn cơm với tôi đi.", pronunciation: "Nǐ gēn wǒ yì qǐ qù chīfàn ba." },
      { id: "zh-food-set-3-15", front: "这道菜味道怎么样？", back: "Mùi vị của món ăn này thế nào?", pronunciation: "Zhè dào cài wèidào zěnme yàng?" },
      { id: "zh-food-set-3-16", front: "我觉得不太好吃。", back: "Tôi thấy không ngon lắm.", pronunciation: "Wǒ juéde bú tài hǎochī." },
      { id: "zh-food-set-3-17", front: "好吃极了。", back: "Ngon tuyệt.", pronunciation: "Hǎochī jí le." },
      { id: "zh-food-set-3-18", front: "给我菜单，我要点菜。", back: "Cho tôi thực đơn, tôi muốn gọi món.", pronunciation: "Gěi wǒ càidān, wǒ yàodiǎn cài." },
      { id: "zh-food-set-3-19", front: "你饿了吗? 我们出去吃饭吧!", back: "Bạn đói chưa? Chúng ta đi ăn cơm thôi!", pronunciation: "Nǐ èle ma? Wǒmen chūqù chīfàn ba!" },
      { id: "zh-food-set-3-20", front: "你们想喝点儿什么？", back: "Các bạn muốn loại nước gì?", pronunciation: "Nǐmen xiǎng hē diǎn er shénme?" },
      { id: "zh-food-set-3-21", front: "给我两瓶可口可乐。", back: "Cho tôi hai chai coca cola.", pronunciation: "Gěi wǒ liǎng píng kěkǒukělè." },
      { id: "zh-food-set-3-22", front: "你做的饭很好吃", back: "Đồ ăn anh nấu thật ngon.", pronunciation: "Nǐ zuò de fàn hěn hào chī" }
    ],
  }
];

export function getBuiltinZhFoodSet(setId: string): FlashcardSet | undefined {
  return builtinZhFoodSets.find((s) => s.id === setId);
}
