import type { Flashcard } from "./types";

// ────────────────────────────────────────────────────────────────────────────
// SET 16 — GLOBAL ENVIRONMENT (Air Pollution / Animals / Water Pollution / World Hunger)
// ────────────────────────────────────────────────────────────────────────────
const globalEnvCards: Flashcard[] = [
  // ── Air Pollution — CAUSES ─────────────────────────────────────────────
  {
    id: "ap-power-plants",
    front:
      "power plants, manufacturing facilities, waste incinerators, furnaces and other types of fuel-burning heating devices (the burning of fossil fuels such as coal, oil, natural gas)",
    back: "nhà máy điện, cơ sở sản xuất, lò đốt chất thải, lò nung và các loại thiết bị đốt nhiên liệu khác (đốt nhiên liệu hóa thạch như than, dầu, khí đốt tự nhiên)",
    pronunciation: "/ˈpaʊər plænts/",
    example: "Power plants burn fossil fuels such as coal, oil or natural gas.",
  },
  {
    id: "ap-agricultural",
    front: "agricultural activities (the use of insecticides, pesticides, fertilizers)",
    back: "hoạt động nông nghiệp (sử dụng thuốc diệt côn trùng, thuốc trừ sâu, phân bón)",
    pronunciation: "/ˌæɡrɪˈkʌltʃərəl ˈæktɪvətiz/",
    example: "Agricultural activities contribute to air pollution through pesticide use.",
  },
  {
    id: "ap-mining",
    front: "mining operations",
    back: "các hoạt động khai thác khoáng sản",
    pronunciation: "/ˈmaɪnɪŋ ˌɒpəˈreɪʃnz/",
    example: "Mining operations release large amounts of dust.",
  },
  {
    id: "ap-deforestation-pasture",
    front: "deforestation → the need for pastureland and growing fields → the removals of trees",
    back: "tàn phá rừng → sự cần thiết của đồng cỏ để chăn nuôi gia súc và các cánh đồng trồng trọt → việc chặt cây",
    pronunciation: "/ˌdiːˌfɒrɪˈsteɪʃn/",
    example: "Deforestation leads to the removal of trees for pastureland.",
  },
  {
    id: "ap-landfills",
    front:
      "waste → landfills → generate methane (greater demand for dumping grounds as a significant source of methane production)",
    back: "chất thải → bãi rác → tạo ra khí mê-tan (nhu cầu chỗ đổ rác tăng → là nguồn sản xuất khí mê-tan đáng kể)",
    pronunciation: "/ˈlændfɪlz/",
    example: "Landfills generate methane, a major greenhouse gas.",
  },
  {
    id: "ap-population-growth",
    front: "population growth, urbanisation",
    back: "gia tăng dân số, đô thị hóa",
    pronunciation: "/ˌpɒpjʊˈleɪʃn ɡrəʊθ/",
    example: "Population growth and urbanisation contribute to air pollution.",
  },
  {
    id: "ap-dust",
    front: "dust: large areas of open land (little or no vegetation) → wind → create dust storms",
    back: "bụi: những vùng đất rộng lớn (ít hoặc không có thảm thực vật) → gió → tạo ra bão bụi",
    pronunciation: "/dʌst stɔːmz/",
    example: "Dust storms are caused by large areas of open land with little vegetation.",
  },
  {
    id: "ap-wildfires",
    front: "wildfires: prolonged dry periods ← season changes + a lack of precipitation",
    back: "cháy rừng: thời gian khô hạn kéo dài ← thay đổi mùa + thiếu mưa",
    pronunciation: "/ˈwaɪldˌfaɪəz/",
    example: "Wildfires are caused by prolonged dry periods.",
  },
  {
    id: "ap-volcanic",
    front: "volcanic activity → produce tremendous amounts of sulfur, chlorine and ash products",
    back: "hoạt động núi lửa → tạo ra một lượng lớn lưu huỳnh, clo và tro",
    pronunciation: "/vɒlˈkænɪk ækˈtɪvəti/",
    example: "Volcanic activity produces tremendous amounts of sulfur and ash.",
  },
  // ── Air Pollution — EFFECTS ────────────────────────────────────────────
  {
    id: "ap-health-problems",
    front:
      "various health problems (reduced lung function, asthma, other respiratory illnesses), premature death",
    back: "các vấn đề sức khỏe khác nhau (giảm chức năng phổi, hen suyễn, các bệnh hô hấp khác), tử vong sớm (chết non)",
    pronunciation: "/ˈrespirətri ˈɪlnəsɪz/",
    example: "Air pollution causes various health problems such as asthma.",
  },
  {
    id: "ap-damage-crops",
    front: "damage crops, forests",
    back: "phá hoại mùa màng, rừng",
    pronunciation: "/ˈdæmɪdʒ krɒps/",
    example: "Air pollution damages crops and forests.",
  },
  {
    id: "ap-acid-rain",
    front:
      "acid rain → degrade water quality in rivers, lakes and streams; cause buildings and monuments to decay",
    back: "mưa axit → làm suy giảm chất lượng nước ở sông, hồ và suối, làm cho các tòa nhà và di tích bị tàn phá",
    pronunciation: "/ˈæsɪd reɪn/",
    example: "Acid rain degrades water quality and damages monuments.",
  },
  {
    id: "ap-animals-birth-defects",
    front:
      "animals: exposure to air pollution → birth defects, diseases, and lower reproductive rates",
    back: "động vật: tiếp xúc với ô nhiễm không khí → dị tật bẩm sinh, bệnh tật và tỷ lệ sinh sản thấp hơn",
    pronunciation: "/bɜːθ ˈdiːfekts/",
    example: "Exposure to air pollution causes birth defects in animals.",
  },
  // ── Air Pollution — SOLUTIONS ───────────────────────────────────────────
  {
    id: "ap-regulate-emissions",
    front: "to adopt laws to regulate emissions",
    back: "thông qua luật để điều tiết lượng khí thải",
    pronunciation: "/ˈrɛɡjʊleɪt ɪˈmɪʃnz/",
    example: "Laws should be adopted to regulate emissions.",
  },
  {
    id: "ap-public-transport",
    front: "to take public transportation instead of driving a car",
    back: "đi phương tiện công cộng thay vì lái xe",
    pronunciation: "/ˈpʌblɪk ˌtrænspɔːˈteɪʃn/",
    example: "Use public transportation instead of driving a car.",
  },
  {
    id: "ap-ride-bike",
    front: "to ride a bike instead of travelling in carbon dioxide-emitting vehicles",
    back: "đi xe đạp thay vì đi trên các phương tiện thải carbon dioxide",
    pronunciation: "/raɪd ə baɪk/",
    example: "Riding a bike reduces carbon emissions.",
  },
  {
    id: "ap-pollution-control",
    front: "to install pollution control devices",
    back: "lắp đặt thiết bị kiểm soát ô nhiễm",
    pronunciation: "/pəˈluːʃn kənˈtrəʊl dɪˈvaɪsɪz/",
    example: "Factories should install pollution control devices.",
  },
  {
    id: "ap-emission-allowance",
    front: "to buy emission allowance",
    back: "mua hạn ngạch khí thải",
    pronunciation: "/ɪˈmɪʃn əˈlaʊəns/",
    example: "Companies can buy emission allowances.",
  },
  {
    id: "ap-friendly-energy",
    front: "to encourage the use of environmentally friendly energy sources",
    back: "khuyến khích sử dụng các nguồn năng lượng thân thiện với môi trường",
    pronunciation: "/ɪnˌvaɪərənˈmɛntəli ˈfrendli ˈɛnədʒi/",
    example: "We should use environmentally friendly energy sources.",
  },
  {
    id: "ap-public-awareness",
    front: "to raise public awareness through campaigns",
    back: "nâng cao nhận thức cộng đồng thông qua các chiến dịch",
    pronunciation: "/reɪz ˈpʌblɪk əˈwɛənəs/",
    example: "Public awareness campaigns can reduce pollution.",
  },
  {
    id: "ap-zero-emissions",
    front: "to replace gasoline-fuelled cars with zero-emissions vehicles",
    back: "thay thế xe chạy bằng xăng bằng xe không thải khí thải ra môi trường",
    pronunciation: "/ˈzɪərəʊ ɪˈmɪʃnz ˈvɪəkəlz/",
    example: "Switch to zero-emissions vehicles for cleaner air.",
  },
  // ── Animals ────────────────────────────────────────────────────────────
  {
    id: "an-endangered-animals",
    front: "endangered animals",
    back: "động vật có nguy cơ tuyệt chủng",
    pronunciation: "/ɪnˈdeɪndʒərd ˈænɪmlz/",
    example: "Endangered animals need our protection.",
  },
  {
    id: "an-endangered-list",
    front: "the endangered species list",
    back: "danh sách các loài có nguy cơ tuyệt chủng",
    pronunciation: "/ɪnˈdeɪndʒərd ˈspiːʃiːz/",
    example: "Many animals are on the endangered species list.",
  },
  {
    id: "an-zoos-parks",
    front: "zoos or wildlife parks",
    back: "sở thú hay công viên động vật hoang dã",
    pronunciation: "/ˈwɪldlaɪf pɑːks/",
    example: "Children love visiting zoos or wildlife parks.",
  },
  {
    id: "an-kept-in-zoos",
    front: "to be kept in zoos",
    back: "bị nhốt trong sở thú",
    pronunciation: "/tu biː kɛpt ɪn zuːz/",
    example: "Some animals are kept in zoos.",
  },
  {
    id: "an-food-chain",
    front: "the food chain",
    back: "chuỗi thức ăn",
    pronunciation: "/ðə fuːd tʃeɪn/",
    example: "Every species plays a role in the food chain.",
  },
  {
    id: "an-danger-extinction",
    front: "to be in danger of extinction",
    back: "có nguy cơ tuyệt chủng",
    pronunciation: "/ɪkˈstɪŋkʃn/",
    example: "Many species are in danger of extinction.",
  },
  {
    id: "an-natural-habitats",
    front: "natural habitats",
    back: "môi trường sống tự nhiên",
    pronunciation: "/ˈnætʃərəl ˈhæbɪtæts/",
    example: "We must protect animals' natural habitats.",
  },
  {
    id: "an-animal-testing",
    front: "animal testing",
    back: "thử nghiệm trên động vật",
    pronunciation: "/ˈænɪml ˈtɛstɪŋ/",
    example: "Animal testing is a controversial practice.",
  },
  {
    id: "an-test-safety-drugs",
    front: "to test the safety of new drugs",
    back: "để kiểm tra sự an toàn của các loại thuốc mới",
    pronunciation: "/tɛst ðə ˈseɪfti əv njuː drʌɡz/",
    example: "Drugs are tested on animals for safety.",
  },
  {
    id: "an-essential-role",
    front: "to play an essential role in...",
    back: "đóng 1 vai trò thiết yếu trong...",
    pronunciation: "/pleɪ ən ɪˈsɛnʃl rəʊl/",
    example: "Bees play an essential role in pollination.",
  },
  {
    id: "an-medical-breakthroughs",
    front: "medical breakthroughs using animal testing",
    back: "các đột phá y học sử dụng thử nghiệm động vật",
    pronunciation: "/ˈmɛdɪkl ˈbreɪkθraʊz/",
    example: "Animal testing has led to medical breakthroughs.",
  },
  {
    id: "an-stress-pain-death",
    front: "to suffer from stress, pain or even death",
    back: "chịu đựng sự căng thẳng, đau đớn hay thậm chí là cái chết",
    pronunciation: "/ˈsʌfər frəm strɛs/",
    example: "Animals may suffer from stress during testing.",
  },
  {
    id: "an-complete-ban",
    front: "a complete ban on...",
    back: "một lệnh cấm toàn diện lên...",
    pronunciation: "/ə kəmˈpliːt bæn/",
    example: "Some countries have imposed a complete ban on animal testing.",
  },
  {
    id: "an-animal-rights",
    front: "to promote animal rights",
    back: "bảo vệ quyền động vật",
    pronunciation: "/ˈænɪml raɪts/",
    example: "Many NGOs promote animal rights.",
  },
  {
    id: "an-save-endangered",
    front: "to save endangered species",
    back: "bảo vệ động vật có nguy cơ tuyệt chủng",
    pronunciation: "/seɪv ɪnˈdeɪndʒərd ˈspiːʃiːz/",
    example: "We must save endangered species.",
  },
  {
    id: "an-treated-respect",
    front: "to be treated with respect",
    back: "được đối xử với sự tôn trọng",
    pronunciation: "/ˈtriːtɪd wɪð rɪˈspɛkt/",
    example: "Animals should be treated with respect.",
  },
  {
    id: "an-breeding-programmes",
    front: "to support breeding programmes",
    back: "ủng hộ các chương trình nhân giống",
    pronunciation: "/ˈbriːdɪŋ ˌprəʊɡræmz/",
    example: "Zoos support breeding programmes.",
  },
  {
    id: "an-conservation-efforts",
    front: "sustained conservation efforts",
    back: "những nỗ lực bảo tồn bền vững",
    pronunciation: "/kənˈsɜːveɪʃn ˈɛfəts/",
    example: "Sustained conservation efforts are needed.",
  },
  {
    id: "an-raise-money",
    front: "to raise more money for conservation",
    back: "quyên góp tiền cho sự bảo tồn động vật",
    pronunciation: "/reɪz mɔːri ˈmʌni/",
    example: "Fundraisers raise more money for conservation.",
  },
  {
    id: "an-ecological-balance",
    front: "a stable ecological balance",
    back: "1 sự cân bằng sinh thái ổn định",
    pronunciation: "/ˌiːkəˈlɒdʒɪkl ˈbæləns/",
    example: "Predators help maintain a stable ecological balance.",
  },
  {
    id: "an-mistreatment",
    front: "the mistreatment of animals",
    back: "sự đối xử bất công với động vật",
    pronunciation: "/ˌmɪsˈtriːtmənt/",
    example: "The mistreatment of animals is unethical.",
  },
  {
    id: "an-illegal-hunting",
    front: "illegal hunting, overfishing",
    back: "săn bắt bất hợp pháp, đánh bắt cá quá mức",
    pronunciation: "/ɪˈliːɡl ˈhʌntɪŋ/",
    example: "Illegal hunting threatens wildlife populations.",
  },
  {
    id: "an-illegal-poaching",
    front: "illegal poaching and trade",
    back: "săn bắn và mua bán động vật bất hợp pháp",
    pronunciation: "/ˈpəʊtʃɪŋ/",
    example: "Illegal poaching and trade must be stopped.",
  },
  {
    id: "an-forest-destruction",
    front: "the destruction of forest habitats",
    back: "sự hủy hoại môi trường rừng",
    pronunciation: "/dɪˈstrʌkʃn/",
    example: "The destruction of forest habitats endangers animals.",
  },
  {
    id: "an-cause-damage",
    front: "to cause great damage to...",
    back: "gây ra sự hủy hoại lớn đối với...",
    pronunciation: "/kɔːz ɡreɪt ˈdæmɪdʒ/",
    example: "Deforestation causes great damage to wildlife.",
  },
  // ── Animal Testing (For + Against) ─────────────────────────────────────
  {
    id: "at-drugs-humans",
    front: "to be used to test drugs before they are given to humans",
    back: "được sử dụng để kiểm tra thuốc trước khi được sử dụng trên đối tượng người",
    pronunciation: "/tɛst drʌɡz bɪˈfɔːr ðeə ɡɪvn tuː ˈhjuːmənz/",
    example: "Animals are used to test drugs before trials on humans.",
  },
  {
    id: "at-genetic-diseases",
    front: "to study the effects of genetic diseases",
    back: "nghiên cứu ảnh hưởng của các bệnh di truyền",
    pronunciation: "/ˈdʒɛnɪtɪk dɪˈziːzɪz/",
    example: "Scientists study the effects of genetic diseases on animals.",
  },
  {
    id: "at-genes-function",
    front: "to find out how genes work / to explore how organisms function",
    back: "tìm hiểu cách thức hoạt động của gen / khám phá cách thức hoạt động của các bộ phận",
    pronunciation: "/fɪnd aʊt haʊ dʒiːnz wɜːk/",
    example: "Animal testing helps find out how genes work.",
  },
  {
    id: "at-treatments",
    front: "to investigate treatments for human diseases",
    back: "nghiên cứu các phương pháp điều trị bệnh ở người",
    pronunciation: "/ɪnˈvɛstɪɡeɪt ˈtriːtmənts/",
    example: "Researchers investigate treatments for human diseases.",
  },
  {
    id: "at-essential-quest",
    front:
      "to be essential in the quest to understand human diseases and to develop new treatments",
    back: "trở nên thiết yếu trong nỗ lực tìm hiểu các căn bệnh ở người và phát triển các phương pháp điều trị mới",
    pronunciation: "/ɪˈsɛnʃl ɪn ðə kwɛst/",
    example: "Animal testing is essential in the quest to cure diseases.",
  },
  {
    id: "at-genetics-bred",
    front:
      "advances in the understanding of genetics → animals can be bred with specific genetic traits → allow researchers to explore a range of conditions (cancer, heart disease, stroke, dementia)",
    back: "những tiến bộ trong sự hiểu biết về di truyền → động vật có thể được nhân giống với những đặc điểm di truyền cụ thể → cho phép các nhà nghiên cứu khám phá một loạt các tình trạng bệnh lý (ung thư, bệnh tim, đột quỵ, mất trí nhớ)",
    pronunciation: "/dʒɪˈnɛtɪks/",
    example: "Advances in genetics allow animals to be bred with specific traits.",
  },
  {
    id: "at-scientific-advances",
    front: "to contribute greatly to scientific advances",
    back: "đóng góp lớn cho những tiến bộ khoa học",
    pronunciation: "/kənˈtrɪbjuːt tuː ˌsaɪənˈtɪfɪk ədˈvaːnsɪz/",
    example: "Animal testing has contributed greatly to scientific advances.",
  },
  {
    id: "at-life-saving",
    front: "serious medical or life-saving purposes",
    back: "những mục đích cứu người và mục đích y tế quan trọng",
    pronunciation: "/ˈsɪəriəs ˈmɛdɪkl/",
    example: "Animal testing serves serious medical purposes.",
  },
  {
    id: "at-medical-advances",
    front:
      "a wealth of medical advances → made with the help of animal research (new vaccines, treatments for cancer, Parkinson's disease, asthma and HIV)",
    back: "vô số tiến bộ y tế → được thực hiện với sự trợ giúp của nghiên cứu động vật (vắc-xin mới, phương pháp điều trị ung thư, bệnh Parkinson, bệnh hen suyễn và HIV)",
    pronunciation: "/wɛlθ əv ˈmɛdɪkl ədˈvaːnsɪz/",
    example: "Medical advances have been made with the help of animal research.",
  },
  {
    id: "at-cause-suffering",
    front: "to cause suffering to animals",
    back: "gây đau khổ cho động vật",
    pronunciation: "/kɔːz ˈsʌfərɪŋ/",
    example: "Animal testing causes suffering to animals.",
  },
  {
    id: "at-cruel-unethical",
    front: "cruel, unethical, meaningless/pointless",
    back: "độc ác, phi đạo đức, vô nghĩa",
    pronunciation: "/ˈkruːəl ʌnˈɛθɪkl/",
    example: "Many argue that animal testing is cruel and unethical.",
  },
  {
    id: "at-physiology-differences",
    front:
      "the differences in physiology, genetics and cell structures between animals and humans → invalidate most cures devised by animal experimentation",
    back: "sự khác biệt về sinh lý, di truyền và cấu trúc tế bào giữa động vật và con người → vô hiệu hóa hầu hết các phương pháp chữa bệnh được tạo ra bởi thí nghiệm trên động vật",
    pronunciation: "/ˌfɪziˈɒlədʒi/",
    example: "Differences in physiology make animal results unreliable.",
  },
  {
    id: "at-HIV-differences",
    front:
      "HIV → deadly to humans but not to most laboratory animals → studying HIV in other species → may not produce results applicable to humans",
    back: "HIV → gây tử vong cho người nhưng không phải với hầu hết các động vật thí nghiệm → nghiên cứu HIV ở các loài khác → có thể không tạo ra kết quả → áp dụng cho người",
    pronunciation: "/ˌeɪtʃˌaɪˈviː/",
    example: "HIV is deadly to humans but not to most lab animals.",
  },
  {
    id: "at-animal-diseases",
    front: "animals do not get many of the human diseases that we do",
    back: "động vật không mắc nhiều bệnh mà chúng ta đang mắc",
    pronunciation: "/ˈænɪmlz dɒz nɒt ɡɛt/",
    example: "Animals don't get many human diseases.",
  },
  {
    id: "at-treatments-rats",
    front: "treatments showing promise in animals → rarely work in humans",
    back: "phương pháp điều trị hứa hẹn ở động vật → hiếm khi hoạt động trên con người",
    pronunciation: "/ˈtriːtmənts ˈʃəʊɪŋ ˈprɒmɪs/",
    example: "Treatments effective in animals rarely work in humans.",
  },
  {
    id: "at-genetically-modified",
    front: "the breeding of genetically modified animals",
    back: "việc nhân giống động vật biến đổi gen",
    pronunciation: "/dʒɪˈnɛtɪkli ˈmɒdɪfaɪd ˈænɪmlz/",
    example: "The breeding of genetically modified animals is controversial.",
  },
  {
    id: "at-non-animal-alternatives",
    front: "non-animal alternative methods",
    back: "các phương pháp thay thế phi động vật",
    pronunciation: "/nɒn ˈænɪml ɔːlˈtɜːnətɪv ˈmɛθədz/",
    example: "Non-animal alternative methods are being developed.",
  },
  {
    id: "at-safety-testing",
    front: "to undergo safety testing involving animals",
    back: "trải qua thử nghiệm an toàn sử dụng động vật",
    pronunciation: "/ˌʌndəˈɡəʊ ˈseɪfti ˈtɛstɪŋ/",
    example: "New products undergo safety testing involving animals.",
  },
  {
    id: "at-alternative-techniques",
    front: "to replace tests with alternative techniques",
    back: "thay thế các xét nghiệm bằng các kỹ thuật thay thế",
    pronunciation: "/ɔːlˈtɜːnətɪv tɛkˈniːks/",
    example: "We can replace tests with alternative techniques.",
  },
  {
    id: "at-human-material",
    front: "to introduce human material into animals",
    back: "đưa các tế bào / mô của con người vào động vật",
    pronunciation: "/ˌɪntrəˈdjuːs ˈhjuːmən məˈtɪəriəl/",
    example: "Researchers introduce human material into animals.",
  },
  {
    id: "at-cancer-mice",
    front:
      "to put human breast tumour cells into mice → allow researchers to test cancer drugs on human tissue",
    back: "đưa tế bào khối u ở người vào chuột → cho phép các nhà nghiên cứu thử nghiệm thuốc ung thư trên mô người",
    pronunciation: "/ˈtjuːmər sɛlz/",
    example: "Human tumour cells are put into mice for cancer research.",
  },
  {
    id: "at-cell-structures",
    front: "to experiment on cell structures instead of whole animals",
    back: "thí nghiệm trên cấu trúc tế bào thay vì trên toàn bộ cơ thể động vật",
    pronunciation: "/ɪkˈspɛrimənt ɒn sɛl ˈstrʌktʃəz/",
    example: "Scientists experiment on cell structures instead of whole animals.",
  },
  {
    id: "at-computer-models",
    front: "to use computer models",
    back: "sử dụng mô hình máy tính",
    pronunciation: "/kəmˈpjuːtər ˈmɒdlz/",
    example: "Researchers use computer models in place of animals.",
  },
  {
    id: "at-human-volunteers",
    front: "to study human volunteers",
    back: "nghiên cứu tình nguyện viên là con người",
    pronunciation: "/ˈvɒlənˌtɪəz/",
    example: "Some studies use human volunteers.",
  },
  {
    id: "at-epidemiological-studies",
    front: "to use epidemiological studies",
    back: "sử dụng nghiên cứu dịch tễ học",
    pronunciation: "/ˌɛpɪˌdiːmiˈɒlədʒɪkl ˈstʌdiz/",
    example: "Epidemiological studies provide alternatives to animal testing.",
  },
  // ── Animal Extinction — CAUSES ─────────────────────────────────────────
  {
    id: "ae-cleared-forests",
    front:
      "forests have been cleared at astonishing rates → killing species in greater number than ever before",
    back: "rừng đã bị chặt phá với tốc độ đáng kinh ngạc → giết chết các loài với số lượng lớn hơn bao giờ hết",
    pronunciation: "/əˈstɒnɪʃɪŋ reɪts/",
    example: "Forests have been cleared at astonishing rates.",
  },
  {
    id: "ae-replace-grassland",
    front:
      "to replace grassland with ... / replace ancient woodland with ... / clear forests to grow crops / change wetlands and forests to croplands and urban areas",
    back: "thay thế đồng cỏ bằng ... / thay thế đất rừng cổ xưa bằng ... / phát quang rừng để trồng trọt / thay đổi vùng đất ngập nước và rừng thành vùng trồng trọt và đô thị",
    pronunciation: "/ˈɡræslænd/",
    example: "Grasslands have been replaced with croplands.",
  },
  {
    id: "ae-agriculture-forests",
    front: "increase in agriculture → at the expense of intact forests",
    back: "tăng sản xuất nông nghiệp → hy sinh rừng (rừng bị chặt hạ)",
    pronunciation: "/ˈæɡrɪkʌltʃər/",
    example: "Agriculture increases at the expense of intact forests.",
  },
  {
    id: "ae-growing-population",
    front: "increased demands for food from a growing global population",
    back: "tăng nhu cầu thực phẩm từ một dân số toàn cầu ngày càng tăng",
    pronunciation: "/dɪˈmɑːndz fɔːr fuːd/",
    example: "A growing global population demands more food.",
  },
  {
    id: "ae-new-diseases",
    front: "new diseases",
    back: "các loại bệnh mới",
    pronunciation: "/njuː dɪˈziːzɪz/",
    example: "New diseases threaten animal populations.",
  },
  {
    id: "ae-new-predators",
    front:
      "new predators: the introduction of exotic species: carry disease, prey on native species, disrupt food webs",
    back: "động vật ăn thịt mới: đưa về các loài ngoại lai: mang mầm bệnh, ăn cả các loài bản địa, làm xáo trộn mạng lưới thức ăn",
    pronunciation: "/ˈprɛdətəz/",
    example: "Exotic species are introduced, disrupting food webs.",
  },
  {
    id: "ae-catastrophic-event",
    front:
      "a single catastrophic event, such as a massive volcanic eruption or a collision between an asteroid and the Earth",
    back: "một sự kiện thảm khốc duy nhất, chẳng hạn như một vụ phun trào núi lửa lớn hoặc một vụ va chạm giữa một thiên thạch và Trái Đất",
    pronunciation: "/ˌkætəˈstrɒfɪk ɪˈvɛnt/",
    example: "A single catastrophic event can wipe out species.",
  },
  {
    id: "ae-hunting-overfishing",
    front: "hunting, overfishing",
    back: "săn bắt, đánh bắt cá quá mức",
    pronunciation: "/ˈəʊvəˌfɪʃɪŋ/",
    example: "Hunting and overfishing drive extinction.",
  },
  {
    id: "ae-polluting",
    front: "polluting",
    back: "ô nhiễm",
    pronunciation: "/pəˈluːtɪŋ/",
    example: "Polluting the environment contributes to species loss.",
  },
  // ── Animal Extinction — EFFECTS ────────────────────────────────────────
  {
    id: "ae-bees-pollination",
    front:
      "the decline in the number of wild bees and other insects → help pollinate fruits and vegetables → harm agricultural production",
    back: "sự suy giảm trong số lượng ong hoang dã và các côn trùng khác → giúp thụ phấn cho rau quả → gây hại cho sản xuất nông nghiệp",
    pronunciation: "/ˈpɒlɪneɪt/",
    example: "The decline of wild bees harms agricultural production.",
  },
  {
    id: "ae-genetic-improvements",
    front: "wild species → might be used for genetic improvements (future)",
    back: "các loài hoang dã → có thể được sử dụng để cải thiện di truyền (trong tương lai)",
    pronunciation: "/dʒɪˈnɛtɪk ɪmˈpruːvmənts/",
    example: "Wild species may be used for genetic improvements in the future.",
  },
  {
    id: "ae-birds-bellwether",
    front: "birds → provide an important bellwether for tracking changes to the biosphere",
    back: "chim → là nguồn dự báo quan trọng để theo dõi các thay đổi đối với sinh quyển",
    pronunciation: "/ˈbɛlˌwɛðər/",
    example: "Birds are an important bellwether for the biosphere.",
  },
  {
    id: "ae-tribes-forced",
    front: "tribes dependent on … → forced to move to new lands in search of food",
    back: "bộ lạc phụ thuộc vào ... → buộc phải di chuyển đến vùng đất mới để tìm kiếm thức ăn",
    pronunciation: "/traɪbz/",
    example: "Some tribes are forced to move to new lands.",
  },
  {
    id: "ae-medical-breakthroughs",
    front:
      "many species → offer insight into curing human disease / hold the key to a number of medical breakthroughs",
    back: "nhiều loài → cung cấp cái nhìn sâu sắc về việc chữa khỏi bệnh ở người / là chìa khóa dẫn tới một loạt các đột phá y học",
    pronunciation: "/ˈmɛdɪkl ˈbreɪkθraʊz/",
    example: "Many species hold the key to medical breakthroughs.",
  },
  {
    id: "ae-bears-hibernation",
    front:
      "to study bears → how they recycle blood toxins during hibernation → to find potential solutions to kidney disorders",
    back: "nghiên cứu gấu → cách chúng tái chế độc tố máu trong thời gian ngủ đông → để tìm giải pháp tiềm năng cho rối loạn thận",
    pronunciation: "/ˌhaɪbəˈneɪʃn/",
    example: "Scientists study bears to find kidney solutions.",
  },
  {
    id: "ae-extinction-disappearance",
    front: "the extinction of a species → potentially lead to the disappearance of others",
    back: "sự tuyệt chủng của một loài → có khả năng dẫn đến sự biến mất của những loài khác",
    pronunciation: "/ˌdɪsəˈpɪərəns/",
    example: "The extinction of one species can lead to others.",
  },
  // ── Water Pollution — CAUSES ───────────────────────────────────────────
  {
    id: "wp-industrial-waste",
    front:
      "the dumping of industrial waste / domestic waste → the discharge of harmful substances into...",
    back: "việc thải chất thải công nghiệp / chất thải sinh hoạt → chất độc hại vào ...",
    pronunciation: "/ɪnˈdʌstriəl weɪst/",
    example: "Industrial waste is dumped into rivers.",
  },
  {
    id: "wp-untreated-hazardous",
    front: "to dump untreated hazardous waste into rivers, streams...",
    back: "thải chất thải nguy hiểm chưa được xử lý vào sông, suối,...",
    pronunciation: "/ʌnˈtriːtɪd ˈhæzərdəs/",
    example: "Untreated hazardous waste pollutes rivers.",
  },
  {
    id: "wp-reservoirs",
    front: "these toxins → threaten reservoirs → provide drinking water to...",
    back: "những chất độc này → đe dọa các hồ chứa nước → cung cấp nước uống cho ...",
    pronunciation: "/ˈrɛzəvwɑːz/",
    example: "Toxins threaten reservoirs that supply drinking water.",
  },
  {
    id: "wp-sewage-disposal",
    front:
      "improper sewage disposal / do not have a proper waste management system / imperfect water treatment plants",
    back: "xử lý nước thải không đúng cách / không có hệ thống quản lý chất thải thích hợp / nhà máy xử lý nước không hợp lệ",
    pronunciation: "/ɪmˈprɒpər ˈsjuːɪdʒ/",
    example: "Improper sewage disposal pollutes water.",
  },
  {
    id: "wp-harmful-bacteria",
    front: "sewage water → carry harmful bacteria + chemicals",
    back: "nước thải → mang vi khuẩn có hại + hóa chất",
    pronunciation: "/ˈhɑːmfʊl bækˈtɪəriə/",
    example: "Sewage water carries harmful bacteria.",
  },
  {
    id: "wp-fertilizers-pesticides",
    front: "the overuse of chemical fertilizers and pesticides",
    back: "việc lạm dụng phân bón hóa học và thuốc trừ sâu",
    pronunciation: "/fɜːˈtɪlaɪzəz/",
    example: "Overuse of fertilizers pollutes waterways.",
  },
  {
    id: "wp-agricultural-runoff",
    front: "agricultural run-off containing pesticides → pollute rivers, streams...",
    back: "nước thải nông nghiệp chứa thuốc trừ sâu → làm ô nhiễm sông, suối, ...",
    pronunciation: "/æɡrɪˈkʌltʃərəl ˈrʌnɒf/",
    example: "Agricultural run-off pollutes rivers.",
  },
  {
    id: "wp-pollutants-rain",
    front:
      "pollutants are carried across or through the ground by rain or melted snow → this run-off contains fertilizers, pesticides and herbicides",
    back: "các chất ô nhiễm ngấm xuống đất do mưa hoặc tuyết tan chảy → dòng chảy này chứa phân bón, thuốc trừ sâu và thuốc diệt cỏ",
    pronunciation: "/pəˈluːtənts/",
    example: "Pollutants are carried by rain into groundwater.",
  },
  {
    id: "wp-mining-drilling",
    front: "mining and drilling",
    back: "hoạt động khoan và khai thác mỏ",
    pronunciation: "/ˈmaɪnɪŋ ənd ˈdrɪlɪŋ/",
    example: "Mining and drilling cause water pollution.",
  },
  {
    id: "wp-acid-coal",
    front:
      "to use acid to remove coal from the surrounding rocks → acid is washed into streams + rivers → release chemical substances",
    back: "sử dụng axit để loại bỏ than từ các tầng đá xung quanh → axit được rửa trôi vào suối + sông → giải phóng các chất hóa học",
    pronunciation: "/ˈsʌrˌaʊndɪŋ rɒks/",
    example: "Acid used in mining washes into streams.",
  },
  // ── Water Pollution — EFFECTS ──────────────────────────────────────────
  {
    id: "wp-aquatic-organisms",
    front: "to pose a serious hazard to aquatic organisms",
    back: "gây nguy hiểm nghiêm trọng cho các sinh vật sống dưới nước",
    pronunciation: "/əˈkwætɪk ˈɔːɡənɪzmz/",
    example: "Water pollution poses serious hazards to aquatic organisms.",
  },
  {
    id: "wp-freshwater-crisis",
    front:
      "to contribute to a freshwater crisis → threaten the sources upon which we rely for drinking water and other critical needs",
    back: "gây ra một cuộc khủng hoảng nước ngọt → đe dọa các nguồn nước mà chúng ta phụ thuộc vào để lấy nước uống và các nhu cầu quan trọng khác",
    pronunciation: "/ˈfrɛʃˌwɔːtər ˈkraɪsɪs/",
    example: "Water pollution contributes to a freshwater crisis.",
  },
  {
    id: "wp-ecosystem-damage",
    front: "to result in human health problems, long-term ecosystem damage",
    back: "dẫn đến các vấn đề sức khỏe của con người, thiệt hại hệ sinh thái lâu dài",
    pronunciation: "/ˌiːkəʊˈsɪstəm ˈdæmɪdʒ/",
    example: "Water pollution results in ecosystem damage.",
  },
  {
    id: "wp-nitrates-infants",
    front:
      "high levels of nitrates in water → harmful to infants (interfere with their ability to deliver oxygen to tissues) → potentially cause blue baby syndrome",
    back: "nồng độ nitrat cao trong nước → có hại cho trẻ sơ sinh → có khả năng gây ra hội chứng em bé da xanh",
    pronunciation: "/ˈnaɪtreɪts ɪn ˈwɔːtər/",
    example: "High nitrate levels in water cause blue baby syndrome.",
  },
  {
    id: "wp-unsanitary-water",
    front:
      "unsanitary water supplies → exact a health toll in the form of disease (polluted water → transmit dangerous diseases such as cholera, typhoid)",
    back: "nguồn cung cấp nước bị ô nhiễm → gây ra nhiều bệnh tật (nước bị ô nhiễm → truyền các bệnh nguy hiểm như bệnh tả, thương hàn)",
    pronunciation: "/ˌʌnˈsænɪtri ˈwɔːtər/",
    example: "Unsanitary water transmits cholera and typhoid.",
  },
  {
    id: "wp-contaminated-water",
    front:
      "people drinking contaminated water → be exposed to hazardous chemicals → diseases such as diarrhea, cholera, dysentery, polio",
    back: "người uống nước bị ô nhiễm → tiếp xúc với các chất hóa học nguy hiểm → bệnh như tiêu chảy, dịch tả, kiết lỵ, bại liệt",
    pronunciation: "/kənˈtæmɪneɪtɪd/",
    example: "Drinking contaminated water causes diarrhoea and cholera.",
  },
  {
    id: "wp-marine-confusion",
    front: "marine creatures mistake garbage for food",
    back: "sinh vật biển nhầm rác với thức ăn",
    pronunciation: "/məˈriːn ˈkriːtʃəz/",
    example: "Marine creatures often mistake garbage for food.",
  },
  // ── World Hunger — CAUSES ──────────────────────────────────────────────
  {
    id: "wh-violent-conflicts",
    front: "the proliferation of violent conflicts and climate-related shocks",
    back: "sự gia tăng của các xung đột bạo lực và các cú sốc liên quan đến khí hậu",
    pronunciation: "/prəˌlɪfəˈreɪʃn/",
    example: "Violent conflicts and climate shocks drive hunger.",
  },
  {
    id: "wh-dietary-habits",
    front: "sweeping changes in dietary habits",
    back: "sự thay đổi sâu rộng trong thói quen ăn uống",
    pronunciation: "/ˈdaɪətəri ˈhæbɪts/",
    example: "Sweeping changes in dietary habits affect food systems.",
  },
  {
    id: "wh-economic-slowdowns",
    front: "economic slowdowns",
    back: "suy thoái kinh tế",
    pronunciation: "/ˌiːkəˈnɒmɪk ˈslaʊdaʊnz/",
    example: "Economic slowdowns lead to food insecurity.",
  },
  {
    id: "wh-rainfall-patterns",
    front: "climate variability affects rainfall patterns and agricultural seasons",
    back: "biến đổi khí hậu ảnh hưởng đến mô hình mưa và mùa màng trong nông nghiệp",
    pronunciation: "/ˈreɪnfɔːl ˈpætənz/",
    example: "Climate variability disrupts rainfall patterns.",
  },
  {
    id: "wh-weather-extremes",
    front: "to be highly exposed to weather extremes",
    back: "tiếp xúc nhiều với thời tiết khắc nghiệt",
    pronunciation: "/ˈwiːðər ɪkˈstriːmz/",
    example: "Farmers are exposed to weather extremes.",
  },
  {
    id: "wh-rainfall-temperature",
    front: "to be highly sensitive to rainfall and temperature variability",
    back: "rất nhạy cảm với sự thay đổi của lượng mưa và nhiệt độ",
    pronunciation: "/ˌvɛəriəˈbɪləti/",
    example: "Crops are sensitive to rainfall and temperature.",
  },
  {
    id: "wh-reduce-access",
    front: "to reduce people's access to food",
    back: "giảm sự tiếp cận thực phẩm của mọi người",
    pronunciation: "/rɪˈdjuːs ˈpiːplz ˈæksɛs/",
    example: "Climate change reduces people's access to food.",
  },
  {
    id: "wh-poor-governance",
    front: "poor governance and inappropriate policies",
    back: "quản trị kém và chính sách không phù hợp",
    pronunciation: "/pɔːr ˈɡʌvənəns/",
    example: "Poor governance worsens food insecurity.",
  },
  {
    id: "wh-disrupt-cycles",
    front: "to disrupt planting and harvest cycles",
    back: "phá vỡ chu kỳ trồng và thu hoạch",
    pronunciation: "/dɪsˈrʌpt ˈsaɪklz/",
    example: "Extreme weather disrupts planting cycles.",
  },
  {
    id: "wh-forced-leave-land",
    front: "to be forced to leave their land",
    back: "bị buộc rời khỏi vùng đất của họ",
    pronunciation: "/fɔːst tuː liːv ðeə lænd/",
    example: "Farmers may be forced to leave their land.",
  },
  // ── World Hunger — SOLUTIONS ───────────────────────────────────────────
  {
    id: "wh-income-workshops",
    front: "income-generating workshops",
    back: "hội thảo tạo thu nhập",
    pronunciation: "/ˈɪŋkʌm ˈdʒɛnəreɪtɪŋ/",
    example: "Income-generating workshops help local communities.",
  },
  {
    id: "wh-food-production",
    front: "to increase food production",
    back: "tăng sản xuất thực phẩm",
    pronunciation: "/fuːd prəˈdʌkʃn/",
    example: "We must increase food production.",
  },
  {
    id: "wh-new-techniques",
    front: "to implement new techniques",
    back: "thực hiện các kỹ thuật mới",
    pronunciation: "/ˈnjuː tɛkˈniːks/",
    example: "Farmers should implement new techniques.",
  },
  {
    id: "wh-reliable-access",
    front:
      "to get involved in working towards a world where everyone has reliable access to enough safe and nutritious food",
    back: "tham gia làm việc hướng tới một thới giới nơi mọi người đều có quyền truy cập đáng tin cậy vào đủ thực phẩm an toàn và bổ dưỡng",
    pronunciation: "/rɪˈlaɪəbl ˈæksɛs/",
    example: "We must work towards reliable access to food.",
  },
  {
    id: "wh-food-banks",
    front: "to donate food to food banks and community organisations",
    back: "quyên góp thực phẩm cho các ngân hàng thực phẩm và các tổ chức cộng đồng",
    pronunciation: "/fuːd bæŋks/",
    example: "Donate food to food banks and community organisations.",
  },
  {
    id: "wh-create-world-no-hunger",
    front: "to create a world without hunger",
    back: "tạo ra một thới giới không còn nạn đói",
    pronunciation: "/kriˈeɪt ə wɜːld wɪˈðaʊt ˈhʌŋɡər/",
    example: "Together we can create a world without hunger.",
  },
  {
    id: "wh-resilience-adaptive",
    front:
      "to accelerate and scale up actions to strengthen the resilience and adaptive capacity of food systems",
    back: "tăng tốc và mở rộng hành động để tăng cường khả năng phục hồi và khả năng thích ứng của các hệ thống thực phẩm",
    pronunciation: "/rɪˈzɪliəns/",
    example: "We should strengthen food systems resilience.",
  },
  {
    id: "wh-guarantee-access",
    front: "to guarantee access to...",
    back: "đảm bảo quyền truy cập vào ...",
    pronunciation: "/ˌɡærənˈtiː ˈæksɛs/",
    example: "Governments should guarantee access to food.",
  },
  {
    id: "wh-stricter-regulations",
    front: "to introduce new laws and stricter regulations in order to...",
    back: "ban hành luật mới và các quy định chặt chẽ hơn để ...",
    pronunciation: "/ˈstrɪktər ˌrɛɡjʊˈleɪʃnz/",
    example: "Introduce stricter regulations to fight hunger.",
  },
  // ── World Hunger — VOCAB ───────────────────────────────────────────────
  {
    id: "wh-extreme-poverty",
    front: "to live in extreme poverty",
    back: "sống trong nghèo khổ cùng cực",
    pronunciation: "/ɪkˈstriːm ˈpɒvəti/",
    example: "Many people live in extreme poverty.",
  },
  {
    id: "wh-agriculture-livelihood",
    front: "to depend on agriculture and related activities for livelihood",
    back: "phụ thuộc vào nông nghiệp và các hoạt động liên quan để sinh sống",
    pronunciation: "/ˈlɪvəlihʊd/",
    example: "Many depend on agriculture for livelihood.",
  },
  {
    id: "wh-lack-access",
    front: "to lack access to...",
    back: "thiếu quyền truy cập vào ...",
    pronunciation: "/læk ˈæksɛs/",
    example: "Poor communities lack access to clean water.",
  },
  {
    id: "wh-hunger-malnutrition",
    front: "to fight hunger and malnutrition",
    back: "chống đói và suy dinh dưỡng",
    pronunciation: "/mælnjuːˈtrɪʃn/",
    example: "NGOs fight hunger and malnutrition.",
  },
  {
    id: "wh-free-humans",
    front: "to free humans from...",
    back: "giải phóng con người khỏi ...",
    pronunciation: "/friː ˈhjuːmənz/",
    example: "Education can free humans from poverty.",
  },
  {
    id: "wh-combat-hunger",
    front: "to combat world hunger, malnutrition and food insecurity",
    back: "chống đói, suy dinh dưỡng và mất an ninh lương thực",
    pronunciation: "/kəmˈbæt/",
    example: "Governments combat food insecurity worldwide.",
  },
  {
    id: "wh-drivers-behind",
    front: "one of the drivers behind...",
    back: "một trong những nguyên nhân đằng sau vấn đề gì",
    pronunciation: "/ˈdraɪvəz bɪˈhaɪnd/",
    example: "Climate change is one of the drivers behind hunger.",
  },
  {
    id: "wh-health-at-risk",
    front: "to put the health of hundreds of millions of people at risk",
    back: "gây nguy hiểm cho sức khỏe của hàng trăm triệu người",
    pronunciation: "/æt rɪsk/",
    example: "Hunger puts millions' health at risk.",
  },
  {
    id: "wh-dying-hunger",
    front: "to be at risk of dying of hunger/starvation",
    back: "có nguy cơ chết vì đói",
    pronunciation: "/stɑːˈveɪʃn/",
    example: "Children in war zones are at risk of starvation.",
  },
  {
    id: "wh-worsening-food",
    front: "to contribute to worsening food insecurity",
    back: "góp phần làm sự mất an ninh thực phẩm trở nên tồi tệ hơn",
    pronunciation: "/ˈwɜːsənɪŋ/",
    example: "Conflicts worsen food insecurity.",
  },
  {
    id: "wh-destroy-crops",
    front: "to destroy crops and livestock",
    back: "phá hoại mùa màng và gia súc",
    pronunciation: "/dɪˈstrɔɪ krɒps/",
    example: "Floods destroy crops and livestock.",
  },
  {
    id: "wh-food-shortages",
    front: "to suffer from food shortages and famine",
    back: "chịu đựng nạn thiếu lương thực và nạn đói",
    pronunciation: "/ˈfæmɪn/",
    example: "War victims suffer from famine.",
  },
  {
    id: "wh-natural-disasters",
    front: "natural disasters",
    back: "những thảm họa thiên nhiên",
    pronunciation: "/ˈnætʃərəl dɪˈzɑːstəz/",
    example: "Natural disasters cause food shortages.",
  },
  {
    id: "wh-prolonged-drought",
    front: "prolonged drought, violent storms",
    back: "hạn hán kéo dài, bão dữ",
    pronunciation: "/prəˈlɒŋd draʊt/",
    example: "Prolonged droughts and violent storms devastate crops.",
  },
  {
    id: "wh-makes-ends-meet",
    front: "to have difficulty making ends meet",
    back: "gặp khó khăn trong việc kiếm sống",
    pronunciation: "/meɪkɪŋ ɛndz miːt/",
    example: "Many families struggle making ends meet.",
  },
  {
    id: "wh-violent-attacks",
    front: "violent attacks, social riots, conflicts and wars",
    back: "các cuộc tấn công bạo lực, bạo loạn xã hội, xung đột và chiến tranh",
    pronunciation: "/ˈrʌɪəts/",
    example: "Wars and social riots cause hunger.",
  },
];

export { globalEnvCards };
