import type { Flashcard } from "./types";

// ────────────────────────────────────────────────────────────────────────────
// SET 7 — EDUCATION
// ────────────────────────────────────────────────────────────────────────────
const educationCards: Flashcard[] = [
  // Idioms
  {
    id: "edu-by-heart",
    front: "to learn something by heart",
    back: "học thuộc lòng",
    pronunciation: "/tu lɜːn ˈsʌmθɪŋ baɪ hɑːt/",
    example: "Students learn poems by heart.",
  },
  {
    id: "edu-bookworm",
    front: "bookworm",
    back: "mọt sách",
    pronunciation: "/ˈbʊkwɜːm/",
    example: "She is a real bookworm.",
  },
  {
    id: "edu-teachers-pet",
    front: "teacher's pet",
    back: "học sinh cưng của giáo viên",
    pronunciation: "/ˈtiːtʃərz pɛt/",
    example: "He was the teacher's pet.",
  },
  {
    id: "edu-draw-blank",
    front: "to draw a blank",
    back: "không tìm thấy hay nhớ ra điều gì",
    pronunciation: "/tu drɔː ə blæŋk/",
    example: "When asked the question, he drew a blank.",
  },
  {
    id: "edu-copycat",
    front: "copycat",
    back: "người bắt chước ý tưởng của người khác",
    pronunciation: "/ˈkɒpikæt/",
    example: "Don't be a copycat.",
  },
  {
    id: "edu-get-hang",
    front: "to get the hang of something",
    back: "hiểu cách làm gì, học cách làm gì",
    pronunciation: "/tu ɡet ðə hæŋ əv ˈsʌmθɪŋ/",
    example: "It takes time to get the hang of it.",
  },
  {
    id: "edu-burn-oil",
    front: "to burn the midnight oil",
    back: "thức khuya để học/làm việc",
    pronunciation: "/tu bɜːn ðə ˈmɪdnaɪt ɔɪl/",
    example: "She's burning the midnight oil for the exam.",
  },
  {
    id: "edu-flying-colours",
    front: "to pass with flying colours",
    back: "đỗ/đậu một cách dễ dàng",
    pronunciation: "/tu pɑːs wɪð ˈflaɪɪŋ ˈkʌləz/",
    example: "He passed the exam with flying colours.",
  },
  {
    id: "edu-back-to-basis",
    front: "to go back to basis",
    back: "quay lại những điều cốt lõi",
    pronunciation: "/tu ɡəʊ bæk tu ˈbeɪsɪs/",
    example: "Let's go back to basics.",
  },
  {
    id: "edu-cover-ground",
    front: "to cover a lot of ground",
    back: "xem lại thật nhiều tài liệu, thông tin",
    pronunciation: "/tu ˈkʌvər ə lɒt əv ɡraʊnd/",
    example: "The lecture covered a lot of ground.",
  },
  // School levels
  {
    id: "edu-kindergarten",
    front: "kindergarten",
    back: "mẫu giáo",
    pronunciation: "/ˈkɪndərɡɑːtn/",
    example: "She teaches at a kindergarten.",
  },
  {
    id: "edu-primary",
    front: "primary school",
    back: "tiểu học",
    pronunciation: "/ˈpraɪməri skuːl/",
    example: "My brother is in primary school.",
  },
  {
    id: "edu-secondary",
    front: "secondary school",
    back: "trung học",
    pronunciation: "/ˈsɛkəndri skuːl/",
    example: "She is in secondary school.",
  },
  {
    id: "edu-university",
    front: "university",
    back: "đại học",
    pronunciation: "/ˌjuːnɪˈvɜːsəti/",
    example: "I am studying at university.",
  },
  // Education vocab
  {
    id: "edu-results",
    front: "to get higher academic results",
    back: "đạt được kết quả học tập cao",
    pronunciation: "/tu ɡet ˈhaɪər ˌækəˈdɛmɪk rɪˈzʌlts/",
    example: "She gets higher academic results every year.",
  },
  {
    id: "edu-study-abroad",
    front: "to study abroad = to study in a different country",
    back: "du học",
    pronunciation: "/tu ˈstʌdi əˈbrɔːd/",
    example: "He wants to study abroad.",
  },
  {
    id: "edu-drop-out",
    front: "to drop out of school",
    back: "bỏ học",
    pronunciation: "/tu drɒp aʊt əv skuːl/",
    example: "Many drop out of school to work.",
  },
  {
    id: "edu-international-qual",
    front: "to gain international qualifications",
    back: "có được bằng cấp quốc tế",
    pronunciation: "/tu ɡeɪn ˌɪntəˈnæʃnəl ˌkwɒlɪfɪˈkeɪʃnz/",
    example: "Many want to gain international qualifications.",
  },
  {
    id: "edu-educational-outcomes",
    front: "to improve educational outcomes",
    back: "nâng cao đầu ra của giáo dục",
    pronunciation: "/tu ɪmˈpruːv ˌɛdjuˈkeɪʃənl ˈaʊtkʌmz/",
    example: "The reforms aim to improve educational outcomes.",
  },
  {
    id: "edu-league-tables",
    front: "to top international educational league tables",
    back: "xếp đầu bảng giáo dục quốc tế",
    pronunciation: "/tu tɒp/",
    example: "Singapore tops international educational league tables.",
  },
  {
    id: "edu-independent-learning",
    front: "to encourage independent learning",
    back: "thúc đẩy việc tự học",
    pronunciation: "/tu ɪnˈkʌrɪdʒ/",
    example: "Teachers should encourage independent learning.",
  },
  {
    id: "edu-pass-fail",
    front: "to pass/fail the exam",
    back: "đậu / rớt kỳ thi",
    pronunciation: "/tu pɑːs/fɛəl ði ɪɡˈzæm/",
    example: "She passed the exam with flying colours.",
  },
  {
    id: "edu-in-depth",
    front: "to gain in-depth knowledge",
    back: "có được kiến thức sâu sắc",
    pronunciation: "/tu ɡeɪn ɪn dɛpθ ˈnɒlɪdʒ/",
    example: "Students gain in-depth knowledge in their major.",
  },
  {
    id: "edu-core-subjects",
    front: "core subjects such as science, English and maths",
    back: "những môn học nòng cốt như khoa học, tiếng Anh và toán",
    pronunciation: "/kɔːr ˈsʌbdʒɪkts/",
    example: "Maths is one of the core subjects.",
  },
  {
    id: "edu-opportunity",
    front: "to have the opportunity to ...",
    back: "có cơ hội làm gì",
    pronunciation: "/tu həv ði ˌɒpəˈtjuːnəti/",
    example: "We have the opportunity to learn from the best.",
  },
  {
    id: "edu-group-work",
    front: "to interact and take part in group work activities",
    back: "tương tác và tham gia vào các hoạt động nhóm",
    pronunciation: "/tu ˌɪntərˈækt/",
    example: "Group work activities build teamwork skills.",
  },
  {
    id: "edu-opposite-sex",
    front: "opposite-sex classmates",
    back: "bạn khác giới",
    pronunciation: "/ˈɒpəzɪt sɛks/",
    example: "Opposite-sex classmates help develop social skills.",
  },
  {
    id: "edu-wide-range",
    front: "to learn a wide range of skills",
    back: "học được các kỹ năng khác nhau",
    pronunciation: "/tu lɜːn ə waɪd reɪndʒ əv skɪlz/",
    example: "School helps learn a wide range of skills.",
  },
  {
    id: "edu-teamwork",
    front: "communication or teamwork skills",
    back: "kỹ năng giao tiếp hay làm việc nhóm",
    pronunciation: "/kəˌmjuːnɪˈkeɪʃn ɔː ˈtiːmwɜːk skɪlz/",
    example: "Communication skills are crucial in life.",
  },
  {
    id: "edu-co-existence",
    front: "co-existence and gender equality",
    back: "sự cùng tồn tại và sự bình đẳng giới",
    pronunciation: "/ˌkəʊɪɡˈzɪstəns ənd ˈdʒɛndər ɪˈkwɒləti/",
    example: "Schools should teach co-existence and gender equality.",
  },
  // Study abroad — additional
  {
    id: "edu-nursery",
    front: "nursery school",
    back: "trường mẫu giáo (cho trẻ 2-5 tuổi, Anh/Anh)",
    pronunciation: "/ˈnɜːsəri skuːl/",
    example: "Young children attend nursery school.",
  },
  {
    id: "edu-culture-shock",
    front: "to encounter culture shock",
    back: "gặp phải cú sốc văn hóa",
    pronunciation: "/tu ɪnˈkaʊntər ˈkʌltʃə ʃɒk/",
    example: "Many students encounter culture shock abroad.",
  },
  {
    id: "edu-part-time",
    front: "to do a part-time job",
    back: "làm công việc bán thời gian",
    pronunciation: "/tu duː ə ˌpɑːt ˈtaɪm dʒɒb/",
    example: "Students do a part-time job to pay bills.",
  },
  {
    id: "edu-favour-over",
    front: "to favour A over B",
    back: "ưu ái / thích A hơn B",
    pronunciation: "/tu ˈfeɪvər eɪ ˈəʊvər biː/",
    example: "Recruiters favour graduates with international degrees over those without.",
  },
  {
    id: "edu-stress-management",
    front: "stress management",
    back: "quản lý căng thẳng",
    pronunciation: "/strɛs ˈmænɪdʒmənt/",
    example: "Stress management is a crucial skill.",
  },
  {
    id: "edu-problem-solving",
    front: "problem-solving skills",
    back: "kỹ năng giải quyết vấn đề",
    pronunciation: "/ˈprɒbləm ˈsɒlvɪŋ skɪlz/",
    example: "Study abroad develops problem-solving skills.",
  },
  {
    id: "edu-invaluable-lessons",
    front: "to learn invaluable life lessons",
    back: "học những bài học cuộc sống vô giá",
    pronunciation: "/tu lɜːn ɪnˌvæljuəbl laɪf ˈlɛsnz/",
    example: "You can learn invaluable life lessons while studying abroad.",
  },
  {
    id: "edu-homesickness",
    front: "homesickness",
    back: "nỗi nhớ nhà",
    pronunciation: "/ˈhəʊmˌsɪknəs/",
    example: "Many students experience homesickness.",
  },
  {
    id: "edu-frustration",
    front: "feelings of frustration",
    back: "cảm giác thất vọng, bực bội",
    pronunciation: "/ˈfiːlɪŋz əv frʌˈstreɪʃn/",
    example: "Living abroad can cause feelings of frustration.",
  },
  {
    id: "edu-make-new-friends",
    front: "to make new friends",
    back: "kết bạn mới",
    pronunciation: "/tu meɪk njuː frendz/",
    example: "Studying abroad gives the chance to make new friends.",
  },
  {
    id: "edu-different-way-living",
    front: "to experience a different way of living",
    back: "trải nghiệm một cách sống khác",
    pronunciation: "/tu ɪkˈspɪəriəns ə ˈdɪfrənt weɪ əv ˈlɪvɪŋ/",
    example: "Study abroad lets you experience a different way of living.",
  },
  {
    id: "edu-living-on-your-own",
    front: "to live on your own (while studying abroad) makes you more independent",
    back: "sống một mình (khi du học) khiến bạn độc lập hơn",
    pronunciation: "/tu lɪv ɒn jɔːr əʊn/",
    example: "Living on your own while studying abroad makes you more independent.",
  },
];

// ────────────────────────────────────────────────────────────────────────────
// SET 8 — ENVIRONMENT (gộp: Global Warming + GM Food + Plastic Pollution)
// ────────────────────────────────────────────────────────────────────────────
const environmentCards: Flashcard[] = [
  // Global warming
  {
    id: "env-carbon",
    front: "to reduce carbon emissions",
    back: "giảm lượng khí thải carbon",
    pronunciation: "/tu rɪˈdjuːs ˈkɑːbən ɪˈmɪʃnz/",
    example: "Countries should reduce carbon emissions.",
  },
  {
    id: "env-biggest-threat",
    front: "to be one of the biggest threats to our planet",
    back: "một trong những mối đe dọa lớn nhất đối với hành tinh của chúng ta",
    pronunciation: "/tu biː wʌn əv ðə ˈbɪɡɪst θrɛts/",
    example: "Climate change is one of the biggest threats.",
  },
  {
    id: "env-limit-warming",
    front: "to limit global warming",
    back: "hạn chế sự nóng lên toàn cầu",
    pronunciation: "/tu ˈlɪmɪt ˈɡləʊbl ˈwɔːmɪŋ/",
    example: "We must limit global warming to 1.5°C.",
  },
  {
    id: "env-extreme",
    front: "extreme weather events",
    back: "các hiện tượng thời tiết khắc nghiệt",
    pronunciation: "/ɪkˈstriːm ˈweðər ɪˈvɛnts/",
    example: "Extreme weather events are increasing.",
  },
  {
    id: "env-intense",
    front: "to become more intense",
    back: "trở nên dữ dội hơn",
    pronunciation: "/tu bɪˈkʌm mɔːr ɪnˈtɛns/",
    example: "Storms become more intense every year.",
  },
  {
    id: "env-contribute",
    front: "to make a significant contribution to ...",
    back: "đóng góp đáng kể vào",
    pronunciation: "/tu meɪk ə sɪɡˈnɪfɪkənt ˌkɒntrɪˈbjuːʃn/",
    example: "Renewable energy makes a significant contribution to reducing pollution.",
  },
  {
    id: "env-fuel-crisis",
    front: "to fuel the climate crisis",
    back: "thúc đẩy cuộc khủng hoảng khí hậu",
    pronunciation: "/tu ˈfjuːəl ðə ˈklaɪmət ˈkraɪsɪs/",
    example: "Fossil fuels fuel the climate crisis.",
  },
  {
    id: "env-brink",
    front: "to push precious wildlife closer to the brink of extinction",
    back: "đẩy động vật hoang dã quý giá đến gần bờ vực tuyệt chủng",
    pronunciation: "/tu pʊʃ/",
    example: "Pollution pushes wildlife closer to the brink of extinction.",
  },
  {
    id: "env-pledge",
    front: "to pledge urgent action",
    back: "cam kết hành động khẩn cấp",
    pronunciation: "/tu plɛdʒ ˈɜːdʒənt ˈækʃn/",
    example: "Nations pledged urgent action.",
  },
  {
    id: "env-sustainable",
    front: "to shift to more sustainable ways of farming",
    back: "chuyển sang các phương pháp canh tác bền vững hơn",
    pronunciation: "/tu ʃɪft/",
    example: "Farmers are shifting to sustainable methods.",
  },
  {
    id: "env-fossil",
    front: "to protect against investment in fossil fuels",
    back: "bảo vệ chống lại sự đầu tư vào nhiên liệu hóa thạch",
    pronunciation: "/tu prəˈtɛkt əˈɡɛnst/",
    example: "Stop investment in fossil fuels.",
  },
  {
    id: "env-impact",
    front: "to reduce your environmental impact",
    back: "giảm tác động môi trường của bạn",
    pronunciation: "/tu rɪˈdjuːs jɔːr ɪnˌvaɪərənˈmɛntl ˈɪmpækt/",
    example: "We can reduce our environmental impact.",
  },
  {
    id: "env-electric",
    front: "to switch from a regular petrol vehicle to an electric car",
    back: "chuyển từ xe chạy xăng thông thường sang xe điện",
    pronunciation: "/tu swɪtʃ/",
    example: "Many are switching to electric cars.",
  },
  {
    id: "env-trap-heat",
    front: "to trap heat in the atmosphere and warm the planet",
    back: "giữ nhiệt trong khí quyển và làm hành tinh ấm lên",
    pronunciation: "/tu træp hiːt/",
    example: "CO2 traps heat in the atmosphere.",
  },
  {
    id: "env-absorb",
    front: "to absorb CO2 from the atmosphere",
    back: "hấp thụ CO2 từ khí quyển",
    pronunciation: "/tu əbˈzɔːb siː tuː/",
    example: "Trees absorb CO2 from the atmosphere.",
  },
  {
    id: "env-call-action",
    front: "to call for urgent action on climate change",
    back: "kêu gọi hành động khẩn cấp về biến đổi khí hậu",
    pronunciation: "/tu kɔːl fɔːr/",
    example: "Leaders are calling for urgent action on climate change.",
  },
  {
    id: "env-fight-planet",
    front: "to fight for the health of our planet",
    back: "chiến đấu cho sức khỏe của hành tinh",
    pronunciation: "/tu faɪt fɔːr ðə hɛlθ əv aʊər ˈplænɪt/",
    example: "We must fight for the health of our planet.",
  },
  {
    id: "env-greenhouse",
    front: "the greenhouse gas effect",
    back: "hiệu ứng nhà kính",
    pronunciation: "/ðə ˈɡriːnhaʊs ɡæs ɪˈfɛkt/",
    example: "The greenhouse gas effect warms the planet.",
  },
  {
    id: "env-threat-life",
    front: "to pose a serious threat to life on earth",
    back: "đe dọa nghiêm trọng đến sự sống trên trái đất",
    pronunciation: "/tu pəʊz/",
    example: "Climate change poses a serious threat to life on earth.",
  },
  // Plastic pollution
  {
    id: "env-pressing",
    front: "pressing environmental issues",
    back: "các vấn đề môi trường cấp bách",
    pronunciation: "/ˈprɛsɪŋ/",
    example: "Plastic pollution is among the most pressing issues.",
  },
  {
    id: "env-disposable",
    front: "disposable plastic products / single-use plastics",
    back: "sản phẩm nhựa dùng một lần",
    pronunciation: "/dɪˈspəʊzəbl ˈplæstɪk ˈprɒdʌkts/",
    example: "Single-use plastics should be banned.",
  },
  {
    id: "env-garbage",
    front: "garbage collection systems",
    back: "hệ thống thu gom rác",
    pronunciation: "/ˈɡɑːbɪdʒ kəˈlɛkʃn ˈsɪstəmz/",
    example: "Garbage collection systems are essential.",
  },
  {
    id: "env-discarded",
    front: "discarded plastics",
    back: "các vật nhựa bị bỏ đi",
    pronunciation: "/dɪsˈkɑːdɪd ˈplæstɪks/",
    example: "Discarded plastics pollute oceans.",
  },
  {
    id: "env-global-plastic",
    front: "the global plastic waste crisis",
    back: "cuộc khủng hoảng rác thải nhựa toàn cầu",
    pronunciation: "/ðə ˈɡləʊbl ˈplæstɪk weɪst ˈkraɪsɪs/",
    example: "We face a global plastic waste crisis.",
  },
  {
    id: "env-float-ocean",
    front: "to float around the world's oceans",
    back: "trôi nổi khắp các đại dương trên thế giới",
    pronunciation: "/tu fləʊt əˈraʊnd ðə wɜːldz ˈəʊʃnz/",
    example: "Plastic floats around the world's oceans.",
  },
  {
    id: "env-marine",
    front: "to kill millions of marine animals",
    back: "giết hàng triệu động vật biển",
    pronunciation: "/tu kɪl ˈmɪljənz əv məˈriːn ˈænɪmlz/",
    example: "Plastic kills millions of marine animals.",
  },
  {
    id: "env-pose-threat",
    front: "to pose a serious threat to...",
    back: "đe dọa nghiêm trọng đến",
    pronunciation: "/tu pəʊz/",
    example: "Plastic poses a serious threat to marine life.",
  },
  {
    id: "env-mistake-food",
    front: "to mistake plastic for food",
    back: "nhầm nhựa với thức ăn",
    pronunciation: "/tu mɪsˈteɪk ˈplæstɪk fɔː fuːd/",
    example: "Turtles mistake plastic for food.",
  },
  {
    id: "env-detrimental",
    front: "to have detrimental effects on...",
    back: "có ảnh hưởng bất lợi lên",
    pronunciation: "/tu həv ˌdɛtrɪˈmɛntl ɪˈfɛkts/",
    example: "Pollution has detrimental effects on health.",
  },
  {
    id: "env-free-plastic",
    front: "a world free of plastic pollution",
    back: "một thế giới không ô nhiễm nhựa",
    pronunciation: "/ə wɜːld friː əv ˈplæstɪk pəˈluːʃn/",
    example: "We must build a world free of plastic pollution.",
  },
  {
    id: "env-integral-part",
    front: "to become an integral part of our daily life",
    back: "trở thành một phần không thể thiếu trong cuộc sống hàng ngày",
    pronunciation: "/tu bɪˈkʌm ən ˈɪntɪɡrəl pɑːt/",
    example: "Plastic has become an integral part of our daily life.",
  },
  {
    id: "env-victims",
    front: "the unfortunate victims of plastic pollution",
    back: "những nạn nhân bất hạnh của nạn ô nhiễm nhựa",
    pronunciation: "/ði ʌnˈfɔːtʃənət ˈvɪktɪmz/",
    example: "Sea creatures are the unfortunate victims of plastic pollution.",
  },
  {
    id: "env-entanglement",
    front: "to suffer from entanglement and ingestion of plastic debris",
    back: "bị vướng/mắc kẹt và nuốt phải mảnh vụn nhựa",
    pronunciation: "/tu ˈsʌfər frəm/",
    example: "Marine animals suffer from entanglement and ingestion of plastic debris.",
  },
  {
    id: "env-discharged",
    front: "to be discharged into ...",
    back: "bị thải ra",
    pronunciation: "/tu biː dɪsˈtʃɑːdʒd ˈɪntuː/",
    example: "Wastewater is discharged into rivers.",
  },
  {
    id: "env-contaminate",
    front: "to contaminate ...",
    back: "làm ô nhiễm",
    pronunciation: "/tu kənˈtæmɪneɪt/",
    example: "Plastic waste contaminates soil and water.",
  },
  {
    id: "env-cooperation",
    front: "the efforts and cooperation of...",
    back: "nỗ lực và sự hợp tác của",
    pronunciation: "/ði ˈɛfəts ənd kəʊˌɒpəˈreɪʃn/",
    example: "This requires the efforts and cooperation of politicians.",
  },
  // Synonyms for environment
  {
    id: "env-syn-warming",
    front: "global warming = increasing global temperatures",
    back: "nóng lên toàn cầu",
    pronunciation: "/ˈɡləʊbl ˈwɔːmɪŋ/",
    example: "Global warming is causing climate change.",
  },
  {
    id: "env-syn-damage",
    front: "cause severe damage to… = pose a serious threat to…",
    back: "gây hậu quả nặng nề cho / gây ra mối đe dọa nghiêm trọng cho",
    pronunciation: "/kɔːz sɪˈvɪər ˈdæmɪdʒ/",
    example: "Climate change causes severe damage to ecosystems.",
  },
  {
    id: "env-syn-extreme",
    front: "extreme weather events = natural disasters",
    back: "thời tiết khắc nghiệt / thảm họa tự nhiên",
    pronunciation: "/ɪkˈstriːm ˈweðər ɪˈvɛnts/",
    example: "Extreme weather events include blizzards and droughts.",
  },
  {
    id: "env-syn-degradation",
    front: "environmental damage = environmental degradation = environmental deterioration",
    back: "suy thoái môi trường",
    pronunciation: "/ɪnˌvaɪərənˈmɛntl ˌdɛɡrəˈdeɪʃn/",
    example: "Pollution causes environmental degradation.",
  },
  {
    id: "env-syn-emissions",
    front: "carbon emissions = heat-trapping gases = greenhouse gases = toxic gases",
    back: "khí thải carbon / khí thải nhà kính / khí thải độc",
    pronunciation: "/ˈkɑːbən ɪˈmɪʃnz/",
    example: "We must reduce carbon emissions.",
  },
  {
    id: "env-syn-fossil",
    front: "fossil fuels = petrol, oil and natural gas = non-renewable energy sources",
    back: "nhiên liệu hóa thạch / nguồn năng lượng không tái tạo",
    pronunciation: "/ˈfɒsl fjuːəlz/",
    example: "Fossil fuels cause pollution.",
  },
  {
    id: "env-syn-renewable",
    front:
      "renewable energy sources = environmentally-friendly energy sources = solar, wind or water power",
    back: "những nguồn năng lượng tái tạo được / thân thiện với môi trường / năng lượng nước, gió và mặt trời",
    pronunciation: "/rɪˈnjuːəbl ˈɛnədʒi sɔːsɪz/",
    example: "We should switch to renewable energy sources like solar, wind or water power.",
  },
  {
    id: "env-syn-deforest",
    front: "deforestation = forest clearance = cutting down trees illegally",
    back: "việc tàn phá rừng / việc chặt cây bất hợp pháp",
    pronunciation: "/diːˌfɒrɪˈsteɪʃn/",
    example: "Deforestation harms wildlife.",
  },
  {
    id: "env-syn-air",
    front: "air pollution = poor air quality",
    back: "ô nhiễm không khí / chất lượng không khí kém",
    pronunciation: "/eər pəˈluːʃn/",
    example: "Cities suffer from poor air quality.",
  },
  {
    id: "env-syn-waste",
    front: "a huge amount of waste = millions of tonnes of waste",
    back: "lượng chất thải khổng lồ",
    pronunciation: "/ə hjuːdʒ əˈmaʊnt əv weɪst/",
    example: "Cities produce a huge amount of waste.",
  },
  {
    id: "env-syn-cause",
    front: "cause… = lead to… = result in…",
    back: "gây ra vấn đề gì",
    pronunciation: "/kɔːz/",
    example: "Pollution causes many health issues.",
  },
  {
    id: "env-syn-responsible",
    front: "to be responsible for… = take the responsibility for…",
    back: "chịu trách nhiệm về vấn đề gì",
    pronunciation: "/tu biː rɪˈspɒnsəbl fɔːr/",
    example: "We are all responsible for protecting nature.",
  },
  {
    id: "env-syn-save",
    front: "save the earth = protect our planet = protect the environment",
    back: "bảo vệ trái đất",
    pronunciation: "/seɪv ði ɜːθ/",
    example: "We must protect our planet.",
  },
  {
    id: "env-syn-solve",
    front: "solve = tackle = address = mitigate",
    back: "giải quyết vấn đề gì",
    pronunciation: "/sɒlv/",
    example: "We must address climate change.",
  },
  {
    id: "env-syn-stricter",
    front: "impose stricter punishments on… = impose more stringent regulations on…",
    back: "áp đặt hình phạt / quy định chặt chẽ hơn lên",
    pronunciation: "/ɪmˈpəʊz ˈstrɪktə/",
    example: "Governments must impose stricter regulations.",
  },
  // GM food
  {
    id: "env-gm-cancer",
    front: "tomatoes and broccoli bursting with cancer-fighting chemicals",
    back: "cà chua và bông cải xanh chứa chất chống ung thư",
    pronunciation: "/tʊˈmeɪtəʊz ənd ˈbrɒkəli/",
    example: "GM tomatoes can contain cancer-fighting chemicals.",
  },
  {
    id: "env-gm-vitamin",
    front: "vitamin-enhanced crops of rice, sweet potatoes",
    back: "lúa, khoai lang được tăng cường thêm vitamin",
    pronunciation: "/ˈvɪtəmɪn ɪnˈhɑːnst krɒps/",
    example: "Vitamin-enhanced rice prevents blindness.",
  },
  {
    id: "env-gm-allergen",
    front: "wheat, soy and peanuts free of allergens / allergen-free peanuts",
    back: "lúa mì, đậu nành và đậu phộng không có chất gây dị ứng",
    pronunciation: "/ˈwiːt sɔɪ ənd ˈpiːnʌts friː əv ˈælədʒənz/",
    example: "Allergen-free peanuts could save lives.",
  },
  {
    id: "env-gm-vaccine",
    front: "bananas that deliver vaccines",
    back: "chuối cung cấp vắc-xin",
    pronunciation: "/bəˈnɑːnəz ðət dɪˈlɪvər vækˈsiːnz/",
    example: "Bananas may one day deliver vaccines.",
  },
  {
    id: "env-gm-therapeutic",
    front: "vegetable oils loaded with therapeutic ingredients",
    back: "dầu thực vật chứa các thành phần điều trị",
    pronunciation: "/ˈvɛdʒtəbl ɔɪlz/",
    example: "Vegetable oils can be loaded with therapeutic ingredients.",
  },
  {
    id: "env-gm-debate",
    front: "have become subjects of intense debate",
    back: "đã trở thành chủ đề tranh luận gay gắt",
    pronunciation: "/həv bɪˈkʌm ˈsʌbdʒɪkts əv ɪnˈtɛns dɪˈbeɪt/",
    example: "GM foods have become subjects of intense debate.",
  },
  {
    id: "env-gm",
    front: "genetically modified foods/crops/products = engineered plants",
    back: "thực phẩm/cây trồng/sản phẩm biến đổi gen",
    pronunciation: "/dʒəˈnɛtɪkli ˈmɒdɪfaɪd fuːdz/",
    example: "Genetically modified foods are controversial.",
  },
  {
    id: "env-gm-population",
    front: "the Earth's burgeoning population",
    back: "dân số Trái đất ngày càng tăng",
    pronunciation: "/ði ɜːθs ˈbɜːdʒənɪŋ ˌpɒpjʊˈleɪʃn/",
    example: "The Earth's burgeoning population strains resources.",
  },
  {
    id: "env-gm-variants",
    front: "to create new crop variants using irradiation and mutagenic chemicals",
    back: "tạo ra các biến thể cây trồng mới bằng cách sử dụng hóa chất chiếu xạ và gây đột biến",
    pronunciation: "/tu kriˈeɪt njuː krɒp ˈveəriənts/",
    example: "Scientists create new crop variants.",
  },
  {
    id: "env-gm-rigorous",
    front: "to do rigorous testing / be subjected to rigorous safety assessments",
    back: "kiểm tra nghiêm ngặt / phải trải qua những quy trình đánh giá an toàn nghiêm ngặt",
    pronunciation: "/tu duː ˈrɪɡərəs ˈtɛstɪŋ/",
    example: "GM foods undergo rigorous testing.",
  },
  {
    id: "env-gm-allergic",
    front: "to cause allergic reactions in humans",
    back: "gây ra phản ứng dị ứng ở người",
    pronunciation: "/tu kɔːz əˈlɜːdʒɪk riˈækʃnz/",
    example: "GM foods may cause allergic reactions.",
  },
  {
    id: "env-gm-pros-cons",
    front: "pros and cons",
    back: "lợi ích và bất lợi",
    pronunciation: "/prəʊz ənd kɒnz/",
    example: "Let's weigh the pros and cons.",
  },
  {
    id: "env-gm-genetic-mod",
    front: "genetic modification = the process of altering the genetic makeup of an organism",
    back: "phương pháp biến đổi gen",
    pronunciation: "/dʒəˈnɛtɪk ˌmɒdɪfɪˈkeɪʃn/",
    example: "Genetic modification alters the genetic makeup of organisms.",
  },
  {
    id: "env-gm-desirable",
    front: "desirable traits",
    back: "các đặc tính, đặc điểm mong muốn",
    pronunciation: "/dɪˈzaɪərəbl treɪts/",
    example: "GM foods are engineered with desirable traits.",
  },
  {
    id: "env-gm-yield",
    front: "yield (n)",
    back: "năng suất",
    pronunciation: "/jiːld/",
    example: "Higher yields benefit farmers.",
  },
  {
    id: "env-gm-gene",
    front: "gene (n)",
    back: "gen",
    pronunciation: "/dʒiːn/",
    example: "Genes control the traits of living things.",
  },
  {
    id: "env-gm-boost",
    front: "to boost something (v)",
    back: "tăng cường, thúc đẩy",
    pronunciation: "/tu buːst/",
    example: "Genetic engineering can boost crop yields.",
  },
  {
    id: "env-gm-resistance",
    front: "resistance to something (n)",
    back: "kháng lại",
    pronunciation: "/rɪˈzɪstəns/",
    example: "Plants develop resistance to disease.",
  },
  {
    id: "env-gm-tolerant",
    front: "tolerant (adj)",
    back: "có khả năng chống chịu",
    pronunciation: "/ˈtɒlərənt/",
    example: "These plants are tolerant of herbicides.",
  },
  {
    id: "env-gm-herbicide",
    front: "herbicide (n)",
    back: "thuốc diệt cỏ",
    pronunciation: "/ˈhɜːrbɪsaɪd/",
    example: "Farmers spray herbicide on unwanted plants.",
  },
  {
    id: "env-gm-defend",
    front: "to defend against something = to protect against something",
    back: "chống lại",
    pronunciation: "/tu dɪˈfɛnd əˈɡɛnst/",
    example: "We must defend against disease.",
  },
  {
    id: "env-gm-food-shortage",
    front: "to address the urgent problems of food shortage and hunger",
    back: "giải quyết các vấn đề cấp bách của tình trạng thiếu lương thực",
    pronunciation: "/tu əˈdrɛs/",
    example: "GM foods can address food shortage.",
  },
  {
    id: "env-gm-increase-yield",
    front: "to increase crop yields, offer crop varieties that resist pests and disease",
    back: "tăng năng suất cây trồng, cung cấp giống cây trồng kháng lại sâu bệnh",
    pronunciation: "/tu ɪnˈkriːs krɒp jiːldz/",
    example: "GM seeds resist pests and disease.",
  },
  {
    id: "env-gm-pesticide",
    front: "to reduce the use of pesticides",
    back: "giảm sử dụng thuốc trừ sâu",
    pronunciation: "/tu rɪˈdjuːs ðə juːs əv ˈpɛstɪsaɪdz/",
    example: "GM crops reduce the use of pesticides.",
  },
  {
    id: "env-gm-blindness",
    front:
      "to help solve some of the world's most vexing nutrition problems, like preventable blindness",
    back: "giúp giải quyết một số vấn đề dinh dưỡng khó giải quyết nhất, như mù lòa có thể phòng ngừa",
    pronunciation: "/tu hɛlp sɒlv/",
    example: "Golden rice helps solve preventable blindness.",
  },
  {
    id: "env-gm-extreme-conditions",
    front: "to be able to grow in places where non-GM crops die",
    back: "có thể phát triển ở những nơi cây trồng không biến đổi gen không phát triển được",
    pronunciation: "/tu biː ˈeɪbl tu ɡrəʊ/",
    example: "Some GM crops can grow in harsh conditions.",
  },
  {
    id: "env-gm-shelf-life",
    front: "to have a longer shelf life",
    back: "có thời hạn sử dụng lâu hơn",
    pronunciation: "/tu həv ə lɒŋɡər ʃɛlf laɪf/",
    example: "Some tomatoes have a longer shelf life.",
  },
  {
    id: "env-gm-negative-health",
    front: "the possibility to negatively affect human health",
    back: "khả năng ảnh hưởng tiêu cực đến sức khỏe con người",
    pronunciation: "/ðə ˌpɒsəˈbɪləti tu ˈnɛɡətɪvli əˈfɛkt/",
    example: "There is the possibility of negatively affecting health.",
  },
  {
    id: "env-gm-nutritional",
    front: "differences in nutritional content, allergic response, undesired side effects",
    back: "sự khác biệt về hàm lượng dinh dưỡng, phản ứng dị ứng, tác dụng phụ không mong muốn",
    pronunciation: "/ˈdɪfrənsɪz ɪn njuːˈtrɪʃənl ˈkɒntɛnt/",
    example: "GM foods may have differences in nutritional content.",
  },
  {
    id: "env-gm-gene-transfer",
    front: "to insert genes into an organism from an entirely different organism",
    back: "chèn gen vào một sinh vật từ một sinh vật hoàn toàn khác",
    pronunciation: "/tu ɪnˈsɜːt dʒiːnz ˈɪntuː/",
    example: "Gene transfer from one species to another raises concerns.",
  },
  // Global warming — additional synonyms từ PDF gốc
  {
    id: "env-syn-threatened",
    front:
      "the world's most threatened and endangered animals = animal species which are on the verge of extinction",
    back: "những loài động vật có nguy cơ tuyệt chủng cao nhất trên thế giới",
    pronunciation: "/ðə wɜːldz məʊst ˈθrɛtənd ənd ɪnˈdeɪndʒərd ˈænɪmlz/",
    example: "We must protect the world's most threatened and endangered animals.",
  },
  {
    id: "env-syn-important",
    front: "to be important = to play an important role",
    back: "đóng vai trò quan trọng",
    pronunciation: "/tu biː ɪmˈpɔːtənt/",
    example: "Forests play an important role in the ecosystem.",
  },
  // Plastic pollution — additional vocab từ PDF gốc
  {
    id: "env-pl-strangled",
    front: "to be strangled by...",
    back: "bị kẹt / siết bởi ...",
    pronunciation: "/tu biː ˈstræŋɡld baɪ/",
    example: "Sea turtles can be strangled by discarded fishing gear.",
  },
  {
    id: "env-pl-urge",
    front: "to reduce the urge to eat",
    back: "giảm ham muốn ăn uống",
    pronunciation: "/tu rɪˈdjuːs ði ɜːdʒ tu iːt/",
    example: "Plastic in their stomachs reduces the urge to eat.",
  },
  {
    id: "env-pl-break-down",
    front: "to break down into...",
    back: "phân hủy / vỡ ra thành...",
    pronunciation: "/tu breɪk daʊn ˈɪntuː/",
    example: "Plastic breaks down into microplastics.",
  },
  {
    id: "env-pl-packaging",
    front: "disposable packaging",
    back: "bao bì dùng một lần",
    pronunciation: "/dɪˈspəʊzəbl ˈpækɪdʒɪŋ/",
    example: "Disposable packaging creates a lot of waste.",
  },
  {
    id: "env-pl-work-towards",
    front: "to work towards...",
    back: "làm việc hướng tới ...",
    pronunciation: "/tu wɜːk təˈwɔːdz/",
    example: "We all need to work towards a cleaner future.",
  },
  // GM food — additional vocab từ PDF gốc
  {
    id: "env-gm-unanticipated",
    front: "to raise the possibility of unanticipated health effects",
    back: "nâng cao khả năng xảy ra các ảnh hưởng sức khỏe không lường trước được",
    pronunciation: "/tu reɪz ðə ˌpɒsəˈbɪləti əv ʌnˈæntɪsɪpeɪtɪd hɛlθ ɪˈfɛkts/",
    example: "Genetic modification raises the possibility of unanticipated health effects.",
  },
  {
    id: "env-gm-safety-consumption",
    front: "to enhance safety for human and animal consumption",
    back: "tăng cường an toàn cho việc tiêu thụ ở người và động vật",
    pronunciation: "/tu ɪnˈhɑːns ˈseɪfti fɔːr ˈhjuːmən ənd ˈænɪml kənˈsʌmpʃn/",
    example: "GM foods enhance safety for human and animal consumption.",
  },
  {
    id: "env-gm-soil-biodiversity",
    front: "to enhance soil fertility and crop biodiversity",
    back: "tăng cường độ phì nhiêu của đất và đa dạng sinh học cây trồng",
    pronunciation: "/tu ɪnˈhɑːns sɔɪl fɜːˈtɪləti ənd krɒp ˌbaɪəʊdaɪˈvɜːsəti/",
    example: "Crop rotation enhances soil fertility and crop biodiversity.",
  },
  {
    id: "env-gm-selectively-bred",
    front: "to be selectively bred over generations to have certain desired traits",
    back: "được lai tạo có chọn lọc qua các thế hệ để có những đặc điểm mong muốn nhất định",
    pronunciation: "/tu biː sɪˈlɛktɪvli brɛd/",
    example: "These crops are selectively bred to resist disease.",
  },
  {
    id: "env-gm-herbicide-weeds",
    front: "the potential development of herbicide-resistant weeds",
    back: "tiềm năng phát triển của cỏ dại kháng thuốc diệt cỏ",
    pronunciation: "/ðə pəˈtɛnʃl dɪˈvɛləpmənt/",
    example: "Herbicide-resistant weeds are a growing problem.",
  },
];

export { educationCards, environmentCards };
