import type { Flashcard } from "./types";

// ────────────────────────────────────────────────────────────────────────────
// SET 3 — FAMILY & RELATIONSHIPS (gộp: cohabitation + family + friendship)
// ────────────────────────────────────────────────────────────────────────────
const familyCards: Flashcard[] = [
  // ── COHABITATION ──
  {
    id: "fam-commit-marriage",
    front: "to fully commit to marriage",
    back: "cam kết hoàn toàn với hôn nhân",
    pronunciation: "/tu ˈfʊli kəˈmɪt tu ˈmærɪdʒ/",
    example: "Some people cohabit before they fully commit to marriage.",
  },
  {
    id: "fam-socially-acceptable",
    front: "to be socially acceptable",
    back: "được xã hội chấp nhận",
    pronunciation: "/tu biː ˈsəʊʃəli əkˈseptəbl/",
    example: "Living together is now socially acceptable.",
  },
  {
    id: "fam-reduce-divorce-risk",
    front: "to reduce the risk of divorce",
    back: "giảm nguy cơ ly hôn",
    pronunciation: "/tu rɪˈdjuːs ðə rɪsk əv dɪˈvɔːrs/",
    example: "Some hope that living together might reduce the risk of divorce.",
  },
  {
    id: "fam-cohabit",
    front: "to live together before marriage = to cohabit before marriage",
    back: "sống thử trước hôn nhân",
    pronunciation: "/tu kəʊˈhæbɪt bɪˈfɔːr ˈmærɪdʒ/",
    example: "Many couples choose to cohabit before marriage.",
  },
  {
    id: "fam-move-in",
    front: "to move in together",
    back: "dọn vào sống cùng nhau",
    pronunciation: "/tu muːv ɪn təˈɡeðər/",
    example: "They decided to move in together.",
  },
  {
    id: "fam-share-place",
    front: "to share a place with someone",
    back: "sống cùng ai đó",
    pronunciation: "/tu ʃeər ə pleɪs wɪð ˈsʌmwʌn/",
    example: "They share a place with two cats.",
  },
  {
    id: "fam-bring-up-issues",
    front: "to bring up a lot of issues",
    back: "xảy ra nhiều vấn đề",
    pronunciation: "/tu brɪŋ ʌp ə lɒt əv ˈɪʃuːz/",
    example: "Cohabitation may bring up a lot of issues.",
  },
  {
    id: "fam-put-to-test",
    front: "to put your relationship to the test",
    back: "thử thách mối quan hệ của bạn",
    pronunciation: "/tu pʊt jɔːr rɪˈleɪʃnʃɪp tu ðə test/",
    example: "Moving in together puts your relationship to the test.",
  },
  {
    id: "fam-same-page",
    front: "to be on the same page about something",
    back: "cùng chung suy nghĩ, ý tưởng (không bất đồng)",
    pronunciation: "/tu biː ɒn ðə seɪm peɪdʒ əˈbaʊt ˈsʌmθɪŋ/",
    example: "We need to be on the same page about money.",
  },
  {
    id: "fam-serious-relationship",
    front: "to be in a serious romantic relationship",
    back: "đang ở trong một mối quan hệ lãng mạn nghiêm túc",
    pronunciation: "/tu biː ɪn ə ˈsɪəriəs rəˈmæntɪk rɪˈleɪʃnʃɪp/",
    example: "They are in a serious romantic relationship.",
  },
  {
    id: "fam-stronger-bond",
    front: "to build a stronger bond",
    back: "xây dựng một mối quan hệ bền chặt hơn",
    pronunciation: "/tu bɪld ə ˈstrɒŋɡər bɒnd/",
    example: "Cohabitation can help build a stronger bond.",
  },
  {
    id: "fam-significant-other",
    front: "your significant other",
    back: "nửa kia của bạn",
    pronunciation: "/jɔːr sɪɡˈnɪfɪkənt ˈʌðər/",
    example: "I went on holiday with my significant other.",
  },
  {
    id: "fam-true-commitment",
    front: "a true commitment",
    back: "một sự cam kết thực sự",
    pronunciation: "/ə truː kəˈmɪtmənt/",
    example: "Marriage is a true commitment.",
  },
  {
    id: "fam-acceptance-cohab",
    front: "a greater acceptance of cohabitation",
    back: "sống thử trước hôn nhân được chấp nhận nhiều hơn",
    pronunciation: "/ə ˈɡreɪtər əkˈseptəns əv ˌkəʊˌhæbɪˈteɪʃn/",
    example: "There is now a greater acceptance of cohabitation.",
  },
  {
    id: "fam-social-norms",
    front: "changes in social norms",
    back: "những thay đổi trong các chuẩn mực xã hội",
    pronunciation: "/ˈtʃeɪndʒɪz ɪn ˈsəʊʃl nɔːmz/",
    example: "There have been changes in social norms.",
  },
  {
    id: "fam-cohabiting-couples",
    front: "cohabiting couples",
    back: "các cặp đôi đang sống thử trước hôn nhân",
    pronunciation: "/kəʊˈhæbɪtɪŋ ˈkʌplz/",
    example: "Cohabiting couples are increasing in number.",
  },
  {
    id: "fam-clear-boundaries",
    front: "to establish clear boundaries",
    back: "thiết lập ranh giới rõ ràng",
    pronunciation: "/tu ɪˈstæblɪʃ klɪər ˈbaʊndəriz/",
    example: "Couples should establish clear boundaries.",
  },
  {
    id: "fam-next-step",
    front: "to take the next step in your relationship",
    back: "thực hiện bước tiếp theo trong mối quan hệ",
    pronunciation: "/tu teɪk ðə nekst step ɪn jɔːr rɪˈleɪʃnʃɪp/",
    example: "Moving in together is taking the next step in your relationship.",
  },
  {
    id: "fam-ruin-relationship",
    front: "to ruin a relationship",
    back: "hủy hoại một mối quan hệ",
    pronunciation: "/tu ˈruːɪn ə rɪˈleɪʃnʃɪp/",
    example: "Some people think cohabitation ruins a relationship.",
  },
  // ── FAMILY vocabulary ──
  {
    id: "fam-laugh-together",
    front: "to have a laugh together",
    back: "cười cùng nhau",
    pronunciation: "/tu həv ə lɑːf təˈɡeðər/",
    example: "We always have a laugh together.",
  },
  {
    id: "fam-quality-time",
    front: "to spend quality time with your family",
    back: "dành thời gian chất lượng cùng gia đình",
    pronunciation: "/tu spend ˈkwɒləti taɪm wɪð jɔːr ˈfæməli/",
    example: "We should spend quality time with our family.",
  },
  {
    id: "fam-get-on",
    front: "to get on well with each other",
    back: "hòa thuận với nhau",
    pronunciation: "/tu ɡet ɒn wel wɪð iːtʃ ˈʌðər/",
    example: "They get on well with each other.",
  },
  {
    id: "fam-look-up-to",
    front: "to look up to my father",
    back: "noi gương cha tôi",
    pronunciation: "/tu lʊk ʌp tu maɪ ˈfɑːðər/",
    example: "I always look up to my father.",
  },
  {
    id: "fam-family-first",
    front: "to put your family first",
    back: "đặt gia đình của bạn lên trên hết",
    pronunciation: "/tu pʊt jɔːr ˈfæməli fɜːst/",
    example: "She puts her family first.",
  },
  {
    id: "fam-set-example",
    front: "to set a good example",
    back: "nêu gương tốt",
    pronunciation: "/tu set ə ɡʊd ɪɡˈzɑːmpl/",
    example: "Parents should set a good example.",
  },
  {
    id: "fam-balance-work",
    front: "to balance your work and home life",
    back: "cân bằng giữa công việc và cuộc sống gia đình",
    pronunciation: "/tu ˈbæləns jɔːr wɜːk ənd həʊm laɪf/",
    example: "It is hard to balance work and home life.",
  },
  {
    id: "fam-open-book",
    front: "to read someone like an open book",
    back: "hiểu rất rõ ai đó",
    pronunciation: "/tu riːd ˈsʌmwʌn laɪk ən ˈəʊpən bʊk/",
    example: "I can read her like an open book.",
  },
  {
    id: "fam-loving-family",
    front: "a loving and caring family",
    back: "một gia đình tràn đầy yêu thương và sự quan tâm",
    pronunciation: "/ə ˈlʌvɪŋ ənd ˈkeərɪŋ ˈfæməli/",
    example: "I grew up in a loving and caring family.",
  },
  {
    id: "fam-hang-out-together",
    front: "to hang out together",
    back: "cùng nhau đi chơi",
    pronunciation: "/tu hæŋ aʊt təˈɡeðər/",
    example: "We hang out together on weekends.",
  },
  {
    id: "fam-make-a-living",
    front: "to make a living",
    back: "kiếm sống",
    pronunciation: "/tu meɪk ə ˈlɪvɪŋ/",
    example: "He makes a living as a musician.",
  },
  // Family problems
  {
    id: "fam-infidelity",
    front: "infidelity",
    back: "sự không chung thủy (ngoại tính)",
    pronunciation: "/ˌɪnfɪˈdeləti/",
    example: "Infidelity can break a marriage.",
  },
  {
    id: "fam-separation",
    front: "separation",
    back: "ly thân",
    pronunciation: "/ˌsepəˈreɪʃn/",
    example: "They decided on a trial separation.",
  },
  {
    id: "fam-divorce",
    front: "divorce",
    back: "ly hôn",
    pronunciation: "/dɪˈvɔːrs/",
    example: "They got divorced after 10 years.",
  },
  {
    id: "fam-abuse",
    front: "abuse",
    back: "bạo hành gia đình",
    pronunciation: "/əˈbjuːs/",
    example: "Child abuse is a serious crime.",
  },
  {
    id: "fam-neglect",
    front: "neglect",
    back: "sự thờ ơ (cha mẹ đối với con cái)",
    pronunciation: "/nɪˈɡlekt/",
    example: "Neglect can harm children.",
  },
  {
    id: "fam-financial-problems",
    front: "financial problems",
    back: "các vấn đề tài chính",
    pronunciation: "/faɪˈnænʃl ˈprɒbləmz/",
    example: "Many families face financial problems.",
  },
  {
    id: "fam-no-communication",
    front: "lack of communication",
    back: "thiếu giao tiếp giữa vợ-chồng, cha mẹ-con cái",
    pronunciation: "/læk əv kəˌmjuːnɪˈkeɪʃn/",
    example: "Lack of communication is the root of many problems.",
  },
  // Idiom family
  {
    id: "fam-flesh-blood",
    front: "your own flesh and blood",
    back: "máu mủ",
    pronunciation: "/jɔːr əʊn fleʃ ənd blʌd/",
    example: "You should help your own flesh and blood.",
  },
  {
    id: "fam-cat-dog",
    front: "to fight like cat and dog",
    back: "cãi nhau như chó với mèo",
    pronunciation: "/tu faɪt laɪk kæt ənd dɒɡ/",
    example: "They fight like cat and dog.",
  },
  {
    id: "fam-no-love-lost",
    front: "there's little/no love lost between them",
    back: "không còn chút tình cảm nào",
    pronunciation: "/ðeərz ˈlɪtl nəʊ lʌv lɒst bɪˈtwiːn ðem/",
    example: "There's no love lost between them.",
  },
  {
    id: "fam-close-ranks",
    front: "close ranks",
    back: "sát cánh, đoàn kết",
    pronunciation: "/kləʊz ræŋks/",
    example: "The family closed ranks after the crisis.",
  },
  {
    id: "fam-turn-on",
    front: "turn on somebody",
    back: "tấn công ai đó",
    pronunciation: "/tɜːn ɒn ˈsʌmwʌn/",
    example: "He turned on his brother unexpectedly.",
  },
  {
    id: "fam-miserable-sin",
    front: "(as) miserable as sin",
    back: "khốn khổ",
    pronunciation: "/æz ˈmɪzrəbl əz sɪn/",
    example: "She felt miserable as sin.",
  },
  {
    id: "fam-take-for-granted",
    front: "take somebody for granted",
    back: "không trân trọng ai",
    pronunciation: "/teɪk ˈsʌmwʌn fɔːr ˈɡrɑːntɪd/",
    example: "Don't take your parents for granted.",
  },
  {
    id: "fam-blood-thicker",
    front: "blood is thicker than water",
    back: "một giọt máu đào hơn ao nước lã",
    pronunciation: "/blʌd ɪz ˈθɪkər ðən ˈwɔːtər/",
    example: "Blood is thicker than water: family comes first.",
  },
  {
    id: "fam-like-father",
    front: "like father, like son",
    back: "cha nào con nấy",
    pronunciation: "/laɪk ˈfɑːðər laɪk sʌn/",
    example: "Like father, like son.",
  },
  {
    id: "fam-run-family",
    front: "run in the family",
    back: "di truyền",
    pronunciation: "/rʌn ɪn ðə ˈfæməli/",
    example: "Baldness runs in the family.",
  },
  {
    id: "fam-black-sheep",
    front: "the black sheep of the family",
    back: "thành viên cá biệt trong gia đình",
    pronunciation: "/ðə blæk ʃiːp əv ðə ˈfæməli/",
    example: "He is the black sheep of the family.",
  },
  // ── FRIENDSHIP ──
  {
    id: "fam-stay-leave",
    front: "to stay even when everyone else has left",
    back: "ở lại ngay cả khi những người khác đã rời bỏ",
    pronunciation: "/tu steɪ ˈiːvn wen ˈevriwʌn els həz left/",
    example: "She stays even when everyone else has left.",
  },
  {
    id: "fam-never-alone",
    front: "to never let you feel that you're alone",
    back: "không bao giờ để bạn cảm thấy rằng bạn cô đơn",
    pronunciation: "/tu ˈnevər let ju fiːl ðət jɔːr əˈləʊn/",
    example: "A true friend never lets you feel that you're alone.",
  },
  {
    id: "fam-talk-behind-back",
    front: "never talk behind your back",
    back: "không bao giờ nói xấu sau lưng bạn",
    pronunciation: "/ˈnevər tɔːk bɪˈhaɪnd jɔːr bæk/",
    example: "A good friend never talks behind your back.",
  },
  {
    id: "fam-show-up",
    front: "to show up for friends",
    back: "có mặt khi bạn bè cần",
    pronunciation: "/tu ʃəʊ ʌp fɔː frendz/",
    example: "She shows up for her friends when they need her.",
  },
  {
    id: "fam-be-there",
    front: "to be there for you in any situation",
    back: "bên bạn trong bất kỳ hoàn cảnh nào",
    pronunciation: "/tu biː ðeə fɔːr ju ɪn ˈɛni ˌsɪtjʊˈeɪʃn/",
    example: "He is always there for you.",
  },
  {
    id: "fam-from-heart",
    front: "to speak openly from the heart",
    back: "những gì họ nói xuất phát từ chính trái tim",
    pronunciation: "/tu spiːk ˈəʊpnli frəm ðə hɑːt/",
    example: "She speaks openly from the heart.",
  },
  {
    id: "fam-keep-promises",
    front: "to keep their promises",
    back: "giữ lời hứa",
    pronunciation: "/tu kiːp ðeə ˈprɒmɪsɪz/",
    example: "A true friend always keeps their promises.",
  },
  {
    id: "fam-believe-potential",
    front: "to believe in your potential to reach your dreams",
    back: "tin tưởng vào tiềm năng đạt ước mơ của bạn",
    pronunciation: "/tu bɪˈliːv ɪn jɔːr pəˈtɛnʃl/",
    example: "She believes in your potential.",
  },
  {
    id: "fam-understand-needs",
    front: "to understand who you are and what you need",
    back: "thực sự hiểu bạn và biết bạn cần gì",
    pronunciation: "/tu ˌʌndəˈstænd huː ju ɑːr ənd wɒt ju niːd/",
    example: "He understands who I am.",
  },
  {
    id: "fam-thick-thin",
    front: "to be with you through thick and thin",
    back: "bên bạn trong bất kỳ hoàn cảnh nào",
    pronunciation: "/tu biː wɪð ju θruː θɪk ənd θɪn/",
    example: "She is with you through thick and thin.",
  },
  {
    id: "fam-click",
    front: "to click with somebody",
    back: "nhanh chóng trở thành bạn với ai đó",
    pronunciation: "/tu klɪk wɪð ˈsʌmwʌn/",
    example: "We just clicked instantly.",
  },
  {
    id: "fam-interests-heart",
    front: "to have someone's (best) interests at heart",
    back: "quan tâm tới ai đó, sẵn sàng giúp họ",
    pronunciation: "/tu həv ˈsʌmwʌnz best ˈɪntrəsts ət hɑːt/",
    example: "She has my best interests at heart.",
  },
  {
    id: "fam-hang-out",
    front: "to hang out",
    back: "đi chơi (với ai đó)",
    pronunciation: "/tu hæŋ aʊt/",
    example: "We hang out on weekends.",
  },
  {
    id: "fam-put-down",
    front: "to put somebody down",
    back: "chỉ trích ai đó",
    pronunciation: "/tu pʊt ˈsʌmwʌn daʊn/",
    example: "Don't put your friends down.",
  },
  {
    id: "fam-make-feel-bad",
    front: "to make somebody feel bad",
    back: "khiến ai đó cảm thấy tồi tệ",
    pronunciation: "/tu meɪk ˈsʌmwʌn fiːl bæd/",
    example: "I don't want to make you feel bad.",
  },
  {
    id: "fam-pretend",
    front: "to pretend",
    back: "giả vờ",
    pronunciation: "/tu prɪˈtend/",
    example: "Don't pretend to be someone else.",
  },
  {
    id: "fam-fit-in",
    front: "to fit in",
    back: "hòa nhập",
    pronunciation: "/tu fɪt ɪn/",
    example: "It takes time to fit in.",
  },
  {
    id: "fam-be-yourself",
    front: "to be yourself",
    back: "là chính mình",
    pronunciation: "/tu biː jɔːˈself/",
    example: "Just be yourself.",
  },
  {
    id: "fam-keep-promise",
    front: "to keep a promise",
    back: "giữ lời hứa",
    pronunciation: "/tu kiːp ə ˈprɒmɪs/",
    example: "Always keep a promise.",
  },
  {
    id: "fam-lie-to",
    front: "to lie to someone",
    back: "nói dối ai đó",
    pronunciation: "/tu laɪ tu ˈsʌmwʌn/",
    example: "Don't lie to your friends.",
  },
  // Friendship — additional vocab từ PDF gốc
  {
    id: "fam-get-your-back",
    front: "to get your back no matter what situation you're about to walk into",
    back: "hỗ trợ bạn trong bất kỳ hoàn cảnh nào",
    pronunciation: "/tu ɡet jɔːr bæk/",
    example: "Real friends get your back no matter what.",
  },
  {
    id: "fam-make-friends",
    front: "to make friends",
    back: "kết bạn",
    pronunciation: "/tu meɪk frendz/",
    example: "It's easy to make friends online.",
  },
  {
    id: "fam-find-similar",
    front: "to find people with similar interests",
    back: "tìm những người có sở thích giống bạn",
    pronunciation: "/tu faɪnd ˈpiːpl wɪð ˈsɪmɪlər ˈɪntrəsts/",
    example: "I found people with similar interests online.",
  },
  {
    id: "fam-give-hand",
    front: "to give others a hand",
    back: "giúp đỡ người khác",
    pronunciation: "/tu ɡɪv ˈʌðərz ə hænd/",
    example: "She always gives others a hand.",
  },
  {
    id: "fam-stand-by-you",
    front: "to stand by you",
    back: "ở bên cạnh bạn",
    pronunciation: "/tu stænd baɪ juː/",
    example: "He will stand by you forever.",
  },
  // Cohabitation — SYNONYMS section từ PDF gốc
  {
    id: "fam-sym-forge",
    front: "to forge a family",
    back: "xây dựng gia đình",
    pronunciation: "/tu fɔːdʒ ə ˈfæməli/",
    example: "They chose to forge a family without marriage.",
  },
  {
    id: "fam-sym-cohabitation",
    front: "cohabitation",
    back: "sống thử trước hôn nhân",
    pronunciation: "/ˌkəʊˌhæbɪˈteɪʃn/",
    example: "Cohabitation is becoming more common.",
  },
  {
    id: "fam-sym-fear",
    front: "the fear of...",
    back: "nỗi sợ...",
    pronunciation: "/ðə fɪər əv/",
    example: "The fear of divorce prevents many from marrying.",
  },
  {
    id: "fam-sym-possibility",
    front: "the possibility of...",
    back: "khả năng ... có thể xảy ra",
    pronunciation: "/ðə ˌpɒsəˈbɪləti əv/",
    example: "Consider the possibility of a relationship ending.",
  },
  {
    id: "fam-sym-collapse",
    front: "collapse",
    back: "sự tan vỡ / sụp đổ",
    pronunciation: "/kəˈlæps/",
    example: "The collapse of the marriage shocked everyone.",
  },
  {
    id: "fam-sym-drive",
    front: "to drive somebody to do something",
    back: "khiến ai đó làm gì",
    pronunciation: "/tu draɪv ˈsʌmwʌn/",
    example: "Fear drove him to cohabit rather than marry.",
  },
  {
    id: "fam-sym-move-in-with",
    front: "to move in with somebody",
    back: "dọn vào sống cùng với ai đó",
    pronunciation: "/tu muːv ɪn wɪð ˈsʌmwʌn/",
    example: "She moved in with him after dating for a year.",
  },
  {
    id: "fam-sym-pitfall",
    front: "pitfall",
    back: "cạm bẫy",
    pronunciation: "/ˈpɪtfɔːl/",
    example: "There are many pitfalls of cohabitation.",
  },
  {
    id: "fam-sym-divorce",
    front: "divorce",
    back: "ly hôn",
    pronunciation: "/dɪˈvɔːrs/",
    example: "Divorce rates are rising worldwide.",
  },
  {
    id: "fam-sym-worth",
    front: "to be worth something",
    back: "đáng (để làm gì)",
    pronunciation: "/tu biː wɜːrθ ˈsʌmθɪŋ/",
    example: "Marriage is worth the effort.",
  },
  {
    id: "fam-get-married",
    front: "to get married",
    back: "cưới, kết hôn",
    pronunciation: "/tu ɡet ˈmærɪd/",
    example: "They got married last summer.",
  },
  {
    id: "fam-account-for",
    front: "to account for something",
    back: "giải thích điều gì, là nguyên nhân của điều gì",
    pronunciation: "/tu əˈkaʊnt fɔːr ˈsʌmθɪŋ/",
    example: "Several factors account for the increase in divorce rates.",
  },
];

export { familyCards };
