import type { Flashcard } from "./types";

// ────────────────────────────────────────────────────────────────────────────
// SET 6 — DAILY ROUTINES & FREE TIME (gộp Daily Routines + Free Time)
// ────────────────────────────────────────────────────────────────────────────
const dailyLifeCards: Flashcard[] = [
  // Wake up
  {
    id: "dl-wake-up",
    front: "I usually wake up some time between 7-8 am",
    back: "Tôi thường thức dậy vào khoảng 7-8 giờ sáng",
    pronunciation: "/wɛɪk ʌp/",
    example: "I usually wake up some time between 7-8 am.",
  },
  {
    id: "dl-before-alarm",
    front: "I wake up around 7.30 am before the alarm goes off",
    back: "Tôi thức dậy vào khoảng 7h30 sáng trước khi chuông báo thức reo",
    pronunciation: "/bɪˈfɔːr ðə əˈlɑːm ɡəʊz ɒf/",
    example: "I woke up before the alarm went off.",
  },
  {
    id: "dl-set-alarm",
    front: "I set an alarm for 7.00 but I normally wake up before that",
    back: "Tôi đặt báo thức lúc 7 giờ nhưng tôi thường thức dậy trước đó",
    pronunciation: "/sɛt ən əˈlɑːm/",
    example: "She set an alarm for 7am.",
  },
  {
    id: "dl-sleeping-in",
    front: "I have a long history of sleeping in",
    back: "tôi có thói quen ngủ nướng",
    pronunciation: "/ˈsliːpɪŋ ɪn/",
    example: "I have a long history of sleeping in.",
  },
  {
    id: "dl-start-day",
    front: "I start my day by getting up around 6.30 am",
    back: "Tôi bắt đầu ngày mới lúc 6.30",
    pronunciation: "/stɑːt maɪ deɪ/",
    example: "I like to start my day early.",
  },
  // Activities
  {
    id: "dl-check-phone",
    front: "I check my phone first thing in the morning",
    back: "Điều đầu tiên tôi làm vào buổi sáng là check điện thoại",
    pronunciation: "/tʃɛk maɪ fəʊn/",
    example: "I check my phone first thing in the morning.",
  },
  {
    id: "dl-right-after",
    front: "I check my phone right after waking up",
    back: "Tôi check điện thoại ngay sau khi thức dậy",
    pronunciation: "/raɪt ˈɑːftər ˈweɪkɪŋ ʌp/",
    example: "Don't check your phone right after waking up.",
  },
  {
    id: "dl-emails",
    front: "to go through my emails",
    back: "xem qua email",
    pronunciation: "/tu ɡəʊ θruː maɪ ˈiːmeɪlz/",
    example: "I go through my emails every morning.",
  },
  {
    id: "dl-scroll",
    front: "to scroll through social media",
    back: "check mạng xã hội",
    pronunciation: "/tu skrəʊl θruː/",
    example: "She scrolls through social media for hours.",
  },
  {
    id: "dl-make-bed",
    front: "to make my bed",
    back: "gấp chăn mền / dọn giường",
    pronunciation: "/tu meɪk maɪ bɛd/",
    example: "Making the bed takes 30 seconds.",
  },
  {
    id: "dl-skincare",
    front: "to head to the bathroom to brush my teeth and do my morning skincare routine",
    back: "đi vào phòng tắm để đánh răng và thực hiện quy trình chăm sóc da buổi sáng",
    pronunciation: "/tu hɛd tu ðə ˈbɑːθruːm/",
    example: "She does her morning skincare routine.",
  },
  {
    id: "dl-yoga-clothes",
    front: "to get changed into my yoga clothes",
    back: "thay đồ tập yoga",
    pronunciation: "/tu ɡet tʃeɪndʒd ˈɪntuː/",
    example: "I get changed into my yoga clothes.",
  },
  {
    id: "dl-stretches",
    front: "to do some stretches",
    back: "tập một số động tác giúp giãn cơ",
    pronunciation: "/tu duː sʌm ˈstrɛtʃɪz/",
    example: "I do some stretches every morning.",
  },
  {
    id: "dl-yoga-meditation",
    front: "to do some yoga/meditation",
    back: "tập yoga / thiền",
    pronunciation: "/tu duː sʌm ˈjəʊɡə/",
    example: "She does yoga every morning.",
  },
  {
    id: "dl-downstairs",
    front: "to head downstairs to work out",
    back: "đi xuống lầu để tập thể dục",
    pronunciation: "/tu hɛd daʊnˈsteəz/",
    example: "He headed downstairs to work out.",
  },
  {
    id: "dl-exercises",
    front: "to do some simple physical exercises",
    back: "tập vài bài tập đơn giản",
    pronunciation: "/tu duː sʌm ˈsɪmpl ˈfɪzɪkl ˈɛksəsaɪzɪz/",
    example: "Doing simple exercises is good for health.",
  },
  {
    id: "dl-breakfast",
    front: "to make and eat breakfast",
    back: "chuẩn bị & ăn sáng",
    pronunciation: "/tu meɪk ənd iːt ˈbrɛkfəst/",
    example: "He makes and eats breakfast quickly.",
  },
  {
    id: "dl-water",
    front: "to drink a glass of lukewarm water",
    back: "uống một ly nước ấm",
    pronunciation: "/tu drɪŋk ə ɡlɑːs əv ˈluːkwɔːm ˈwɔːtər/",
    example: "Drinking lukewarm water boosts metabolism.",
  },
  {
    id: "dl-warm-drink",
    front: "to have something warm to drink on an empty stomach",
    back: "uống thứ gì đó ấm khi bụng đói",
    pronunciation: "/tu həv ˈsʌmθɪŋ wɔːm/",
    example: "Don't drink coffee on an empty stomach.",
  },
  {
    id: "dl-self-help",
    front: "to read a self-help book to keep me motivated",
    back: "đọc sách self-help để có động lực",
    pronunciation: "/tu riːd ə sɛlf hɛlp bʊk/",
    example: "I read a self-help book every morning.",
  },
  {
    id: "dl-dogs",
    front: "to take my dogs out for a walk",
    back: "dắt chó đi dạo",
    pronunciation: "/tu teɪk maɪ dɒɡz aʊt fɔːr ə wɔːk/",
    example: "I take my dogs out every morning.",
  },
  {
    id: "dl-coffee",
    front: "to make my favourite morning coffee",
    back: "pha món cà phê yêu thích",
    pronunciation: "/tu meɪk maɪ ˈfeɪvərɪt ˈmɔːnɪŋ ˈkɒfi/",
    example: "She makes her morning coffee first.",
  },
  // Free time general
  {
    id: "dl-spare-time",
    front: "free time/spare time",
    back: "thời gian rảnh",
    pronunciation: "/friː taɪm/",
    example: "I have very little spare time.",
  },
  {
    id: "dl-me-time",
    front: 'to have a little "me time"',
    back: "có một chút thời gian dành cho riêng mình",
    pronunciation: "/tu həv ə ˈlɪtl miː taɪm/",
    example: "Everyone needs some me time.",
  },
  {
    id: "dl-most-free",
    front: "to make the most of your free time",
    back: "tận dụng tối đa thời gian rảnh",
    pronunciation: "/tu meɪk ðə məʊst əv jɔːr friː taɪm/",
    example: "Make the most of your free time.",
  },
  {
    id: "dl-make-time",
    front: "to make time for yourself",
    back: "dành thời gian cho chính mình",
    pronunciation: "/tu meɪk taɪm fɔːr jɔːˈself/",
    example: "Make time for yourself every day.",
  },
  {
    id: "dl-productive-free",
    front: "to spend your free time in a productive way",
    back: "dành thời gian rảnh một cách hiệu quả",
    pronunciation: "/tu spɛnd jɔːr friː taɪm ɪn ə prəˈdʌktɪv weɪ/",
    example: "Spend your free time in a productive way.",
  },
  {
    id: "dl-schedule-free",
    front: "to schedule your free time",
    back: "lên kế hoạch cho thời gian rảnh",
    pronunciation: "/tu ˈskɛdʒuːl/",
    example: "Schedule your free time to relax properly.",
  },
  {
    id: "dl-priority",
    front: "to make something a priority",
    back: "ưu tiên điều gì",
    pronunciation: "/tu meɪk ˈsʌmθɪŋ ə praɪˈɒrəti/",
    example: "You should make family a priority.",
  },
  {
    id: "dl-better-use",
    front: "to be put in better use",
    back: "được sử dụng tốt hơn",
    pronunciation: "/tu biː pʊt ɪn ˈbɛtər juːs/",
    example: "Money should be put to better use.",
  },
  {
    id: "dl-set-aside",
    front: "to set aside your free time",
    back: "dành một khoảng thời gian cho bản thân",
    pronunciation: "/tu sɛt əˈsaɪd/",
    example: "Set aside an hour for yourself.",
  },
  // Free time activities
  {
    id: "dl-read",
    front: "read a book",
    back: "đọc sách",
    pronunciation: "/riːd ə bʊk/",
    example: "I read a book in my free time.",
  },
  {
    id: "dl-hang-friends",
    front: "to hang out with friends",
    back: "đi chơi với bạn bè",
    pronunciation: "/tu hæŋ aʊt wɪð frendz/",
    example: "We hang out with friends on weekends.",
  },
  {
    id: "dl-walk",
    front: "to go for a walk",
    back: "đi dạo",
    pronunciation: "/tu ɡəʊ fɔːr ə wɔːk/",
    example: "I go for a walk after dinner.",
  },
  {
    id: "dl-bath",
    front: "to take a bath",
    back: "tắm",
    pronunciation: "/tu teɪk ə bɑːθ/",
    example: "I take a bath to relax.",
  },
  {
    id: "dl-paint-nails",
    front: "to paint your nails",
    back: "sơn móng tay",
    pronunciation: "/tu peɪnt jɔːr neɪlz/",
    example: "She paints her nails every Sunday.",
  },
  {
    id: "dl-shop-outfit",
    front: "to go shopping for a new outfit",
    back: "mua một bộ đồ mới",
    pronunciation: "/tu ɡəʊ ˈʃɒpɪŋ/",
    example: "I went shopping for a new outfit.",
  },
  {
    id: "dl-bake",
    front: "to bake a cake",
    back: "nướng bánh",
    pronunciation: "/tu beɪk ə keɪk/",
    example: "She bakes a cake on Sundays.",
  },
  {
    id: "dl-call-old",
    front: "to call an old friend",
    back: "gọi cho một người bạn cũ",
    pronunciation: "/tu kɔːl ən əʊld frend/",
    example: "I called an old friend last night.",
  },
  {
    id: "dl-music",
    front: "to play a musical instrument",
    back: "chơi một nhạc cụ",
    pronunciation: "/tu pleɪ ə ˈmjuːzɪkl ˈɪnstrəmənt/",
    example: "He plays the guitar in his free time.",
  },
  // Idioms
  {
    id: "dl-culture-vulture",
    front: "culture vulture",
    back: "người yêu thích các loại hình văn hóa",
    pronunciation: "/ˈkʌltʃər ˈvʌltʃər/",
    example: "She's a real culture vulture.",
  },
  {
    id: "dl-couch-potato",
    front: "couch potato",
    back: "người có lối sống thụ động",
    pronunciation: "/kaʊtʃ pəˈteɪtəʊ/",
    example: "He is a typical couch potato.",
  },
  {
    id: "dl-lock-away",
    front: "to lock yourself away",
    back: "cô lập với thế giới bên ngoài",
    pronunciation: "/tu lɒk jɔːˈself əˈweɪ/",
    example: "She locks herself away in her room.",
  },
  {
    id: "dl-hooked",
    front: "to be hooked on",
    back: "nghiện",
    pronunciation: "/tu biː hʊkt ɒn/",
    example: "He is hooked on motor racing.",
  },
  {
    id: "dl-chill-out",
    front: "to chill out",
    back: "thư giãn, xả hơi",
    pronunciation: "/tu tʃɪl aʊt/",
    example: "I need to chill out this weekend.",
  },
  {
    id: "dl-come-round",
    front: "to come round",
    back: "đến nhà ai",
    pronunciation: "/tu kʌm raʊnd/",
    example: "Why don't you come round?",
  },
  {
    id: "dl-get-up-to",
    front: "to get up to",
    back: "làm (gì đó)",
    pronunciation: "/tu ɡet ʌp tu/",
    example: "What did you get up to at the weekend?",
  },
  {
    id: "dl-catch-up",
    front: "to catch up with",
    back: "bắt kịp, theo kịp (tin tức)",
    pronunciation: "/tu kætʃ ʌp wɪð/",
    example: "Let's catch up over coffee.",
  },
  {
    id: "dl-into",
    front: "to be into",
    back: "thích",
    pronunciation: "/tu biː ˈɪntuː/",
    example: "She's really into jazz.",
  },
  {
    id: "dl-let-hair-down",
    front: "to let your hair down",
    back: "thư giãn, xõa",
    pronunciation: "/tu lɛt jɔːr heər daʊn/",
    example: "It's time to let your hair down.",
  },
  {
    id: "dl-time-flies",
    front: "time flies",
    back: "thời gian trôi nhanh quá",
    pronunciation: "/taɪm flaɪz/",
    example: "Time flies when you're having fun.",
  },
  {
    id: "dl-time-money",
    front: "time is money",
    back: "thời gian đáng giá như tiền",
    pronunciation: "/taɪm ɪz ˈmʌni/",
    example: "Hurry up, time is money!",
  },
  {
    id: "dl-rough-time",
    front: "to have/ go through a rough/ hard/ tough time",
    back: "trải qua giai đoạn khó khăn",
    pronunciation: "/tu həv ə rʌf taɪm/",
    example: "She went through a tough time.",
  },
  {
    id: "dl-pressed-time",
    front: "to be pressed for time",
    back: "vội, bị thúc bách về thời gian",
    pronunciation: "/tu biː prɛst fɔːr taɪm/",
    example: "I'm pressed for time today.",
  },
  {
    id: "dl-blue-moon",
    front: "once in a blue moon",
    back: "hiếm khi",
    pronunciation: "/wʌns ɪn ə bluː muːn/",
    example: "We meet once in a blue moon.",
  },
  {
    id: "dl-weight-mind",
    front: "to take the weight off your mind",
    back: "trút bỏ gánh nặng",
    pronunciation: "/tu teɪk ðə weɪt ɒf jɔːr maɪnd/",
    example: "It really took the weight off my mind.",
  },
  // Other useful
  {
    id: "dl-rise-shine",
    front: "rise and shine",
    back: "thức dậy tràn trề năng lượng",
    pronunciation: "/raɪz ənd ʃaɪn/",
    example: "Rise and shine, sleepyhead!",
  },
  {
    id: "dl-hit-books",
    front: "to hit the books",
    back: "cắm đầu vào học",
    pronunciation: "/tu hɪt ðə bʊks/",
    example: "I need to hit the books tonight.",
  },
  {
    id: "dl-check-up",
    front: "to check up on somebody",
    back: "kiểm tra xem ai đó đang làm đúng việc không",
    pronunciation: "/tu tʃɛk ʌp ɒn ˈsʌmwʌn/",
    example: "She checks up on her parents every day.",
  },
  {
    id: "dl-look-through",
    front: "to look through",
    back: "lướt nhanh",
    pronunciation: "/tu lʊk θruː/",
    example: "I looked through the magazine quickly.",
  },
  {
    id: "dl-warm-up",
    front: "to warm up",
    back: "khởi động",
    pronunciation: "/tu wɔːm ʌp/",
    example: "Always warm up before exercising.",
  },
  {
    id: "dl-meet-up",
    front: "to meet up with",
    back: "gặp ai",
    pronunciation: "/tu miːt ʌp wɪð/",
    example: "Let's meet up after work.",
  },
  {
    id: "dl-set-off",
    front: "to set off",
    back: "bắt đầu làm gì",
    pronunciation: "/tu sɛt ɒf/",
    example: "We set off at 6am.",
  },
  {
    id: "dl-tidy-up",
    front: "to tidy up",
    back: "dọn dẹp",
    pronunciation: "/tu ˈtaɪdi ʌp/",
    example: "Tidy up your room!",
  },
  {
    id: "dl-start-right",
    front: "to start your day right",
    back: "bắt đầu một ngày mới đúng cách",
    pronunciation: "/tu stɑːt jɔːr deɪ raɪt/",
    example: "Drink water to start your day right.",
  },
  {
    id: "dl-mind-ready",
    front: "to get my mind ready for the day",
    back: "chuẩn bị tâm trí cho ngày mới",
    pronunciation: "/tu ɡet maɪ maɪnd ˈredi/",
    example: "I meditate to get my mind ready for the day.",
  },
  {
    id: "dl-early-bird",
    front: "an early bird/ a morning person",
    back: "người có thói quen dậy sớm",
    pronunciation: "/ən ˈɜːli bɜːd/",
    example: "She's an early bird.",
  },
  {
    id: "dl-night-owl",
    front: "a night owl",
    back: "người có thói quen thức khuya",
    pronunciation: "/ə naɪt aʊl/",
    example: "I'm a night owl.",
  },
  {
    id: "dl-plenty-time",
    front: "to give myself plenty of time to ...",
    back: "cho tôi nhiều thời gian để làm gì",
    pronunciation: "/tu ɡɪv maɪˈsɛlf ˈplɛnti əv taɪm/",
    example: "Give yourself plenty of time to relax.",
  },
  {
    id: "dl-kick-start",
    front: "to kick start your day",
    back: "bắt đầu ngày mới của bạn",
    pronunciation: "/tu kɪk stɑːt/",
    example: "Coffee kick starts my day.",
  },
  {
    id: "dl-playlist",
    front: "to put on a good playlist",
    back: "mở một list nhạc hay",
    pronunciation: "/tu pʊt ɒn ə ɡʊd ˈpleɪlɪst/",
    example: "Put on a good playlist while you work.",
  },
  {
    id: "dl-productive-morning",
    front: "a productive morning routine",
    back: "thói quen buổi sáng hiệu quả",
    pronunciation: "/ə prəˈdʌktɪv ˈmɔːnɪŋ ruːˈtiːn/",
    example: "Build a productive morning routine.",
  },
  {
    id: "dl-sense-productivity",
    front: "to feel a sense of productivity",
    back: "cảm thấy mình làm việc có năng suất",
    pronunciation: "/tu fiːl ə sɛns əv ˌprɒdʌkˈtɪvəti/",
    example: "I feel a sense of productivity when I exercise.",
  },
  {
    id: "dl-nighttime",
    front: "a nighttime ritual",
    back: "thói quen các việc mình thường làm trước khi ngủ",
    pronunciation: "/ə ˈnaɪttaɪm ˈrɪtʃʊəl/",
    example: "Reading is part of my nighttime ritual.",
  },
  // Importance
  {
    id: "dl-reduce-stress",
    front: "to reduce stress levels",
    back: "giảm căng thẳng",
    pronunciation: "/tu rɪˈdjuːs strɛs ˈlɛvlz/",
    example: "Yoga helps reduce stress levels.",
  },
  {
    id: "dl-refreshed",
    front: "to feel refreshed",
    back: "cảm thấy sảng khoái",
    pronunciation: "/tu fiːl rɪˈfrɛʃt/",
    example: "I feel refreshed after a good night's sleep.",
  },
  {
    id: "dl-forget-worries",
    front: "to forget your everyday worries",
    back: "quên đi những lo lắng hàng ngày",
    pronunciation: "/tu fəˈɡɛt jɔːr ˈɛvrɪdeɪ ˈwʌriz/",
    example: "Free time helps forget everyday worries.",
  },
  {
    id: "dl-calm-down",
    front: "to calm you down",
    back: "bình tĩnh lại, bớt lo lắng",
    pronunciation: "/tu kɑːm ju daʊn/",
    example: "Music calms me down.",
  },
  {
    id: "dl-recharge",
    front: "to recharge your mind and body",
    back: "nạp năng lượng cho tâm trí và cơ thể",
    pronunciation: "/tu ˌriːˈtʃɑːdʒ jɔːr maɪnd ənd ˈbɒdi/",
    example: "I take a vacation to recharge.",
  },
  // Free Time — additional vocab từ PDF gốc
  {
    id: "dl-bit-spare",
    front: "to have a bit of spare time",
    back: "có một chút thời gian rảnh rỗi",
    pronunciation: "/tu həv ə bɪt əv speə taɪm/",
    example: "I have a bit of spare time this afternoon.",
  },
  {
    id: "dl-hang-out-with-someone",
    front: "to hang out with someone",
    back: "đi chơi với ai đó",
    pronunciation: "/tu hæŋ aʊt wɪð ˈsʌmwʌn/",
    example: "I love to hang out with someone on weekends.",
  },
];

export { dailyLifeCards };
