import { FlashcardSet } from "./types";
import { builtinZhFoodSets, getBuiltinZhFoodSet } from "./flashcards-zh-food";

/** Built-in flashcard sets shipped with the app. User can add more via the
 *  import-CSV flow on the /flashcards hub page. */
export const builtinFlashcardSets: FlashcardSet[] = [
  ...builtinZhFoodSets,
  {
    id: "builtin:ielts-100-core",
    name: "IELTS 100 từ vựng cốt lõi",
    description: "100 từ vựng xuất hiện nhiều nhất trong IELTS Academic Reading & Writing",
    icon: "globe",
    color: "#2563eb",
    builtin: true,
    cards: [
      { id: "ielts-1", front: "analyse", back: "phân tích", pronunciation: "/ˈænəlaɪz/", example: "The study analyses data from 500 participants." },
      { id: "ielts-2", front: "approach", back: "phương pháp, cách tiếp cận", pronunciation: "/əˈproʊtʃ/", example: "We need a new approach to this problem." },
      { id: "ielts-3", front: "assess", back: "đánh giá, ước lượng", pronunciation: "/əˈses/", example: "Teachers assess students' progress regularly." },
      { id: "ielts-4", front: "assume", back: "giả định, cho rằng", pronunciation: "/əˈsuːm/", example: "I assume you've already read the report." },
      { id: "ielts-5", front: "available", back: "có sẵn, khả dụng", pronunciation: "/əˈveɪləbl/", example: "Tickets are available at the door." },
      { id: "ielts-6", front: "benefit", back: "lợi ích", pronunciation: "/ˈbenɪfɪt/", example: "Regular exercise has many health benefits." },
      { id: "ielts-7", front: "concept", back: "khái niệm", pronunciation: "/ˈkɒnsept/", example: "The concept of time is complex." },
      { id: "ielts-8", front: "conclude", back: "kết luận", pronunciation: "/kənˈkluːd/", example: "The report concludes that more research is needed." },
      { id: "ielts-9", front: "conduct", back: "tiến hành, thực hiện", pronunciation: "/kənˈdʌkt/", example: "They conducted a survey last month." },
      { id: "ielts-10", front: "consequence", back: "hậu quả", pronunciation: "/ˈkɒnsɪkwəns/", example: "Actions have consequences." },
      { id: "ielts-11", front: "consider", back: "cân nhắc, xem xét", pronunciation: "/kənˈsɪdər/", example: "Please consider my proposal carefully." },
      { id: "ielts-12", front: "consist", back: "bao gồm, gồm có", pronunciation: "/kənˈsɪst/", example: "Water consists of hydrogen and oxygen." },
      { id: "ielts-13", front: "consume", back: "tiêu thụ, sử dụng", pronunciation: "/kənˈsuːm/", example: "Cars consume a lot of fuel." },
      { id: "ielts-14", front: "context", back: "bối cảnh, ngữ cảnh", pronunciation: "/ˈkɒntekst/", example: "Consider the historical context of the event." },
      { id: "ielts-15", front: "contribute", back: "đóng góp", pronunciation: "/kənˈtrɪbjuːt/", example: "Many factors contribute to climate change." },
      { id: "ielts-16", front: "create", back: "tạo ra, sáng tạo", pronunciation: "/kriˈeɪt/", example: "Artists create beauty from nothing." },
      { id: "ielts-17", front: "data", back: "dữ liệu", pronunciation: "/ˈdeɪtə/", example: "We need more data to draw conclusions." },
      { id: "ielts-18", front: "define", back: "định nghĩa", pronunciation: "/dɪˈfaɪn/", example: "Can you define this word?" },
      { id: "ielts-19", front: "demonstrate", back: "chứng minh, thể hiện", pronunciation: "/ˈdemənstreɪt/", example: "The results demonstrate the theory." },
      { id: "ielts-20", front: "derive", back: "suy ra, bắt nguồn", pronunciation: "/dɪˈraɪv/", example: "Many English words derive from Latin." },
      { id: "ielts-21", front: "develop", back: "phát triển", pronunciation: "/dɪˈveləp/", example: "The company plans to develop new products." },
      { id: "ielts-22", front: "distribute", back: "phân phối, phân tán", pronunciation: "/dɪˈstrɪbjuːt/", example: "Volunteers distributed food to the homeless." },
      { id: "ielts-23", front: "economy", back: "nền kinh tế", pronunciation: "/ɪˈkɒnəmi/", example: "The economy is growing rapidly." },
      { id: "ielts-24", front: "effect", back: "tác động, ảnh hưởng", pronunciation: "/ɪˈfekt/", example: "The effect of the medicine was immediate." },
      { id: "ielts-25", front: "element", back: "yếu tố, nguyên tố", pronunciation: "/ˈelɪmənt/", example: "Trust is an essential element of friendship." },
      { id: "ielts-26", front: "environment", back: "môi trường", pronunciation: "/ɪnˈvaɪrənmənt/", example: "We must protect the environment." },
      { id: "ielts-27", front: "establish", back: "thành lập, thiết lập", pronunciation: "/ɪˈstæblɪʃ/", example: "The school was established in 1950." },
      { id: "ielts-28", front: "estimate", back: "ước tính", pronunciation: "/ˈestɪmeɪt/", example: "We estimate the cost at $10,000." },
      { id: "ielts-29", front: "evaluate", back: "đánh giá", pronunciation: "/ɪˈvæljueɪt/", example: "Let's evaluate the options carefully." },
      { id: "ielts-30", front: "evidence", back: "bằng chứng, chứng cứ", pronunciation: "/ˈevɪdəns/", example: "There is strong evidence for this claim." },
      { id: "ielts-31", front: "factor", back: "yếu tố", pronunciation: "/ˈfæktər/", example: "Many factors influence the outcome." },
      { id: "ielts-32", front: "feature", back: "đặc điểm, tính năng", pronunciation: "/ˈfiːtʃər/", example: "This phone has many useful features." },
      { id: "ielts-33", front: "function", back: "chức năng, hoạt động", pronunciation: "/ˈfʌŋkʃn/", example: "What is the function of this button?" },
      { id: "ielts-34", front: "impact", back: "tác động mạnh", pronunciation: "/ˈɪmpækt/", example: "The accident had a huge impact on him." },
      { id: "ielts-35", front: "indicate", back: "chỉ ra, cho thấy", pronunciation: "/ˈɪndɪkeɪt/", example: "The data indicates a positive trend." },
      { id: "ielts-36", front: "individual", back: "cá nhân", pronunciation: "/ˌɪndɪˈvɪdʒuəl/", example: "Each individual has unique needs." },
      { id: "ielts-37", front: "influence", back: "ảnh hưởng", pronunciation: "/ˈɪnfluəns/", example: "Friends influence our behavior." },
      { id: "ielts-38", front: "interpret", back: "diễn giải, giải thích", pronunciation: "/ɪnˈtɜːprɪt/", example: "How do you interpret this poem?" },
      { id: "ielts-39", front: "involve", back: "liên quan, bao gồm", pronunciation: "/ɪnˈvɒlv/", example: "The job involves traveling." },
      { id: "ielts-40", front: "issue", back: "vấn đề, phát hành", pronunciation: "/ˈɪʃuː/", example: "Climate change is a serious issue." },
      { id: "ielts-41", front: "method", back: "phương pháp", pronunciation: "/ˈmeθəd/", example: "We need a better method for this." },
      { id: "ielts-42", front: "obtain", back: "thu được, đạt được", pronunciation: "/əbˈteɪn/", example: "She obtained a degree in biology." },
      { id: "ielts-43", front: "occur", back: "xảy ra", pronunciation: "/əˈkɜːr/", example: "Earthquakes occur frequently in this area." },
      { id: "ielts-44", front: "percent", back: "phần trăm", pronunciation: "/pəˈsent/", example: "Twenty percent of students passed." },
      { id: "ielts-45", front: "period", back: "giai đoạn, thời kỳ", pronunciation: "/ˈpɪriəd/", example: "The study covers a 5-year period." },
      { id: "ielts-46", front: "policy", back: "chính sách", pronunciation: "/ˈpɒləsi/", example: "The government introduced a new policy." },
      { id: "ielts-47", front: "principle", back: "nguyên tắc", pronunciation: "/ˈprɪnsəpl/", example: "Honesty is an important principle." },
      { id: "ielts-48", front: "process", back: "quá trình", pronunciation: "/ˈprəʊses/", example: "Learning is a continuous process." },
      { id: "ielts-49", front: "produce", back: "sản xuất, tạo ra", pronunciation: "/prəˈdjuːs/", example: "The factory produces 1000 cars a day." },
      { id: "ielts-50", front: "proportion", back: "tỷ lệ", pronunciation: "/prəˈpɔːʃn/", example: "A large proportion of students live on campus." },
      { id: "ielts-51", front: "provide", back: "cung cấp", pronunciation: "/prəˈvaɪd/", example: "The school provides free lunches." },
      { id: "ielts-52", front: "purpose", back: "mục đích", pronunciation: "/ˈpɜːpəs/", example: "What is the purpose of your visit?" },
      { id: "ielts-53", front: "react", back: "phản ứng", pronunciation: "/riˈækt/", example: "How did she react to the news?" },
      { id: "ielts-54", front: "reduce", back: "giảm", pronunciation: "/rɪˈdjuːs/", example: "We need to reduce waste." },
      { id: "ielts-55", front: "refer", back: "tham chiếu, đề cập", pronunciation: "/rɪˈfɜːr/", example: "Please refer to the manual." },
      { id: "ielts-56", front: "reflect", back: "phản ánh", pronunciation: "/rɪˈflekt/", example: "Her eyes reflected the sunset." },
      { id: "ielts-57", front: "regard", back: "coi như, đánh giá", pronunciation: "/rɪˈɡɑːd/", example: "I regard him as a friend." },
      { id: "ielts-58", front: "relate", back: "liên hệ", pronunciation: "/rɪˈleɪt/", example: "How does this relate to your theory?" },
      { id: "ielts-59", front: "require", back: "yêu cầu, đòi hỏi", pronunciation: "/rɪˈkwaɪər/", example: "This job requires patience." },
      { id: "ielts-60", front: "research", back: "nghiên cứu", pronunciation: "/rɪˈsɜːtʃ/", example: "Scientific research takes years." },
      { id: "ielts-61", front: "respond", back: "phản hồi, đáp lại", pronunciation: "/rɪˈspɒnd/", example: "She didn't respond to my email." },
      { id: "ielts-62", front: "result", back: "kết quả", pronunciation: "/rɪˈzʌlt/", example: "The result of the test was positive." },
      { id: "ielts-63", front: "role", back: "vai trò", pronunciation: "/rəʊl/", example: "He plays a key role in the team." },
      { id: "ielts-64", front: "section", back: "phần, mục", pronunciation: "/ˈsekʃn/", example: "Read section 3 of the chapter." },
      { id: "ielts-65", front: "significant", back: "quan trọng, có ý nghĩa", pronunciation: "/sɪɡˈnɪfɪkənt/", example: "There has been significant progress." },
      { id: "ielts-66", front: "similar", back: "tương tự", pronunciation: "/ˈsɪmələr/", example: "The two cases are similar." },
      { id: "ielts-67", front: "source", back: "nguồn", pronunciation: "/sɔːs/", example: "The river is the source of the legend." },
      { id: "ielts-68", front: "specific", back: "cụ thể", pronunciation: "/spəˈsɪfɪk/", example: "Please be more specific." },
      { id: "ielts-69", front: "structure", back: "cấu trúc", pronunciation: "/ˈstrʌktʃər/", example: "The building has a unique structure." },
      { id: "ielts-70", front: "theory", back: "lý thuyết", pronunciation: "/ˈθɪəri/", example: "Einstein's theory of relativity." },
      { id: "ielts-71", front: "vary", back: "thay đổi, dao động", pronunciation: "/ˈveəri/", example: "Prices vary from store to store." },
      { id: "ielts-72", front: "achieve", back: "đạt được", pronunciation: "/əˈtʃiːv/", example: "She achieved her goal." },
      { id: "ielts-73", front: "affect", back: "ảnh hưởng đến", pronunciation: "/əˈfekt/", example: "The weather affects my mood." },
      { id: "ielts-74", front: "attempt", back: "cố gắng, thử", pronunciation: "/əˈtempt/", example: "He attempted to climb the mountain." },
      { id: "ielts-75", front: "authority", back: "quyền lực, cơ quan có thẩm quyền", pronunciation: "/ɔːˈθɒrəti/", example: "The local authority approved the plan." },
      { id: "ielts-76", front: "available", back: "có sẵn", pronunciation: "/əˈveɪləbl/", example: "Seats are still available." },
      { id: "ielts-77", front: "capacity", back: "năng lực, sức chứa", pronunciation: "/kəˈpæsəti/", example: "The hall has a capacity of 500." },
      { id: "ielts-78", front: "challenge", back: "thách thức", pronunciation: "/ˈtʃælɪndʒ/", example: "Climate change is a global challenge." },
      { id: "ielts-79", front: "community", back: "cộng đồng", pronunciation: "/kəˈmjuːnəti/", example: "We live in a small community." },
      { id: "ielts-80", front: "complex", back: "phức tạp", pronunciation: "/ˈkɒmpleks/", example: "It's a complex problem." },
      { id: "ielts-81", front: "consistent", back: "nhất quán", pronunciation: "/kənˈsɪstənt/", example: "His work is consistently good." },
      { id: "ielts-82", front: "cultural", back: "thuộc về văn hóa", pronunciation: "/ˈkʌltʃərəl/", example: "Cultural differences can be challenging." },
      { id: "ielts-83", front: "despite", back: "mặc dù", pronunciation: "/dɪˈspaɪt/", example: "Despite the rain, we went out." },
      { id: "ielts-84", front: "economic", back: "thuộc về kinh tế", pronunciation: "/ˌiːkəˈnɒmɪk/", example: "The country faces economic problems." },
      { id: "ielts-85", front: "efficient", back: "hiệu quả", pronunciation: "/ɪˈfɪʃnt/", example: "This is an efficient method." },
      { id: "ielts-86", front: "enhance", back: "nâng cao, tăng cường", pronunciation: "/ɪnˈhɑːns/", example: "Music can enhance learning." },
      { id: "ielts-87", front: "essential", back: "thiết yếu", pronunciation: "/ɪˈsenʃl/", example: "Water is essential for life." },
      { id: "ielts-88", front: "expert", back: "chuyên gia", pronunciation: "/ˈekspɜːt/", example: "She's an expert in linguistics." },
      { id: "ielts-89", front: "facility", back: "cơ sở vật chất", pronunciation: "/fəˈsɪləti/", example: "The hotel has excellent facilities." },
      { id: "ielts-90", front: "global", back: "toàn cầu", pronunciation: "/ˈɡləʊbl/", example: "Global warming is a serious issue." },
      { id: "ielts-91", front: "identify", back: "nhận dạng, xác định", pronunciation: "/aɪˈdentɪfaɪ/", example: "Can you identify the problem?" },
      { id: "ielts-92", front: "imply", back: "ngụ ý, hàm ý", pronunciation: "/ɪmˈplaɪ/", example: "What are you implying?" },
      { id: "ielts-93", front: "major", back: "lớn, chủ yếu", pronunciation: "/ˈmeɪdʒər/", example: "This is a major decision." },
      { id: "ielts-94", front: "obvious", back: "rõ ràng, hiển nhiên", pronunciation: "/ˈɒbviəs/", example: "The answer is obvious." },
      { id: "ielts-95", front: "opportunity", back: "cơ hội", pronunciation: "/ˌɒpəˈtjuːnəti/", example: "Don't miss this opportunity." },
      { id: "ielts-96", front: "perceive", back: "nhận thức, cảm nhận", pronunciation: "/pəˈsiːv/", example: "How do you perceive the situation?" },
      { id: "ielts-97", front: "potential", back: "tiềm năng", pronunciation: "/pəˈtenʃl/", example: "She has great potential." },
      { id: "ielts-98", front: "reliable", back: "đáng tin cậy", pronunciation: "/rɪˈlaɪəbl/", example: "He is a reliable friend." },
      { id: "ielts-99", front: "strategy", back: "chiến lược", pronunciation: "/ˈstrætədʒi/", example: "We need a new marketing strategy." },
      { id: "ielts-100", front: "trend", back: "xu hướng", pronunciation: "/trend/", example: "There's a trend towards remote work." },
    ],
  },
  {
    id: "builtin:linux-50",
    name: "Linux 50 lệnh phổ biến nhất",
    description: "50 lệnh terminal Linux dành cho sinh viên học QTHTM",
    icon: "terminal",
    color: "#10b981",
    builtin: true,
    cards: [
      { id: "linux-c-1", front: "ls", back: "Liệt kê file và thư mục trong thư mục hiện tại", example: "ls -la (hiển thị chi tiết kèm file ẩn)" },
      { id: "linux-c-2", front: "cd", back: "Chuyển sang thư mục khác", example: "cd /home/user/Documents" },
      { id: "linux-c-3", front: "pwd", back: "In ra đường dẫn thư mục hiện tại", example: "pwd" },
      { id: "linux-c-4", front: "cat", back: "Hiển thị nội dung file", example: "cat file.txt" },
      { id: "linux-c-5", front: "cp", back: "Sao chép file hoặc thư mục", example: "cp file1.txt file2.txt" },
      { id: "linux-c-6", front: "mv", back: "Di chuyển hoặc đổi tên file", example: "mv old.txt new.txt" },
      { id: "linux-c-7", front: "rm", back: "Xóa file hoặc thư mục", example: "rm -rf /tmp/test (xóa cả thư mục)" },
      { id: "linux-c-8", front: "mkdir", back: "Tạo thư mục mới", example: "mkdir my_folder" },
      { id: "linux-c-9", front: "rmdir", back: "Xóa thư mục rỗng", example: "rmdir empty_folder" },
      { id: "linux-c-10", front: "touch", back: "Tạo file rỗng hoặc cập nhật timestamp", example: "touch new.txt" },
      { id: "linux-c-11", front: "chmod", back: "Thay đổi quyền truy cập file", example: "chmod 755 script.sh" },
      { id: "linux-c-12", front: "chown", back: "Đổi chủ sở hữu file", example: "chown user:group file.txt" },
      { id: "linux-c-13", front: "ps", back: "Liệt kê tiến trình đang chạy", example: "ps aux" },
      { id: "linux-c-14", front: "top", back: "Hiển thị tiến trình realtime", example: "top" },
      { id: "linux-c-15", front: "kill", back: "Kết thúc tiến trình theo PID", example: "kill 1234" },
      { id: "linux-c-16", front: "grep", back: "Tìm chuỗi trong file", example: "grep 'error' log.txt" },
      { id: "linux-c-17", front: "find", back: "Tìm file theo tên hoặc điều kiện", example: "find / -name 'config'" },
      { id: "linux-c-18", front: "df", back: "Hiển thị dung lượng ổ đĩa", example: "df -h" },
      { id: "linux-c-19", front: "du", back: "Hiển thị dung lượng thư mục", example: "du -sh /var" },
      { id: "linux-c-20", front: "free", back: "Hiển thị bộ nhớ RAM", example: "free -m" },
      { id: "linux-c-21", front: "ip", back: "Quản lý network interfaces", example: "ip addr show" },
      { id: "linux-c-22", front: "ping", back: "Kiểm tra kết nối mạng", example: "ping google.com" },
      { id: "linux-c-23", front: "wget", back: "Tải file từ internet", example: "wget https://example.com/file" },
      { id: "linux-c-24", front: "curl", back: "Truyền dữ liệu với URL", example: "curl https://api.example.com" },
      { id: "linux-c-25", front: "ssh", back: "Kết nối shell từ xa", example: "ssh user@server.com" },
      { id: "linux-c-26", front: "scp", back: "Sao chép file qua SSH", example: "scp file.txt user@host:/path" },
      { id: "linux-c-27", front: "tar", back: "Nén/giải nén archive", example: "tar -xzf file.tar.gz" },
      { id: "linux-c-28", front: "zip / unzip", back: "Nén/giải nén định dạng zip", example: "unzip file.zip" },
      { id: "linux-c-29", front: "useradd", back: "Tạo user mới", example: "useradd -m john" },
      { id: "linux-c-30", front: "userdel", back: "Xóa user", example: "userdel john" },
      { id: "linux-c-31", front: "passwd", back: "Đổi mật khẩu user", example: "passwd john" },
      { id: "linux-c-32", front: "systemctl", back: "Quản lý systemd service", example: "systemctl restart nginx" },
      { id: "linux-c-33", front: "journalctl", back: "Xem log systemd", example: "journalctl -u nginx" },
      { id: "linux-c-34", front: "apt", back: "Package manager Debian/Ubuntu", example: "apt install vim" },
      { id: "linux-c-35", front: "yum / dnf", back: "Package manager RHEL/CentOS", example: "yum install httpd" },
      { id: "linux-c-36", front: "crontab", back: "Lập lịch tác vụ tự động", example: "crontab -e" },
      { id: "linux-c-37", front: "echo", back: "In ra chuỗi hoặc biến", example: "echo $PATH" },
      { id: "linux-c-38", front: "env", back: "Hiển thị biến môi trường", example: "env" },
      { id: "linux-c-39", front: "export", back: "Thiết lập biến môi trường", example: "export PATH=$PATH:/opt" },
      { id: "linux-c-40", front: "head", back: "Hiển thị N dòng đầu của file", example: "head -n 5 file.txt" },
      { id: "linux-c-41", front: "tail", back: "Hiển thị N dòng cuối của file", example: "tail -f /var/log/syslog" },
      { id: "linux-c-42", front: "less", back: "Xem file theo trang", example: "less bigfile.log" },
      { id: "linux-c-43", front: "vi / vim", back: "Trình soạn thảo văn bản mạnh mẽ", example: "vim file.txt" },
      { id: "linux-c-44", front: "nano", back: "Trình soạn thảo văn bản đơn giản", example: "nano file.txt" },
      { id: "linux-c-45", front: "diff", back: "So sánh sự khác biệt giữa 2 file", example: "diff a.txt b.txt" },
      { id: "linux-c-46", front: "wc", back: "Đếm dòng / từ / byte", example: "wc -l file.txt" },
      { id: "linux-c-47", front: "sort", back: "Sắp xếp dòng theo thứ tự", example: "sort file.txt" },
      { id: "linux-c-48", front: "uniq", back: "Lọc dòng trùng lặp liên tiếp", example: "sort file.txt | uniq" },
      { id: "linux-c-49", front: "sed", back: "Tìm và thay thế chuỗi", example: "sed 's/old/new/g' file.txt" },
      { id: "linux-c-50", front: "awk", back: "Xử lý văn bản theo cột", example: "awk '{print $1}' file.txt" },
    ],
  },
];

export function getBuiltinFlashcardSet(setId: string): FlashcardSet | undefined {
  return builtinFlashcardSets.find((s) => s.id === setId);
}
