import type { Flashcard } from "./types";

// ────────────────────────────────────────────────────────────────────────────
// SET 11 — MONEY & FINANCE
// ────────────────────────────────────────────────────────────────────────────
const moneyCards: Flashcard[] = [
  {
    id: "money-save-future",
    front: "to save for the future",
    back: "tiết kiệm cho tương lai",
    pronunciation: "/tu seɪv fɔːr ðə ˈfjuːtʃər/",
    example: "She saves for the future.",
  },
  {
    id: "money-save-retirement",
    front: "to save for retirement",
    back: "tiết kiệm cho việc nghỉ hưu",
    pronunciation: "/tu seɪv fɔːr rɪˈtaɪərmənt/",
    example: "It's wise to save for retirement.",
  },
  {
    id: "money-out-of-debt",
    front: "to get out of debt",
    back: "thoát khỏi nợ nần",
    pronunciation: "/tu ɡet aʊt əv dɛt/",
    example: "She finally got out of debt.",
  },
  {
    id: "money-credit-score",
    front: "a solid credit score",
    back: "điểm tín dụng tốt",
    pronunciation: "/ə ˈsɒlɪd ˈkrɛdɪt skɔːr/",
    example: "He has a solid credit score.",
  },
  {
    id: "money-long-goals",
    front: "long-term financial goals",
    back: "mục tiêu tài chính dài hạn",
    pronunciation: "/lɒŋ tɜːm faɪˈnænʃl ɡəʊlz/",
    example: "Set long-term financial goals.",
  },
  {
    id: "money-control",
    front: "to take control of your finances",
    back: "kiểm soát tài chính của bạn",
    pronunciation: "/tu teɪk kənˈtrəʊl əv jɔːr faɪˈnænsɪz/",
    example: "You should take control of your finances.",
  },
  {
    id: "money-success",
    front: "financial success",
    back: "thành công tài chính",
    pronunciation: "/faɪˈnænʃl səkˈsɛs/",
    example: "Financial success requires discipline.",
  },
  {
    id: "money-long-savings",
    front: "long-term savings",
    back: "tiết kiệm dài hạn",
    pronunciation: "/lɒŋ tɜːm ˈseɪvɪŋz/",
    example: "Long-term savings take time to build.",
  },
  {
    id: "money-overspend",
    front: "to overspend",
    back: "chi tiêu quá mức",
    pronunciation: "/tu ˌəʊvəˈspend/",
    example: "Don't overspend on luxury items.",
  },
  {
    id: "money-budget",
    front: "to set up a budget",
    back: "lập ngân sách",
    pronunciation: "/tu sɛt ʌp ə ˈbʌdʒɪt/",
    example: "Set up a budget every month.",
  },
  {
    id: "money-adjustments",
    front: "to make adjustments where necessary",
    back: "thực hiện các điều chỉnh khi cần thiết",
    pronunciation: "/tu meɪk əˈdʒʌstmənts/",
    example: "Make adjustments where necessary.",
  },
  {
    id: "money-net-income",
    front: "your net income after taxes",
    back: "thu nhập ròng của bạn sau thuế",
    pronunciation: "/jɔːr nɛt ˈɪnkʌm ˈɑːftər ˈtæksɪz/",
    example: "Net income is what you actually take home.",
  },
  {
    id: "money-pay-off",
    front: "to pay off debt",
    back: "trả nợ",
    pronunciation: "/tu peɪ ɒf dɛt/",
    example: "Pay off debt as soon as possible.",
  },
  {
    id: "money-burden",
    front: "a huge financial burden",
    back: "một gánh nặng tài chính lớn",
    pronunciation: "/ə hjuːdʒ faɪˈnænʃl ˈbɜːdn/",
    example: "Medical bills became a huge financial burden.",
  },
  {
    id: "money-independent",
    front: "to become financially independent",
    back: "trở nên độc lập về tài chính",
    pronunciation: "/tu bɪˈkʌm faɪˈnænʃli ˌɪndɪˈpɛndənt/",
    example: "She wants to become financially independent.",
  },
  {
    id: "money-emergency",
    front: "an emergency fund",
    back: "quỹ cho các trường hợp khẩn cấp",
    pronunciation: "/ən iˈmɜːdʒənsi fʌnd/",
    example: "An emergency fund is essential.",
  },
  {
    id: "money-cut-expenses",
    front: "to cut your monthly expenses",
    back: "cắt giảm chi phí hàng tháng của bạn",
    pronunciation: "/tu kʌt jɔːr ˈmʌnθli ɪkˈspɛnsɪz/",
    example: "Cut your monthly expenses.",
  },
  {
    id: "money-credit-card",
    front: "high-interest credit card debt",
    back: "nợ thẻ tín dụng lãi suất cao",
    pronunciation: "/haɪ ˈɪntrəst ˈkrɛdɪt kɑːd dɛt/",
    example: "High-interest credit card debt is dangerous.",
  },
  {
    id: "money-make-ends-meet",
    front: "to make ends meet",
    back: "kiếm sống, xoay sở cho đủ sống",
    pronunciation: "/tu meɪk ɛndz miːt/",
    example: "We struggle to make ends meet.",
  },
  {
    id: "money-student-loans",
    front: "student loans",
    back: "khoản vay cho sinh viên",
    pronunciation: "/ˈstjuːdnt ləʊnz/",
    example: "Student loans take years to repay.",
  },
  // Idioms
  {
    id: "money-not-grow-trees",
    front: "money doesn't grow on trees",
    back: "tiền không mọc từ trên cây → không nên tiêu pha quá nhiều tiền, vì tiền chỉ có hạn",
    pronunciation: "/ˈmʌni dʌznt ɡrəʊ ɒn triːz/",
    example: "Money doesn't grow on trees.",
  },
  {
    id: "money-bread-butter",
    front: "bread and butter",
    back: "kế sinh nhai, công việc giúp bạn trang trải cuộc sống",
    pronunciation: "/brɛd ənd ˈbʌtər/",
    example: "Teaching is my bread and butter.",
  },
  {
    id: "money-bring-home",
    front: "bring home the bacon",
    back: "kiếm tiền về nuôi sống gia đình",
    pronunciation: "/brɪŋ həʊm ðə ˈbeɪkən/",
    example: "He brings home the bacon.",
  },
  {
    id: "money-silver-spoon",
    front: "born with a silver spoon in your mouth",
    back: "sinh ra đã ngậm thìa bạc → được sinh ra trong một gia đình giàu có",
    pronunciation: "/bɔːn wɪð ə ˈsɪlvər spuːn ɪn jɔːr maʊθ/",
    example: "She was born with a silver spoon in her mouth.",
  },
  {
    id: "money-penny-saved",
    front: "a penny saved is a penny earned",
    back: "một xu tiết kiệm cũng chính là một xu làm ra",
    pronunciation: "/ə ˈpeni seɪvd ɪz ə ˈpeni ɜːnd/",
    example: "A penny saved is a penny earned.",
  },
  {
    id: "money-arm-leg",
    front: "an arm and a leg",
    back: "đắt đỏ",
    pronunciation: "/ən ɑːm ənd ə lɛɡ/",
    example: "That bag cost an arm and a leg.",
  },
  {
    id: "money-break-bank",
    front: "break the bank",
    back: "rất đắt, rất tốn kém",
    pronunciation: "/breɪk ðə bæŋk/",
    example: "Holiday shopping doesn't have to break the bank.",
  },
  {
    id: "money-easy-money",
    front: "easy money",
    back: "tiền dễ kiếm",
    pronunciation: "/ˈiːzi ˈmʌni/",
    example: "There is no easy money in this job.",
  },
  {
    id: "money-foot-bill",
    front: "to foot the bill",
    back: "chi trả",
    pronunciation: "/tu fʊt ðə bɪl/",
    example: "Who is going to foot the bill?",
  },
  {
    id: "money-breadline",
    front: "on the breadline",
    back: "cuộc sống rất khó khăn, nghèo khổ",
    pronunciation: "/ɒn ðə ˈbrɛdlaɪn/",
    example: "Many families are on the breadline.",
  },
  {
    id: "money-pay-way",
    front: "pay your (own) way",
    back: "tự chi trả",
    pronunciation: "/peɪ jɔːr əʊn weɪ/",
    example: "I always pay my own way.",
  },
];

// ────────────────────────────────────────────────────────────────────────────
// SET 12 — POVERTY
// ────────────────────────────────────────────────────────────────────────────
const povertyCards: Flashcard[] = [
  {
    id: "poverty-2-day",
    front: "to live on less than $2 a day",
    back: "sống với ít hơn $2 một ngày",
    pronunciation: "/tu lɪv ɒn lɛs ðæn tuː dɒlərz ə deɪ/",
    example: "Many still live on less than $2 a day.",
  },
  {
    id: "poverty-extreme",
    front: "to live in extreme poverty",
    back: "sống trong cảnh nghèo đói cùng cực",
    pronunciation: "/tu lɪv ɪn ɪkˈstriːm ˈpɒvəti/",
    example: "Children live in extreme poverty.",
  },
  {
    id: "poverty-below-line",
    front: "to live below the poverty line",
    back: "sống dưới mức nghèo",
    pronunciation: "/tu lɪv bɪˈləʊ ðə ˈpɒvəti laɪn/",
    example: "Millions live below the poverty line.",
  },
  {
    id: "poverty-vicious",
    front: "the vicious cycle of poverty",
    back: "vòng luẩn quẩn của sự nghèo khó",
    pronunciation: "/ðə ˈvɪʃəs ˈsaɪkl əv ˈpɒvəti/",
    example: "The vicious cycle of poverty is hard to break.",
  },
  {
    id: "poverty-no-education",
    front: "lack of education",
    back: "thiếu giáo dục",
    pronunciation: "/læk əv ˌɛdjuˈkeɪʃn/",
    example: "Lack of education fuels poverty.",
  },
  {
    id: "poverty-paycheck",
    front: "to live paycheck to paycheck",
    back: "kiếm đồng nào tiêu đồng nấy",
    pronunciation: "/tu lɪv ˈpeɪtʃɛk tu ˈpeɪtʃɛk/",
    example: "Many families live paycheck to paycheck.",
  },
  {
    id: "poverty-lifted",
    front: "to be lifted out of extreme poverty",
    back: "thoát khỏi cảnh nghèo cùng cực",
    pronunciation: "/tu biː ˈlɪftɪd aʊt/",
    example: "More people have been lifted out of extreme poverty.",
  },
  {
    id: "poverty-farming",
    front: "to rely on farming to earn a living",
    back: "dựa vào việc làm nông để kiếm sống",
    pronunciation: "/tu rɪˈlaɪ ɒn ˈfɑːmɪŋ/",
    example: "Many rural families rely on farming.",
  },
  {
    id: "poverty-fewer-opps",
    front: "to have fewer opportunities to move ahead in life",
    back: "có ít cơ hội để tiến lên phía trước trong cuộc sống",
    pronunciation: "/tu həv ˈfjuːər ˌɒpəˈtjuːnətiz/",
    example: "Poor people have fewer opportunities to move ahead in life.",
  },
  {
    id: "poverty-multiple",
    front: "to work multiple jobs",
    back: "làm nhiều công việc",
    pronunciation: "/tu wɜːk ˈmʌltɪpl dʒɒbz/",
    example: "Many work multiple jobs to survive.",
  },
  {
    id: "poverty-put-food",
    front: "to struggle to put food on the table",
    back: "khó khăn trong việc kiếm tiền để trang trải cuộc sống",
    pronunciation: "/tu ˈstrʌɡl tu pʊt fuːd ɒn ðə ˈteɪbl/",
    example: "Many struggle to put food on the table.",
  },
  {
    id: "poverty-hungry",
    front: "to go to bed hungry",
    back: "không có gì ăn / lót bụng vào buổi tối",
    pronunciation: "/tu ɡəʊ tu bɛd ˈhʌŋɡri/",
    example: "Many children go to bed hungry.",
  },
  {
    id: "poverty-slow",
    front: "to slow poverty reduction progress",
    back: "làm chậm tiến độ giảm tỷ lệ nghèo",
    pronunciation: "/tu sləʊ ˈpɒvəti rɪˈdʌkʃn ˈprəʊɡrɛs/",
    example: "Wars slow poverty reduction progress.",
  },
  {
    id: "poverty-hunger-malnutrition",
    front: "to suffer from hunger and malnutrition",
    back: "bị đói và suy dinh dưỡng",
    pronunciation: "/tu ˈsʌfər frəm ˈhʌŋɡər/",
    example: "Children suffer from hunger and malnutrition.",
  },
  {
    id: "poverty-acute",
    front: "to face acute food shortages",
    back: "đối mặt với tình trạng thiếu lương thực trầm trọng",
    pronunciation: "/tu feɪs əˈkjuːt fuːd ˈʃɔːtɪdʒɪz/",
    example: "Many regions face acute food shortages.",
  },
  {
    id: "poverty-feed-family",
    front: "to be unable to buy enough food to feed their families",
    back: "không có khả năng mua đủ thực phẩm để nuôi gia đình",
    pronunciation: "/tu biː ʌnˈeɪbl tu baɪ ɪˈnʌf fuːd/",
    example: "Many are unable to feed their families.",
  },
  // Phrases
  {
    id: "poverty-scrape-by",
    front: "to scrape by",
    back: "sống qua ngày",
    pronunciation: "/tu skreɪp baɪ/",
    example: "We just scrape by on his salary.",
  },
  {
    id: "poverty-short-cash",
    front: "to be short of cash",
    back: "thiếu tiền",
    pronunciation: "/tu biː ʃɔːt əv kæʃ/",
    example: "I'm short of cash this month.",
  },
  {
    id: "poverty-broke",
    front: "to be broke",
    back: "không có tiền",
    pronunciation: "/tu biː brəʊk/",
    example: "I'm broke until payday.",
  },
  {
    id: "poverty-breadline",
    front: "to live on the breadline",
    back: "cực nghèo",
    pronunciation: "/tu lɪv ɒn ðə ˈbrɛdlaɪn/",
    example: "Many live on the breadline.",
  },
  {
    id: "poverty-dole",
    front: "to be on the dole",
    back: "sống nhờ vào trợ cấp thất nghiệp",
    pronunciation: "/tu biː ɒn ðə dəʊl/",
    example: "He has been on the dole for months.",
  },
  {
    id: "poverty-rags-riches",
    front: "from rags to riches",
    back: "phất lên, ăn lên làm ra (từ nghèo → giàu)",
    pronunciation: "/frəm ræɡz tu ˈrɪtʃɪz/",
    example: "He went from rags to riches.",
  },
  {
    id: "poverty-in-debt",
    front: "to be in debt",
    back: "nợ tiền",
    pronunciation: "/tu biː ɪn dɛt/",
    example: "Many families are in debt.",
  },
  {
    id: "poverty-out-of-debt",
    front: "to be out of debt",
    back: "trả hết nợ",
    pronunciation: "/tu biː aʊt əv dɛt/",
    example: "She is finally out of debt.",
  },
  {
    id: "poverty-fight",
    front: "in the fight against something",
    back: "trong cuộc chiến chống lại thứ gì",
    pronunciation: "/ɪn ðə faɪt əˈɡɛnst ˈsʌmθɪŋ/",
    example: "In the fight against global poverty.",
  },
  {
    id: "poverty-jeopardize",
    front: "to jeopardize (v)",
    back: "gây nguy hiểm cho",
    pronunciation: "/tu ˈdʒɛpərdaɪz/",
    example: "The crisis jeopardizes children's futures.",
  },
  {
    id: "poverty-afford",
    front: "to afford (v)",
    back: "đủ khả năng chi trả",
    pronunciation: "/tu əˈfɔːrd/",
    example: "Many can't afford school fees.",
  },
  {
    id: "poverty-impoverished",
    front: "impoverished (adj)",
    back: "rất nghèo",
    pronunciation: "/ɪmˈpɒvərɪʃt/",
    example: "Impoverished families need help.",
  },
  {
    id: "poverty-medical-treatment",
    front: "medical treatment",
    back: "điều trị y tế",
    pronunciation: "/ˈmɛdɪkl ˈtriːtmənt/",
    example: "Many can't afford medical treatment.",
  },
  {
    id: "poverty-shelter",
    front: "shelter (n)",
    back: "chỗ ở",
    pronunciation: "/ˈʃɛltər/",
    example: "Shelter is a basic human need.",
  },
  {
    id: "poverty-root-causes",
    front: "the root causes of something",
    back: "nguyên nhân gốc rễ / chính yếu gây ra vấn đề gì",
    pronunciation: "/ðə ruːt ˈkɔːzɪz əv ˈsʌmθɪŋ/",
    example: "We must tackle the root causes of poverty.",
  },
  {
    id: "poverty-necessity",
    front: "necessity (n)",
    back: "thứ thiết yếu",
    pronunciation: "/nəˈsɛsəti/",
    example: "Food and shelter are basic necessities.",
  },
  {
    id: "poverty-discrimination",
    front: "discrimination (n)",
    back: "sự đối xử phân biệt",
    pronunciation: "/dɪˌskrɪmɪˈneɪʃn/",
    example: "Discrimination also causes poverty.",
  },
  {
    id: "poverty-lead-into",
    front: "to lead somebody into poverty",
    back: "đưa ai đó vào cảnh nghèo khó",
    pronunciation: "/tu liːd ˈsʌmwʌn ˈɪntuː ˈpɒvəti/",
    example: "Bad decisions can lead someone into poverty.",
  },
];

export { moneyCards, povertyCards };
