import type { Flashcard } from "./types";

// ────────────────────────────────────────────────────────────────────────────
// SET 19 — WORK & SOCIETY (Business / Family / Ageing Population / Average Life / Health / Throwaway / Gap)
// ────────────────────────────────────────────────────────────────────────────
const workSocietyCards: Flashcard[] = [
  // ── Business and Money ────────────────────────────────────────────────
  {
    id: "bm-make-profit",
    front: "to make a profit",
    back: "tạo lợi nhuận",
    pronunciation: "/meɪk ə ˈprɒfɪt/",
    example: "Companies want to make a profit.",
  },
  {
    id: "bm-competitive-world",
    front: "to survive in a competitive world / to survive in a fast-changing world",
    back: "sống sót trong một thế giới đầy cạnh tranh / sống sót trong một thế giới thay đổi nhanh chóng",
    pronunciation: "/kəmˈpɛtətɪv wɜːld/",
    example: "Businesses must survive in a competitive world.",
  },
  {
    id: "bm-modern-business",
    front: "to achieve success in the modern business world",
    back: "đạt được thành công trong thế giới kinh doanh hiện đại",
    pronunciation: "/əˈtʃiːv səkˈsɛs/",
    example: "Many aspire to achieve success.",
  },
  {
    id: "bm-entrepreneurs",
    front: "entrepreneurs",
    back: "doanh nhân",
    pronunciation: "/ˌɒntrəprəˈnɜːr/",
    example: "Entrepreneurs take risks.",
  },
  {
    id: "bm-difficult-clients",
    front: "to deal with difficult clients",
    back: "làm việc với những khách hàng khó tính",
    pronunciation: "/dɪˈfiːkəlt ˈklaɪənts/",
    example: "Staff deal with difficult clients.",
  },
  {
    id: "bm-wealth-knowledge",
    front: "to be provided with a wealth of knowledge",
    back: "được cung cấp nhiều kiến thức",
    pronunciation: "/wɛlθ əv ˈnɒlɪdʒ/",
    example: "Students are provided with a wealth of knowledge.",
  },
  {
    id: "bm-significant-contributions",
    front: "to make significant contributions to...",
    back: "có những đóng góp to lớn cho ...",
    pronunciation: "/sɪɡˈnɪfɪkənt kɒntrɪˈbjuːʃnz/",
    example: "NGOs make significant contributions.",
  },
  {
    id: "bm-start-business",
    front: "to start a business",
    back: "bắt đầu 1 doanh nghiệp",
    pronunciation: "/stɑːt ə ˈbɪznəs/",
    example: "He started a business last year.",
  },
  {
    id: "bm-specialise",
    front: "to specialise in...",
    back: "chuyên về ...",
    pronunciation: "/ˈspɛʃəlaɪz/",
    example: "We specialise in marketing.",
  },
  {
    id: "bm-clear-strategy",
    front: "to have a clear strategy",
    back: "có 1 chiến lược rõ ràng",
    pronunciation: "/klɪər ˈstrætɪdʒi/",
    example: "Successful firms have a clear strategy.",
  },
  {
    id: "bm-running-costs",
    front: "to cover its running costs",
    back: "bao quát được chi phí vận hành của nó",
    pronunciation: "/ˈrʌnɪŋ kɒsts/",
    example: "Revenue must cover running costs.",
  },
  {
    id: "bm-costs-business",
    front: "costs involved in running a business",
    back: "những chi phí liên quan đến việc vận hành 1 doanh nghiệp",
    pronunciation: "/ˈkɒsts ɪnˈvɒlvd/",
    example: "Costs include rent and salaries.",
  },
  {
    id: "bm-boost-productivity",
    front: "to boost productivity",
    back: "tăng năng suất",
    pronunciation: "/buːst ˌprɒdʌkˈtɪvəti/",
    example: "New tools boost productivity.",
  },
  {
    id: "bm-customer-satisfaction",
    front: "to maximise customer satisfaction",
    back: "tối đa hóa sự hài lòng của khách hàng",
    pronunciation: "/ˈmæksɪmaɪz ˈkʌstəmər ˌsætɪsˈfækʃn/",
    example: "We maximise customer satisfaction.",
  },
  {
    id: "bm-social-responsibilities",
    front: "to have social responsibilities",
    back: "có trách nhiệm xã hội",
    pronunciation: "/ˌsəʊʃl rɪˌspɒnsəˈbɪlɪtiz/",
    example: "Companies have social responsibilities.",
  },
  {
    id: "bm-financial-support",
    front: "to provide financial support for...",
    back: "cung cấp hỗ trợ tài chính cho ...",
    pronunciation: "/faɪˈnænʃl səˈpɔːt/",
    example: "They provide financial support for charities.",
  },
  {
    id: "bm-charitable-donations",
    front:
      "charitable donations, environmental protection programmes or staff volunteering projects",
    back: "các khoản đóng góp từ thiện, các chương trình bảo vệ môi trường hoặc các dự án tình nguyện viên của nhân viên",
    pronunciation: "/ˈtʃærɪtəbl dəʊˈneɪʃnz/",
    example: "Companies engage in charitable donations.",
  },
  {
    id: "bm-employment-opportunities",
    front: "to create more employment opportunities for people",
    back: "tạo thêm cơ hội việc làm cho mọi người",
    pronunciation: "/ɪmˈplɔɪmənt ˌɒpəˈtjuːnɪtiz/",
    example: "Firms create more employment opportunities.",
  },
  {
    id: "bm-company-reputation",
    front: "to improve a company's reputation",
    back: "nâng cao danh tiếng của công ty",
    pronunciation: "/ˌrɛpjʊˈteɪʃn/",
    example: "CSR improves a company's reputation.",
  },
  {
    id: "bm-challenges-obstacles",
    front: "to encounter various challenges and obstacles",
    back: "gặp phải nhiều thử thách và trở ngại khác nhau",
    pronunciation: "/ɪnˈkaʊntər ˈtʃælɪndʒɪz/",
    example: "Businesses encounter various challenges.",
  },
  {
    id: "bm-financial-crisis",
    front: "serious financial and economic crisis",
    back: "khủng hoảng tài chính và kinh tế nghiêm trọng",
    pronunciation: "/saɪˈrɪəriəs faɪˈnænʃl/",
    example: "We face a serious financial crisis.",
  },
  {
    id: "bm-risky-contracts",
    front: "to take on risky contracts",
    back: "nhận các hợp đồng rủi ro",
    pronunciation: "/ˈrɪski ˈkɒntrækts/",
    example: "Firms should avoid risky contracts.",
  },
  {
    id: "bm-cash-flow",
    front: "to experience regular cash flow problems",
    back: "gặp vấn đề về dòng tiền thường xuyên",
    pronunciation: "/kæʃ fləʊ/",
    example: "Many SMEs have cash flow problems.",
  },
  {
    id: "bm-ineffective",
    front:
      "ineffective business strategies // ineffective market research // poor customer service",
    back: "chiến lược kinh doanh không hiệu quả // nghiên cứu thị trường không hiệu quả // dịch vụ khách hàng kém",
    pronunciation: "/ˌɪnɪˈfɛktɪv ˈstrætɪdʒiz/",
    example: "Ineffective strategies lead to failure.",
  },
  {
    id: "bm-multinational-giants",
    front: "to compete against multinational giants",
    back: "cạnh tranh với những tập đoàn khổng lồ đa quốc gia",
    pronunciation: "/ˌmʌltiˈnæʃənl ˈdʒaɪənts/",
    example: "SMEs struggle to compete with multinational giants.",
  },
  {
    id: "bm-potential-collapse",
    front: "to face potential collapse",
    back: "đối mặt với sự sụp đổ tiềm ẩn",
    pronunciation: "/pəˈtɛnʃl kəˈlæps/",
    example: "Some firms face potential collapse.",
  },
  {
    id: "bm-bankruptcy",
    front: "to go bankrupt / to declare bankruptcy / to go out of business",
    back: "phá sản / tuyên bố phá sản / ra khỏi kinh doanh",
    pronunciation: "/bæŋˈkrʌptsi/",
    example: "Many businesses go bankrupt.",
  },
  {
    id: "bm-banking-system",
    front: "to strengthen the banking system",
    back: "tăng cường / củng cố hệ thống ngân hàng",
    pronunciation: "/ˈstrɛŋθn ðə ˈbæŋkɪŋ/",
    example: "We need to strengthen the banking system.",
  },
  {
    id: "bm-government-assistance",
    front: "government assistance for small and medium-sized enterprises",
    back: "hỗ trợ của chính phủ cho các doanh nghiệp vừa và nhỏ",
    pronunciation: "/ˈɡʌvənmənt əˈsɪstəns/",
    example: "SMEs benefit from government assistance.",
  },
  {
    id: "bm-in-depth-advice",
    front: "to offer in-depth advice on something",
    back: "đưa ra lời khuyên chuyên sâu về điều gì đó",
    pronunciation: "/ɪn dɛpθ ədˈvaɪs/",
    example: "Consultants offer in-depth advice.",
  },
  // ── Family Structure & Family Roles ──────────────────────────────────
  {
    id: "fr-stay-at-home-dads",
    front: "stay-at-home dads",
    back: "những ông bố ở nhà (chăm con, lo việc nhà)",
    pronunciation: "/steɪ ət həʊm dædz/",
    example: "Stay-at-home dads are common now.",
  },
  {
    id: "fr-breadwinners",
    front: "family breadwinners",
    back: "những trụ cột gia đình",
    pronunciation: "/ˈbrɛdˌwɪnəz/",
    example: "Parents are family breadwinners.",
  },
  {
    id: "fr-childcare",
    front: "to take childcare responsibilities",
    back: "nhận lãnh trách nhiệm chăm sóc trẻ",
    pronunciation: "/ˈtʃaɪldkɛər/",
    example: "Many fathers take childcare responsibilities.",
  },
  {
    id: "fr-most-time-working",
    front: "to spend most of their time working",
    back: "dành phần lớn thời gian làm việc",
    pronunciation: "/məʊst əv ðeə taɪm ˈwɜːkɪŋ/",
    example: "Parents spend most of their time working.",
  },
  {
    id: "fr-little-time-family",
    front: "to have little time for their family",
    back: "có rất ít thời gian cho gia đình họ",
    pronunciation: "/ˈlɪtl taɪm fɔːr ðeə ˈfæmɪli/",
    example: "Many have little time for family.",
  },
  {
    id: "fr-household-chores",
    front: "to share household chores",
    back: "chia sẻ việc nhà",
    pronunciation: "/ˈhaʊshəʊld tʃɔːz/",
    example: "Couples should share household chores.",
  },
  {
    id: "fr-same-roof",
    front: "to live under the same roof",
    back: "sống chung dưới một mái nhà",
    pronunciation: "/səʊm ruːf/",
    example: "Generations live under the same roof.",
  },
  {
    id: "fr-own-career",
    front: "to have the chance to pursue their own career",
    back: "có cơ hội theo đuổi sự nghiệp riêng của họ",
    pronunciation: "/pəˈsjuːr ðeə əʊn kəˈrɪər/",
    example: "Women have the chance to pursue their careers.",
  },
  {
    id: "fr-financial-pressures",
    front: "to be under enormous financial pressures",
    back: "chịu áp lực tài chính nặng nề",
    pronunciation: "/ɪˈnɔːməs faɪˈnænʃl ˈprɛʃəz/",
    example: "Families are under enormous financial pressures.",
  },
  {
    id: "fr-rely-relatives",
    front: "to rely on relatives for...",
    back: "nhờ cậy họ hàng về việc gì",
    pronunciation: "/rɪˈlaɪ ɒn ˈrɛlətɪvz/",
    example: "We rely on relatives for childcare.",
  },
  {
    id: "fr-nuclear-families",
    front: "the growing popularity of nuclear and single-parent families",
    back: "sự phổ biến ngày càng tăng của gia đình hạt nhân và gia đình chỉ có cha / mẹ",
    pronunciation: "/ˈnjuːkliər ˈfæmɪliz/",
    example: "Nuclear families are growing in popularity.",
  },
  {
    id: "fr-have-children-later",
    front: "to decide to have children later in life",
    back: "quyết định có con trễ",
    pronunciation: "/dɪˈsaɪd tuː hæv ˈtʃɪldrən ˈleɪtər ɪn laɪf/",
    example: "Many decide to have children later.",
  },
  {
    id: "fr-high-cost-living",
    front: "to cope with the high cost of living",
    back: "đối phó với chi phí cuộc sống cao",
    pronunciation: "/kəʊp wɪð ðə haɪ kɒst əv ˈlɪvɪŋ/",
    example: "Families cope with the high cost of living.",
  },
  {
    id: "fr-decline-structure",
    front: "the decline in traditional family structure",
    back: "sự suy giảm trong cấu trúc gia đình truyền thống",
    pronunciation: "/dɪˈklaɪn ɪn trəˈdɪʃənl ˈfæmɪli ˈstrʌktʃər/",
    example: "There is a decline in traditional family structures.",
  },
  {
    id: "fr-work-life-balance",
    front: "to achieve / maintain a healthy work-life balance",
    back: "đạt được sự cân bằng giữa cuộc sống riêng và công việc",
    pronunciation: "/wɜːk laɪf ˈbæləns/",
    example: "Many struggle to maintain work-life balance.",
  },
  {
    id: "fr-family-trees",
    front: "family trees",
    back: "gia phả",
    pronunciation: "/ˈfæmɪli triːz/",
    example: "We traced our family tree.",
  },
  {
    id: "fr-cohabitation",
    front: "cohabitation = sex before marriage",
    back: "sống thử trước hôn nhân",
    pronunciation: "/ˌkəʊˌhæbɪˈteɪʃn/",
    example: "Cohabitation is increasingly common.",
  },
  {
    id: "fr-socially-acceptable",
    front: "to be socially acceptable",
    back: "được xã hội chấp nhận",
    pronunciation: "/ˈsəʊʃəli əkˈsɛptəbl/",
    example: "Cohabitation is now socially acceptable.",
  },
  {
    id: "fr-same-sex",
    front: "same-sex marriage",
    back: "hôn nhân đồng giới",
    pronunciation: "/seɪm sɛks ˈmærɪdʒ/",
    example: "Many countries legalised same-sex marriage.",
  },
  {
    id: "fr-couple-relationships",
    front: "better couple relationships",
    back: "mối quan hệ vợ chồng tốt đẹp hơn",
    pronunciation: "/ˈkʌpl rɪˈleɪʃnʃɪps/",
    example: "Communication improves couple relationships.",
  },
  {
    id: "fr-mothers-work",
    front: "a dramatic rise in the number of mothers who work",
    back: "một sự tăng mạnh mẽ trong số lượng những người mẹ ra ngoài làm việc",
    pronunciation: "/drəˈmætɪk raɪz/",
    example: "There's a dramatic rise in working mothers.",
  },
  {
    id: "fr-access-education",
    front: "to have the chance to access better education",
    back: "có được cơ hội tiếp cận với nền giáo dục tốt hơn",
    pronunciation: "/ˈæksɛs bɛtər ˌɛdjuˈkeɪʃn/",
    example: "Girls now access better education.",
  },
  {
    id: "fr-loneliness-isolation",
    front: "to experience feelings of loneliness and isolation",
    back: "trải qua cảm giác cô đơn và đơn độc",
    pronunciation: "/ˌaɪsəˈleɪʃn/",
    example: "Elderly experience loneliness and isolation.",
  },
  // ── Average Life Expectancy ───────────────────────────────────────────
  {
    id: "le-life-expectancy",
    front: "improvements in life expectancy / preventative health care",
    back: "những sự cải thiện trong tuổi thọ / chăm sóc sức khỏe phòng bệnh",
    pronunciation: "/laɪf ɪkˈspɛktənsi/",
    example: "Improvements in life expectancy continue.",
  },
  {
    id: "le-fertility-mortality",
    front: "a decrease in fertility and mortality rates",
    back: "một sự giảm sút trong tỷ lệ sinh và tỷ lệ tử",
    pronunciation: "/fɜːˈtɪlɪti ənd mɔːˈtælɪti/",
    example: "Fertility and mortality rates are decreasing.",
  },
  {
    id: "le-declining-mortality",
    front: "declining mortality rates",
    back: "tỷ lệ tử vong giảm",
    pronunciation: "/dɪˈklaɪnɪŋ mɔːˈtælɪti/",
    example: "Mortality rates have declined.",
  },
  {
    id: "le-pressure-finances",
    front: "to increase pressure on public finances",
    back: "tăng áp lực lên tài chính công",
    pronunciation: "/ˈprɛʃər ɒn ˈpʌblɪk faɪˈnænsɪz/",
    example: "Ageing populations pressure public finances.",
  },
  {
    id: "le-burden-care",
    front: "to place an increasing burden on health care and social services",
    back: "đặt áp lực ngày càng tăng lên chăm sóc sức khỏe và các dịch vụ xã hội",
    pronunciation: "/ˈbɜːdn ɒn hɛlθ keər/",
    example: "Ageing places a burden on healthcare.",
  },
  {
    id: "le-funding-demands",
    front: "to face greater funding demands",
    back: "đối mặt với nhu cầu trợ cấp lớn hơn",
    pronunciation: "/ˈfʌndɪŋ dɪˈmɑːndz/",
    example: "Governments face greater funding demands.",
  },
  {
    id: "le-social-care-pressure",
    front: "pressure on social care increases",
    back: "áp lực lên chăm sóc xã hội gia tăng",
    pronunciation: "/ˈsəʊʃl keər/",
    example: "Pressure on social care keeps increasing.",
  },
  {
    id: "le-retired-workers",
    front: "to struggle to meet an ever increasing number of retired workers & pension commitments",
    back: "khó khăn để đáp ứng ngày càng nhiều người lao động về hưu & cam kết lương hưu",
    pronunciation: "/rɪˈtraɪəd ˈwɜːkəz/",
    example: "Systems struggle to meet pension commitments.",
  },
  {
    id: "le-shrinking-population",
    front: "to place a higher burden on the shrinking working population",
    back: "đặt một gánh nặng cao hơn đối với dân số làm việc đang bị thu hẹp dần",
    pronunciation: "/ˈʃrɪŋkɪŋ ˈpɒpjʊˌleɪʃn/",
    example: "Fewer workers face a higher burden.",
  },
  {
    id: "le-pension-benefits",
    front: "more people claim pension benefits",
    back: "nhiều người yêu cầu trợ cấp hưu trí",
    pronunciation: "/ˈpɛnʃn ˈbɛnɪfɪts/",
    example: "More people claim pension benefits.",
  },
  {
    id: "le-ageing-needs",
    front: "to face significant challenges to meet the needs of an ageing population",
    back: "đối mặt với những thách thức đáng kể để đáp ứng nhu cầu của dân số già",
    pronunciation: "/ˈeɪdʒɪŋ ˌpɒpjʊˈleɪʃn/",
    example: "Significant challenges meet ageing needs.",
  },
  {
    id: "le-independent-lives",
    front: "to struggle to live independent lives",
    back: "khó khăn để sống cuộc sống độc lập",
    pronunciation: "/ˌɪndɪˈpɛndənt laɪvz/",
    example: "Elderly may struggle to live independently.",
  },
  {
    id: "le-access-professionals",
    front: "to have limited access to health care professionals",
    back: "tiếp cận hạn chế với các chuyên gia chăm sóc sức khỏe",
    pronunciation: "/ˈlɪmɪtɪd ˈæksɛs/",
    example: "Many have limited access to health professionals.",
  },
  {
    id: "le-unaffordable-treatment",
    front: "unaffordable medical treatment for chronic conditions",
    back: "điều trị y tế đắt đỏ cho các bệnh mãn tính",
    pronunciation: "/ˌʌnəˈfɔːdəbl ˈmɛdɪkl ˈtriːtmənt/",
    example: "Chronic care is unaffordable.",
  },
  {
    id: "le-socially-isolated",
    front: "socially isolated and developmental and physical health issues",
    back: "các vấn đề sức khỏe thể chất và phát triển và cô lập về mặt xã hội",
    pronunciation: "/ˈsəʊʃəli ˈaɪsəleɪtɪd/",
    example: "Many elderly become socially isolated.",
  },
  {
    id: "le-high-tax-rates",
    front: "to require high tax rates on the current, shrinking workforce",
    back: "yêu cầu mức thuế cao đối với lực lượng lao động hiện tại đang giảm dần",
    pronunciation: "/ʃrɪŋkɪŋ ˈwɜːkfɔːs/",
    example: "Higher taxes on shrinking workforce.",
  },
  {
    id: "le-fall-productivity",
    front: "a fall in productivity & growth",
    back: "1 sự giảm trong năng suất và tăng trưởng",
    pronunciation: "/fɔːl ɪn ˌprɒdʌkˈtɪvəti/",
    example: "Productivity falls with ageing.",
  },
  {
    id: "le-shortage-workers",
    front: "a shortage of workers → to push up wages → wage inflation",
    back: "thiếu hụt công nhân → đẩy tiền lương lên → lạm phát tiền lương",
    pronunciation: "/ˈʃɔːtɪdʒ əv ˈwɜːkəz/",
    example: "Worker shortages push up wages.",
  },
  {
    id: "le-challenges-economy",
    front:
      "to present many challenges to labour markets, government tax, government spending & the wider economy",
    back: "đưa ra nhiều thách thức đối với thị trường lao động, thuế chính phủ, chi tiêu chính phủ và nền kinh tế",
    pronunciation: "/ˈleɪbər ˈmɑːkɪts/",
    example: "Ageing presents many economic challenges.",
  },
  {
    id: "le-declining-quality",
    front: "declining quality of life",
    back: "chất lượng cuộc sống giảm sút",
    pronunciation: "/dɪˈklaɪnɪŋ ˈkwɒlɪti/",
    example: "Quality of life can decline.",
  },
  {
    id: "le-save-proportion",
    front: "to force people to save a proportion of their income",
    back: "buộc mọi người phải tiết kiệm một phần thu nhập của họ",
    pronunciation: "/prəˈpɔːʃn əv ðeər ˈɪŋkʌm/",
    example: "Some forces people to save.",
  },
  {
    id: "le-age-friendly-cities",
    front: "to build age-friendly cities & housing",
    back: "xây dựng nhà ở và thành phố thích hợp với già hóa dân số",
    pronunciation: "/eɪdʒ ˈfrɛndli ˈsɪtiz/",
    example: "Build age-friendly cities.",
  },
  {
    id: "le-economic-implications",
    front: "to study the economic & social implication of...",
    back: "nghiên cứu ý nghĩa kinh tế & xã hội của ...",
    pronunciation: "/ˌɪmplɪˈkeɪʃnz/",
    example: "Study economic and social implications.",
  },
  {
    id: "le-plan-decades",
    front: "to plan decades ahead",
    back: "lên kế hoạch cho các thập kỷ tới",
    pronunciation: "/pleɪn ˈdɛkeɪdz əˈhɛd/",
    example: "Plan decades ahead for ageing.",
  },
  {
    id: "le-retirement-age",
    front: "to increase the retirement age from ... to...",
    back: "tăng tuổi nghỉ hưu từ ... lên ...",
    pronunciation: "/rɪˈtraɪərmənt eɪdʒ/",
    example: "Many countries raise the retirement age.",
  },
  {
    id: "le-private-sector",
    front: "to increase the role / importance of the private sector",
    back: "tăng vai trò của khu vực tư nhân",
    pronunciation: "/ˈpraɪvət ˈsɛktər/",
    example: "Increase the role of the private sector.",
  },
  {
    id: "le-increase-tax-pension",
    front: "to increase tax to pay for pension costs",
    back: "tăng thuế để trả chi phí lương hưu",
    pronunciation: "/ɪnˈkriːs tæks tuː peɪ fɔːr ˈpɛnʃn kɒsts/",
    example: "Increase tax to pay pensions.",
  },
  {
    id: "le-young-migrants",
    front:
      "to encourage young migrants of working age / to encourage the immigration of young working adults",
    back: "khuyến khích người di cư trẻ trong độ tuổi lao động",
    pronunciation: "/ɪnˈkʌrɪdʒ ɪˌmɪˈɡreɪʃn/",
    example: "Encourage immigration of young workers.",
  },
  {
    id: "le-reform-pension",
    front: "to reform pension systems",
    back: "cải cách hệ thống hưu trí",
    pronunciation: "/rɪˈfɔːm ˈpɛnʃn ˈsɪstəmz/",
    example: "Reform pension systems.",
  },
  {
    id: "le-changing-ageing",
    front: "the changing and ageing structure of our population",
    back: "cấu trúc già đi và thay đổi của dân số chúng ta",
    pronunciation: "/ˈtʃeɪndʒɪŋ ˈstrʌktʃər/",
    example: "Our population is ageing and changing.",
  },
  {
    id: "le-driven-by",
    front: "to be primarily driven by...",
    back: "bị thúc đẩy chủ yếu bởi ...",
    pronunciation: "/ˈprɪmərəli ˈdrɪvən baɪ/",
    example: "Migration is primarily driven by jobs.",
  },
  {
    id: "le-opportunities-challenges",
    front: "to bring both opportunities & challenges",
    back: "mang lại cả các cơ hội và thử thách",
    pronunciation: "/ˌɒpəˈtjuːnɪtiz/",
    example: "Ageing brings both opportunities and challenges.",
  },
  {
    id: "le-healthy-retirees",
    front: "healthy retirees",
    back: "những người nghỉ hưu khỏe mạnh",
    pronunciation: "/ˈhɛlθi rɪˈtraɪəz/",
    example: "Many seniors are healthy retirees.",
  },
  {
    id: "le-increases-life",
    front: "increases in life expectancy",
    back: "những sự gia tăng trong tuổi thọ",
    pronunciation: "/ˈɪnkriːsɪz/",
    example: "Increases in life expectancy continue.",
  },
  {
    id: "le-government-intervention",
    front: "government intervention",
    back: "sự can thiệp của chính phủ",
    pronunciation: "/ˌɪntəˈvɛnʃn/",
    example: "Government intervention is needed.",
  },
  {
    id: "le-live-longer",
    front: "to live longer",
    back: "sống lâu hơn",
    pronunciation: "/lɪv ˈlɒŋɡər/",
    example: "People live longer than before.",
  },
  {
    id: "le-source-concern",
    front: "to be a source of concern for...",
    back: "là một mối quan tâm đối với ...",
    pronunciation: "/sɔːs əv kənˈsɜːn/",
    example: "Ageing is a source of concern.",
  },
  {
    id: "le-demographic-patterns",
    front: "changing demographic patterns",
    back: "thay đổi mô hình nhân khẩu học",
    pronunciation: "/ˌdɛməˈɡræfɪk ˈpætənz/",
    example: "Demographic patterns are changing.",
  },
  {
    id: "le-baby-boomer",
    front: "the ageing of the baby boomer generation",
    back: "sự già hóa của thế hệ baby boomer",
    pronunciation: "/ˈbeɪbi buːmər/",
    example: "Baby boomers are ageing.",
  },
  {
    id: "le-embrace-challenges",
    front: "to both embrace these opportunities and prepare for any challenges ahead",
    back: "nắm lấy cả những cơ hội này và chuẩn bị cho mọi thử thách phía trước",
    pronunciation: "/ɪmˈbreɪs/",
    example: "Embrace opportunities and prepare for challenges.",
  },
  {
    id: "le-age-related-spending",
    front: "to meet age-related spending needs",
    back: "đáp ứng nhu cầu chi tiêu liên quan đến tuổi già",
    pronunciation: "/eɪdʒ rɪˈleɪtɪd ˈspɛndɪŋ/",
    example: "Meet age-related spending needs.",
  },
  {
    id: "le-great-opportunities",
    front: "to provide great opportunities for...",
    back: "mang đến cơ hội lớn cho ...",
    pronunciation: "/ɡreɪt ˌɒpəˈtjuːnɪtiz/",
    example: "Ageing provides great opportunities.",
  },
  {
    id: "le-voluntary-community",
    front: "increased involvement in voluntary & community activities",
    back: "tăng cường sự tham gia vào các hoạt động tình nguyện và hoạt động cộng đồng",
    pronunciation: "/ˈvɒləntri/",
    example: "Seniors join more voluntary activities.",
  },
  {
    id: "le-community-activities",
    front: "to be more likely to be involved in community activities",
    back: "có nhiều khả năng tham gia vào các hoạt động cộng đồng",
    pronunciation: "/kəˈmjuːnɪti ækˈtɪvɪtiz/",
    example: "Many retirees join community activities.",
  },
  // ── Ageing Population ────────────────────────────────────────────────
  {
    id: "ap-life-expectancy",
    front: "life expectancy",
    back: "tuổi thọ",
    pronunciation: "/laɪf ɪkˈspɛktənsi/",
    example: "Life expectancy is rising.",
  },
  {
    id: "ap-ageing-pop",
    front: "ageing populations",
    back: "dân số già hóa",
    pronunciation: "/ˈeɪdʒɪŋ ˌpɒpjʊˈleɪʃnz/",
    example: "Ageing populations are a global trend.",
  },
  {
    id: "ap-elderly-terms",
    front: "old people / elderly people / senior citizens / people at the age of 60 and more / ...",
    back: "người già / người cao tuổi / người già / người ở độ tuổi 60 trở lên / ...",
    pronunciation: "/ˈɛldərli ˈpiːpl/",
    example: "We use different terms for elderly people.",
  },
  {
    id: "ap-fertility-decline",
    front: "the decline in fertility rates",
    back: "sự suy giảm về tỷ lệ sinh",
    pronunciation: "/fɜːˈtɪlɪti reɪts/",
    example: "Fertility rates decline.",
  },
  {
    id: "ap-demographic-change",
    front: "demographic change",
    back: "sự thay đổi nhân khẩu học",
    pronunciation: "/ˌdɛməˈɡræfɪk tʃeɪndʒ/",
    example: "Demographic change affects policy.",
  },
  {
    id: "ap-proportion-over-60",
    front: "a dramatic increase in the proportion of people aged 60 or over",
    back: "sự gia tăng đáng kể về tỷ lệ người từ 60 tuổi trở lên",
    pronunciation: "/prəˈpɔːʃn/",
    example: "There's a dramatic increase in over-60s.",
  },
  {
    id: "ap-working-age-decline",
    front: "a decline in the working-age population",
    back: "sự suy giảm dân số trong độ tuổi lao động",
    pronunciation: "/ˈwɜːkɪŋ eɪdʒ/",
    example: "Working-age populations decline.",
  },
  {
    id: "ap-sheer-number",
    front: "the sheer number of older people",
    back: "số lượng người già lớn",
    pronunciation: "/ʃɪər ˈnʌmbər/",
    example: "The sheer number of older people grows.",
  },
  {
    id: "ap-heavy-pressure",
    front:
      "to put heavy pressure on health systems = to place an increasing burden on health systems",
    back: "gây áp lực nặng nề lên hệ thống y tế = đặt gánh nặng ngày càng tăng lên hệ thống y tế",
    pronunciation: "/ˈhɛvi ˈprɛʃər/",
    example: "Ageing pressures health systems.",
  },
  {
    id: "ap-increased-demand",
    front: "an increased demand for health and social care",
    back: "tăng nhu cầu chăm sóc sức khỏe và xã hội",
    pronunciation: "/ɪnˈkriːst dɪˈmɑːnd/",
    example: "There's increased demand for care.",
  },
  {
    id: "ap-various-health",
    front:
      "to suffer from various health problems such as high blood pressure, diabetes, stroke or heart attack",
    back: "bị các vấn đề sức khỏe khác nhau như cao huyết áp, tiểu đường, đột quỵ hoặc đau tim",
    pronunciation: "/ˈvaɪərəs ˈhɛlθ prɒbləmz/",
    example: "Elderly suffer various health problems.",
  },
  {
    id: "ap-government-pensions",
    front:
      "the government has to spend more on pensions → to put pressure on national budgets and the working population",
    back: "chính phủ phải chi nhiều hơn vào lương hưu → gây áp lực lên ngân sách quốc gia và dân số làm việc",
    pronunciation: "/ˈpɛnʃnz/",
    example: "Governments spend more on pensions.",
  },
  {
    id: "ap-pay-more-taxes",
    front: "working adults may have to pay more taxes → to adversely affect their lives",
    back: "người làm việc có thể phải trả nhiều thuế hơn → ảnh hưởng xấu đến cuộc sống của họ",
    pronunciation: "/peɪ mɔːr tæksɪz/",
    example: "Workers may pay more taxes.",
  },
  {
    id: "ap-competition-jobs",
    front:
      "increased competition for jobs ← many elderly candidates compete with younger ones for the same jobs",
    back: "tăng khả năng cạnh tranh cho công việc ← nhiều ứng cử viên cao tuổi cạnh tranh với những người trẻ hơn cho cùng một công việc",
    pronunciation: "/ˌkɒmpəˈtɪʃn fɔːr dʒɒbs/",
    example: "Competition for jobs grows.",
  },
  {
    id: "ap-care-elderly",
    front: "young people have to spend more time taking care of their elderly parents",
    back: "những người trẻ tuổi phải dành nhiều thời gian hơn để chăm sóc cha mẹ già của họ",
    pronunciation: "/ˈɛldərli ˈpɛərənts/",
    example: "Many care for elderly parents.",
  },
  {
    id: "ap-community-services",
    front:
      "older people spend more time taking part in community services and volunteer work → beneficial for their communities",
    back: "những người lớn tuổi dành nhiều thời gian tham gia vào các dịch vụ cộng đồng và công việc tình nguyện → có lợi cho cộng đồng của họ",
    pronunciation: "/kəˈmjuːnɪti ˈsɜːvɪsɪz/",
    example: "Seniors contribute through community services.",
  },
  {
    id: "ap-skills-younger",
    front: "older employees have various skills to pass on to their younger counterparts",
    back: "các nhân viên lớn tuổi có nhiều kỹ năng khác nhau để chuyển sang các đối tác trẻ hơn",
    pronunciation: "/pɑːs ɒn tuː jʌŋɡər ˈkaʊntərpɑːts/",
    example: "Older employees pass on skills.",
  },
  {
    id: "ap-retirement-age",
    front: "to increase the retirement age",
    back: "tăng tuổi nghỉ hưu",
    pronunciation: "/ɪnˈkriːs ðə rɪˈtraɪərmənt eɪdʒ/",
    example: "Some propose raising the retirement age.",
  },
  // ── Health ────────────────────────────────────────────────────────────
  {
    id: "he-excessive-consumption",
    front: "excessive consumption of...",
    back: "việc tiêu thụ quá mức ...",
    pronunciation: "/ɪkˈsɛsɪv kənˈsʌmpʃn/",
    example: "Excessive consumption of sugar is unhealthy.",
  },
  {
    id: "he-sedentary-lifestyle",
    front: "sedentary lifestyles",
    back: "lối sống thụ động",
    pronunciation: "/ˈsɛdntri ˈlaɪfˌstaɪl/",
    example: "Sedentary lifestyles harm health.",
  },
  {
    id: "he-fast-food",
    front: "fast food = junk food = pre-made food",
    back: "thức ăn nhanh = đồ ăn vặt = thức ăn được chuẩn bị sẵn",
    pronunciation: "/fɑːst fuːd/",
    example: "Fast food is everywhere.",
  },
  {
    id: "he-healthy-diet",
    front: "to have a healthy diet = to have a balanced diet",
    back: "có 1 chế độ ăn lành mạnh, cân bằng",
    pronunciation: "/ˈhɛlθi ˈdaɪət/",
    example: "Have a healthy diet.",
  },
  {
    id: "he-unhealthy-diet",
    front: "to have an unhealthy diet = to have an imbalanced diet",
    back: "có 1 chế độ ăn không lành mạnh, không cân bằng",
    pronunciation: "/ʌnˈhɛlθi ˈdaɪət/",
    example: "Avoid an unhealthy diet.",
  },
  {
    id: "he-take-part-in",
    front: "to take part in = to participate in = to engage in",
    back: "tham gia vào",
    pronunciation: "/teɪk pɑːt ɪn/",
    example: "Take part in sports regularly.",
  },
  {
    id: "he-weight-gain",
    front: "weight gain",
    back: "sự tăng cân",
    pronunciation: "/weɪt ɡeɪn/",
    example: "Weight gain can harm health.",
  },
  {
    id: "he-weight-problems",
    front: "weight problems",
    back: "các vấn đề về cân nặng",
    pronunciation: "/weɪt ˈprɒbləmz/",
    example: "Weight problems affect millions.",
  },
  {
    id: "he-obesity",
    front: "obesity (n)",
    back: "sự béo phì",
    pronunciation: "/əʊˈbiːsəti/",
    example: "Obesity is a global epidemic.",
  },
  {
    id: "he-childhood-obesity",
    front: "childhood obesity = obesity among children",
    back: "béo phì ở trẻ em",
    pronunciation: "/ˈtʃaɪldhʊd əʊˈbiːsəti/",
    example: "Childhood obesity is rising.",
  },
  {
    id: "he-regular-exercise",
    front: "to take regular exercise",
    back: "tập thể dục thường xuyên",
    pronunciation: "/ˈrɛɡjʊlər ˈɛksərsaɪz/",
    example: "Take regular exercise.",
  },
  {
    id: "he-physical-activity",
    front: "physical activity",
    back: "hoạt động thể chất",
    pronunciation: "/ˈfɪzɪkl ækˈtɪvɪti/",
    example: "Physical activity improves health.",
  },
  {
    id: "he-healthier-food",
    front: "to make healthier food choices",
    back: "lựa chọn thực phẩm lành mạnh hơn",
    pronunciation: "/ˈhɛlθiər fuːd/",
    example: "Make healthier food choices.",
  },
  {
    id: "he-public-health-campaigns",
    front: "public health campaigns",
    back: "các chiến dịch sức khỏe cộng đồng",
    pronunciation: "/ˈpʌblɪk hɛlθ kæmˈpeɪnz/",
    example: "Public health campaigns raise awareness.",
  },
  {
    id: "he-suffer-issues",
    front: "to suffer from various health issues",
    back: "mắc hàng loạt các vấn đề về sức khỏe",
    pronunciation: "/ˈsʌfər frəm ˈvɛəriəs ˈɪʃuːz/",
    example: "Many suffer from various health issues.",
  },
  {
    id: "he-home-cooked",
    front: "home-cooked food",
    back: "thức ăn được nấu tại nhà",
    pronunciation: "/həʊm kʊkt fuːd/",
    example: "Home-cooked food is healthier.",
  },
  {
    id: "he-higher-risk-heart",
    front: "to be at a higher risk of heart diseases",
    back: "tỷ lệ cao mắc phải bệnh tim",
    pronunciation: "/haɪər rɪsk əv hɑːt dɪˈziːzɪz/",
    example: "Sedentary people are at higher risk of heart disease.",
  },
  {
    id: "he-treatment-costs",
    front: "treatment costs",
    back: "chi phí chữa trị",
    pronunciation: "/ˈtriːtmənt kɒsts/",
    example: "Treatment costs are rising.",
  },
  {
    id: "he-prevalence-fast-food",
    front: "the prevalence of fast food and processed food",
    back: "việc thịnh hành của thức ăn nhanh và các thức ăn được chế biến sẵn",
    pronunciation: "/ˈprɛvələns/",
    example: "Fast food is prevalent everywhere.",
  },
  {
    id: "he-raise-awareness",
    front: "to raise public awareness",
    back: "nâng cao ý thức cộng đồng",
    pronunciation: "/reɪz ˈpʌblɪk əˈwɛənəs/",
    example: "Campaigns raise public awareness.",
  },
  {
    id: "he-eat-vegetables",
    front: "to try to eat more vegetables and fruit",
    back: "cố gắng ăn nhiều rau củ quả và trái cây",
    pronunciation: "/ˈvɛdʒtəblz ənd fruːt/",
    example: "Try to eat more fruit and veg.",
  },
  {
    id: "he-healthy-eating",
    front: "healthy eating",
    back: "ăn uống lành mạnh",
    pronunciation: "/ˈhɛlθi ˈiːtɪŋ/",
    example: "Healthy eating starts at home.",
  },
  {
    id: "he-health-risks",
    front: "health risks",
    back: "các nguy cơ gây hại cho sức khỏe",
    pronunciation: "/hɛlθ rɪsks/",
    example: "Sugar poses health risks.",
  },
  {
    id: "he-addictive-ingredients",
    front: "highly addictive ingredients",
    back: "các thành phần gây nghiện cao",
    pronunciation: "/əˈdɪktɪv ɪnˈɡriːdiənts/",
    example: "Sugary drinks have addictive ingredients.",
  },
  {
    id: "he-improve-public-health",
    front: "to improve public health",
    back: "cải thiện sức khỏe cộng đồng",
    pronunciation: "/ɪmˈpruːv ˈpʌblɪk hɛlθ/",
    example: "Sport improves public health.",
  },
  // ── Throwaway Society ────────────────────────────────────────────────
  {
    id: "ts-overconsumption",
    front: "overconsumption = excessive consumption",
    back: "việc tiêu thụ quá mức",
    pronunciation: "/ˌəʊvəkənˈsʌmpʃn/",
    example: "Overconsumption harms the planet.",
  },
  {
    id: "ts-overproduction",
    front: "overproduction = excessive production",
    back: "việc sản xuất quá mức",
    pronunciation: "/ˌəʊvəprəˈdʌkʃn/",
    example: "Overproduction leads to waste.",
  },
  {
    id: "ts-long-lived",
    front:
      "long-lived products = durable products = products that are made to last for a long period of time",
    back: "những sản phẩm có tuổi thọ dài",
    pronunciation: "/ˈlɒŋ lɪvd/",
    example: "Durable products last for years.",
  },
  {
    id: "ts-short-lived",
    front:
      "short-lived products = non-durable products = products that are made to last for a short period of time",
    back: "những sản phẩm có tuổi thọ ngắn",
    pronunciation: "/ʃɔːt lɪvd/",
    example: "Plastic bottles are short-lived.",
  },
  {
    id: "ts-repurchase",
    front: "repurchase = buy again",
    back: "mua lại",
    pronunciation: "/riːˈpʌtʃəs/",
    example: "Companies encourage repurchase.",
  },
  {
    id: "ts-repeat-customers",
    front: "repeat customers",
    back: "những khách hàng sẽ mua hàng lại ở cửa hàng họ đã mua",
    pronunciation: "/rɪˈpiːt ˈkʌstəməz/",
    example: "Stores want repeat customers.",
  },
  {
    id: "ts-dent-finance",
    front: "to make a dent in your finance",
    back: "làm giảm số tiền bạn đang có",
    pronunciation: "/meɪk ə dɛnt ɪn jɔːr faɪˈnæns/",
    example: "Constant buying dents your finances.",
  },
  {
    id: "ts-profit-margins",
    front: "higher profit margins for manufacturers",
    back: "lợi nhuận biên lớn hơn cho các nhà sản xuất",
    pronunciation: "/ˈprɒfɪt ˈmɑːdʒɪnz/",
    example: "Manufacturers love higher margins.",
  },
  {
    id: "ts-novelty-items",
    front: "to tempt customers into buying the latest, novelty items",
    back: "thu hút khách hàng mua những sản phẩm mới nhất",
    pronunciation: "/ˈnɒvəlti ˈaɪtəmz/",
    example: "Companies tempt customers with novelty.",
  },
  {
    id: "ts-disposable",
    front: "disposable products",
    back: "những sản phẩm dùng một lần rồi vứt đi",
    pronunciation: "/dɪˈspəʊzəbl ˈprɒdʌkts/",
    example: "Plastic cups are disposable products.",
  },
  {
    id: "ts-solid-waste",
    front: "solid waste generation rates",
    back: "tỷ lệ thải ra chất thải rắn",
    pronunciation: "/ˈsɒlɪd weɪst ˌdʒɛnəˈreɪʃn/",
    example: "Solid waste generation is rising.",
  },
  {
    id: "ts-environmental-degradation",
    front: "environmental degradation",
    back: "sự suy thoái môi trường",
    pronunciation: "/ɪnˌvaɪərənˈmɛntl dɪˌɡrəˈdeɪʃn/",
    example: "Disposable goods cause environmental degradation.",
  },
  {
    id: "ts-contaminate",
    front: "to contaminate soil and water",
    back: "làm ô nhiễm đất và nước",
    pronunciation: "/kənˈtæmɪneɪt/",
    example: "Waste contaminates soil and water.",
  },
  {
    id: "ts-consumer-spending",
    front: "to increase consumer spending",
    back: "tăng chi tiêu của khách hàng",
    pronunciation: "/kənˈsjuːmər ˈspɛndɪŋ/",
    example: "Companies push consumer spending.",
  },
  {
    id: "ts-bad-habits",
    front: "bad spending habits",
    back: "thói quen tiêu xài xấu",
    pronunciation: "/bæd ˈspɛndɪŋ ˈhæbɪts/",
    example: "Avoid bad spending habits.",
  },
  {
    id: "ts-leftover-food",
    front: "leftover food",
    back: "đồ ăn thừa",
    pronunciation: "/ˈlɛftˌəʊvər fuːd/",
    example: "Many throw away leftover food.",
  },
  {
    id: "ts-new-version",
    front: "a new version with more features",
    back: "phiên bản mới với nhiều tính năng hơn",
    pronunciation: "/njuː ˈvɜːʃn/",
    example: "Phones get new versions yearly.",
  },
  {
    id: "ts-negative-effect",
    front: "to have a negative / detrimental / harmful effect on...",
    back: "có ảnh hưởng có hại lên ...",
    pronunciation: "/ˌdɛtrɪˈmɛntl ɪˈfɛkt/",
    example: "Throwaway culture has harmful effects.",
  },
  {
    id: "ts-do-not-need",
    front: "to buy things that you do not really need",
    back: "mua những thứ mà bạn không thực sự cần",
    pronunciation: "/ðæts juː dəʊ nɒt ˈrɪəli niːd/",
    example: "Avoid buying what you don't need.",
  },
  {
    id: "ts-waste-of-money",
    front: "a waste of money",
    back: "một sự lãng phí tiền của",
    pronunciation: "/weɪst əv ˈmʌni/",
    example: "Many purchases are a waste of money.",
  },
  {
    id: "ts-relieve-stress",
    front: "to buy new things to relieve stress or anxiety",
    back: "mua đồ mới để giải tỏa căng thẳng và lo âu",
    pronunciation: "/rɪˈliːv strɛs/",
    example: "Some buy things to relieve stress.",
  },
  {
    id: "ts-overspend",
    front: "to overspend = to spend beyond one's income",
    back: "chi tiêu quá mức",
    pronunciation: "/ˌəʊvəˈspɛnd/",
    example: "Many overspend during holidays.",
  },
  {
    id: "ts-toxic-waste",
    front: "huge amounts of toxic waste",
    back: "lượng khổng lồ chất thải độc hại",
    pronunciation: "/ˈtɒksɪk weɪst/",
    example: "Factories produce toxic waste.",
  },
  {
    id: "ts-discharged",
    front: "to be discharged into the environment",
    back: "bị thải ra môi trường",
    pronunciation: "/dɪsˈtʃɑːdʒd/",
    example: "Toxic waste is discharged into rivers.",
  },
  {
    id: "ts-reuse-recycle",
    front: "to encourage people to reuse and recycle more",
    back: "khuyến khích người dân tái chế và tái sử dụng nhiều hơn",
    pronunciation: "/riːˈjuːz ənd ˈriːˌsaɪkl/",
    example: "Encourage reuse and recycle.",
  },
  {
    id: "ts-serious-debt",
    front: "to get into serious debt",
    back: "bị mắc nợ nghiêm trọng",
    pronunciation: "/ˈsɪəriəs dɛt/",
    example: "Overspending leads to debt.",
  },
  // ── The Gap Between Rich and Poor ────────────────────────────────────
  {
    id: "gp-economic-inequality",
    front: "economic inequality",
    back: "sự mất cân bằng kinh tế",
    pronunciation: "/ˌiːkəˈnɒmɪk ˌɪnɪˈkwɒləti/",
    example: "Economic inequality is rising.",
  },
  {
    id: "gp-growing-disparity",
    front: "the growing disparity between the wealthy and the poor",
    back: "sự chênh lệch ngày càng tăng giữa người giàu và người nghèo",
    pronunciation: "/dɪˈspærɪti/",
    example: "The disparity between rich and poor grows.",
  },
  {
    id: "gp-income-inequality",
    front: "to narrow / widen / increase income inequality",
    back: "thu hẹp / mở rộng / tăng bất bình đẳng thu nhập",
    pronunciation: "/ˈɪŋkʌm ˌɪnɪˈkwɒləti/",
    example: "Policies can narrow income inequality.",
  },
  {
    id: "gp-income-disparities",
    front: "income disparities",
    back: "những sự chênh lệch về thu nhập",
    pronunciation: "/ˈɪŋkʌm dɪsˈpærɪtiz/",
    example: "Income disparities fuel tension.",
  },
  {
    id: "gp-high-inequality",
    front: "high levels of inequality",
    back: "mức độ bất bình đẳng cao",
    pronunciation: "/haɪ ˈlɛvlz əv ˌɪnɪˈkwɒləti/",
    example: "Some countries have high inequality.",
  },
  {
    id: "gp-basic-needs",
    front: "to cannot meet their basic needs such as food and accommodation",
    back: "không thể đáp ứng nhu cầu cơ bản của họ như thực phẩm và chỗ ở",
    pronunciation: "/beɪsɪk niːdz/",
    example: "Many cannot meet their basic needs.",
  },
  {
    id: "gp-access-education",
    front: "to not have access to proper education",
    back: "không được tiếp cận với giáo dục phù hợp",
    pronunciation: "/ˈæksɛs tuː ˈprɒpər ˌɛdjuˈkeɪʃn/",
    example: "Poor families lack access to education.",
  },
  {
    id: "gp-find-good-job",
    front: "to have difficulty finding a good job",
    back: "gặp khó khăn trong việc tìm kiếm một công việc tốt",
    pronunciation: "/dɪˈfɪkəlti faɪndɪŋ ə ɡʊd dʒɒb/",
    example: "Many struggle to find a good job.",
  },
  {
    id: "gp-practical-skills",
    front: "a lack of practical skills and experience",
    back: "thiếu kỹ năng và kinh nghiệm thực tế",
    pronunciation: "/ˈpræktɪkl skɪlz/",
    example: "Many lack practical skills.",
  },
  {
    id: "gp-struggle-financially",
    front: "to struggle financially = to face financial problems",
    back: "khó khăn tài chính = đối mặt với vấn đề tài chính",
    pronunciation: "/ˈstrʌɡl faɪˈnænʃəli/",
    example: "Many struggle financially.",
  },
  {
    id: "gp-invest-effectively",
    front: "to not know how to invest effectively / how to manage their budgets better",
    back: "không biết cách đầu tư hiệu quả / cách quản lý ngân sách tốt hơn",
    pronunciation: "/ɪnˈvɛst ɪˈfɛktɪvli/",
    example: "Many don't know how to invest.",
  },
  {
    id: "gp-free-education",
    front: "to provide free education to poor people",
    back: "cung cấp giáo dục miễn phí cho người nghèo",
    pronunciation: "/friː ˌɛdjuˈkeɪʃn/",
    example: "Provide free education to the poor.",
  },
  {
    id: "gp-financial-support-poor",
    front: "to provide financial support to...",
    back: "cung cấp hỗ trợ tài chính cho",
    pronunciation: "/faɪˈnænʃl səˈpɔːt/",
    example: "Provide financial support to the poor.",
  },
  {
    id: "gp-financial-courses",
    front:
      "to provide free financial courses / workshops on how to manage personal finance more effectively",
    back: "cung cấp khóa học / hội thảo tài chính miễn phí về cách quản lý tài chính cá nhân hiệu quả hơn",
    pronunciation: "/ˈfɪnænsɪ kɔːsɪz/",
    example: "Free financial courses help the poor.",
  },
  {
    id: "gp-money-management",
    front:
      "to not have the chance to learn skills such as money management which are necessary for their future jobs",
    back: "không có cơ hội học các kỹ năng như quản lý tiền bạc cần thiết cho công việc tương lai của họ",
    pronunciation: "/ˈmʌni ˈmænɪdʒmənt/",
    example: "Money management is essential.",
  },
  {
    id: "gp-public-awareness-finance",
    front: "to raise public awareness of the importance of financial education",
    back: "nâng cao nhận thức cộng đồng về tầm quan trọng của giáo dục tài chính",
    pronunciation: "/faɪˈnænʃl ˌɛdjuˈkeɪʃn/",
    example: "Raise awareness of financial education.",
  },
  {
    id: "gp-social-problems",
    front: "to lead to various social problems",
    back: "dẫn đến các vấn đề xã hội khác nhau",
    pronunciation: "/ˈsəʊʃl ˈprɒbləmz/",
    example: "Inequality leads to social problems.",
  },
  {
    id: "gp-poverty-crime",
    front: "to increase in poverty and crime rates",
    back: "tăng tỷ lệ nghèo đói và tội phạm",
    pronunciation: "/ˈpɒvəti ənd kraɪm/",
    example: "Inequality raises poverty and crime.",
  },
  {
    id: "gp-tension-riots",
    front: "to lead to tension and conflicts → social riots",
    back: "dẫn đến căng thẳng và xung đột → bạo loạn xã hội",
    pronunciation: "/ˈrʌɪəts/",
    example: "Inequality leads to social riots.",
  },
  {
    id: "gp-strikes",
    front: "strikes / demonstrations are happening in some parts of the world",
    back: "các cuộc đình công / biểu tình đang diễn ra ở một số nơi trên thế giới",
    example: "Strikes and demonstrations happen globally.",
  },
  {
    id: "gp-threat-stability",
    front: "to pose a serious threat to the safety and stability of society",
    back: "đặt ra một mối đe dọa nghiêm trọng đối với sự an toàn và ổn định của xã hội",
    pronunciation: "/staɪˈbɪlɪti əv səˈsaɪəti/",
    example: "Inequality threatens stability.",
  },
  {
    id: "gp-willing-do-anything",
    front:
      "to be willing to do anything, regardless of whether it is legal or not, just to survive",
    back: "sẵn sàng làm bất cứ điều gì, bất kể nó có hợp pháp hay không, chỉ để tồn tại",
    pronunciation: "/ˈwɪlɪŋ tuː duː ˈɛniθɪŋ/",
    example: "Many will do anything to survive.",
  },
  {
    id: "gp-wealth-redistribution",
    front: "to introduce laws regarding wealth redistribution or taxation",
    back: "ban hành luật liên quan đến phân phối lại tài sản hoặc thuế",
    pronunciation: "/ˌriːdɪstrɪˈbjuːʃn/",
    example: "Introduce wealth redistribution laws.",
  },
  {
    id: "gp-progressive-tax",
    front:
      "to employ a progressive tax and benefits system which imposes proportionately more tax on those with higher levels of income, and redistributes welfare benefits to poor people",
    back: "sử dụng một hệ thống thuế lũy tiến, trong đó áp dụng thuế tương ứng nhiều hơn đối với những người có mức thu nhập cao hơn và phân phối lại phúc lợi cho người nghèo",
    pronunciation: "/prəˈɡrɛsɪv tæks/",
    example: "Use a progressive tax system.",
  },
];

export { workSocietyCards };
