import type { Flashcard } from "./types";

// ────────────────────────────────────────────────────────────────────────────
// SET 4 — COVID-19 & HEALTH
// ────────────────────────────────────────────────────────────────────────────
const covidCards: Flashcard[] = [
  // General
  {
    id: "covid-pandemic",
    front: "the COVID-19 pandemic",
    back: "đại dịch COVID-19",
    pronunciation: "/ðə kəʊvɪd naɪnteen ˈpændɪmɪk/",
    example: "The COVID-19 pandemic changed daily life.",
  },
  {
    id: "covid-vaccinated",
    front: "to be fully vaccinated",
    back: "được tiêm chủng đầy đủ",
    pronunciation: "/tu biː ˈfʊli ˈvæksɪneɪtɪd/",
    example: "More people are now fully vaccinated.",
  },
  {
    id: "covid-confirmed-cases",
    front: "confirmed COVID-19 cases",
    back: "các trường hợp mắc Covid 19 đã được ghi nhận",
    pronunciation: "/kənˈfɜːmd kəʊvɪd naɪnteen keɪsɪz/",
    example: "Confirmed cases are rising.",
  },
  {
    id: "covid-unprecedented-challenge",
    front: "to present an unprecedented challenge to...",
    back: "đặt ra thách thức chưa từng có đối với...",
    pronunciation: "/tu prɪˈzent ən ʌnˈprɛsɪˌdɛntɪd ˈtʃælɪndʒ tu/",
    example: "The pandemic presented an unprecedented challenge to public health.",
  },
  {
    id: "covid-extreme-poverty",
    front: "to be at risk of falling into extreme poverty",
    back: "có nguy cơ rơi vào cảnh nghèo khó cùng cực",
    pronunciation: "/tu biː æt rɪsk/",
    example: "Many families were at risk of falling into extreme poverty.",
  },
  {
    id: "covid-existential-threat",
    front: "to face an existential threat",
    back: "đối mặt với một mối đe dọa tới sự tồn tại",
    pronunciation: "/tu feɪs ən ˌɛɡzɪˈstɛnʃl θrɛt/",
    example: "We faced an existential threat.",
  },
  {
    id: "covid-earn-income",
    front: "to earn an income during lockdowns",
    back: "kiếm thu nhập trong thời gian phong tỏa",
    pronunciation: "/tu ɜːn ən ˈɪnkʌm ˈdjʊərɪŋ ˈlɒkdaʊnz/",
    example: "Many couldn't earn an income during lockdowns.",
  },
  {
    id: "covid-hospital-beds",
    front: "a lack of hospital beds",
    back: "thiếu giường bệnh",
    pronunciation: "/ə læk əv ˈhɒspɪtl bɛdz/",
    example: "Hospitals faced a lack of beds.",
  },
  {
    id: "covid-financial-hardship",
    front: "to experience financial hardship",
    back: "gặp khó khăn về tài chính",
    pronunciation: "/tu ɪkˈspɪəriəns faɪˈnænʃl ˈhɑːdʃɪp/",
    example: "Many experienced financial hardship.",
  },
  {
    id: "covid-delta-variant",
    front: "the Delta variant",
    back: "biến thể Delta",
    pronunciation: "/ðə ˈdɛltə ˈveəriənt/",
    example: "The Delta variant spread rapidly.",
  },
  {
    id: "covid-life-threatening",
    front: "to be life-threatening",
    back: "đe dọa tính mạng",
    pronunciation: "/tu biː laɪf θrɛtənɪŋ/",
    example: "The infection is life-threatening.",
  },
  {
    id: "covid-spread-rapidly",
    front: "to spread rapidly around the world",
    back: "lây lan nhanh chóng trên toàn thế giới",
    pronunciation: "/tu sprɛd ˈræpɪdli əˈraʊnd ðə wɜːld/",
    example: "The virus spread rapidly around the world.",
  },
  {
    id: "covid-breathing-problems",
    front: "to develop severe breathing problems",
    back: "tiến triển các vấn đề về hô hấp nghiêm trọng",
    pronunciation: "/tu dɪˈvɛləp sɪˈvɪər ˈbriːðɪŋ ˈprɒbləmz/",
    example: "He developed severe breathing problems.",
  },
  {
    id: "covid-underlying-conditions",
    front: "underlying medical conditions",
    back: "bệnh nền",
    pronunciation: "/ˌʌndəˈlaɪɪŋ ˈmɛdɪkl kənˈdɪʃnz/",
    example: "People with underlying conditions are at higher risk.",
  },
  {
    id: "covid-wide-range",
    front: "to cause a wide range of illnesses",
    back: "gây ra nhiều loại bệnh",
    pronunciation: "/tu kɔːz ə waɪd reɪndʒ əv ˈɪlnəsɪz/",
    example: "Smoking causes a wide range of illnesses.",
  },
  {
    id: "covid-global-crisis",
    front: "a global health crisis",
    back: "một cuộc khủng hoảng sức khỏe toàn cầu",
    pronunciation: "/ə ˈɡləʊbl hɛlθ ˈkraɪsɪs/",
    example: "It became a global health crisis.",
  },
  {
    id: "covid-halt-spread",
    front: "to halt the spread of the virus",
    back: "ngăn chặn sự lây lan của vi rút",
    pronunciation: "/tu hɔːlt ðə sprɛd əv ðə ˈvaɪərəs/",
    example: "Lockdowns helped halt the spread of the virus.",
  },
  {
    id: "covid-tighter-restrictions",
    front: "to impose tighter restrictions on movement",
    back: "áp đặt những hạn chế chặt chẽ hơn đối với việc đi lại",
    pronunciation: "/tu ɪmˈpəʊz ˈtaɪtər rɪˈstrɪkʃnz ɒn ˈmuːvmənt/",
    example: "Authorities imposed tighter restrictions on movement.",
  },
  // Effects
  {
    id: "covid-tip-poverty",
    front: "to tip ... back into extreme poverty",
    back: "đưa ... trở về sự nghèo khó cùng cực",
    pronunciation: "/tu tɪp/",
    example: "The pandemic tipped millions back into poverty.",
  },
  {
    id: "covid-loss-trade-tourism",
    front: "loss of trade and tourism",
    back: "tổn thất thương mại và du lịch",
    pronunciation: "/lɒs əv treɪd ənd ˈtʊərɪzəm/",
    example: "Loss of trade and tourism hit hardest.",
  },
  {
    id: "covid-economic-growth",
    front: "to negatively affect global economic growth",
    back: "ảnh hưởng tiêu cực đến tăng trưởng kinh tế toàn cầu",
    pronunciation: "/tu ˈnɛɡətɪvli əˈfɛkt/",
    example: "It negatively affected global economic growth.",
  },
  {
    id: "covid-disrupt-education",
    front: "significant disruptions to education",
    back: "gián đoạn đáng kể đối với giáo dục",
    pronunciation: "/sɪɡˈnɪfɪkənt dɪsˈrʌpʃnz/",
    example: "There were significant disruptions to education.",
  },
  // Idioms
  {
    id: "covid-under-the-weather",
    front: "to be under the weather",
    back: "cảm thấy không được khỏe",
    pronunciation: "/tu biː ˈʌndər ðə ˈweðər/",
    example: "I'm a bit under the weather today.",
  },
  {
    id: "covid-last-legs",
    front: "on your last legs",
    back: "suy yếu cùng cực",
    pronunciation: "/ɒn jɔːr lɑːst lɛɡz/",
    example: "He is on his last legs.",
  },
  {
    id: "covid-out-of-sort",
    front: "to be out of sort",
    back: "cảm thấy khó chịu trong người",
    pronunciation: "/tu biː aʊt əv sɔːt/",
    example: "She's out of sorts today.",
  },
  {
    id: "covid-not-yourself",
    front: "you're not your usual/normal self",
    back: "không bình thường như mọi ngày",
    pronunciation: "/jɔːr nɒt jɔːr ˈjuːʒʊəl sɛlf/",
    example: "You don't seem your usual self.",
  },
  {
    id: "covid-off-colour",
    front: "off-colour",
    back: "có vẻ ốm yếu",
    pronunciation: "/ɒf ˈkʌlər/",
    example: "She's feeling a bit off-colour.",
  },
  {
    id: "covid-death-warmed-up",
    front: "feel/look like death warmed up",
    back: "nhìn rất mệt mỏi, nhợt nhạt",
    pronunciation: "/fiːl laɪk dɛθ ˈwɔːmd ʌp/",
    example: "I felt like death warmed up after that flight.",
  },
  {
    id: "covid-throw-up",
    front: "to throw up",
    back: "nôn mửa",
    pronunciation: "/tu θrəʊ ʌp/",
    example: "The food made me throw up.",
  },
  {
    id: "covid-keel-over",
    front: "to keel over",
    back: "ngất đi",
    pronunciation: "/tu kiːl ˈəʊvər/",
    example: "He keeled over from the heat.",
  },
  {
    id: "covid-pass-out",
    front: "to pass out",
    back: "đột ngột bất tỉnh",
    pronunciation: "/tu pɑːs aʊt/",
    example: "She passed out from exhaustion.",
  },
  {
    id: "covid-wear-off",
    front: "to wear off (pain/effect)",
    back: "dần tan biến",
    pronunciation: "/tu weər ɒf/",
    example: "The pain wore off after an hour.",
  },
  {
    id: "covid-come-down",
    front: "to come/go down with something",
    back: "bị bệnh gì",
    pronunciation: "/tu kʌm daʊn wɪð ˈsʌmθɪŋ/",
    example: "She came down with the flu.",
  },
  {
    id: "covid-go-round",
    front: "to go round (illness)",
    back: "lây lan",
    pronunciation: "/tu ɡəʊ raʊnd/",
    example: "The flu is going round the office.",
  },
  {
    id: "covid-pick-up",
    front: "to pick something up (illness)",
    back: "nhiễm bệnh",
    pronunciation: "/tu pɪk ˈsʌmθɪŋ ʌp/",
    example: "I picked up a cold on the train.",
  },
  {
    id: "covid-take-it-easy",
    front: "to take things/it easy",
    back: "nghỉ ngơi",
    pronunciation: "/tu teɪk θɪŋz ˈiːzi/",
    example: "Take it easy and don't work too hard.",
  },
];

// ────────────────────────────────────────────────────────────────────────────
// SET 5 — CRIME & PUNISHMENT
// ────────────────────────────────────────────────────────────────────────────
const crimeCards: Flashcard[] = [
  {
    id: "crime-commit",
    front: "to commit a crime = to commit an offence = to break the law",
    back: "thực hiện hành vi phạm tội",
    pronunciation: "/tu kəˈmɪt ə kraɪm/",
    example: "He committed a crime at the age of 19.",
  },
  {
    id: "crime-reoffend",
    front: "to reoffend",
    back: "tái phạm",
    pronunciation: "/tu ˌriːəˈfend/",
    example: "Most offenders do not reoffend after rehabilitation.",
  },
  {
    id: "crime-criminals",
    front: "criminals = offenders = lawbreakers",
    back: "kẻ phạm tội",
    pronunciation: "/ˈkrɪmɪnlz/",
    example: "The police are searching for the criminals.",
  },
  {
    id: "crime-engage",
    front: "to engage in criminal activities = to take part in unlawful acts",
    back: "tham gia vào các hoạt động phạm pháp",
    pronunciation: "/tu ɪnˈɡeɪdʒ/",
    example: "Many young people engage in criminal activities.",
  },
  {
    id: "crime-minor",
    front: "minor crimes such as shoplifting or pickpocketing",
    back: "các tội nhẹ như ăn trộm vặt tại các cửa hàng hay móc túi",
    pronunciation: "/ˈmaɪnə kraɪmz/",
    example: "Minor crimes are rising.",
  },
  {
    id: "crime-serious",
    front: "serious crimes such as robbery or murder",
    back: "các tội nặng như cướp hay giết người",
    pronunciation: "/ˈsɪəriəs kraɪmz/",
    example: "He was charged with serious crimes.",
  },
  {
    id: "crime-capital-punishment",
    front: "to receive capital punishment = to receive the death penalty",
    back: "nhận án tử hình",
    pronunciation: "/tu rɪˈsiːv ˈkæpɪtl ˈpʌnɪʃmənt/",
    example: "Many countries have abolished capital punishment.",
  },
  {
    id: "crime-prison-sentences",
    front: "to receive prison sentences",
    back: "nhận án tù / bị bỏ tù",
    pronunciation: "/tu rɪˈsiːv ˈprɪzn ˈsentənsɪz/",
    example: "He received a 5-year prison sentence.",
  },
  {
    id: "crime-life-imprisonment",
    front: "life imprisonment",
    back: "tù chung thân",
    pronunciation: "/laɪf ɪmˈprɪznmənt/",
    example: "He was sentenced to life imprisonment.",
  },
  {
    id: "crime-stricter-punishments",
    front: "to impose stricter/more severe punishments on...",
    back: "áp đặt những hình phạt nặng nề hơn",
    pronunciation: "/tu ɪmˈpəʊz/",
    example: "The government imposed stricter punishments on drunk drivers.",
  },
  {
    id: "crime-vocational-training",
    front: "to provide education and vocational training",
    back: "cung cấp giáo dục và đào tạo nghề",
    pronunciation: "/tu prəˈvaɪd/",
    example: "Prisons should provide education and vocational training.",
  },
  {
    id: "crime-living",
    front: "to commit crimes as a way of making a living",
    back: "phạm tội như một cách để kiếm sống",
    pronunciation: "/tu kəˈmɪt kraɪmz/",
    example: "Many commit crimes as a way of making a living.",
  },
  {
    id: "crime-released",
    front: "to be released from prison",
    back: "được thả / ra tù",
    pronunciation: "/tu biː rɪˈliːst frəm ˈprɪzn/",
    example: "He was released from prison after 10 years.",
  },
  {
    id: "crime-rehab-programmes",
    front: "rehabilitation programmes",
    back: "những chương trình cải tạo",
    pronunciation: "/ˌriːhəˌbɪlɪˈteɪʃn ˈprəʊɡræmz/",
    example: "Rehabilitation programmes help reduce reoffending.",
  },
  {
    id: "crime-threat-society",
    front: "to pose a serious threat to society",
    back: "gây ra mối đe dọa nghiêm trọng cho xã hội",
    pronunciation: "/tu pəʊz/",
    example: "These criminals pose a serious threat to society.",
  },
  {
    id: "crime-deterrent",
    front: "to act/serve as a deterrent",
    back: "đóng vai trò như một sự cảnh báo/ngăn chặn",
    pronunciation: "/tu ækt əz ə dɪˈterənt/",
    example: "Harsh punishments serve as a deterrent.",
  },
  {
    id: "crime-surveillance",
    front: "security cameras and home surveillance equipment",
    back: "thiết bị giám sát tại nhà và camera an ninh",
    pronunciation: "/sɪˈkjʊərəti ˈkæmərəz/",
    example: "Surveillance equipment helps prevent crime.",
  },
  {
    id: "crime-prevention",
    front: "crime prevention programmes",
    back: "những chương trình phòng chống tội phạm",
    pronunciation: "/kraɪm prɪˈvɛnʃn/",
    example: "Crime prevention programmes are essential.",
  },
  {
    id: "crime-juvenile",
    front: "juvenile crimes = youth crimes = crimes among young adults",
    back: "tội phạm vị thành niên / ở giới trẻ",
    pronunciation: "/ˈdʒuːvənaɪl kraɪmz/",
    example: "Juvenile crimes are a serious concern.",
  },
  {
    id: "crime-innocent",
    front: "innocent people",
    back: "những người vô tội",
    pronunciation: "/ˈɪnəsnt ˈpiːpl/",
    example: "Many innocent people were harmed.",
  },
  {
    id: "crime-wrongly-convicted",
    front: "to be wrongly convicted and executed",
    back: "bị kết tội và xử oan",
    pronunciation: "/tu biː ˈrɒŋli kənˈvɪktɪd/",
    example: "He was wrongly convicted and executed.",
  },
  {
    id: "crime-violent-culture",
    front: "to create a violent culture",
    back: "tạo ra một nền văn hóa bạo lực",
    pronunciation: "/tu kriˈeɪt/",
    example: "Violent media can create a violent culture.",
  },
  {
    id: "crime-potential",
    front: "potential criminals",
    back: "những người có khả năng cao trở thành tội phạm",
    pronunciation: "/pəˈtɛnʃl ˈkrɪmɪnlz/",
    example: "We need to stop potential criminals.",
  },
  {
    id: "crime-safety",
    front: "a sense of safety and security",
    back: "một cảm giác an toàn và an ninh",
    pronunciation: "/ə sɛns əv ˈseɪfti/",
    example: "Surveillance gives people a sense of safety.",
  },
  // Idioms
  {
    id: "crime-cover-tracks",
    front: "to cover your tracks",
    back: "che giấu những vết tích hay những việc mình đã làm",
    pronunciation: "/tu ˈkʌvər jɔːr træks/",
    example: "The criminals covered their tracks.",
  },
  {
    id: "crime-behind-bars",
    front: "to be behind bars",
    back: "ngồi tù",
    pronunciation: "/tu biː bɪˈhaɪnd bɑːz/",
    example: "He is behind bars.",
  },
  {
    id: "crime-red-handed",
    front: "to catch somebody red handed",
    back: "bắt quả tang",
    pronunciation: "/tu kætʃ ˈsʌmwʌn rɛd ˈhændɪd/",
    example: "He was caught red handed.",
  },
  {
    id: "crime-nose-clean",
    front: "to keep your nose clean",
    back: "giữ cho mình tránh khỏi gặp rắc rối",
    pronunciation: "/tu kiːp jɔːr nəʊz kliːn/",
    example: "Keep your nose clean from now on.",
  },
  {
    id: "crime-by-the-book",
    front: "to do something by the book",
    back: "làm theo sách vở, đúng quy tắc, luật lệ",
    pronunciation: "/tu duː ˈsʌmθɪŋ bai ðə bʊk/",
    example: "She does everything by the book.",
  },
  {
    id: "crime-come-clean",
    front: "to come clean",
    back: "thú thật điều gì mà trước đây mình giấu kín",
    pronunciation: "/tu kʌm kliːn/",
    example: "He finally came clean about it.",
  },
  {
    id: "crime-turn-in",
    front: "to turn somebody in",
    back: "giao nộp ai đó cho cảnh sát",
    pronunciation: "/tu tɜːn ˈsʌmwʌn ɪn/",
    example: "She turned her brother in to the police.",
  },
  {
    id: "crime-get-away",
    front: "to get away with murder",
    back: "làm điều sai trái mà không bị trừng phạt",
    pronunciation: "/tu ɡet əˈweɪ wɪð ˈmɜːdər/",
    example: "He gets away with murder at work.",
  },
  {
    id: "crime-blind-eye",
    front: "to turn a blind eye",
    back: "nhắm mắt làm ngơ",
    pronunciation: "/tu tɜːn ə blaɪnd aɪ/",
    example: "We shouldn't turn a blind eye to this.",
  },
  {
    id: "crime-bail-out",
    front: "to bail someone out",
    back: "bảo lãnh",
    pronunciation: "/tu beɪl ˈsʌmwʌn aʊt/",
    example: "His parents bailed him out.",
  },
];

export { covidCards, crimeCards };
