import type { FlashcardSet } from "./types";
// `resolveJsonModule: true` is set in tsconfig.json so we can import JSON.
import oxfordData from "./oxford-3000-source.json";

type SourceCard = {
  word: string;
  pos: string;
  ipa: string;
  meaning: string;
};

type SourceTopic = {
  index: number;
  name: string;
  cards: SourceCard[];
};

// Cast once so the rest of this module is fully type-safe.
const SOURCE: SourceTopic[] = (oxfordData as { topics: SourceTopic[] }).topics;

/**
 * 3000 most common English vocabulary words, grouped by 60 everyday topics
 * (translated by Oxford Wordlist / popular Vietnamese learning resources).
 *
 * Source: `lib/oxford-3000-source.json` (generated by
 * `scripts/parse-oxford-source.cjs` from the supplied PDF).
 *
 * Each topic becomes its own FlashcardSet so the user can drill into one
 * area at a time. The set id is `builtin:oxford-{index}-{slug}` so users
 * can keep progress independently of the topic name.
 */
function slugify(input: string): string {
  return input
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40);
}

const TOPIC_ICONS = [
  "book-open",
  "palette",
  "utensils",
  "sparkles",
  "calculator",
  "shopping-bag",
  "bed",
  "users",
  "cooking-pot",
  "gem",
  "leaf",
  "sofa",
  "hospital",
  "monitor",
  "broom",
  "store",
  "theater",
  "plane",
  "moon",
  "dumbbell",
  "trees",
  "heart-handshake",
  "plane-takeoff",
  "heart-pulse",
  "carrot",
  "clock",
  "car",
  "smile",
  "user",
  "cup-soda",
  "flower-2",
  "film",
  "volleyball",
  "snowflake",
  "utensils-crossed",
  "music",
  "heart",
  "hotel",
  "graduation-cap",
  "palette",
  "cloud-sun",
  "shirt",
  "body",
  "school",
  "users-round",
  "apple",
  "paw-print",
  "bug",
  "book-marked",
  "leaf",
  "globe",
  "fish",
  "zap",
  "briefcase",
  "apple",
  "alert-triangle",
  "map",
  "concierge-bell",
  "mail",
  "landmark",
];

const TOPIC_COLORS = [
  "#3b82f6",
  "#8b5cf6",
  "#10b981",
  "#f59e0b",
  "#06b6d4",
  "#ec4899",
  "#6366f1",
  "#14b8a6",
  "#f97316",
  "#a855f7",
  "#84cc16",
  "#06b6d4",
  "#ef4444",
  "#0ea5e9",
  "#22c55e",
  "#f59e0b",
  "#8b5cf6",
  "#3b82f6",
  "#f59e0b",
  "#ef4444",
  "#22c55e",
  "#ec4899",
  "#0ea5e9",
  "#ef4444",
  "#84cc16",
  "#f59e0b",
  "#6366f1",
  "#ec4899",
  "#a855f7",
  "#0ea5e9",
  "#ec4899",
  "#3b82f6",
  "#22c55e",
  "#06b6d4",
  "#f97316",
  "#8b5cf6",
  "#ec4899",
  "#f59e0b",
  "#6366f1",
  "#a855f7",
  "#0ea5e9",
  "#10b981",
  "#3b82f6",
  "#14b8a6",
  "#22c55e",
  "#84cc16",
  "#f97316",
  "#0ea5e9",
  "#22c55e",
  "#3b82f6",
  "#06b6d4",
  "#f59e0b",
  "#6366f1",
  "#ef4444",
  "#10b981",
  "#a855f7",
  "#f97316",
  "#f59e0b",
];

function cleanText(s: string | undefined | null): string {
  if (!s) return "";
  return String(s)
    .replace(/\uFFFD+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

// Strip the "T\u1eef v\u1ef1ng v\u1ec1 " prefix common to every topic
// header so we can use the rest as a short, friendly name.
function topicShortName(name: string): string {
  return name.replace(/^T\u1eef\s+v\u1ef1ng\s+v\u1ec1\s+/i, "");
}

function buildOxfordSets(): FlashcardSet[] {
  const result: FlashcardSet[] = [];
  for (const t of SOURCE) {
    const short = topicShortName(t.name);
    const slug = slugify(short) || `topic-${t.index}`;
    const icon = TOPIC_ICONS[(t.index - 1) % TOPIC_ICONS.length];
    const color = TOPIC_COLORS[(t.index - 1) % TOPIC_COLORS.length];

    const cards: FlashcardSet["cards"] = t.cards.map((c, idx) => ({
      id: `oxford-${t.index}-${slug}-${idx + 1}`,
      front: cleanText(c.word),
      back: cleanText(c.meaning) || cleanText(c.word),
      pronunciation: cleanText(c.ipa) || undefined,
    }));

    result.push({
      id: `builtin:oxford-${String(t.index).padStart(2, "0")}-${slug}`,
      name: short,
      description: `${t.cards.length} t\u1eef v\u1ef1ng ti\u1ebfng Anh theo ch\u1ee7 \u0111\u1ec1 "${t.name}"`,
      icon,
      color,
      builtin: true,
      cards,
    });
  }
  return result;
}

export const builtinOxfordSets: FlashcardSet[] = buildOxfordSets();
